src/handler/http/request/organization/mod.rs
src/service/search/datafusion/exec.rs
src/service/users.rs

fix: user list error

---

src/infra/config.rs

fix: data directory set is not working

---

Cargo.lock
Cargo.toml
coverage.sh
src/common/auth.rs
src/common/base64.rs
src/common/file.rs
src/common/http.rs
src/common/json.rs
src/common/mod.rs
src/common/stream.rs
src/common/time.rs
src/common/utils.rs
src/handler/grpc/auth/mod.rs
src/handler/grpc/mod.rs
src/handler/http/auth/mod.rs
src/handler/http/request/organization/mod.rs
src/handler/http/request/search/mod.rs
src/job/files/mod.rs
src/meta/mod.rs
src/meta/search.rs
src/meta/user.rs
src/service/alert_manager.rs
src/service/alerts.rs
src/service/compact/delete.rs
src/service/compact/lifecycle.rs
src/service/db/compact/delete.rs
src/service/db/user.rs
src/service/search/sql.rs
src/service/users.rs
tests/integration_test.rs

feat: support encode SQL

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
CONTRIBUTING.md

New team members can easily get up and running using devcontainers.

feat: Added devcontainers for easy development

---

web/src/plugins/logs/DetailTable.vue

fix: added toggle to wrap/fold log details #268

---

src/infra/errors.rs
src/meta/sql.rs
src/service/search.rs
src/service/search/sql.rs

fix: query condition contains limit

---

src/handler/http/request/kv/mod.rs
src/handler/http/request/mod.rs
src/handler/http/router/mod.rs
src/handler/http/router/openapi.rs
src/infra/config.rs
src/service/db/kv.rs
src/service/db/mod.rs
src/service/kv.rs

feat: add kv

---

src/service/search/sql.rs

fix: query with histogram #331

---

web/src/composables/useLogs.ts
web/src/plugins/logs/Index.vue
web/src/plugins/logs/IndexList.vue
web/src/plugins/logs/SearchResult.vue
web/src/utils/zincutils.ts

fix: add log filter local cache(#256)

---

web/src/components/alerts/AddDestination.vue
web/src/components/alerts/AddTemplate.vue
web/src/components/alerts/AlertList.vue
web/src/components/alerts/DestinationList.vue
web/src/views/AppAlerts.vue
web/src/views/Ingestion.vue

Made Template-form body input resizable and capitalized tabs label.
Redirected to alert list page after saving alert.
Filtered out headers with empty keys or values.

fix: UI fixes in alerts

---

src/common/notification.rs

fix: send notification error

---

src/handler/http/request/search/mod.rs
src/handler/http/router/mod.rs
src/handler/http/router/openapi.rs
src/service/search/sql.rs

feat: add top n values for fields

---

web/src/components/dashboards/AddDashboard.vue
web/src/components/dashboards/PanelHeader.vue
web/src/components/dashboards/SearchBar.vue
web/src/components/dashboards/addPanel/ChartRender.vue
web/src/components/dashboards/addPanel/ChartSelection.vue
web/src/components/dashboards/addPanel/IndexList.vue
web/src/components/dashboards/addPanel/Layout.vue
web/src/composables/useDashboardPanel.ts
web/src/locales/languages/en.json
web/src/router/index.ts
web/src/views/Dashboards/Dashboards.vue
web/src/views/Dashboards/ViewDashboard.vue
web/src/views/Dashboards/addPanel/AddPanel.vue

- histogram function for timestamp
- x-axis label and aggregation with histogram
- date format on histogram x axis
- error fix - custom query mode - chart not rendering
- added missing labels in charts
- capital understandable labels
- console errors fixed on chart render on page load
- URL paths updated
- Error message update for incorrect x and y axis values
- mapping alias for generated query
- resizable field list for add panel
- fixes #365 
- fixes #357 
- fixes #358
- fixes #359

fix: dashboard feedback

---

src/infra/storage/s3.rs
src/service/compact/merge.rs

fix: compact with partition keys

---

web/src/components/dashboards/addPanel/ChartRender.vue
web/src/views/Dashboards/Dashboards.vue
web/src/views/Dashboards/ViewDashboard.vue

H-bar label cutoff
remove other aggregation options on the x-axis
remove edit, save, and delete button in view dashboard page and auto-save on drag-drop and resize the panel
back button in view dashboard page
change the delete icon on the dashboard list and add confirm popup
resize chart

fix: dashboard feedback2

---

web/src/plugins/logs/DetailTable.vue

fix: saved wrap log details state in local storage

---

web/src/components/dashboards/SearchBar.vue
web/src/components/dashboards/addPanel/ChartRender.vue
web/src/composables/useDashboardPanel.ts

fix: dashboard issues (#401, #404)

---

web/src/components/alerts/AddTemplate.vue

1. Copy and pasting in template body
2. Added validation for Json in template body

fix: fixed template body input issues

---

src/service/search/sql.rs

fix: query in multiple lines is not working

---

web/src/components/alerts/AddDestination.vue
web/src/components/alerts/DestinationList.vue
web/src/components/alerts/TemplateList.vue

1. Changed destination method select input text to uppercase.
2. Updated notifications while fetching destinations and templates

fix: alert destinations and template UI fixes

---

src/service/search/sql.rs

fix: issue #445

---

web/src/components/dashboards/SearchBar.vue
web/src/components/dashboards/addPanel/ChartRender.vue
web/src/components/dashboards/addPanel/IndexList.vue
web/src/components/dashboards/addPanel/Layout.vue
web/src/components/shared/grid/NoPanel.vue
web/src/composables/useDashboardPanel.ts
web/src/locales/languages/de.json
web/src/locales/languages/en.json
web/src/locales/languages/es.json
web/src/locales/languages/fr.json
web/src/locales/languages/it.json
web/src/locales/languages/ja.json
web/src/locales/languages/ko.json
web/src/locales/languages/nl.json
web/src/locales/languages/pt.json
web/src/locales/languages/tr.json
web/src/locales/languages/zh.json
web/src/views/Dashboards/ViewDashboard.vue
web/src/views/Dashboards/addPanel/AddPanel.vue

- #436 
- #452 
- #424 
- #453 
- #434 & performance optimizations for chart rendering
- Panel name add on top of Add Panel page
- Show add panel button when there are no panels in a new dashboard.

fix: dashboard enhancements

---

src/handler/http/router/mod.rs
src/handler/http/router/ui.rs
src/service/search/sql.rs
web/index.html
web/src/components/dashboards/addPanel/ChartRender.vue
web/src/components/logBarChart.vue
web/src/components/shared/plotly/barchartMetrics.vue
web/src/components/shared/plotly/linechart.vue
web/src/components/shared/plotly/tablechart.vue
web/src/plugins/logs/Index.vue

fix: histogram time format

---

src/infra/config.rs
src/infra/storage/s3.rs

feat: add prefix for s3 bucket

---

Cargo.lock
Cargo.toml
src/infra/cluster.rs
src/main.rs
src/service/db/dashboard.rs
src/service/file_list.rs
src/service/search/datafusion/exec.rs
src/service/search/mod.rs

fix: panic with datafusion 21

---

web/src/plugins/logs/SearchBar.vue

feat: Download logs in .txt file 

---

CONTRIBUTING.md

Add the instructions on how to install `protoc` and its include files to `CONTRIBUTING.md`.

docs: add protoc install instructions to CONTRIBUTING.md

---

web/src/components/dashboards/addPanel/ChartRender.vue
web/src/composables/useDashboardPanel.ts
web/src/views/Dashboards/addPanel/AddPanel.vue

- Fix dashboard - add panel issues (console log errors)
- Show to the user when there is no data in dashboard panel
- https://github.com/zinclabs/zincobserve/issues/532
- https://github.com/zinclabs/zincobserve/issues/531
- https://github.com/zinclabs/zincobserve/issues/513

fix: dashboard errors, no data message, filter values api change

---

web/src/views/Dashboards/Dashboards.vue

fix: update the list of dashboards after deleting one

---

web/src/components/dashboards/ExportDashboard.vue
web/src/composables/shared/router.ts
web/src/locales/languages/en.json
web/src/views/Dashboards/Dashboards.vue
web/src/views/Dashboards/ImportDashboard.vue
web/src/views/Dashboards/ViewDashboard.vue

Needs testing after #503 is merged

feat: dashboard import export

---

Cargo.lock
Cargo.toml
src/infra/cache/file_data.rs
src/infra/cache/file_list.rs
src/infra/cache/stats.rs
src/infra/cluster.rs
src/infra/config.rs
src/infra/file_lock.rs
src/infra/metrics.rs
src/meta/telemetry.rs

Use one_cell Lazy will more easy to understand the code

feat: use one_cell lazy

---

src/service/search/datafusion/exec.rs
src/service/search/exec.rs

fix: query offset error when only local cache

---

src/service/search/sql.rs

fix: query with newline

---

src/handler/http/request/status/mod.rs
src/infra/config.rs

feat: add config for enable sql bas64 in UI

---

web/src/components/dashboards/PanelContainer.vue
web/src/components/dashboards/addPanel/ChartRender.vue
web/src/views/Dashboards/ViewDashboard.vue
web/src/views/Dashboards/addPanel/AddPanel.vue

fix: dashboard table render

---

src/handler/grpc/auth/mod.rs
src/infra/config.rs
src/service/compact/mod.rs

rename `ZO_DATA_LIFECYCLE` to `ZO_COMPACT_DATA_RETENTION`

fix: rename ZO_DATA_LIFECYCLE to ZO_COMPACT_DATA_RETENTION

---

src/handler/http/request/prom/mod.rs
src/service/router/mod.rs
tests/integration_test.rs

Make change to prometheus endpoints so grafana queries can succeed.

fix: fix for grafana querying prometheus endpoint

---

web/src/views/Dashboards/ViewDashboard.vue

fix: solve menu bar toggle resize issue

---

src/infra/config.rs
web/src/components/ingestion/metrics/OtelCollector.vue
web/src/components/ingestion/metrics/PrometheusConfig.vue
web/src/components/ingestion/metrics/TelegrafConfig.vue

1. updated metrics ingestion url to base_url/{org_id}/prometheus/api/v1/write
2. updated TCP, UDP port to 5541

fix: updated metrics ingestion url and tcp/udp port

---

src/common/utils.rs
src/handler/http/request/prom/mod.rs
src/handler/http/request/search/mod.rs
src/handler/http/request/status/mod.rs
src/infra/config.rs
src/meta/prom.rs
src/meta/sql.rs
src/service/logs/bulk.rs
src/service/logs/json.rs
src/service/logs/kinesis_firehose.rs
src/service/logs/mod.rs
src/service/logs/multi.rs
src/service/logs/syslog.rs
src/service/metrics/mod.rs
src/service/metrics/prom.rs
src/service/promql/engine.rs
src/service/promql/functions/histogram.rs
src/service/promql/functions/mod.rs
src/service/promql/search/grpc/storage.rs
src/service/promql/search/grpc/wal.rs
src/service/promql/value.rs
src/service/search/datafusion/exec.rs
src/service/search/mod.rs
src/service/search/sql.rs
src/service/traces/metadata.rs
src/service/traces/mod.rs
src/service/traces/otlp_http.rs

renamed `ZO_TIME_STAMP_COL` to `ZO_COLUMN_TIMESTAMP`
check stream update time with `start` and `end`, and returns the fields of the streams in the time range as labels.
1. label is `__name__`
it equals to fetch stream list, just get the stream list and check the update time with `start` and `end`
2. label is others
must provider `match[]` to set stream name. then return the topK values for the `label(field)` in the stream and with time range `start` and `end`

feat: impl /labels and /label/x/values API

---

src/meta/prom.rs
src/meta/stream.rs
src/service/metrics/prom.rs
src/service/promql/search/grpc/mod.rs

- feat: implement `/prometheus/api/v1/series` API
- refactor: extract `try_into_metric_name`; document the implementation
- feat: introduce `StreamStats::time_range_intersects`
- refactor: derive `Default` for `StreamStats`
Closes #692

feat: implement `/prometheus/api/v1/series` API

---

src/common/notification.rs
src/infra/config.rs

fix #733 
default:  `ZO_REQ_ACCEPT_INVALID_CERTS=false`
user can enable it by: `ZO_REQ_ACCEPT_INVALID_CERTS=true`

feat: send notification skip cert verify

---

src/handler/grpc/request/metrics.rs
src/handler/http/auth/mod.rs
src/handler/http/request/prom/mod.rs
src/meta/prom.rs
src/service/metrics/prom.rs
src/service/promql/binaries/add.rs
src/service/promql/binaries/mod.rs
src/service/promql/binaries/sub.rs
src/service/promql/engine.rs
src/service/promql/mod.rs

fix: promQL with Grafana

---

src/service/promql/engine.rs
src/service/promql/functions/irate.rs

fix: promQL error with irate

---

proto/cluster/metrics.proto
src/handler/grpc/mod.rs
src/handler/grpc/request/metrics.rs
src/handler/http/request/prom/mod.rs
src/service/promql/engine.rs
src/service/promql/functions/irate.rs
src/service/promql/mod.rs
src/service/promql/search/grpc/mod.rs
src/service/promql/search/grpc/storage.rs
src/service/promql/search/grpc/wal.rs
src/service/promql/search/mod.rs
src/service/search/datafusion/exec.rs
src/service/search/datafusion/storage/file_list.rs

- Max data points = 1000
- Min interval = 10s
- step = Time range / max data points

fix: promql query WAL lost

---

src/handler/http/router/mod.rs

fix: hack for openapi urls

---

web/src/composables/useLogs.ts
web/src/plugins/logs/DetailTable.vue
web/src/plugins/logs/Index.vue
web/src/plugins/logs/IndexList.vue
web/src/plugins/logs/SearchResult.vue

1. Added stream type selection for lookuptable and logs.
2. Disabled Histogram for lookuptable type
3. Disabled search around in log details for lookuptable type

feat: Enabled 'lookuptable' stream type in logs

---

README.md

Added links to the top of the readme.

fix: links on top

---

web/src/components/users/User.vue

fix: Add User button getting disabled for root user

---

web/src/components/ingestion/logs/SysLog.vue
web/src/components/ingestion/metrics/Index.vue
web/src/plugins/traces/Index.vue
web/src/plugins/traces/SearchResult.vue
web/src/views/Ingestion.vue

1. Syslog delete route
2. Remove tooltip from ingestion tabs
3. Metrics tab flickering on tab change
4. Updated traces on chart zoom

fix: syslog delete route 

---

web/src/components/dashboards/addPanel/ChartRender.vue
web/src/services/search.ts

fix: updated promql chart margin and fix loading indicator not showing after initial rendering

---

src/infra/config.rs

change default port of syslog server to 5514

fix: change default port

---

web/src/components/dashboards/addPanel/ChartRender.vue

fix: dashboard table alignment

---

web/src/components/MenuLink.vue
web/src/layouts/MainLayout.vue
web/src/plugins/logs/DetailTable.vue
web/src/plugins/logs/Index.vue
web/src/plugins/logs/SearchResult.vue

1. Disabled trimming of column content when only one column is added.
2. Added log expansion in log row
3. Changed font to 'monospace'
4. Added Field List collapse
5. Expanded sidebar on hover

fix: Log page UI fixes

---

src/service/search/datafusion/exec.rs

While creating a datafusion context, we enable the pushdown filter
`datafusion.execution.parquet.pushdown_filters=true`
The performance implication would be that the filter expressions will be applied during the parquet decoding operation and will reduce the number of rows decoded, thus slightly improved query times.

perf: enable push down filters for datafusion

---

proto/cluster/metrics.proto
src/handler/grpc/request/metrics.rs
src/handler/http/request/status/mod.rs
src/handler/http/request/stream/mod.rs
src/infra/config.rs
src/infra/errors.rs
src/infra/file_lock.rs
src/main.rs
src/service/ingestion/mod.rs
src/service/logs/bulk.rs
src/service/logs/json.rs
src/service/logs/kinesis_firehose.rs
src/service/logs/multi.rs
src/service/logs/syslog.rs
src/service/lookup_table/mod.rs
src/service/metrics/prom.rs
src/service/promql/engine.rs
src/service/promql/search/grpc/storage.rs
src/service/promql/search/grpc/wal.rs
src/service/promql/search/mod.rs
src/service/search/datafusion/exec.rs
src/service/search/datafusion/storage/memory.rs
src/service/search/datafusion/storage/nocache.rs
src/service/search/grpc/storage.rs
src/service/search/grpc/wal.rs
src/service/search/mod.rs
src/service/search/sql.rs
src/service/stream.rs
src/service/traces/mod.rs
src/service/traces/otlp_http.rs

fix: #852 
```
ZO_MEMORY_CACHE_MAX_SIZE = 0 // default 50% of total memory
ZO_MEMORY_CACHE_SKIP_SIZE = 0 // will skip the cache when a query need cache great than this value, default is 80% of max_size
```

feat: improve search with wal

---

web/src/components/ingestion/logs/Index.vue
web/src/components/ingestion/metrics/Index.vue
web/src/components/ingestion/traces/Index.vue
web/src/components/logstream/schema.vue
web/src/mixins/mainLayout.mixin.ts
web/src/views/Ingestion.vue

Fix #873 
Ingestion auth token was not getting generated on page refresh

fix: ingestion auth token issue

---

web/src/plugins/logs/Index.vue
web/src/plugins/logs/IndexList.vue
web/src/plugins/logs/SearchResult.vue
web/src/plugins/traces/DetailTable.vue
web/src/plugins/traces/Index.vue
web/src/utils/zincutils.ts

1. start time and end time in enrichment table query
2. #893

fix: fixed enrichment table query timeline

---

Cargo.lock
Cargo.toml
src/infra/cluster.rs
src/infra/config.rs
src/infra/storage/mod.rs
src/job/files/disk.rs
src/job/files/memory.rs
src/meta/sql.rs
src/service/compact/delete.rs
src/service/db/file_list/local.rs
src/service/db/file_list/mod.rs
src/service/db/file_list/remote.rs
src/service/enrichment_table/mod.rs
src/service/file_list.rs
src/service/ingestion/mod.rs
src/service/logs/mod.rs
src/service/organization.rs
src/service/promql/search/grpc/storage.rs
src/service/search/datafusion/exec.rs
src/service/search/grpc/mod.rs
src/service/search/grpc/storage.rs
src/service/search/grpc/wal.rs
src/service/search/mod.rs
src/service/search/sql.rs

fix: query report error when deleting stream

---

src/infra/config.rs
web/src/components/logstream/schema.vue

1. Skip schema validation during ingestion 
2. updated ZO_COMPACT_DATA_RETENTION_DAYS default value to 3650

feat: skip schema validation during ingestion

---

web/src/components/dashboards/addPanel/ChartRender.vue

fix: update dashboard legends behavior

---

web/src/plugins/logs/DetailTable.vue
web/src/plugins/logs/SearchResult.vue
web/src/plugins/traces/DetailTable.vue

Noticed a minor typo when browsing the UI.

fix: Fixes `Inlcude` typo in UI

---

web/src/components/shared/plotly/doubleLinechart.vue
web/src/enterprise/components/billings/usage.vue
web/src/locales/languages/en.json
web/src/plugins/logs/Index.vue
web/src/plugins/logs/IndexList.vue
web/src/plugins/logs/SearchBar.vue
web/src/plugins/logs/SearchResult.vue
web/src/utils/common.ts

1. fixed chart_panel_usage not found issue in billing page (Sentry)
2. fix #904 
3. fix #888 
4. fix #731 
5. fix #716

fix: billing and logs page issues

---

web/src/components/ingestion/logs/FileBeat.vue

fix: let default as the default index name

---

src/job/mod.rs

fix: typo in mod.rs

---

web/src/components/dashboards/PanelContainer.vue
web/src/components/dashboards/PanelHeader.vue
web/src/locales/languages/en.json
web/src/views/Dashboards/Dashboards.vue
web/src/views/Dashboards/ViewDashboard.vue

feat: duplicate dashboard & duplicate panel options

---

README.md

docs: Embed introduction video

---

web/src/plugins/logs/Index.vue
web/src/plugins/logs/IndexList.vue
web/src/plugins/metrics/Index.vue
web/src/plugins/metrics/MetricList.vue

1. Logs page histogram chart title
2. Fetching updated streams in logs on switching to logs page
3. Fetching updated streams in metrics on switching to logs page

fix: logs page UI fixes

---

.github/ISSUE_TEMPLATE/3-docs-bug.yaml
CONTRIBUTING.md
README.md
src/handler/http/request/syslog/mod.rs
src/handler/http/router/openapi.rs

fix: readme link

---

src/service/stream.rs
web/src/components/logstream/schema.vue
web/src/views/LogStream.vue

fix: logs fields can't used for partition key

---

src/main.rs

fix: ipv6 support

---

src/handler/http/request/organization/mod.rs
web/src/components/users/add.vue

fix: root user should list all organizations include created empty orgs

---

src/infra/config.rs
src/service/metrics/json.rs
src/service/metrics/prom.rs
src/service/promql/engine.rs
src/service/promql/exec.rs
src/service/promql/mod.rs
src/service/promql/search/grpc/mod.rs
src/service/promql/search/grpc/storage.rs
src/service/promql/search/grpc/wal.rs
src/service/promql/search/mod.rs
src/service/search/mod.rs

fix: add scan_size for promql

---

web/src/components/dashboards/addPanel/ChartRender.vue

fix: only load visible panel issue #963

---

src/handler/http/router/mod.rs

- /swagger -> /swagger/
- /docs    -> /swagger/

feat: add redirects for swagger docs

---

src/service/logs/mod.rs

https://zincobserve.slack.com/archives/C04QC53TPD2/p1687817620787329

feat: Inform about ZO_INGEST_ALLOWED_UPTO in the error message

---

proto/cluster/metrics.proto
src/service/promql/binaries/vector_operations.rs
src/service/promql/engine.rs
src/service/promql/exec.rs
src/service/promql/functions/math_operations.rs
src/service/promql/functions/mod.rs
src/service/promql/functions/time_operations.rs
src/service/promql/search/grpc/mod.rs
src/service/promql/value.rs

- Abs, Ceil, Floor, Exp, Sqrt, Ln, Log2, Log10, Round

feat: promql math functions support

---

src/service/promql/engine.rs
src/service/promql/functions/absent.rs
src/service/promql/functions/absent_over_time.rs
src/service/promql/functions/avg_over_time.rs
src/service/promql/functions/changes.rs
src/service/promql/functions/clamp.rs
src/service/promql/functions/count_over_time.rs
src/service/promql/functions/delta.rs
src/service/promql/functions/increase.rs
src/service/promql/functions/irate.rs
src/service/promql/functions/last_over_time.rs
src/service/promql/functions/math_operations.rs
src/service/promql/functions/max_over_time.rs
src/service/promql/functions/min_over_time.rs
src/service/promql/functions/mod.rs
src/service/promql/functions/rate.rs
src/service/promql/functions/stddev_over_time.rs
src/service/promql/functions/stdvar_over_time.rs
src/service/promql/functions/sum_over_time.rs
src/service/promql/functions/vector.rs

Absent
AbsentOverTime
Changes
Clamp
ClampMin
ClampMax
LastOverTime
Sgn
StddevOverTime
StdvarOverTime

feat: promql further implementations

---

src/service/promql/engine.rs
src/service/promql/functions/mod.rs
src/service/promql/functions/resets.rs

https://prometheus.io/docs/prometheus/latest/querying/functions/#resets

feat: promql `resets` function implementation

---

Cargo.lock
Cargo.toml
src/common/meta/prom.rs
src/service/promql/engine.rs
src/service/promql/search/grpc/storage.rs
src/service/search/grpc/storage.rs
src/service/stream.rs

feat: support promql offset

---

src/service/promql/engine.rs
src/service/promql/functions/time_operations.rs

The date/time-like functions also accept a default param of type `vector(time())` in case no param is passed to them. This is implemented in this PR.
Can be tested using something like following:
```
day_of_month()
```
or
```
day_of_month(any-vector-type-metric)
```

feat: promql date/time functions default value

---

.cargo/config.toml

ci: remove one feature to supports more platform

---

web/src/composables/useMetrics.ts
web/src/plugins/metrics/Index.vue
web/src/plugins/metrics/MetricList.vue
web/src/plugins/traces/Index.vue

1. Updated _timestamp alias in traces query
2. Added help text
3. Added loader in metrics when fetching metrics

fix: fixed _timestamp alias in traces query

---

web/src/components/D3Chart.vue
web/src/components/DateTime.vue
web/src/components/logstream/explore/SearchBar.vue
web/src/plugins/logs/Index.vue
web/src/plugins/logs/IndexList.vue
web/src/plugins/logs/SearchBar.vue
web/src/plugins/metrics/Index.vue
web/src/plugins/traces/Index.vue
web/src/plugins/traces/SearchBar.vue
web/src/views/StreamExplorer.vue

1. fixed date time component recursive update
2. Update traces, metrics, logs chart on resize
3. Fixed timestamp while adding absolute time to query request

fix: fixed date time component recursive update

---

web/src/components/dashboards/addPanel/ChartRender.vue

fix: dashboard timestamp field format

---

web/src/components/DateTime.vue
web/src/components/logBarChart.vue
web/src/components/logstream/schema.vue
web/src/composables/usePromqlSuggestions.ts
web/src/plugins/logs/DetailTable.vue
web/src/plugins/logs/IndexList.vue
web/src/plugins/logs/SearchResult.vue
web/src/plugins/metrics/Index.vue
web/src/plugins/metrics/MetricList.vue
web/src/plugins/traces/IndexList.vue
web/src/utils/date.ts
web/src/utils/zincutils.ts
web/src/views/LogStream.vue

1. Fix #1219 
2. Fix #1205 
3. Fix #1204
4. Fix #1198 
5. Fix #1177 
6. Fix #1176

fix: UI Improvements

---

Cargo.lock
Cargo.toml
src/common/infra/cluster.rs
src/common/infra/config.rs
src/common/infra/db/etcd.rs

impl #1212 , just set `ZO_ETCD_ADDR = "localhost:2379,localhost:2378"`

feat: support multiple etcd hosts

---

web/src/components/AutoRefreshInterval.vue
web/src/utils/date.ts

fix: default shows Off for autoInterval

---

web/src/components/DateTime.vue
web/src/composables/useLogs.ts
web/src/composables/useMetrics.ts
web/src/enterprise/components/organizations/JoinOrganization.vue
web/src/enterprise/components/organizations/ListAssociatedMembers.vue
web/src/enterprise/components/organizations/Organization.vue
web/src/enterprise/components/users/User.vue
web/src/plugins/logs/DetailTable.vue
web/src/plugins/logs/Index.vue
web/src/plugins/logs/JsonPreview.vue
web/src/plugins/logs/SearchBar.vue
web/src/plugins/logs/SearchResult.vue
web/src/plugins/metrics/Index.vue
web/src/plugins/metrics/MetricList.vue
web/src/services/metrics.ts
web/src/ts/interfaces/query.ts

fix #1156 
fix #1199 
fix #1235

fix: UI fixes in logs and metrics

---

src/common/meta/prom.rs
src/handler/http/router/mod.rs
src/service/db/metrics.rs
src/service/metrics/prom.rs

remove expansive clone operation in metrics ingestion.

refactor: remove expensive clone operation

---

web/src/components/DateTime.vue
web/src/composables/useLogs.ts
web/src/enterprise/components/billings/usage.vue
web/src/layouts/MainLayout.vue
web/src/plugins/logs/Index.vue
web/src/plugins/logs/IndexList.vue
web/src/plugins/metrics/Index.vue
web/src/plugins/traces/Index.vue

fix: fixed logs query parsing issue

---

src/service/promql/functions/histogram.rs

Added a missing case handling empty bucket
Added a bunch of test cases to verify the implementation 
Implemented a new() for Bucket - to test.

feat: histogram_quantile refactor

---

src/service/metrics/prom.rs

refactor: optimize metrics write

---

web/src/components/DateTime.vue
web/src/composables/useLogs.ts
web/src/enterprise/components/users/User.vue
web/src/locales/languages/en.json
web/src/plugins/logs/Index.vue
web/src/views/HomeView.vue
web/src/views/LogStream.vue

fix #1237 
fix #1303 
fix #1283

fix: added status column in org users table

---

web/src/components/dashboards/PanelHeader.vue
web/src/components/dashboards/VariablesValueSelector.vue
web/src/components/dashboards/addPanel/ChartRender.vue
web/src/components/dashboards/settings/VariableQueryValueSelector.vue
web/src/views/Dashboards/ViewDashboard.vue

- https://github.com/openobserve/openobserve/issues/1310

fix: dashboard variable loading issue

---

Cargo.lock
Cargo.toml
src/common/infra/cache/file_list.rs
src/common/infra/cache/tmpfs.rs
src/service/compact/file_list.rs
src/service/compact/merge.rs
src/service/db/file_list/mod.rs
src/service/db/file_list/remote.rs
src/service/search/datafusion/exec.rs

perf: optimize compactor

---

src/common/meta/ingestion.rs
src/service/logs/bulk.rs
src/service/metrics/mod.rs

fix: set status to 422 when bulk api return error message

---

web/src/components/alerts/AddAlert.vue
web/src/components/alerts/AlertList.vue

fix: add/edit alert custom sql getting lost during editing

---

src/handler/grpc/request/traces.rs
src/handler/http/request/traces/mod.rs
src/service/traces/mod.rs
src/service/traces/otlp_http.rs

fix: traces issues 1316 1090

---

src/common/infra/wal.rs
src/common/utils/file.rs
src/handler/grpc/request/metrics.rs
src/job/file_list.rs
src/job/files/disk.rs
src/job/files/mod.rs
src/job/metrics.rs
src/job/mod.rs
src/service/compact/retention.rs
src/service/db/file_list/local.rs
src/service/db/schema.rs
src/service/enrichment_table/mod.rs
src/service/ingestion/mod.rs
src/service/logs/json.rs
src/service/logs/mod.rs
src/service/mod.rs
src/service/search/grpc/wal.rs
src/service/traces/mod.rs
src/service/traces/otlp_http.rs

feat: improve wal file with partition key

---

src/service/search/sql.rs

fix: issue 1225

---

Cargo.lock
Cargo.toml
src/common/infra/config.rs
src/service/compact/merge.rs
src/service/promql/search/grpc/storage.rs
src/service/promql/search/grpc/wal.rs
src/service/search/datafusion/exec.rs
src/service/search/grpc/storage.rs
src/service/search/grpc/wal.rs

feat: upgrade to datafusion 30

---

.github/workflows/release.yml

ci: add simd version binary

---

src/common/infra/config.rs
src/handler/http/request/search/mod.rs
src/main.rs

fix: top values api error when the filter is empty

---

web/src/utils/dashboard/convertSQLData.ts

fix: dashboard multi x axis for line charts

---

src/handler/http/request/logs/ingest.rs
src/handler/http/request/metrics/ingest.rs
src/handler/http/request/search/mod.rs
src/service/functions.rs
src/service/metrics/otlp_http.rs
src/service/traces/mod.rs
src/service/traces/otlp_http.rs

fix: vrl , values api filtering

---

web/src/plugins/logs/IndexList.vue

To filter field values based on query, updated sql query with where clause in field values api.
fix #699

fix: Updated sql query with where clause in field values api 

---

src/common/infra/config.rs
src/handler/grpc/request/event.rs
src/handler/http/request/status/mod.rs
src/service/db/file_list/broadcast.rs

feat: add more debug logs

---

web/src/plugins/traces/IndexList.vue

fix: In traces updated sql query with where clause in field values api

---

web/src/views/Dashboards/addPanel/AddPanel.vue

fix: unsaved changes warning when saving a new panel in the dashboard

---

src/common/infra/config.rs
src/common/meta/ingestion.rs
src/handler/grpc/request/logs.rs
src/handler/grpc/request/traces.rs
src/handler/http/request/logs/ingest.rs
src/handler/http/request/traces/mod.rs
src/service/logs/otlp_grpc.rs
src/service/logs/otlp_http.rs
src/service/traces/mod.rs
src/service/traces/otlp_http.rs

Fixes https://github.com/openobserve/openobserve/issues/1544

fix: OTLP ingestion fixes

---

web/src/components/dashboards/addPanel/ConfigPanel.vue
web/src/utils/dashboard/convertDataIntoUnitValue.ts

feat: Add microseconds & millisecond units in the dashboard panels

---

src/common/infra/config.rs

fixes : https://github.com/openobserve/openobserve/issues/1537

fix: Enable widening schema evolution as default

---

src/common/infra/db/dynamo.rs
src/service/dashboards/folders.rs
src/service/db/dashboards/folders.rs

Previously before folder , dashboards had key /dashboard/dashboard_id now it will be dashboard/folder_id/dashboard_id

fix: dynamodb changes for dashboard

---

src/common/infra/config.rs
src/common/migration/dashboards.rs
src/main.rs

fix:  revert zo grpc org header key

---

src/common/meta/telemetry.rs
src/common/utils/http.rs
src/common/utils/notification.rs
src/common/utils/stream.rs
src/service/alerts/mod.rs
src/service/ingestion/grpc.rs
src/service/logs/syslog.rs
src/service/promql/common.rs
src/service/promql/value.rs
src/service/search/mod.rs
tests/integration_test.rs

`tests` module had a few clippy errors/warnings. Applied the fixes.

fix: Clippy errors in tests

---

web/src/components/dashboards/AddDashboard.vue
web/src/components/dashboards/AddFolder.vue
web/src/components/dashboards/ExportDashboard.vue
web/src/components/dashboards/MoveDashboardToAnotherFolder.vue
web/src/components/dashboards/PanelHeader.vue
web/src/components/dashboards/SelectFolderDropdown.vue
web/src/components/dashboards/settings/AddSettingVariable.vue
web/src/components/dashboards/settings/GeneralSettings.vue
web/src/components/dashboards/settings/VariableSettings.vue
web/src/layouts/MainLayout.vue
web/src/locales/languages/en.json
web/src/plugins/metrics/AddToDashboard.vue
web/src/services/dashboards.ts
web/src/stores/index.ts
web/src/utils/commons.ts
web/src/views/Dashboards/Dashboards.vue
web/src/views/Dashboards/ImportDashboard.vue
web/src/views/Dashboards/ViewDashboard.vue
web/src/views/Dashboards/addPanel/AddPanel.vue

feat: folders for dashboards ui

---

web/src/composables/useSuggestions.ts

This PR contains the changes for the query editor in the logs page. Query Editor type ahead popup contains fields, operators, and custom functions. To differentiate them we have added appropriate icons for fields and functions.

feat: added icons for functions and fields

---

src/job/stats.rs
src/service/usage/ingestion_service.rs

- Stopped reporting stats to stats stream from usage stream , as stats are being calculated from filelist
- Add randomness to node selection for usage reporting

fix:stats calculation

---

web/src/components/dashboards/AddDashboard.vue
web/src/components/dashboards/PanelContainer.vue
web/src/views/Dashboards/RenderDashboardCharts.vue
web/src/views/Dashboards/ViewDashboard.vue
web/src/views/Dashboards/addPanel/AddPanel.vue

Converts the dashboard page to a separate component, which can be used in other pages as well

fix: generalize view dashboard page to utilize on other part of the application

---

web/src/composables/dashboard/usePanelDataLoader.ts
web/src/composables/useDashboardPanel.ts

- Fix the dashboard error message to look at multiple places in the API response before showing "Something went wrong"
- Fixes #1562

fix: filter does not allow integer values to be saved and dashboard error message

---

web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
web/src/utils/commons.ts
web/src/views/Dashboards/ImportDashboard.vue
web/src/views/Dashboards/addPanel/AddPanel.vue

Few exception-related issues: 
- Can't find variable: store, H(assets/ViewDashboard) 
- JSON.parse: unexpected character
- Function.allSettled undefined is not iterable

fix: dashboard sentry issues

---

src/service/schema.rs

refactor: small memory-bound optimizations in schema

---

src/handler/http/request/dashboards/folders.rs
src/service/db/functions.rs
src/service/functions.rs

- Fixes the swagger doc in #1649, `title` -> `name` in the parameters.
- Also removed unnecessary clones

fix: fixes the create-folder docs in #1649

---

src/common/infra/db/mod.rs
src/common/infra/db/sqlite.rs
src/common/infra/file_list/sqlite.rs
src/main.rs

fix: reset stream stats can't work

---

src/service/compact/retention.rs

fix: #1696

---

web/src/components/settings/General.vue
web/src/components/settings/index.vue
web/src/composables/dashboard/usePanelDataLoader.ts
web/src/layouts/MainLayout.vue
web/src/services/organizations.ts
web/src/stores/index.ts

- UI for https://github.com/openobserve/openobserve/issues/1408

feat: rate interval variables for promql in dashboard

---

web/src/views/Dashboards/ViewDashboard.vue

Removed the duplicate key `openSettingsDialog` from component structure

fix: removed duplicate key

---

.github/ISSUE_TEMPLATE/1-bug-report.yaml

Adding Real User Monitoring option under selections

docs: Update 1-bug-report.yaml

---

web/src/layouts/MainLayout.vue
web/src/plugins/logs/Index.vue
web/src/views/RUM/ErrorViewer.vue

1. The left menu navigation bar was not functioning as expected. Upon investigation, it was found that the issue stemmed from a v-if condition placed on a component inside a <keep-alive> wrapper.
Added v-if condition outside keep-alive in template
2. In ErrorViewer replace onActivated hook with onMounted

fix: Left Menu Navigation Bar Functionality

---

web/src/components/AppTable.vue
web/src/components/rum/ErrorDetail.vue
web/src/components/rum/PlayerEventsSidebar.vue
web/src/components/rum/errorTracking/view/ErrorEvents.vue
web/src/components/rum/errorTracking/view/ErrorHeader.vue
web/src/components/rum/errorTracking/view/ErrorSessionReplay.vue
web/src/components/rum/errorTracking/view/ErrorStackTrace.vue
web/src/components/rum/errorTracking/view/ErrorTag.vue
web/src/components/rum/errorTracking/view/ErrorTags.vue
web/src/views/RUM/SessionViewer.vue

fix: dark mode css and background color fix

---

web/src/components/AppTable.vue
web/src/components/common/AppTabs.vue
web/src/components/rum/performance/ApiDashboard.vue
web/src/components/rum/performance/ErrorsDashboard.vue
web/src/components/rum/performance/PerformanceSummary.vue
web/src/components/rum/performance/WebVitalsDashboard.vue
web/src/components/shared/grid/NoPanel.vue
web/src/composables/rum/usePerformance.ts
web/src/composables/shared/router.ts
web/src/plugins/traces/Index.vue
web/src/utils/rum/api.json
web/src/utils/rum/errors.json
web/src/utils/rum/overview.json
web/src/utils/rum/web_vitals.json
web/src/views/Dashboards/RenderDashboardCharts.vue
web/src/views/RUM/AppPerformance.vue
web/src/views/RUM/RealUserMonitoring.vue

Added Performance dashboard UI in RUM

feat: RUM Performance dashboard UI

---

src/service/schema.rs
src/service/search/grpc/storage.rs
src/service/search/grpc/wal.rs

fix: merge result is wrong in some cases

---

web/src/components/rum/performance/ApiDashboard.vue
web/src/components/rum/performance/ErrorsDashboard.vue
web/src/components/rum/performance/PerformanceSummary.vue
web/src/components/rum/performance/WebVitalsDashboard.vue
web/src/composables/shared/router.ts
web/src/utils/rum/errors.json
web/src/views/Dashboards/RenderDashboardCharts.vue
web/src/views/RUM/AppPerformance.vue
web/src/views/RUM/RealUserMonitoring.vue

Added Rum Performance tabs Overview, Web Vitals, Errors and API as url path

fix: updated RUM Performance section tabs in url path

---

web/src/components/rum/VideoPlayer.vue
web/src/composables/shared/router.ts
web/src/composables/useSessionReplay.ts
web/src/layouts/MainLayout.vue
web/src/views/RUM/AppErrors.vue
web/src/views/RUM/AppPerformance.vue
web/src/views/RUM/AppSessions.vue
web/src/views/RUM/ErrorViewer.vue
web/src/views/RUM/RealUserMonitoring.vue
web/src/views/RUM/SessionViewer.vue

fix: #1764 , #1762 , #1752 , #1742 , #1733 , #1732 , #1724

fix: RUM UI issues 

---

web/src/components/rum/errorTracking/view/ErrorTags.vue
web/src/composables/rum/usePerformance.ts
web/src/layouts/MainLayout.vue
web/src/locales/languages/en.json
web/src/views/RUM/AppPerformance.vue
web/src/views/RUM/AppSessions.vue
web/src/views/RUM/RealUserMonitoring.vue
web/src/views/RUM/SessionViewer.vue

fix: Rum UI Issues

---

web/src/components/functions/FunctionList.vue

fix: on creation of new function the page should refresh to show the newly created function

---

web/src/plugins/metrics/AddToDashboard.vue
web/src/plugins/metrics/Index.vue
web/src/views/Dashboards/addPanel/AddPanel.vue

- #1757 
Here it add the panel to the dashboard in default folder for now. We will be adding to select folder option in another issue.

fix: add to dashboard not working from metric explorer

---

web/src/components/dashboards/addPanel/FieldList.vue
web/src/plugins/metrics/MetricList.vue

feat: dashboard add panel metric steams shows metric type icon next to stream name

---

web/src/plugins/metrics/AddToDashboard.vue
web/src/plugins/metrics/Index.vue

fix: added folder selection in add to dashboard from metrics page

---

src/common/utils/mod.rs
src/common/utils/schema.rs
src/job/files/disk.rs
src/job/files/memory.rs
src/service/ingestion/mod.rs
src/service/metrics/json.rs
src/service/schema.rs
src/service/search/datafusion/exec.rs
src/service/search/grpc/wal.rs

fix: use u64 for start_time & end_time for traces

---

web/src/plugins/metrics/AddToDashboard.vue

fix: add to dashboard from metric explore page

---

web/package-lock.json
web/src/components/AppTable.vue
web/src/components/rum/VideoPlayer.vue
web/src/styles/app.scss
web/src/views/RUM/AppSessions.vue
web/src/views/RUM/SessionViewer.vue

Added minor improvement to toggle play/pause video on clicking player

fix: added toggle play/pause video on clicking player

---

src/job/mod.rs
src/service/db/file_list/remote.rs
web/package-lock.json

fix: issue #1813

---

src/service/search/datafusion/exec.rs

fix: #1833

---

web/src/utils/dashboard/convertPromQLData.ts
web/src/utils/dashboard/convertSQLData.ts

Fixed metric tooltip overflow for the dashboard and metrics page

fix: metric tooltip overflow

---

web/src/components/dashboards/PanelSchemaRenderer.vue
web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
web/src/components/dashboards/settings/AddSettingVariable.vue
web/src/components/dashboards/settings/VariableSettings.vue
web/src/utils/dashboard/convertPromQLData.ts
web/src/utils/dashboard/convertSQLData.ts

Fixed issues reported in sentry related to dashboard.
Most issues were related to undefined or null.

fix: issues reported in sentry related to dashboard

---

web/src/components/dashboards/PanelSchemaRenderer.vue

fix: show no data when missing axis value which is required for plotting charts

---

web/src/components/ingestion/Recommended.vue
web/src/components/ingestion/recommended/OtelConfig.vue

Fix label from OTEL -> OTEL Collector

fix: OTEL label

---

src/common/meta/mod.rs
src/common/meta/proxy.rs
src/handler/http/auth/mod.rs
src/handler/http/router/mod.rs
src/main.rs

Can be queried using http://localhost:5080/proxy/{target_url}

feat: Overcome the cors issue using a proxy

---

web/package-lock.json
web/package.json
web/src/components/rum/VideoPlayer.vue
web/src/components/rum/errorTracking/view/ErrorTag.vue
web/src/components/rum/performance/ErrorsDashboard.vue
web/src/components/rum/performance/WebVitalsDashboard.vue
web/src/components/rum/sessionReplay/SessionLocationColumn.vue
web/src/layouts/MainLayout.vue
web/src/utils/rum/api.json
web/src/utils/rum/errors.json
web/src/utils/rum/overview.json
web/src/utils/rum/web_vitals.json
web/src/views/RUM/AppErrors.vue
web/src/views/RUM/AppPerformance.vue
web/src/views/RUM/AppSessions.vue

1. Restoring date time on reloading Errors and Session page
2. Minor styling fixes in Error tag on error page

fix: fixed rum UI issues

---

src/common/infra/cluster.rs
src/main.rs

fix: support sidecar querier for ingester

---

web/src/components/AutoRefreshInterval.vue
web/src/plugins/logs/SearchBar.vue
web/src/plugins/metrics/Index.vue
web/src/plugins/metrics/SyntaxGuideMetrics.vue
web/src/plugins/traces/SearchBar.vue

fix: ui issue on logs, metrics, traces

---

web/src/styles/app.scss

fix: overlap issue

---

web/src/components/dashboards/PanelSchemaRenderer.vue
web/src/utils/rum/overview.json

When custom error handling is enabled, the application displays custom error messages or default data if an error occurs.
If no default data is set, it shows a custom error message to inform users about the issue.

fix: custom error handling for dashboard components

---

web/src/components/DateTime.vue

fix: date picker auto close on relative / absolute date change

---

web/src/plugins/logs/IndexList.vue

Fields values were not getting fetched in sql mode due to query parsing issue

fix: Logs field values filtering in sql mode

---

src/common/infra/wal.rs
src/handler/grpc/request/metrics/querier.rs
src/job/files/disk.rs
src/job/files/memory.rs
src/service/compact/merge.rs
src/service/compact/mod.rs
src/service/search/datafusion/exec.rs
src/service/search/datafusion/mod.rs
src/service/search/grpc/wal.rs

fix: enable compact for distinct_values

---

web/src/components/AppTable.vue
web/src/components/DateTime.vue
web/src/components/rum/performance/ApiDashboard.vue
web/src/components/rum/performance/ErrorsDashboard.vue
web/src/components/rum/performance/PerformanceSummary.vue
web/src/components/rum/performance/WebVitalsDashboard.vue
web/src/composables/rum/usePerformance.ts
web/src/composables/rum/useRum.ts
web/src/views/RUM/AppErrors.vue
web/src/views/RUM/AppPerformance.vue
web/src/views/RUM/AppSessions.vue
web/src/views/RUM/RealUserMonitoring.vue
web/src/views/RUM/SessionViewer.vue

fix: fixed switching to absolute time in RUM

---

web/src/components/rum/VideoPlayer.vue
web/src/views/RUM/SessionViewer.vue

Some session events were missing during session replay, when navigated from Error Viewer page

fix: Session events were not getting fetched correctly

---

web/src/components/dashboards/PanelSchemaRenderer.vue
web/src/components/dashboards/settings/AddSettingVariable.vue

fix: capitalize issue and no data for pie and donut

---

web/src/plugins/traces/Index.vue

fix: time show error

---

web/src/components/shared/grid/Pagination.vue

fix: dashboards table list max record label overlap issue for francais language

---

web/src/components/rum/errorTracking/view/ErrorHeader.vue
web/src/components/rum/errorTracking/view/ErrorTags.vue

1. Added additional check for browser and os versions as was getting undefined in some cases
2. Support to copy error id

fix: Minor UI fixes in RUM error tracking

---

src/service/alerts/templates.rs
src/service/dashboards/mod.rs

fix: return 404 if the delete target not exists

---

src/service/alerts/destinations.rs

fix: del alert error return status change

---

src/common/utils/notification.rs
src/handler/http/request/alerts/destinations.rs
src/handler/http/request/alerts/mod.rs
src/handler/http/request/alerts/templates.rs
src/handler/http/request/dashboards/folders.rs
src/handler/http/request/dashboards/mod.rs
src/handler/http/request/functions/mod.rs
src/service/alerts/destinations.rs
src/service/alerts/mod.rs
src/service/alerts/templates.rs
src/service/dashboards/folders.rs
src/service/dashboards/mod.rs
src/service/db/alerts/destinations.rs
src/service/db/alerts/mod.rs
src/service/db/alerts/templates.rs
src/service/functions.rs
src/service/triggers.rs

feat: delete API should return 200, 404 or 500

---

web/src/components/ingestion/recommended/FrontendRumConfig.vue
web/src/components/ingestion/recommended/KubernetesConfig.vue
web/src/components/ingestion/recommended/LinuxConfig.vue
web/src/components/ingestion/recommended/OtelConfig.vue
web/src/components/ingestion/recommended/WindowsConfig.vue
web/src/components/ingestion/traces/OpenTelemetry.vue

Added explanation for ingestion page

docs: Explanation

---

web/src/utils/dashboard/convertDataIntoUnitValue.ts

fix: date format

---

src/main.rs

fix: ip logger show

---

src/service/db/dashboards/mod.rs

fixes : https://github.com/openobserve/openobserve/issues/1687

fix: dashboard make title mandatory

---

README.md

docs: add RUM

---

web/src/components/dashboards/addPanel/FieldList.vue

fix: steam not updated when stream type is changed in add dashboard panel

---

src/common/infra/cache/file_data/disk.rs
src/common/infra/cache/file_data/memory.rs
src/common/infra/db/sqlite.rs

fix: query cache error in concurrency

---

src/service/search/grpc/storage.rs
src/service/search/grpc/wal.rs

fix: query merge error in some case

---

src/common/infra/config.rs
src/service/metrics/json.rs
src/service/metrics/mod.rs
src/service/metrics/otlp_grpc.rs
src/service/metrics/otlp_http.rs
src/service/search/datafusion/mod.rs

fix: metrics ingest calculate

---

web/src/composables/useTraces.ts
web/src/plugins/traces/Index.vue
web/src/plugins/traces/IndexList.vue
web/src/plugins/traces/SearchBar.vue
web/src/plugins/traces/SearchResult.vue
web/src/plugins/traces/TraceBlock.vue
web/src/plugins/traces/TraceDetails.vue
web/src/plugins/traces/TraceTree.vue
web/src/utils/traces/convertTraceData.ts

fix: Traces UI enhancements

---

web/src/plugins/traces/Index.vue
web/src/plugins/traces/SearchBar.vue
web/src/plugins/traces/TraceBlock.vue
web/src/plugins/traces/TraceDetails.vue
web/src/plugins/traces/TraceHeader.vue
web/src/plugins/traces/TraceTree.vue

1. Converted trace start time from nano to micro
2. Minor UI fixes in trace details dark mode
3. Added loader while fetching traces meta data

fix: Traces UI Issues

---

src/common/infra/db/mysql.rs
src/common/infra/db/postgres.rs
src/common/migration/file_list.rs
src/common/migration/meta.rs
src/main.rs
src/service/compact/file_list_deleted.rs
src/service/compact/mod.rs

fix: migration with file_list_deleted

---

src/service/alerts/templates.rs

fix: judge body is empty

---

README.md
src/common/infra/cluster.rs
src/common/infra/db/mysql.rs
src/common/infra/file_list/mysql.rs
src/common/infra/file_list/postgres.rs
src/common/infra/file_list/sqlite.rs
src/handler/http/request/search/mod.rs
src/handler/http/request/traces/mod.rs
src/handler/http/router/mod.rs
src/handler/http/router/openapi.rs

fix: don't need to send broadcast with mysql

---

web/src/composables/useTraces.ts
web/src/plugins/traces/Index.vue
web/src/plugins/traces/SearchBar.vue
web/src/plugins/traces/SearchResult.vue
web/src/plugins/traces/SpanBlock.vue
web/src/plugins/traces/TraceBlock.vue
web/src/plugins/traces/TraceDetails.vue
web/src/services/search.ts

1. Added support for trace id in url
2. Updated new Url for fetching traces
3. Fixed traces loader during pagination

fix: Updated new url for fetching traces

---

src/service/alerts/templates.rs
src/service/db/file_list/local.rs
src/service/db/file_list/remote.rs

fix: parse file_list when got an invalid json

---

src/service/metrics/otlp_grpc.rs

fix: the metric name format is incorrect. (#2003)

---

web/src/plugins/traces/Index.vue
web/src/plugins/traces/SearchResult.vue

1. Added check to restrict fetching traces if no more data is present
2. Added method to generate traces service colors

fix: traces pagination issues

---

src/handler/http/request/enrichment_table/mod.rs
src/service/enrichment_table/mod.rs
web/src/components/functions/AddEnrichmentTable.vue
web/src/locales/languages/en.json
web/src/services/jstransform.ts

Added append toggle to allow appending data:

feat:append data to enrichment tables

---

src/service/metrics/otlp_grpc.rs
src/service/metrics/otlp_http.rs

fixes : [2009](https://github.com/openobserve/openobserve/issues/2009)

fix: histogram type processing 

---

Cargo.lock
Cargo.toml
src/common/infra/storage/local.rs
src/common/infra/storage/mod.rs
src/common/infra/storage/remote.rs
src/common/utils/schema.rs
src/service/search/datafusion/exec.rs
src/service/search/datafusion/storage/file_list.rs
src/service/search/datafusion/storage/memory.rs
src/service/search/datafusion/storage/tmpfs.rs

There is a bug of datafusion that is like this:
```
datafusion execute error: Optimizer rule 'single_distinct_aggregation_to_group_by' failed
```
and i found this bug already fixed by https://github.com/apache/arrow-datafusion/issues/7987
So, we need to upgrade datafusion for fix it.

fix: single_distinct_aggregation_to_group_by

---

LICENSE
web/src/components/ingestion/recommended/KubernetesConfig.vue

docs: change license

---

web/src/plugins/traces/Index.vue
web/src/plugins/traces/SearchBar.vue
web/src/plugins/traces/SearchResult.vue

fix: Traces run query button was not getting triggered

---

src/common/utils/flatten.rs
src/service/ingestion/mod.rs
src/service/ingestion/otlp_json.rs
src/service/logs/otlp_http.rs
src/service/metrics/otlp_http.rs

fix: otlp http changes

---

Cargo.lock
Cargo.toml

Upgraded vrl version to latest 0.8.1

chore: upgrade vrl version

---

web/src/utils/dashboard/convertSQLData.ts

On the x-axis getting the timestamp value,
So, converted its timestamp value to a time series.
**Previous:**
**Now:**

fix: convert timestamp value on x-axis as timeseries

---

src/job/mmdb_downloader.rs

This PR fixes the scenario when, the client wont be initialized if the file wasnt downloaded.
for e.g. if someone restarted the server and the mmdb file was already present the client will not be initialized.

fix: download mmdb files and initialize the client

---

web/src/components/alerts/AddAlert.vue
web/src/components/alerts/AddDestination.vue
web/src/components/alerts/AddTemplate.vue
web/src/components/alerts/AlertList.vue
web/src/components/alerts/DestinationList.vue
web/src/components/alerts/FieldsInput.vue
web/src/components/alerts/TemplateList.vue
web/src/layouts/MainLayout.vue

1. Added filtering on streams and conditions columns
2. Added back buttons on Add/Edit destination/template pages

fix: Alerts UI fixes

---

web/src/components/AutoRefreshInterval.vue
web/src/components/dashboards/PanelContainer.vue
web/src/components/dashboards/viewPanel/ViewPanel.vue
web/src/views/Dashboards/RenderDashboardCharts.vue
web/src/views/Dashboards/ViewDashboard.vue

feat: maximize panel in dashboard

---

src/common/meta/dashboards/v2/mod.rs
web/src/components/dashboards/PanelSchemaRenderer.vue
web/src/components/dashboards/addPanel/ConfigPanel.vue
web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
web/src/components/dashboards/addPanel/SortByBtnGrp.vue
web/src/components/icons/AscSort.vue
web/src/components/icons/DescSort.vue
web/src/composables/useDashboardPanel.ts

feat: built in support for top N results

---

src/common/meta/stream.rs
src/service/schema.rs

impl #1659 add setting api for bloom filter

feat: add bloomfilter for setting API

---

src/common/meta/dashboards/v2/mod.rs
web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
web/src/components/dashboards/addPanel/HistogramIntervalDropDown.vue
web/src/components/dashboards/viewPanel/ViewPanel.vue

feat: specify interval for histogram aggregation function

---

src/job/files/disk.rs
src/job/files/memory.rs
src/service/compact/merge.rs
src/service/db/schema.rs
src/service/search/datafusion/exec.rs
src/service/search/datafusion/mod.rs
src/service/stream.rs

feat: apply stream level bloom filter settings

---

web/src/components/dashboards/QueryEditor.vue
web/src/components/dashboards/addPanel/DashboardQueryEditor.vue

fix: dashboard query editor scroll and query error message issue

---

src/common/infra/file_list/dynamo.rs
src/common/infra/file_list/mod.rs
src/common/infra/file_list/mysql.rs
src/common/infra/file_list/postgres.rs
src/common/infra/file_list/sqlite.rs
src/common/infra/storage/mod.rs
src/handler/grpc/request/metrics/querier.rs
src/job/compact.rs
src/service/compact/file_list_deleted.rs
src/service/compact/merge.rs
src/service/compact/mod.rs
src/service/compact/retention.rs
src/service/search/grpc/wal.rs
src/service/usage/stats.rs

Thanks a lot to @domyway for his help, he has tested many development versions.👍🏻

fix: compaction issues

---

src/handler/http/request/alerts/destinations.rs
src/handler/http/request/alerts/mod.rs
src/handler/http/request/alerts/templates.rs
src/handler/http/request/functions/mod.rs
src/handler/http/request/kv/mod.rs
src/handler/http/request/search/saved_view.rs
src/handler/http/request/users/mod.rs
src/service/alerts/destinations.rs
src/service/alerts/mod.rs
src/service/alerts/templates.rs
src/service/dashboards/folders.rs
src/service/db/dashboards/mod.rs
src/service/functions.rs
src/service/usage/mod.rs

fix: add empty name check

---

web/src/components/alerts/AddDestination.vue
web/src/components/alerts/AddTemplate.vue

fix: Alerts UI Issues

---

deploy/build/Dockerfile.aarch64
deploy/build/Dockerfile.amd64
deploy/build/Dockerfile.tag-debug.aarch64
deploy/build/Dockerfile.tag-debug.amd64

Adding psql to debug container for debugging

fix: add psql for debugging

---

web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
web/src/utils/dashboard/convertSQLData.ts
web/src/views/Dashboards/addPanel/AddPanel.vue

fix: gauge chart issue

---

src/cli/basic/cli.rs
src/cli/basic/mod.rs
src/cli/data/cli.rs
src/cli/data/export.rs
src/cli/data/import.rs
src/cli/data/mod.rs
src/cli/mod.rs
src/handler/http/request/prom/mod.rs
src/main.rs

feat: cli import or export data

---

web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
web/src/composables/useDashboardPanel.ts

fix: dashboard drag and reorder issue

---

src/common/meta/middleware_data.rs

We renamed `oo` prefix in RUM related data to `o2`, but tags werent being parsed properly.
This PR fixes it

fix: parsing of o2tags + ootags

---

src/common/infra/config.rs
src/common/meta/alerts/mod.rs
src/handler/http/request/traces/mod.rs
src/handler/tcp_udp/mod.rs

fix: Fixed some small issues

---

src/common/infra/config.rs
src/main.rs
src/service/alerts/mod.rs

feat: impl alert row template

---

web/src/components/ingestion/logs/OtelConfig.vue
web/src/components/ingestion/metrics/OtelCollector.vue
web/src/components/ingestion/recommended/OtelConfig.vue

otlp grpc is now available on router.

docs: grpc on router is now available

---

web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
web/src/components/dashboards/addPanel/FieldList.vue
web/src/composables/dashboard/usePanelDataLoader.ts
web/src/composables/useDashboardPanel.ts
web/src/views/Dashboards/addPanel/AddPanel.vue

fix: dashboard drag reorder issues

---

web/src/components/DateTime.vue

fix: absolute date time issue for dashboard

---

web/src/components/ingestion/traces/OpenTelemetry.vue

OTLP grpc is now supported on router.

docs: otlp grpc support 2

---

web/src/components/ingestion/traces/OpenTelemetry.vue

docs: add header for grpc

---

web/src/components/dashboards/viewPanel/ViewPanel.vue
web/src/views/Dashboards/RenderDashboardCharts.vue
web/src/views/Dashboards/ViewDashboard.vue

- use currently selected same time in maximize panel.
- #2260

fix: maximize panel pass same time whether relative or absolute

---

web/src/views/Dashboards/ViewDashboard.vue

feat: share dashboard functionality

---

web/src/composables/useTraces.ts
web/src/locales/languages/en.json
web/src/plugins/traces/Index.vue
web/src/plugins/traces/SpanBlock.vue
web/src/plugins/traces/SpanDetails.vue
web/src/plugins/traces/SpanRenderer.vue
web/src/plugins/traces/TraceDetails.vue
web/src/plugins/traces/TraceDetailsSidebar.vue
web/src/plugins/traces/TraceHeader.vue
web/src/plugins/traces/TraceTree.vue

feat: Expandable Spans in Trace details

---

web/src/components/alerts/AddAlert.vue
web/src/components/alerts/AlertList.vue
web/src/components/alerts/FieldsInput.vue
web/src/components/alerts/ScheduledAlert.vue
web/src/components/alerts/VariablesInput.vue
web/src/composables/shared/router.ts
web/src/layouts/MainLayout.vue
web/src/plugins/traces/SearchBar.vue
web/src/views/RUM/AppSessions.vue

fix: #2274 #2203 #2208 #2209 #2206 #2218 #2235

fix: Alerts and Traces UI issues

---

web/src/components/dashboards/addPanel/FieldList.vue
web/src/components/dashboards/settings/VariableAdHocValueSelector.vue

fix: metric stream drop-down for dark mode

---

web/src/components/dashboards/panels/ChartRenderer.vue
web/src/utils/dashboard/convertSQLData.ts

fix: reverse order issue for h bar

---

src/cli/basic/cli.rs
src/common/utils/auth.rs
src/handler/http/auth/validator.rs
src/handler/http/request/users/mod.rs
src/job/mod.rs
src/service/db/user.rs
src/service/organization.rs
src/service/users.rs

fix: user api checks

---

web/src/mixins/mainLayout.mixin.ts

fix: Fixed the problem that the front-end menu "Function" has an unnecessary string "1"

---

src/common/infra/config.rs
src/common/utils/functions.rs
src/job/mmdb_downloader.rs
src/service/enrichment_table/geoip.rs
src/service/search/mod.rs

feat: maxmind asn db as vrl enrichment table

---

src/common/infra/config.rs
web/src/locales/languages/en.json
web/src/views/HomeView.vue

1. Add human friendly geoip URL
2. Remove video from home page

fix: add human friendly geoip URL

---

web/src/components/dashboards/PanelContainer.vue
web/src/components/dashboards/addPanel/ConfigPanel.vue

feat: dashboard panel description 

---

web/src/composables/dashboard/usePanelDataLoader.ts
web/src/composables/useMetricsExplorer.ts
web/src/plugins/metrics/Index.vue

- Run query button not working in metrics page

fix: run query button not working in metrics page

---

src/common/meta/dashboards/v2/mod.rs
web/src/components/dashboards/addPanel/ConfigPanel.vue
web/src/composables/useDashboardPanel.ts
web/src/utils/dashboard/convertDataIntoUnitValue.ts
web/src/utils/dashboard/convertPromQLData.ts
web/src/utils/dashboard/convertSQLData.ts

- configure decimal point using config panel.
- default value will be 2.
- #2178

feat: decimal point option in config panel

---

src/common/meta/dashboards/v2/mod.rs
web/src/components/dashboards/AddDashboard.vue
web/src/components/dashboards/VariablesValueSelector.vue
web/src/components/dashboards/settings/AddSettingVariable.vue
web/src/components/dashboards/settings/GeneralSettings.vue
web/src/components/dashboards/settings/VariableAdHocValueSelector.vue
web/src/components/dashboards/settings/VariableSettings.vue
web/src/utils/commons.ts
web/src/views/Dashboards/RenderDashboardCharts.vue
web/src/views/Dashboards/ViewDashboard.vue

- Use dynamic filters as a checkbox compared to part of variables
- In the Dashboard's general settings, will get an option to show dynamic filters apart from set variables

fix: dynamic filters

---

web/src/components/dashboards/viewPanel/ViewPanel.vue
web/src/views/Dashboards/addPanel/AddPanel.vue

fix: dynamic variables for add and maximize panel

---

tests/ui-testing/cypress/e2e/tests/dashboard/add_dashboard.cy.js

- Add a new dashboard
- Add and delete the created dashboard
- Delete all dashboards
- Verify if save button enabled if dashboard name has only spaces added

feat: e2e create dashboard testcases

---

web/src/utils/dashboard/convertSQLData.ts
web/src/utils/dashboard/convertTableData.ts

- #2383 
- table sorting issue

fix: timeseries issue for area stacked chart

---

tests/ui-testing/cypress/e2e/tests/functions_tests.cy.js
tests/ui-testing/cypress/fixtures/enrichment_info.csv
tests/ui-testing/package-lock.json
tests/ui-testing/package.json

- Display error when creating function without mandatory fields
- Display error on entering invalid name under function and save
- Display error on entering invalid function and save
- Display error on entering adding function with same name
- Add a function and associate a stream with the same
- Display error add a function and associate a stream with the same
- Upload a enrichment table under functions and save

test: added tests for functions page

---

web/src/utils/dashboard/convertDataIntoUnitValue.ts
web/src/utils/dashboard/convertPromQLData.ts
web/src/utils/dashboard/convertSQLData.ts
web/src/utils/dashboard/convertTableData.ts

fix: tofixed method getting undefined

---

src/service/search/datafusion/transform_udf.rs
src/service/traces/mod.rs

refactor: Remove unnecessary methods

refactor: Remove unnecessary methods

---

.github/workflows/build-pr-image.yml
deploy/build/Dockerfile.pr.amd64

- Building and publishing docker-images for a given PR using github
actions
- Use ubicloud as the build provider
- Build the image outside of the container, thus using cache and
reducing build time.

feat: support building and publishing to registry via actions

---

tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js

- Verify if the vrl function added is displayed in the expanded search result view

test: logs vrl testcase assertion added

---

web/src/components/common/sidebar/FieldList.vue
web/src/components/functions/AssociatedStreamFunction.vue
web/src/locales/languages/en.json
web/src/plugins/traces/SpanDetails.vue
web/src/plugins/traces/TraceDetailsSidebar.vue
web/src/plugins/traces/TraceTree.vue
web/src/views/RUM/AppSessions.vue

fix: added exceptions tab in trace details

---

tests/ui-testing/cypress/e2e/tests/dashboard/add_dashboard.cy.js
tests/ui-testing/cypress/e2e/tests/dashboard/create_dashboard.cy.js
tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js

- Display added function on switching between tabs and again navigate to logs

test: added logs-vrlfunction testcase

---

tests/ui-testing/cypress.config.js
tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js

- Changes to config for test run

test: cypress test changes

---

src/common/meta/dashboards/v2/mod.rs
web/src/components/dashboards/addPanel/ConfigPanel.vue
web/src/composables/useDashboardPanel.ts
web/src/locales/languages/en.json
web/src/utils/dashboard/convertPromQLData.ts
web/src/utils/dashboard/convertSQLData.ts

- Set legend width dynamically based on its name and given option in config
- If promql has no data then remove axis
- Added config option for axis width and axis border
- #1950 
- #2231

fix: dashboard legend width and axis width, border

---

web/src/utils/dashboard/convertDataIntoUnitValue.ts

fix: dashboard unit conversion for negative values

---

tests/ui-testing/cypress/e2e/tests/dashboard/add_dashboard.cy.js
tests/ui-testing/cypress/e2e/tests/dashboard/create_dashboard.cy.js
tests/ui-testing/cypress/e2e/tests/dashboard/edit_dashboard.cy.js
tests/ui-testing/cypress/e2e/tests/functions_tests.cy.js
tests/ui-testing/cypress/fixtures/dashboard.json

- Added edit dashboard tests
- updated locator under add dashboard
- fixed breaking testcase under create dashboard
- fixed file delete testcase under functions
- updated query under fixtures

test:edit dashboard testcases

---

web/src/components/dashboards/addPanel/ConfigPanel.vue
web/src/utils/dashboard/convertSQLData.ts

fix: dashboard legend width and title overlap 

---

web/src/assets/inputs.scss
web/src/assets/main.css
web/src/components/alerts/AddAlert.vue
web/src/components/alerts/AlertList.vue
web/src/components/alerts/FieldsInput.vue
web/src/components/alerts/PreviewAlert.vue
web/src/components/alerts/RealTimeAlert.vue
web/src/components/alerts/ScheduledAlert.vue
web/src/components/alerts/VariablesInput.vue
web/src/composables/dashboard/usePanelDataLoader.ts
web/src/locales/languages/en.json
web/src/services/alerts.ts
web/src/styles/quasar-overrides.scss
web/src/utils/alerts/alertChartData.ts
web/src/views/AppAlerts.vue

**Add/Update Alerts**
Alert preview chart will be shown while adding or updating alert

feat: added preview for alerts

---

src/common/meta/alerts/mod.rs
src/config/src/config.rs
src/handler/http/request/traces/mod.rs
src/job/files/parquet.rs
src/service/alerts/mod.rs
src/service/compact/merge.rs
web/src/components/alerts/AddTemplate.vue

feat: alert support PromQL

---

web/src/composables/useLogs.ts
web/src/plugins/logs/Index.vue
web/src/plugins/logs/IndexList.vue
web/src/views/LogStream.vue

fix #2363 
Redirected stream explorer streams from stream page to logs page

feat: Stream Explorer UI improvements

---

web/src/plugins/traces/Index.vue
web/src/plugins/traces/IndexList.vue
web/src/services/search.ts

feat: stream selection support in traces

---

tests/ui-testing/cypress/e2e/tests/alerts_tests.cy.js
tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js

- Add a new template
- Display error when template added without name
- Display error when template added with invalid body
- Add a new destination
- Display error when destination added without name
- Add alert
- Display error when alert added without name under alerts
- Display error when alert added without stream under alerts
- Display error when user directly clicks save without any values under alerts
- Delete destination
- Delete template
- Verify if add template displayed on alerts page if no template added
- Verify if add template displayed on destination page if no template added 
- Verify a success message displayed on destination creation
- Verify if Add destination button is displayed
- Verify if on cancel on delete confirmation the alert does not get deleted
- Verify logs …

test:added alerts testcases and fixed logs tests

---

web/src/utils/zincutils.ts

Disabled billing page redirection to check the impact of ingestion page redirection.

fix: disabled billing page redirection

---

web/src/components/dashboards/viewPanel/ViewPanel.vue

- On maximize panel mode some times get scroll bars.

fix: dashboard maximize panel scroll issue

---

web/src/components/alerts/AddAlert.vue
web/src/components/alerts/AddDestination.vue
web/src/components/alerts/AddTemplate.vue
web/src/components/alerts/AlertList.vue
web/src/components/alerts/DestinationList.vue
web/src/components/alerts/FieldsInput.vue
web/src/components/alerts/PreviewAlert.vue
web/src/components/alerts/RealTimeAlert.vue
web/src/components/alerts/ScheduledAlert.vue
web/src/components/alerts/TemplateList.vue
web/src/components/alerts/VariablesInput.vue
web/src/styles/quasar-overrides.scss

Added support for promql in alerts

feat: promql support in alerts

---

web/src/components/dashboards/viewPanel/ViewPanel.vue
web/src/layouts/MainLayout.vue
web/src/plugins/logs/Index.vue
web/src/utils/zincutils.ts

Fix: Histogram refresh issue on toggle sql mode.

fix: minor issue and redirection

---

tests/ui-testing/cypress/e2e/tests/alerts_tests.cy.js
tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js

- Added logs testcase to test this bug - #2461

test: logs histogram graph testcase

---

web/src/plugins/metrics/Index.vue
web/src/plugins/metrics/MetricList.vue

fix: fixed sharing metrics url issue

---

web/src/components/ingestion/traces/OpenTelemetry.vue
web/src/services/jstransform.ts

Modified endpoints as per the backend changes

fix: endpoint sync release v0.8.0

---

web/src/components/alerts/AddAlert.vue
web/src/components/alerts/PreviewAlert.vue
web/src/components/alerts/ScheduledAlert.vue
web/src/plugins/logs/Index.vue
web/src/plugins/logs/IndexList.vue
web/src/plugins/traces/Index.vue
web/src/plugins/traces/IndexList.vue
web/src/plugins/traces/SpanBlock.vue
web/src/plugins/traces/TraceDetailsSidebar.vue

fix #2478 #2480 #2479 #2487 #2489 #2477

fix: log UI issues

---

web/src/composables/dashboard/usePanelDataLoader.ts

- Resets the chart rendering when there are no queries, fixes the alert preview chart when switching from the SQL to promql

fix: reset the data when there are no queries to execute

---

web/src/components/dashboards/panels/ChartRenderer.vue
web/src/utils/dashboard/convertPromQLData.ts
web/src/utils/dashboard/convertSQLData.ts

- Fix wrong tooltip item highlights when hovering on a view dashboard page

fix: chart tooltip wrong legend highlight

---

web/src/utils/dashboard/convertPromQLData.ts
web/src/utils/dashboard/convertSQLData.ts

fix: alert preview chart x axis label overlap issue

---

web/src/components/dashboards/VariablesValueSelector.vue
web/src/utils/date.ts

fix: dynamic filters disappear issue when change in time

---

web/src/components/ingestion/recommended/KubernetesConfig.vue
web/src/locales/languages/en.json
web/src/main.ts

Two different tabs added under Kubernetes ingestion option. It will serve the This cluster and different cluster information. It will be only applicable to opensource version not for cloud.

feat: kubernetes tabs integration

---

src/service/search/grpc/mod.rs

fix: issue/2501

---

web/src/components/alerts/AddAlert.vue

Allowed 0 as alert silence value
fix #2498

fix: Fixed alert silence value validation

---

src/common/meta/alerts/templates.rs
src/service/alerts/mod.rs
src/service/alerts/templates.rs
web/src/components/alerts/AddTemplate.vue

feat: add length limit for alert variables

---

web/src/composables/useDashboardPanel.ts
web/src/utils/commons.ts
web/src/views/Dashboards/RenderDashboardCharts.vue

- #2346 
- By default take 50% width on add panel

fix: table chart histogram field by default sortby as desc

---

web/src/services/http.ts
web/src/views/Login.vue

Fix below issues:
- Get organization details after login on enterprise login
- Login screen flash after successful login

fix: ui issue

---

web/src/composables/useLogs.ts
web/src/plugins/logs/Index.vue

- https://github.com/openobserve/openobserve/issues/2555
- https://github.com/openobserve/openobserve/issues/2557

fix: #2555 & #2557

---

src/common/utils/json.rs
src/service/ingestion/mod.rs
src/service/logs/bulk.rs
src/service/logs/ingest.rs
src/service/logs/mod.rs
src/service/logs/multi.rs
src/service/logs/otlp_grpc.rs
src/service/logs/otlp_http.rs
src/service/logs/syslog.rs

1. Optimize log write procedure, avoid log copy operation
2. Add tests for estimate_json_bytes

refactor: optimize log write procedure

---

web/src/plugins/logs/SearchResult.vue

#2549 removed first and last page navigation option.

fix: Update SearchResult.vue

---

web/src/plugins/logs/SearchBar.vue

fix: pagination ui issue

---

web/src/composables/useLogs.ts
web/src/plugins/logs/IndexList.vue
web/src/plugins/traces/Index.vue
web/src/plugins/traces/IndexList.vue
web/src/plugins/traces/fields-sidebar/AdvancedValuesFilter.vue

fix: fixed traces UI issues

---

web/src/composables/useLogs.ts
web/src/composables/useTraces.ts
web/src/plugins/logs/Index.vue
web/src/plugins/logs/SearchBar.vue
web/src/plugins/traces/Index.vue

[#2576](https://github.com/openobserve/openobserve/issues/2576)
[#2580](https://github.com/openobserve/openobserve/issues/2580)
[#2577](https://github.com/openobserve/openobserve/issues/2577)

Fix/stream explorer UI fix

---

Cargo.lock
Cargo.toml
src/service/metrics/otlp_grpc.rs
src/service/search/datafusion/date_format_udf.rs
src/service/search/datafusion/exec.rs
src/service/search/datafusion/match_udf.rs
src/service/search/datafusion/storage/memory.rs
src/service/search/datafusion/storage/mod.rs
src/service/search/datafusion/storage/tmpfs.rs
src/service/search/datafusion/time_range_udf.rs
src/service/search/grpc/errors.rs

feat: update to datafusion 35

---

web/src/composables/useLogs.ts
web/src/plugins/logs/SearchBar.vue

fix: fixed saved views functionality for metrics and traces stream type in logs page

---

src/common/infra/db/sqlite.rs
src/common/infra/file_list/sqlite.rs
src/common/meta/search.rs
src/ingester/src/wal.rs
src/job/compact.rs
src/service/compact/file_list_deleted.rs
src/service/compact/mod.rs
src/service/db/enrichment_table.rs
src/service/search/grpc/wal.rs
src/service/search/mod.rs

fix: enrichment table query

---

src/common/infra/config.rs
src/common/meta/stream.rs
src/service/logs/bulk.rs
src/service/schema.rs

refactor: optimize schema check

---

tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js

- fixed saved views delete testcase

test: fix saved view deletion under logs

---

src/infra/src/cache/file_data/disk.rs
src/infra/src/cache/file_data/memory.rs
src/job/files/parquet.rs
src/service/compact/merge.rs
src/service/db/mod.rs
src/service/promql/search/grpc/storage.rs
src/service/search/grpc/storage.rs

fix: #2619

---

web/src/utils/commons.ts
web/src/utils/dashboard/convertDashboardSchemaVersion.ts
web/src/views/Dashboards/RenderDashboardCharts.vue

- max column number from 12 to 48 for grid.

fix: increase number of columns for panel grid

---

tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js

-  Display added function on switching between tabs and again navigate to logs
- Change stream settings and click on search stream
- Not display error if match all case added in log query search

test: logs to stream navigation testcases

---

src/service/traces/mod.rs
src/service/traces/otlp_http.rs

refactor: optimize traces write

---

.github/workflows/ui-testing.yml
tests/ui-testing/cypress/e2e/tests/alerts_tests.cy.js

- Added locators and fixed failing testcase for alerts

test: updated locators for alerts

---

web/src/composables/useLogs.ts
web/src/plugins/logs/Index.vue

search partition also applied while sql mode which was incorrect.

fix: sql mode partition fix

---

src/service/users.rs
web/src/components/RouteTabs.vue
web/src/components/iam/groups/EditGroup.vue
web/src/components/iam/roles/EditRole.vue
web/src/components/iam/users/User.vue
web/src/components/login/Login.vue
web/src/locales/languages/en.json
web/src/ts/interfaces/iam.ts
web/src/views/IdentityAccessManagement.vue
web/src/views/User.vue

1. fixed "Add User" functionality in IAM users
2. Fixed IAM active tab was getting disabled on going to editRole and editGroup
3. Fixed filtering in IAM role permissions

fix: Fixed IAM users functionality

---

web/src/utils/dashboard/convertMapData.ts

fix: dashboard geolocation issue

---

web/src/components/iam/groups/GroupRoles.vue
web/src/components/iam/groups/GroupUsers.vue
web/src/components/iam/roles/EditRole.vue
web/src/views/IdentityAccessManagement.vue

In stream Logs child resources were not loading during initial render

fix: fixed IAM Permissions issue

---

web/src/components/alerts/ScheduledAlert.vue
web/src/components/iam/groups/AddGroup.vue
web/src/components/iam/groups/EditGroup.vue
web/src/components/iam/roles/AddRole.vue
web/src/components/iam/roles/EditRole.vue

1. Added validation for role and group name
2. Added notification if there are no changes and user clicks on save role or group

fix: IAM UI fixes

---

web/src/composables/useLogs.ts

Latest record not getting return in multiple partition.

fix: pagination sorting issue

---

web/src/components/alerts/ScheduledAlert.vue

fix: fixed editing non aggregated alerts

---

web/src/components/alerts/AddAlert.vue
web/src/components/alerts/ScheduledAlert.vue
web/src/composables/useLogs.ts
web/src/locales/languages/en.json
web/src/plugins/logs/Index.vue

1. Duplicated calls in logs page on redirecting to logs from streams page
2. Added frequency input in alerts

fix: added frequency input in alerts 

---

web/src/composables/useDashboardPanel.ts
web/src/views/Dashboards/addPanel/AddPanel.vue

- When switching from map to sankey fixed validation error.
- When switching from bar, line etc to map or sankey with limit value set, wrong validation message was triggered

fix: chart type switching with sankey

---

src/service/alerts/mod.rs

fixed #2712 
alert set
alert_query in alert_url

fix(alert): support sql mode in alert_url

---

src/config/src/config.rs
src/ingester/src/entry.rs
src/ingester/src/memtable.rs
src/ingester/src/partition.rs
src/ingester/src/stream.rs
src/ingester/src/writer.rs
src/main.rs
src/service/alerts/mod.rs

perf: improve per thread lock

---

web/src/components/dashboards/addPanel/FieldList.vue

- for edit panel, stream list not rendering

fix: on chart type change stream field list rendering issue in add panel

---

web/src/components/dashboards/PanelSchemaRenderer.vue

- When drilling down to a new tab, the /web/ part is not being included in the URL
- drilldown list pop up hide issue on route change.

fix: dashboard drilldown url creation issue for new tab

---

src/common/infra/mod.rs
src/config/src/config.rs
src/service/db/schema.rs
src/service/search/mod.rs

perf: improve enrichmentTable

---

web/src/composables/useStreams.ts

If user has permission on specific type of streams it was creating issue

fix: RBAC get all streams issues

---

web/src/utils/commons.ts
web/src/views/Dashboards/Dashboards.vue

- show correct error message on folder delete
- #2762

fix: on folder delete show correct error message

---

web/src/components/dashboards/PanelSchemaRenderer.vue
web/src/components/dashboards/panels/ChartRenderer.vue
web/src/components/dashboards/viewPanel/ViewPanel.vue
web/src/utils/dashboard/convertPromQLData.ts
web/src/utils/dashboard/convertSQLData.ts
web/src/views/Dashboards/RenderDashboardCharts.vue

- fix: view panel drilldown issue for same tab.
- fix: on legend click, show only one series.
- fix: for add panel page, chart tooltip not working.

fix: dashboard tooltip and drilldown issue

---

src/common/utils/http.rs
src/config/src/meta/stream.rs
web/src/components/logstream/AddStream.vue
web/src/components/logstream/StreamFieldInputs.vue
web/src/components/logstream/schema.vue
web/src/composables/useLogs.ts
web/src/composables/useStreams.ts
web/src/locales/languages/en.json
web/src/plugins/logs/SearchResult.vue
web/src/views/LogStream.vue

1. Added new stream indexing options Inverted Index and Hash Partition
2. Added functionality to create new stream
3. On Refresh Stats btn click, updated streams cache
4. On adding and deleting stream updated same in streams cache

feat: Updated stream creation and stream settings

---

web/src/composables/useLogs.ts
web/src/locales/languages/en.json
web/src/plugins/logs/SearchResult.vue

This PR contains a fix for two histogram issues.
1. If the histogram is disabled, it should not send the histogram request.
2. Histogram request fails, it should display the table data and display an error message for the histogram.

fix: histogram fix

---

web/src/composables/useLogs.ts
web/src/plugins/logs/SearchBar.vue

fix: Search around logs page

---

web/src/components/alerts/AddDestination.vue
web/src/components/alerts/AddTemplate.vue
web/src/components/logstream/AddStream.vue
web/src/components/logstream/schema.vue
web/src/composables/useStreams.ts
web/src/views/LogStream.vue

fix #2792 
fix #2790 
fix #2789 
fix #2788

fix: fixed issues in add and update streams

---

web/src/views/LogStream.vue

1. Duplicated streams on clicking Refresh Stats on streams page multiple times
2. Filtering streams was not working as expected

fix: streams filtering

---

tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js

- Skipped stream settings testcase as UI changed.

test: removed stream settings testcase

---

src/service/logs/mod.rs

perf: tradeof between query performance and ingester performance

---

src/config/src/config.rs
src/infra/src/cache/file_data/disk.rs
src/infra/src/cache/file_data/memory.rs
src/infra/src/cache/file_data/mod.rs

feat: impl FIFO for query cache

---

web/src/components/alerts/AddAlert.vue
web/src/components/alerts/ScheduledAlert.vue
web/src/locales/languages/en.json
web/src/locales/languages/zh.json

1. Renamed Scheduled alerts to Standard alerts and Custom to Quick
2. Added info for threshold, period, frequency and silence notification

fix: UI improvements in alerts

---

src/service/search/grpc/wal.rs

Skip file when reading data for searching in inverted index , fixes issues ErrorCode(ServerInternalError("ArrowError# Io error: failed to fill whole buffer"))

fix: inverted index issue

---

web/src/components/iam/users/AddUser.vue

User update with change password will force logout user from the system.

fix: logout user functionality

---

src/config/src/config.rs
src/handler/http/request/status/mod.rs
web/src/components/login/Login.vue
web/src/layouts/MainLayout.vue
web/src/locales/languages/en.json

Logo text for enterprise version (two places: Login Page, Top left on every page)
Renamed Fast Mode to Quick Mode

fix: Custom logo text single line

---

web/src/composables/useLogs.ts

- 'hits' changed to 'events'
- Fixed incorrect pagination & title in sql mode with limits

fix: changed hits to events and limit count fix

---

web/src/plugins/logs/Index.vue
web/src/plugins/logs/SearchResult.vue

- After reset filter in full sql mode if limit applied, changing rows per page not getting reflected

fix: after reset filter records per page not getting reflected

---

src/config/src/config.rs
src/service/search/datafusion/exec.rs
src/service/search/grpc/storage.rs
src/service/search/grpc/wal.rs
src/service/search/sql.rs

Now we need three options for quick mode:
```
ZO_FAST_MODE_NUM_FIELDS = 4
ZO_FAST_MODE_STRATEGY = "first"
ZO_FAST_MODE_FILE_LIST_ENABLED = true
```

fix: fast mode field not found

---

web/src/views/Dashboards/addPanel/AddPanel.vue

feat: dashboard tutorial button

---

web/src/views/About.vue

- Additional message added on about us page.

fix: about text

---

tests/ui-testing/cypress/e2e/tests/logs_queries.cy.js

Added testcases for the following scenarios 
- should match total - histogram mode ignore case for normal and index search test
- should match total - histogram mode match all for normal and index search

test: inverted index value for queries testcase

---

src/service/db/schema.rs
src/service/metrics/otlp_grpc.rs
src/service/metrics/otlp_http.rs

fix: issue #2921

---

src/service/search/datafusion/exec.rs
src/service/search/datafusion/mod.rs
src/service/search/datafusion/rewrite.rs

fix: use sqlparser-rs rewrite count_distinct

---

src/common/meta/dashboards/v3/mod.rs
web/src/components/dashboards/addPanel/ConfigPanel.vue
web/src/composables/useDashboardPanel.ts
web/src/utils/dashboard/convertPromQLData.ts
web/src/utils/dashboard/convertSQLData.ts

- Previous chart
- Corrected chart
- config option to connect null points:

fix: stacked area chart color filling issue

---

web/src/plugins/logs/Index.vue

fix: refresh with sql mode on sending duplicate requests

---

web/src/plugins/logs/SearchBar.vue
web/src/plugins/logs/SearchResult.vue

When we copy log column value we were converting it to JSON string. So, prevented converting value to JSON string

fix: On copy prevent conversion of Log column value to JSON strings

---

src/service/search/datafusion/exec.rs
src/service/search/datafusion/rewrite.rs

fix: remove where clause use sqlparser

---

src/config/src/config.rs
src/service/search/sql.rs

We are no more supporting ZO_FEATURE_FULLTEXT_ON_ALL_FIELDS env vars

fix: remove ZO_FEATURE_FULLTEXT_ON_ALL_FIELDS

---

Cargo.lock
src/common/infra/cluster.rs
src/common/infra/config.rs
src/common/meta/sql.rs
src/config/Cargo.toml
src/config/src/config.rs
src/config/src/utils/parquet.rs
src/handler/grpc/request/event.rs
src/handler/http/request/status/mod.rs
src/handler/http/router/mod.rs
src/infra/src/cache/file_data/disk.rs
src/main.rs
src/service/compact/merge.rs
src/service/db/file_list/local.rs
src/service/db/schema.rs
src/service/search/sql.rs
web/package-lock.json
web/package.json
web/src/layouts/MainLayout.vue
web/src/main.ts

Add a new ENV for it: `ZO_FAST_MODE_FILE_LIST_INTERVAL=300`, update every 5 minutes.
Other new environments:
```
ZO_RUM_ENABLED=false
ZO_RUM_CLIENT_TOKEN=""
ZO_RUM_APPLICATION_ID=""
ZO_RUM_SITE=""
ZO_RUM_SERVICE=""
ZO_RUM_ENV=""
ZO_RUM_VERSION=""
ZO_RUM_ORGANIZATION_IDENTIFIER=""
ZO_RUM_API_VERSION=""
ZO_RUM_INSECURE_HTTP=false
O2_CUSTOM_SLACK_URL=""
O2_CUSTOM_DOCS_URL=""
```
- Doc URL and Slack URL will be custom configurable for enterprise version
- RUM configuration can be enabled via environment variable.

fix: cache latest file & cache stream fields

---

src/common/infra/cluster/etcd.rs
src/common/infra/cluster/mod.rs
src/common/infra/cluster/nats.rs
src/config/src/config.rs
src/main.rs
src/service/distinct_values.rs
src/service/search/datafusion/exec.rs
src/service/search/datafusion/rewrite.rs

fix: add group by field to select

---

web/src/components/rum/AppTable.vue
web/src/views/RUM/AppErrors.vue
web/src/views/RUM/AppSessions.vue

fix: RUM session and error explorer issues

---

web/src/components/logstream/schema.vue
web/src/components/rum/PlayerEventsSidebar.vue
web/src/components/rum/performance/ApiDashboard.vue
web/src/components/rum/performance/ErrorsDashboard.vue
web/src/components/rum/performance/PerformanceSummary.vue
web/src/components/rum/performance/WebVitalsDashboard.vue
web/src/views/Dashboards/RenderDashboardCharts.vue
web/src/views/RUM/AppErrors.vue
web/src/views/RUM/AppPerformance.vue
web/src/views/RUM/SessionViewer.vue

fix #2982
1. Fix RUM performance dashboards overlapping issue
2. Fixed search field not found issues in Error Explorer when data is not present
3. Fixed filtering of session events in session viewer
4. Partition key not getting restored in UI after saving  #2976

fix: RUM error explorer UI issues

---

web/src/layouts/MainLayout.vue

fix: set rum user for non cloud

---

tests/api-testing/tests/test_search.py

- added match all valid cases for histogram and sql
- match_all_indexed cases for histogram and sql
- match_all_ignore case for histogram and sql
- match_all_indexed_ignorecase for histogram and sql

test: added testcase for search queries

---

web/src/components/dashboards/addPanel/ConfigPanel.vue
web/src/components/dashboards/panels/GeoMapRenderer.vue
web/src/utils/dashboard/convertMapData.ts

fix: error on blank input in dashboard panel config 

---

web/src/plugins/traces/Index.vue
web/src/plugins/traces/IndexList.vue

fix #3005 
1. By default added 0 min  100000 max duration
2. Removed duration slider

fix: updated traces duration filter functionality

---

web/src/components/iam/roles/EditRole.vue
web/src/composables/useStreams.ts

fix: enabled metadata streams in streams page

---

tests/api-testing/tests/test_search.py
tests/ui-testing/cypress/e2e/tests/dashboard/folders.cy.js

- added search API tests for aggregation queries
- fixed dashboard-folders tests

test: added aggregation queries and folders testcase fix

---

src/common/meta/search.rs
src/service/search/mod.rs
tests/ui-testing/cypress/e2e/allfunctions/logs.js
tests/ui-testing/cypress/e2e/tests/logs_queries.cy.js
tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
web/src/components/DateTime.vue
web/src/components/settings/General.vue
web/src/composables/useLogs.ts
web/src/layouts/MainLayout.vue
web/src/plugins/logs/Index.vue
web/src/plugins/logs/IndexList.vue
web/src/plugins/logs/SearchBar.vue
web/src/services/stream.ts
web/src/stores/index.ts
web/src/utils/zincutils.ts

- The notification has been eliminated during the configuration of absolute dates.
- The SQL mode should not trigger the query automatically upon deactivation if run query flag is true.
- The Histogram feature should remain inactive while SQL mode is enabled.
- Modifications related to the quick mode.
- Within SQL mode, the "_timestamp" field is required, and an "order by" clause is necessary.

feat: Interesting fields UI changes

---

tests/ui-testing/cypress/e2e/tests/dashboard/drilldown.cy.js
tests/ui-testing/cypress/support/commons.js

- should not allow adding drilldown without name
- should add variable under drilldown and verify if drilldown is added 
- delete the created dashboard once verification is done

test: added drilldown tests

---

src/infra/src/cache/file_data/disk.rs

fix: disk cache with s3 bucket prefix

---

src/common/infra/cluster/etcd.rs
src/common/infra/cluster/mod.rs
src/common/infra/cluster/nats.rs
src/common/infra/ofga.rs
src/common/meta/sql.rs
src/common/migration/mod.rs
src/common/migration/schema.rs
src/config/src/config.rs
src/infra/src/db/etcd.rs
src/infra/src/db/mod.rs
src/infra/src/db/mysql.rs
src/infra/src/db/nats.rs
src/infra/src/db/postgres.rs
src/job/files/parquet.rs
src/service/alerts/alert_manager.rs
src/service/db/ofga.rs
src/service/db/schema.rs
src/service/distinct_values.rs
src/service/search/datafusion/exec.rs
src/service/search/datafusion/rewrite.rs
src/service/search/datafusion/string_to_array_v2_udf.rs
src/service/search/sql.rs
web/src/components/dashboards/QueryEditor.vue
web/src/components/logstream/schema.vue
web/src/composables/useLogs.ts
web/src/composables/useSuggestions.ts
web/src/utils/dashboard/convertPromQLData.ts
web/src/utils/dashboard/convertSQLData.ts
web/src/views/Dashboards/ViewDashboard.vue
web/src/views/RUM/AppErrors.vue

To enable row per schema version use: ZO_ENTRY_PER_SCHEMA_VERSION_ENABLED = true.
One can migrate schemas from single row to row per schema version using : migrate-schemas command
Before migration :
- DROP INDEX meta_module_key2_idx ON meta
- ALTER TABLE meta ADD COLUMN start_dt BIGINT NOT NULL DEFAULT 0;
- CREATE UNIQUE INDEX meta_module_start_dt_idx ON meta (start_dt, key2, key1, module);

fix: schema versions as separate key

---

.github/workflows/ui-testing.yml

ensure that recording functionality is skipped during the forked PRs for the cypress tests.

test: Improve secret handling in forks

---

tests/ui-testing/cypress/e2e/tests/logs_queries.cy.js
web/src/composables/useLogs.ts
web/src/plugins/logs/SearchBar.vue

fix: saved view issues

---

src/config/src/config.rs
src/handler/http/request/status/mod.rs
src/service/dashboards/reports.rs
web/src/components/reports/CreateReport.vue
web/src/enterprise/mixins/mainLayout.mixin.ts
web/src/layouts/MainLayout.vue
web/src/mixins/mainLayout.mixin.ts

config settings for hiding menu items

feat: add custom hide menu field in the /config

---

web/src/composables/useLogs.ts
web/src/plugins/logs/Index.vue

Stream names with hyphen (-) were not getting parsed correctly

fix: stream names with hyphen (-) were not getting parsed correctly

---

src/config/src/utils/parquet.rs
src/ingester/src/partition.rs

chore: code refactor

---

src/common/utils/auth.rs
src/handler/http/request/status/mod.rs
src/handler/http/request/users/mod.rs
src/handler/http/router/mod.rs
src/service/functions.rs
src/service/search/mod.rs
web/src/components/iam/users/AddUser.vue
web/src/components/login/Login.vue
web/src/components/rum/VideoPlayer.vue
web/src/composables/router.ts
web/src/enterprise/composables/router.ts
web/src/enterprise/mixins/mainLayout.mixin.ts
web/src/layouts/MainLayout.vue
web/src/router/index.ts
web/src/services/http.ts
web/src/services/httpsearch.ts
web/src/services/users.ts
web/src/utils/zincutils.ts

This will break openobserve cloud , DON'T deploy UI changes until we accommodate cookies for cloud

chore: cookies for authentication

---

web/package.json

Fix missing module date-fns. Fixes #2709

fix: missing module date-fns. Fixes #2709

---

Cargo.lock
Cargo.toml
src/main.rs

Debug mode:
```
RUSTFLAGS="--cfg tokio_unstable" cargo build --features=tokio-console
```
Relase mode:
```
RUSTFLAGS="--cfg tokio_unstable" cargo build --features=tokio-console --profile=release-profiling
```

fix: add tokio console

---

src/ingester/src/wal.rs

fix: wal on windows

---

web/src/plugins/traces/Index.vue

Added traces stream name to get trace details as now there can be multiple traces streams
fix: #3188

fix: trace details share link was not working

---

README.md
openobserve.cdx.xml
src/config/config.cdx.xml
src/infra/infra.cdx.xml
src/ingester/ingester.cdx.xml
src/proto/proto.cdx.xml
src/wal/wal.cdx.xml

Add SBOM (Software Bill of Materials) for OpenObserve in cyclonedx format. Also add instructions in README to generate fresh SBOM.

feat: add SBOM

---

src/handler/http/request/search/job.rs
src/handler/http/request/search/mod.rs
src/handler/http/request/traces/mod.rs

fix: modify cancel query status code to 429

---

src/common/meta/http.rs
src/common/utils/http.rs
src/config/src/config.rs
src/config/src/meta/search.rs
src/handler/grpc/mod.rs
src/handler/grpc/request/search.rs
src/handler/http/request/search/job.rs
src/handler/http/request/search/mod.rs
src/handler/http/request/traces/mod.rs
src/infra/src/cache/file_data/disk.rs
src/infra/src/cache/file_data/memory.rs
src/infra/src/cache/file_data/mod.rs
src/job/files/parquet.rs
src/proto/proto/cluster/common.proto
src/proto/proto/cluster/search.proto
src/service/alerts/mod.rs
src/service/promql/search/grpc/mod.rs
src/service/promql/search/grpc/storage.rs
src/service/promql/search/grpc/wal.rs
src/service/promql/search/mod.rs
src/service/search/datafusion/exec.rs
src/service/search/datafusion/storage/file_list.rs
src/service/search/grpc/mod.rs
src/service/search/grpc/storage.rs
src/service/search/grpc/wal.rs
src/service/search/mod.rs

Now, it will shows `trace_id` for search.

feat: replace `sessiond_id` to `trace_id` when enable tracing

---

src/common/infra/cluster/mod.rs

fix: #3190

---

web/src/components/dashboards/viewPanel/ViewPanel.vue
web/src/views/Dashboards/RenderDashboardCharts.vue

fix: dashboard view panel scroll issue

---

web/src/utils/zincutils.ts

Excluded iam routes from restricted route on data ingestion.

fix: excluded iam route

---

src/config/src/utils/asynchronism/file.rs
src/infra/src/db/nats.rs
src/job/files/mod.rs
src/job/files/parquet.rs
src/job/mod.rs

perf: add a job to clean empty dir to let scan_dir faster

---

src/config/src/meta/sql.rs

fix: sql fields parse error

---

src/config/src/meta/usage.rs
src/handler/http/request/search/mod.rs
src/service/usage/mod.rs

feat: introduce cached_ratio to usage reporting for search usage type

---

web/src/composables/useLogs.ts
web/src/plugins/logs/Index.vue
web/src/plugins/logs/SearchBar.vue

Fix for saved apply directly without navigating stream page.

fix: apply saved view error fix

---

web/src/utils/dashboard/useCustomDebouncer.ts

- for printmode, issue with isDashboardLoaded flag.

fix: isDashboardLoaded flag issue for print mode

---

Cargo.lock
Cargo.toml
src/common/infra/mod.rs
src/handler/http/request/alerts/destinations.rs
src/handler/http/request/alerts/mod.rs
src/handler/http/request/alerts/templates.rs
src/handler/http/request/search/mod.rs
src/handler/http/request/traces/mod.rs
src/service/alerts/destinations.rs
src/service/alerts/mod.rs
src/service/alerts/templates.rs
src/service/search/cluster/mod.rs
src/service/search/mod.rs

fix: value API is always waiting

---

src/service/enrichment_table/mod.rs

fix: enrichment table field name format

---

src/service/usage/mod.rs

fix: include all search events in usage reporting

---

src/ingester/src/lib.rs
src/ingester/src/partition.rs
src/job/files/parquet.rs
src/service/search/grpc/wal.rs

Get parquet metadata take a lot of time when the schema is very big, so we cache the metadata. it will more faster to load file for search.

perf: improve wal parquet load speed

---

src/service/usage/mod.rs

fix reqwest client auth issue when reporting usage remotely

fix: reporting usage remotely

---

web/src/components/ingestion/logs/KinesisFirehose.vue
web/src/components/ingestion/metrics/CloudWatchMetrics.vue

Add the missing org identifier to cloudwatch ingestion endpoints on UI

fix: UI - cloudwatch ingestion endpoints

---

web/src/composables/shared/router.ts
web/src/views/Functions.vue

Removed duplicated menus in pipeline tab and duplicated pipeline routes

fix: Ingestion pipeline UI issues

---

src/handler/http/router/ui.rs
src/infra/src/db/etcd.rs
src/infra/src/db/mod.rs
src/infra/src/db/mysql.rs
src/infra/src/db/nats.rs
src/infra/src/db/sqlite.rs
src/infra/src/file_list/mod.rs
src/infra/src/file_list/mysql.rs
src/infra/src/file_list/postgres.rs
src/infra/src/file_list/sqlite.rs
src/infra/src/lib.rs
src/infra/src/scheduler/mod.rs
src/infra/src/schema/history/mod.rs
src/infra/src/schema/history/mysql.rs
src/infra/src/schema/history/postgres.rs
src/infra/src/schema/history/sqlite.rs
src/infra/src/schema/mod.rs
src/job/files/parquet.rs
src/service/compact/retention.rs
src/service/db/schema.rs
src/service/search/grpc/wal.rs

feat: add schema history

---

.github/workflows/dispatch-event-enterprise.yml

For each incoming PR, build the enterprise container too.

ci: initiate enterprise build

---

web/src/utils/dashboard/convertSQLData.ts

fix: dashboard stacked chart wrong data render issue

---

tests/ui-testing/playwright-tests/logspage.spec.js
tests/ui-testing/playwright-tests/variable.spec.js

Dashboard : Multi select variables 
- Should select 1 variable 
- should select multiple variable
- should select All variables 
- Verify selection appears on UI. 
- Delete a panel and dashboard 
Logs:
- Search around to work when only histogram enabled 
- Search around to work when SQL is enabled

test: multi-select variables-logs-testcases

---

tests/ui-testing/playwright-tests/pipeline.spec.js

- Fix for add streamroute node flaky testcase

test: fix flaky testcase

---

src/config/src/config.rs
src/handler/http/request/status/mod.rs
web/src/components/common/AppTabs.vue
web/src/components/logstream/AddStream.vue
web/src/components/logstream/schema.vue
web/src/locales/languages/en.json

1. Users can define schema fields for existing streams.
2. During querying/exploring only those defined schema fields will be available in schema, rest all fields will be available in "_all" field in the schema.

feat: User defined schema for existing streams

---

.github/workflows/playwright.yml
tests/ui-testing/playwright-tests/region.spec.js

Tests for following scenarios
- Verify if user is able to view region tab
- Verify if user is able to click on region tab
- Verify if 2 options displayed under region tab
- Verify if 1 Region saved under saved view is displayed when the view applied
- Verify if user is able to select stream explorer and click on saved view only 1 selected option to be displayed
- Verify if saved view is deleted after adding only1 region should click on region, change

test: e2e-region-testcases

---

src/handler/http/request/search/mod.rs

fix: region filter for _around API

---

.github/workflows/playwright.yml
tests/ui-testing/playwright-tests/region.spec.js
tests/ui-testing/playwright-tests/schema.spec.js

Automation for below scenarios-
- Verify if Add to defined schema fields is displayed on UI
- Verify if on clicking the checkbox for items, the button gets enabled
- Verify on adding on user defined schema the selected fields are displayed.
- Verify after updating these settings user is able to navigate to stream via stream explorer
- Verify if user is able to click on log search results after updating schema settings
- Verify if the updated schema displayed under results as ALL post new data ingestion
- Verify if user is able to remove the fields and update the settings
- Verify after removing, the fields do not display under all in UI

test: e2e-user-defined-schema

---

Cargo.lock
Cargo.toml
src/common/utils/auth.rs
src/handler/http/auth/token.rs
src/handler/http/request/search/job.rs
src/service/ingestion/mod.rs
web/src/components/queries/RunningQueriesList.vue
web/src/services/search.ts

fix: invalid peer certificate

---

README.md

Add details of different editions in which OpenObserve is available. oss, enterprise and cloud

chore: add editions

---

web/src/components/pipeline/PipelineEditor.vue
web/src/components/pipeline/PipelinesList.vue

fix: pipelines with same name

---

README.md

Add workload management (QoS) to feature list.

chore: add QoS to feature list

---

README.md

Add audit trail to feature list

chore: Add audit trail feature

---

tests/ui-testing/playwright-tests/schema.spec.js

Testcases for the following scenarios - 
- Verify if user is able to create stream with empty name 
- Verify if user navigates to logs and selects empty name stream and then selects a stream with fields, all the data should load
- Verify if user is able to add field
- Verify if user is able to delete field

test: e2e-schema-testcases

---

src/common/meta/dashboards/v3/mod.rs
web/src/components/DateTime.vue
web/src/components/DateTimePickerDashboard.vue
web/src/components/dashboards/AddDashboard.vue
web/src/components/dashboards/settings/GeneralSettings.vue
web/src/composables/shared/router.ts
web/src/views/Dashboards/ViewDashboard.vue
web/src/views/Dashboards/addPanel/AddPanel.vue

feat: dashboard date-time settings

---

src/config/src/utils/record_batch_ext.rs
src/job/compact.rs
src/job/files/parquet.rs
src/service/compact/merge.rs
src/service/db/schema.rs
src/service/schema.rs

fix: use defined schema for vertical partition merge

---

src/handler/http/request/logs/ingest.rs
src/handler/http/request/metrics/ingest.rs
src/handler/http/request/search/mod.rs

- Add cluster selection in logs search queries for additional filtering based on region/clusters
- add org/stream info in ingestion http handler error logging

feat: cluster selection in logs

---

web/src/components/reports/CreateReport.vue

fix #3558 
1. Extra star appearing in cron field on edit
2. Editing an existing report gives error but works after reload
3. Change error message when saving report with same name

fix: report UI issues

---

src/common/meta/dashboards/reports.rs
src/service/dashboards/reports.rs

fix: add dynamic variables to report and allow v1, v2 dashboards in reports

---

src/handler/http/request/status/mod.rs

feat: support build-type in configuration

---

web/src/components/logstream/schema.vue

fix: fields getting duplicated in user defined schema

---

web/src/plugins/logs/IndexList.vue
web/src/services/stream.ts

add the missing clusters parameters to _value api calls

fix: _value api missing "clusters"

---

web/src/components/rum/VideoPlayer.vue

Fixed rrweb player import in RUM session VideoPlayer

fix: fixed rrweb player import

---

src/config/src/meta/search.rs
src/handler/http/request/search/mod.rs
web/src/composables/useLogs.ts

fix: search partition with base64

---

src/infra/src/file_list/mysql.rs
src/infra/src/file_list/postgres.rs
src/infra/src/file_list/sqlite.rs

feat: use global lock replace select for update for file list jobs

---

web/src/components/dashboards/SelectDashboardDropdown.vue
web/src/components/dashboards/SelectFolderDropdown.vue
web/src/components/dashboards/SelectTabDropdown.vue
web/src/plugins/logs/SearchBar.vue
web/src/plugins/logs/VisualizeLogsQuery.vue
web/src/plugins/metrics/AddToDashboard.vue

- `Add To Dashboard` pop up css issue.
- Confirmation dialog issue for logs visualize toggle button.

fix: visualization css issues

---

src/service/alerts/alert_manager.rs
src/service/alerts/mod.rs
src/service/search/sql.rs

fix: some small issues of alert

---

web/src/components/dashboards/PanelSchemaRenderer.vue
web/src/components/dashboards/panels/ChartRenderer.vue
web/src/utils/dashboard/convertSQLData.ts

- `convertSQLData`: Cache `xAxis` data that has been converted to the appropriate timezone.

perf: breakdown timechart performance improvement

---

src/cli/data/export.rs
src/handler/http/request/search/mod.rs
src/handler/http/request/search/multi_streams.rs
src/handler/http/request/traces/mod.rs
src/service/alerts/mod.rs
src/service/db/enrichment_table.rs
src/service/metrics/prom.rs
src/service/search/cache/mod.rs
src/service/search/mod.rs
src/service/usage/stats.rs

Reverts openobserve/openobserve#4726

Revert "feat: use one trace_id for all query in query cache"

---

src/service/search/cluster/mod.rs
src/service/search/mod.rs

fix tracing for query cache, make all query in query cache have one trace_id, like below

fix: tracing for query cache

---

src/handler/http/request/short_url/mod.rs

fix: invalid short url redirect

---

src/handler/http/request/short_url/mod.rs

fix: `shorten` api error handling

---

src/common/utils/http.rs
src/config/src/meta/search.rs
src/config/src/meta/usage.rs
src/handler/http/request/search/mod.rs
src/handler/http/request/search/multi_streams.rs
src/service/search/cache/mod.rs
src/service/search/mod.rs
src/service/usage/mod.rs

cherry-pick from https://github.com/openobserve/openobserve/pull/4784

feat: add short and long query to usage reported

---

web/src/components/dashboards/addPanel/HistogramIntervalDropDown.vue

feat: added new options for histogram intervals

---

src/common/meta/organization.rs
src/config/src/meta/usage.rs
src/config/src/metrics.rs
src/handler/grpc/request/search/mod.rs
src/handler/http/request/organization/settings.rs
src/service/db/organization.rs
src/service/ingestion/mod.rs
src/service/logs/bulk.rs
src/service/logs/ingest.rs
src/service/logs/mod.rs
src/service/logs/otlp_grpc.rs
src/service/logs/otlp_http.rs
src/service/logs/syslog.rs
src/service/schema.rs
src/service/usage/mod.rs
src/service/usage/stats.rs
web/src/components/settings/OrganizationSettings.vue
web/src/layouts/MainLayout.vue
web/src/locales/languages/en.json

for #4899 
This adds a conditional logging for ingestion errors, adds dropped count in the usage report and adds a metric for ingestion errors.
Currently only done for log streams,  traces and metrics are WIP.

feat: add logs and metrics for ingestion errors

---

web/src/utils/billing/convertBillingData.ts

- Tooltip issue with multiple series.

fix: tooltip issue for billing page usage chart

---

src/config/src/meta/search.rs
src/handler/http/request/search/search_job.rs
src/infra/src/table/search_job/search_jobs.rs
src/service/search_jobs.rs

```
curl --request GET \
--url 'http://localhost:5080/api/default/search_jobs/bL3PkaKBp9maA6DpJ8Z/result?from=10&size=30' 
```

feat: add pagination for search job result

---

web/src/components/dashboards/PanelSchemaRenderer.vue

fix: dashboard promql chart fails to render

---

web/src/composables/useLogs.ts
web/src/ts/interfaces/query.ts

fix: multi region search in web sockets

---

tests/ui-testing/playwright-tests/sanity.spec.js
web/src/components/alerts/AlertList.vue
web/src/plugins/logs/IndexList.vue

1. select stream as a place holder text added in logs page

fix: place holder text for select stream

---

.github/workflows/playwright.yml
tests/ui-testing/pages/dashboardPage.js
tests/ui-testing/pages/loginPage.js
tests/ui-testing/pages/reportsPage.js
tests/ui-testing/playwright-tests/reportsUpdated.spec.js
tests/ui-testing/playwright-tests/reportsUpdated2.spec.js

Reports playwright two parts with added test cases in Super Cluster

test: Reports playwright two parts with added test cases in Super Cluster

---

src/service/search/cache/cacher.rs
src/service/search/cache/mod.rs
src/service/search/cache/multi.rs
web/src/composables/useLogs.ts
web/src/ts/interfaces/query.ts

1. multi region search in web sockets (#5871)
2. fix: result cache (#5872)
3. fix: search api pagination when cache enabled (#5893)

fix: cherry pick fixes v0.14.2-pb1

---

src/infra/src/lib.rs
src/infra/src/local_lock.rs
src/service/schema.rs

This PR add a new library, `local_lock` compare to `dist_lock` it only create a lock for sharing in local threads.

feat: add local lock

---

src/service/schema.rs

to ensure only one thread updates db and the rest gets from cache

fix: schema db update 

---

.github/workflows/playwright.yml
tests/ui-testing/playwright-tests/schemaload.spec.js

**Tests covered** 
- Ingest 79k fields with 100 user defined schema
- Reset stream selection while reloading home page and navigating to logs
- Selecting stream and checking schema and values
- Go to streams page and enable store original data 
- Go to stresstest stream via stream explorer 
- Check if results are visible

test: e2e-logs-loadtest

---

src/common/infra/cluster/mod.rs
src/config/src/config.rs
src/infra/src/queue/mod.rs
src/infra/src/queue/nats.rs
src/infra/src/queue/nop.rs
src/service/search/grpc/storage.rs

perf: optimize search thread num

---

src/service/promql/search/cache/mod.rs
src/super_cluster_queue/alerts.rs
src/super_cluster_queue/short_urls.rs

This PR fixed the issue we didn't drop the part which less than start in metrics cache.

fix: metrics with cache

---

web/src/components/dashboards/settings/AddSettingVariable.vue

feat: dashboard variables added new streamType metadata

---

web/src/components/dashboards/settings/TabsSettings.vue
web/src/components/dashboards/settings/VariableSettings.vue

feat: dashboard reorder feature for variables listing

---

web/src/utils/dashboard/convertSQLData.ts

fix: Boolean breakdown field issue for dashboard stacked chart

---

src/job/alert_manager.rs
src/main.rs
src/service/promql/search/mod.rs

fix: promql return type error when the step over max_file_retention

---

web/src/views/Dashboards/RenderDashboardCharts.vue
web/src/views/Dashboards/ViewDashboard.vue

fix: disable resize and drag panel, if saveDashboard is ongoing

---

src/config/src/config.rs
src/handler/http/request/organization/settings.rs
src/handler/http/request/status/mod.rs
src/handler/http/request/websocket/mod.rs
src/handler/http/request/websocket/search.rs
src/handler/http/request/websocket/session.rs
src/handler/http/request/websocket/utils.rs
src/main.rs
src/router/http/mod.rs

New Env: 
```
ZO_WEBSOCKET_ENABLED=true
ZO_WEBSOCKET_CLOSE_FRAME_DELAY=50 // microseconds
ZO_WEBSOCKET_SESSION_IDLE_TIMEOUT_SECS=300
ZO_WEBSOCKET_SESSION_MAX_LIFETIME_SECS=3600
ZO_WEBSOCKET_SESSION_GC_INTERVAL_SECS=60
ZO_WEBSOCKET_PING_INTERVAL_SECS=15
```

fix: ws connection optimizations

---

web/src/components/alerts/AddAlert.vue
web/src/components/alerts/PreviewAlert.vue
web/src/locales/languages/en.json

#6009 
Chart was not getting rendered due to empty Y-axis label

fix: Alerts preview not getting rendered 

---

src/config/src/meta/dashboards/v5/mod.rs
web/src/components/dashboards/addPanel/ConfigPanel.vue
web/src/composables/dashboard/usePanelDataLoader.ts
web/src/composables/useDashboardPanel.ts
web/src/services/search.ts

feat: dashboard step setting for promql query

---

web/src/composables/dashboard/usePanelDataLoader.ts

fix: dashboard promql step undefined error

---

src/common/infra/cluster/mod.rs
src/handler/grpc/flight/mod.rs
src/ingester/src/errors.rs
src/ingester/src/wal.rs
src/service/promql/engine.rs
src/service/promql/search/mod.rs
src/service/search/cluster/flight.rs
src/service/search/cluster/http.rs
src/service/search/datafusion/distributed_plan/remote_scan.rs
src/service/search/datafusion/plan/tantivy_count_exec.rs
src/service/search/datafusion/udf/str_match_udf.rs
src/service/search/grpc/flight.rs
src/service/search/grpc/wal.rs
src/service/search/mod.rs
src/service/search/super_cluster/follower.rs

There is a lot of small RecordBatch in memory, merge it into big RecordBatch can improve the memory usage and search speed.

perf: improve search in memory

---

web/src/composables/useLogs.ts
web/src/composables/useWebSocket.ts
web/src/plugins/logs/Index.vue
web/src/ts/interfaces/query.ts

1. Fixed cancel query flow
2. Reset request trace_id's and cancel query operation before initiating new search operation
3. Run query disabling histogram, later enable histogram. This was throwing error

fix: websocket frontend issues

---

src/common/meta/http.rs
src/handler/http/request/dashboards/mod.rs
src/service/dashboards/mod.rs
src/service/organization.rs
tests/integration_test.rs

https://github.com/openobserve/o2-enterprise/issues/366

fix: Filter items returned by `ListDashboards` by permissions

---

.github/workflows/playwright.yml

- updated the runner specs from ubicloud-standard-16 to ubicloud-standard-8 to avoid throttling.

fix: change ubicloud runner specs

---

src/config/src/meta/stream.rs

on serailization we deduplicate udf fields and then store in DB

fix: Dedup UDS fields

---

src/config/src/config.rs
src/handler/http/request/websocket/session.rs
src/service/search/datafusion/udf/regexp_matches_udf.rs

- fix #6106
- fix: re_matches udf #6112

fix: cherry-pick udf & closeframe

---

.github/workflows/playwright.yml
src/config/src/meta/pipeline/components.rs
src/config/src/meta/pipeline/mod.rs
src/handler/grpc/request/ingest.rs
src/job/promql_self_consume.rs
src/proto/proto/cluster/ingest.proto
src/proto/src/generated/cluster.rs
src/service/alerts/scheduler.rs
src/service/self_reporting/ingestion.rs
tests/ui-testing/pages/logsPage.js
tests/ui-testing/pages/pipelinePage.js
tests/ui-testing/playwright-tests/pipelines.spec.js
web/src/components/alerts/ScheduledAlert.vue
web/src/components/common/sidebar/FieldList.vue
web/src/components/functions/TestFunction.vue
web/src/components/logstream/AddStream.vue
web/src/components/pipeline/NodeForm/AssociateFunction.vue
web/src/components/pipeline/NodeForm/PreviewPromqlQuery.vue
web/src/components/pipeline/NodeForm/Query.vue
web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
web/src/components/pipeline/NodeForm/Stream.vue
web/src/components/pipeline/PipelineEditor.vue
web/src/composables/useLogs.ts
web/src/plugins/logs/JsonPreview.vue
web/src/plugins/logs/TenstackTable.vue
web/src/plugins/pipelines/CustomEdge.vue
web/src/plugins/pipelines/CustomNode.vue
web/src/plugins/pipelines/useDnD.ts

1. this PR introduces new design for query node 
2. dynamic stream name for destination node instead of create new stream it allows user to input any non existing stream name as destination and at the time of ingestion it will be created dynamically
3. Fixes issues of #5886

fix: Pipeline improvements 

---

web/src/components/dashboards/panels/CustomChartRenderer.vue
web/src/composables/useDashboardPanel.ts
web/src/utils/dashboard/convertCustomChartData.ts
web/src/utils/dashboard/convertPanelData.ts
web/src/views/Dashboards/ViewDashboard.vue

1. no data error before rendering
2. chart rerenders even after loading
3. all charts rererenders if we click on refresh of one chart

fix: custom chart rerendering issues

---

web/src/composables/useLogs.ts

fix: extractvalue query fix

---

src/config/src/utils/flatten.rs
src/job/compactor.rs
src/job/files/parquet.rs
src/service/db/file_list/broadcast.rs

fix: fields missing issue

---

web/src/components/pipeline/NodeForm/Query.vue
web/src/components/pipeline/PipelinesList.vue

1. reduced query time for sql validation from 15mins to 5 seconds 
2. silence column is removed from the pipeline list as we are not supporting in the UI

fix: reduce query time and silence column removal

---

src/router/http/ws.rs

- Impl `WsProxySession` and `Drop`

fix: ws open fds at router

---

src/service/pipeline/batch_execution.rs

feat: improve remote pipeline

---

src/job/metrics.rs
src/service/search/sql.rs
src/service/search/utils.rs

fix: #6170

---

web/src/composables/dashboard/usePanelDataLoader.ts

fix: search type issue for reports

---

.cargo/audit.toml
src/cli/data/export.rs
src/config/src/config.rs
src/config/src/meta/cluster.rs
src/config/src/meta/search.rs
src/handler/http/request/search/around.rs
src/handler/http/request/search/mod.rs
src/handler/http/request/search/multi_streams.rs
src/handler/http/request/traces/mod.rs
src/proto/proto/cluster/plan.proto
src/proto/src/generated/cluster.rs
src/service/alerts/mod.rs
src/service/db/enrichment_table.rs
src/service/metrics/prom.rs
src/service/search/cluster/flight.rs
src/service/search/datafusion/distributed_plan/node.rs
src/service/search/datafusion/distributed_plan/remote_scan.rs
src/service/search/mod.rs
src/service/search/request.rs
src/service/search/super_cluster/follower.rs

feat: use local node for load enrichmentable

---

web/src/views/Dashboards/Dashboards.vue

1. added search feature for folders
2. added navigation to respective folder when user clicks on any folder name when using search across folders feature

fix: Dashboard folders improvements

---

web/src/plugins/logs/IndexList.vue

fix: cluster info in values api.

---

web/src/views/Dashboards/Dashboards.vue

This PR removes the extra padding added around dashboard folder search and also added some padding the y axis

fix: dashboards folder search extra padding removed

---

web/src/components/settings/index.vue

1. this PR adds the limit for splitter in management page/ settings page

fix: splitter limit in management page

---

web/src/composables/useLogs.ts
web/src/plugins/logs/JsonPreview.vue

1. This PR fixes the issue in #5993

fix: unflattened data expand in logs page fixed

---

web/src/components/alerts/AlertList.vue

1. removed condition / sql from the main columns and included in the expanded row 
2. added period , frequency in the columns
3. the name of the alert would be truncated to 50chars 
4. the owner if it is greater than 20 displaying first 10 and last 4 remaining will be ****

fix: Alert table changes

---

src/common/infra/cluster/mod.rs
src/common/infra/cluster/nats.rs
src/common/infra/cluster/scheduler.rs
src/config/src/metrics.rs
src/config/src/utils/sysinfo/mod.rs
src/config/src/utils/sysinfo/net.rs
src/config/src/utils/sysinfo/os.rs
src/proto/proto/cluster/node.proto
src/proto/src/generated/cluster.rs
src/service/node.rs

- add `zo_node_open_fds` & `zo_node_tcp_conn_resets` to node metrics

feat: add `zo_node_open_fds` & `zo_node_tcp_conn_resets` metrics

---

src/service/logs/bulk.rs
src/service/logs/ingest.rs
src/service/logs/syslog.rs
src/service/pipeline/batch_execution.rs

fix: handle timestamp after pipeline processing

---

web/src/composables/useDashboardPanel.ts
web/src/locales/languages/en.json
web/src/utils/dashboard/convertDashboardSchemaVersion.ts
web/src/utils/dashboard/convertDataIntoUnitValue.ts
web/src/views/Dashboards/DashboardJsonEditor.vue
web/src/views/Dashboards/ViewDashboard.vue

feat: dashboard `JSON` schema editor

---

web/src/components/alerts/AlertList.vue

this PR introduces some changes in alert list those are 
1. added period , frequency columns in the table 
2. moved condition , description to the expanded row so when user clicks on row it will get expanded and will be visible
3. the alert name is now trimmed to 50 chars if it is greater than 50 and on hover it will be shown the full.
4. the owner it is greater than 20 then first 10 and last 4 chars will be visible and remaining between and also added tooltip to view full owner if is > 20 chars

fix: Alert list table changes 

---

web/src/components/dashboards/PanelContainer.vue
web/src/components/dashboards/PanelSchemaRenderer.vue
web/src/components/dashboards/panels/TableRenderer.vue

feat: download raw data as csv/json for dashboard panel

---

src/config/src/config.rs
src/service/promql/search/cache/mod.rs

fix: disable query cache if disk_cache is disabled

---

src/job/mod.rs
src/main.rs

fix: caching pipeline after enrichment_table is cached

---

src/job/mod.rs

remove cluster stream stat cache at startup

fix: cancel init cache stat

---

src/common/infra/ofga/migrations/alert_folders.rs
src/common/infra/ofga/mod.rs
src/job/stats.rs
src/service/db/ofga.rs
src/service/metrics/otlp.rs
src/service/metrics/prom.rs
src/super_cluster_queue/alerts.rs

fix: histogram stream sync

---

web/src/composables/useDashboardPanel.ts

fix: with query fields validation issue

---

src/config/src/meta/destinations.rs
src/handler/http/models/destinations.rs
web/src/components/actionScripts/EditScript.vue
web/src/components/alerts/AlertsDestinationList.vue
web/src/components/alerts/ImportDestination.vue
web/src/components/functions/TestFunction.vue
web/src/composables/shared/useEnterpriseRoutes.ts
web/src/layouts/MainLayout.vue
web/src/locales/languages/en.json

fix: Actions UI issues

---

web/src/components/actionScripts/ActionScipts.vue
web/src/components/alerts/AddDestination.vue
web/src/components/alerts/ImportDestination.vue
web/src/composables/useActions.ts
web/src/layouts/MainLayout.vue
web/src/locales/languages/en.json
web/src/plugins/traces/TraceDetails.vue

1. If actions are disabled and user tries to import action in destination, Unknown Error was shown instead of 'Action type not supported'

fix: added errors when actions are not enabled while creating destination

---

web/src/components/dashboards/addPanel/ConfigPanel.vue
web/src/components/dashboards/addPanel/DrilldownPopUp.vue
web/src/utils/dashboard/convertSQLData.ts

fix: dashboard breakdown value not present chart not getting plot

---

src/service/alerts/mod.rs
tests/ui-testing/playwright-tests/sanity.spec.js
web/src/components/alerts/AddAlert.vue
web/src/components/alerts/AlertList.vue
web/src/components/alerts/ImportAlert.vue
web/src/components/common/sidebar/AddFolder.vue
web/src/components/common/sidebar/FolderList.vue
web/src/components/common/sidebar/MoveAcrossFolders.vue
web/src/components/common/sidebar/SelectFolderDropDown.vue
web/src/components/iam/roles/EditRole.vue
web/src/components/iam/roles/PermissionsTable.vue
web/src/locales/languages/en.json
web/src/services/alerts.ts
web/src/services/common.ts
web/src/stores/index.ts
web/src/utils/commons.ts
web/src/views/Dashboards/Dashboards.vue

implemented alerts folders in the UI
1. search across folders
2. alert listing page moved condition and description column to the expand so whenever user clicks on any row it will show respective condition and description if there
3. provided fixed width for columns so that all columns are in view port visibility expect name column as it can be varied depending upon name given by user
4. search across all folders implemented in this PR only
Import alert add ons
1 additional things done to import alert as well like introducing the folders in import page

feat: alerts folder implementation (UI)

---

web/src/components/dashboards/PanelSchemaRenderer.vue
web/src/components/dashboards/viewPanel/ViewPanel.vue
web/src/plugins/metrics/Index.vue
web/src/views/Dashboards/addPanel/AddPanel.vue

fix: dashboard empty error issue

---

web/src/locales/languages/en.json
web/src/plugins/logs/SearchBar.vue
web/src/plugins/logs/SyntaxGuide.vue
web/src/plugins/logs/TransformSelector.vue

1. added tooltip for every icons in icon bar

fix: added tooltip for all icons in icon bar

---

web/src/components/actionScripts/EditScript.vue
web/src/composables/useLogs.ts
web/src/locales/languages/en.json

1. Remove action_id from Histogram and Page-count search payload
2. Rename Action type `Service` to `Real Time`
3. Added validation for service account selection while creating action

fix: Actions UI improvements

---

src/config/src/meta/pipeline/mod.rs
src/service/alerts/alert.rs
src/service/ingestion/mod.rs
src/service/logs/bulk.rs
src/service/logs/ingest.rs
src/service/logs/otlp_grpc.rs
src/service/logs/otlp_http.rs
src/service/logs/syslog.rs
src/service/pipeline/batch_execution.rs

- avoid creating empty stream with dynamic stream regex
- lower case all stream names created by pipeline, dynamic or static
fix #6383 and #6375

fix: pipeline dynamic stream

---

src/handler/http/models/alerts/responses.rs
web/src/components/alerts/AlertList.vue
web/src/components/alerts/ImportAlert.vue
web/src/components/common/sidebar/SelectFolderDropDown.vue
web/src/locales/languages/en.json

1. code refactoring for alert list

fix: alerts folders UI improvements 

---

src/handler/grpc/flight/mod.rs

improve openobserve trace when openobserve enable tracing

feat: add a span when FlightSenderStream drop

---

web/src/composables/useLogs.ts
web/src/plugins/logs/SearchResult.vue

1. This PR fixes the histogram no data for histogram found only when there is no data

fix: histogram issue

---

web/src/components/alerts/AlertList.vue

1. This PR will allow cloning of alerts to different folders

fix: added folders in cloning of alerts

---

src/config/src/meta/self_reporting/usage.rs
src/config/src/metrics.rs
src/infra/src/db/mysql.rs
src/infra/src/db/postgres.rs
src/infra/src/file_list/mysql.rs
src/infra/src/file_list/postgres.rs
src/infra/src/scheduler/mysql.rs
src/infra/src/scheduler/postgres.rs
src/infra/src/schema/history/mysql.rs
src/infra/src/schema/history/postgres.rs
src/service/alerts/scheduler/handlers.rs
src/service/ingestion/mod.rs

- Add key to DB_QUERY_NUMS metrics
- Remove all the delete calls from scheduler

fix: remove scheduled_jobs delete calls from scheduler

---

src/handler/http/request/stream/mod.rs

fix: #6454

---

web/src/components/settings/Nodes.vue
web/src/components/settings/index.vue
web/src/composables/useIsMetaOrg.ts

1. this PR will fix the issues in #6444

fix: node list changes

---

web/src/utils/dashboard/convertDataIntoUnitValue.ts

fix: validate filters config while dashboard panel save

---

src/service/search/datafusion/distributed_plan/remote_scan.rs

With this PR we can print the num_rows returns by each node.

fix: add num_rows for node response for query

---

src/infra/src/table/ratelimit.rs

Remove the sleep for update API.

fix: optimize update slow

---

src/config/src/utils/sysinfo/mod.rs

fix: cpu usage

---

src/config/src/router.rs
src/router/http/mod.rs

fix: ingest route incorrectly recognized as ws route

---

src/service/websocket_events/utils.rs

fix: ws error code to match http code

---

src/router/http/ws_v2/connection.rs
src/router/http/ws_v2/handler.rs

fix: ws locks

---

src/service/alerts/alert.rs

fixed https://github.com/openobserve/openobserve/issues/6471

fix: variable should not be escaped

---

web/src/components/alerts/AddAlert.vue
web/src/components/alerts/ImportAlert.vue
web/src/components/pipeline/PipelineEditor.vue

1. this PR fixes the issue #6530

fix: multiple api calls issue while creating pipelines , alerts

---

web/src/components/dashboards/PanelContainer.vue
web/src/components/dashboards/PanelSchemaRenderer.vue
web/src/components/dashboards/panels/ChartRenderer.vue
web/src/components/dashboards/panels/CustomChartRenderer.vue
web/src/components/dashboards/viewPanel/ViewPanel.vue
web/src/composables/dashboard/usePanelDataLoader.ts
web/src/plugins/metrics/Index.vue
web/src/views/Dashboards/addPanel/AddPanel.vue

fix: show 4xx error message on UI

---

web/src/utils/query/sqlUtils.ts

fix: `LIKE` query parsing issue for visualization

---

web/src/components/reports/CreateReport.vue

fix: added validation for six * cron expression

---

src/service/search/mod.rs
src/service/search/partition.rs

fix: mini partitions ordering

---

web/src/components/functions/EnrichmentSchema.vue
web/src/components/functions/EnrichmentTableList.vue

1. additional info to the enrichment table added 
2. schema page introduced for enrichment tables

fix: Enrichment table additional info added and schema page added

---

web/src/components/iam/roles/EditRole.vue
web/src/components/pipeline/ImportPipeline.vue
web/src/components/pipeline/PipelineEditor.vue
web/src/components/pipeline/PipelinesList.vue
web/src/composables/shared/router.ts
web/src/locales/languages/en.json

1. This PR implements the #6212

feat: pipeline import and export

---

web/src/plugins/logs/SearchHistory.vue

1. some times due to same trace id for multiple rows when we expand it will lead to expanding the same trace id rows (multiple) for that we had a fix like combination of trace_id + sql which would be unique but due to some times we might get same trace_id and sql as well 
2. to fix this when we are receiving response we are dynamically generating UUID for each hit and assigning it to each row so that we will expand based on UUID

fix: expand row needs to have unique row id in search history

---

.github/workflows/playwright.yml
tests/ui-testing/pages/alertsPage.js
tests/ui-testing/playwright-tests/alertsfolders.spec.js

These tests include 
- Added a new alert
- Add a new folder
- Added a new alert in this folder
- Moved 1 alert in 1 folder
- Bulk move alerts from default folder to new created folder
- Deleted the alerts that were moved to new folder
- Deleted the folder
- Deleted the template and destination

test: alert-folder-testcases

---

src/config/src/meta/alerts/mod.rs
src/handler/http/models/alerts/mod.rs
src/infra/src/file_list/mod.rs
src/infra/src/file_list/mysql.rs
src/infra/src/file_list/postgres.rs
src/infra/src/file_list/sqlite.rs
src/infra/src/table/alerts/mod.rs
src/service/alerts/mod.rs
src/service/compact/merge.rs
src/service/compact/retention.rs
src/service/file_list.rs
src/service/search/sql.rs

This PR implement add new files & delete merged files into one transaction then we can both succeed or failed.

fix: add new file & delete merged file should be in one transcation

---

web/src/components/pipeline/ImportPipeline.vue

while importing the pipeline if the node is function or condition node then we dont have org_id in the data object so we need to skip the validation the node is fn or condition

fix: if pipeline node is function or condition skip org validation 

---

web/src/components/alerts/ImportAlert.vue
web/src/components/alerts/ImportDestination.vue

fix: import dest , alert issues

---

src/common/infra/config.rs
src/handler/http/request/ws_v2/session.rs
src/service/websocket_events/search.rs
src/service/websocket_events/utils.rs

fix: ws remove locks from querier

---

web/src/composables/useLogs.ts

this PR removes the console logs that were added during WITH query development

fix: removed console logs from logs page

---

src/service/ingestion/grpc.rs

fix:  otel logs fields type is not correct

---

web/src/components/settings/Nodes.vue
web/src/locales/languages/en.json

1. This PR fixes the minor issues that are there in node list UI 
2. --> when the node is offline or prepare state then the border to the particular is not shown
3. --> change header of TCP to TCP Connections in table

fix: node list UI issues

---

web/src/components/functions/EnrichmentTableList.vue

1. this PR fixes the issue of #6645

fix: changed the start time of explore of enrichment table from 1min to 1sec

---

src/config/src/meta/sql.rs
src/handler/http/request/search/mod.rs
src/service/websocket_events/search.rs

fix: `values` event sql

---

src/config/src/config.rs
src/handler/grpc/request/event.rs
src/proto/proto/cluster/common.proto
src/proto/proto/cluster/event.proto
src/proto/src/generated/cluster.rs

We should extent slice not replace slice for download with streaming.
Testing this feature need to enable ENV:
```
ZO_CACHE_LATEST_FILES_ENABLED = true
ZO_CACHE_LATEST_FILES_DOWNLOAD_FROM_NODE=true
```

fix: download multiple files

---

src/common/utils/auth.rs
src/handler/http/request/status/mod.rs
src/handler/http/request/users/mod.rs
tests/api-testing/tests/pages/enrichment_page.py
tests/api-testing/tests/test_websocket2.py

fixes : [6564](https://github.com/openobserve/openobserve/issues/6564)

fix: base64 encode cookies

---

src/config/src/meta/websocket.rs
src/service/websocket_events/search.rs
src/service/websocket_events/utils.rs
src/service/websocket_events/values.rs
tests/api-testing/tests/test_websocket2.py
web/src/components/common/LoadingProgress.vue
web/src/components/dashboards/PanelSchemaRenderer.vue
web/src/composables/dashboard/usePanelDataLoader.ts
web/src/composables/useLogs.ts

feat: add `EventProgress` server event

---

src/handler/http/request/ws/mod.rs
src/handler/http/request/ws/session.rs
src/router/http/ws/connection.rs
src/router/http/ws/handler.rs

- clone channel before spawning tasks
- disable tasks to clean up `ResponseRouter`

fix: channel closed

---

web/src/components/dashboards/addPanel/DrilldownPopUp.vue

fix: loading indicator while loading folders, dashboard or tabs in drilldown pop up

---

src/service/alerts/alert.rs
src/service/organization.rs

fix: summary api should list all folder alerts

---

src/service/websocket_events/search.rs
web/src/composables/dashboard/usePanelDataLoader.ts
web/src/composables/useLogs.ts

fix: encode search query if `ZO_UI_SQL_BASE64_ENABLED=true`

---

src/service/traces/mod.rs

fix: realtime pipeline for trace ingestion into wrong stream

---

src/config/src/metrics.rs
src/infra/src/storage/local.rs
src/infra/src/storage/remote.rs
src/job/file_downloader.rs
src/service/compact/merge.rs
src/service/search/grpc/storage.rs

fix: metrics for storage

---

web/src/components/HighLight.vue
web/src/plugins/logs/SearchResult.vue
web/src/plugins/logs/TenstackTable.vue

1. This PR reintroduces the highlighting the particular keywords that are there in the match_all or fuzzy_match_all conditions

 fix: highlight syntax in logs page

---

.github/workflows/playwright.yml
tests/ui-testing/pages/streamPage.js
tests/ui-testing/playwright-tests/streamname.spec.js
tests/ui-testing/utils/apiUtils.js

Added a test to add stream name and assert if stream with uppercase exists
add a stream with lowercase and assert if stream name with lowercase exists

test: e2e-stream-name

---

src/handler/grpc/flight/mod.rs
src/handler/grpc/request/search/mod.rs
src/proto/proto/cluster/search.proto
src/proto/src/generated/cluster.rs
src/service/search/datafusion/distributed_plan/remote_scan.rs
src/service/search/super_cluster/follower.rs
src/service/search/super_cluster/leader.rs
src/service/search/utils.rs

This syncs the scan stats across nodes from super cluster

fix: supercluster scan stats

---

src/common/utils/stream.rs
src/handler/http/request/status/mod.rs
src/service/stream.rs
web/src/composables/useLogs.ts
web/src/plugins/traces/Index.vue

fix: ZO_DEFAULT_MAX_QUERY_RANGE_DAYS env should be returned by streams list api

---

src/handler/grpc/flight/mod.rs
src/handler/grpc/request/search/mod.rs
src/proto/proto/cluster/search.proto
src/proto/src/generated/cluster.rs
src/service/search/super_cluster/follower.rs
src/service/search/super_cluster/leader.rs
src/service/search/utils.rs

cherry pick of https://github.com/openobserve/openobserve/pull/6763

fix: supercluster scan stats (#6763)

---

tests/ui-testing/playwright-tests/dashboards/dashboard-filter.spec.js

Fixed the skipped test cases by using an appropriate selector instead of force: true.

test: fix dashboard filter testcase

---

tests/ui-testing/pages/logsPage.js
tests/ui-testing/playwright-tests/logsqueries.spec.js

- Verify search results are triggered when pressing Cmd+Enter or Ctrl+Enter
- Verify query executes with keyboard shortcut after clicking elsewhere
- Verify different query executes with keyboard shortcut
- Verify SQL query executes with keyboard shortcut

test: e2e-cmd+enter-test

---

src/infra/src/cache/file_data/mod.rs
src/infra/src/storage/mod.rs
src/service/compact/flatten.rs

same changes as https://github.com/openobserve/openobserve/pull/6822

fix: validate download size with blob store and validate file

---

src/config/src/meta/search.rs
src/handler/http/request/search/mod.rs
src/handler/http/request/ws/session.rs
src/infra/src/db/nats.rs
src/infra/src/db/postgres.rs
src/ingester/src/writer.rs
src/service/compact/merge.rs
src/service/dashboards/mod.rs
src/service/file_list.rs
src/service/search/datafusion/plan/tantivy_count_exec.rs
src/service/search/grpc_search.rs
src/service/search/search_stream.rs
src/service/search/super_cluster/follower.rs
src/service/search_jobs.rs
src/super_cluster_queue/search_job/search_jobs.rs

This PR fixed machine id is `0` when we init ider.

fix: ider init with machine id

---

src/service/search/datafusion/optimizer/mod.rs

fix: match one join query with join key filter (#6845)

---

src/service/db/schema.rs
src/service/enrichment_table/mod.rs
src/service/search/search_stream.rs
src/service/stream.rs
src/super_cluster_queue/schemas.rs

fix: delete stream over regions

---

src/cli/basic/cli.rs
src/cli/basic/http.rs
src/common/infra/cluster/etcd.rs
src/common/infra/cluster/mod.rs
src/common/infra/cluster/nats.rs
src/config/src/meta/search.rs
src/config/src/metrics.rs
src/handler/http/request/status/mod.rs
src/handler/http/router/mod.rs

fix: consistent hashing

---

src/cli/basic/cli.rs
src/common/migration/file_list.rs
src/config/src/meta/stream.rs
src/handler/http/request/status/mod.rs
src/infra/src/file_list/mod.rs
src/infra/src/file_list/mysql.rs
src/infra/src/file_list/postgres.rs
src/infra/src/file_list/sqlite.rs
src/job/files/broadcast.rs
src/job/files/parquet.rs
src/proto/proto/cluster/common.proto
src/proto/src/generated/cluster.rs
src/service/compact/flatten.rs
src/service/compact/merge.rs
src/service/compact/worker.rs
src/service/db/file_list/broadcast.rs
src/service/db/file_list/mod.rs
src/service/file_list.rs

This PR fixed the issue we should use file id for consistent hashing for broadcast event

fix: broadcast event use file id

---

tests/ui-testing/playwright-tests/dashboards/dashboard-filter.spec.js
web/src/composables/dashboard/usePanelDataLoader.ts
web/src/utils/query/sqlUtils.ts

fix: pass query as single line for partition and search API call

---

tests/api-testing/tests/test_streaming.py

validate max_query_range for 1 hour pytest
1. HTTP Cache False
2. HTTP Cache True
3. Streaming Search Cache False
4. Streaming Search Cache True

test: validate max_query_range for 1 hour pytest

---

web/src/components/common/AppDialog.vue
web/src/components/dashboards/addPanel/Drilldown.vue
web/src/components/dashboards/addPanel/DrilldownPopUp.vue

In dashboard panel edit mode, repeatedly adding and closing a drill-down with an SQL query causes the UI to freeze due to a memory leak in the Quasar dialog component.

fix: Dashboard drilldown editor issue

---

web/src/components/common/AppDialog.vue
web/src/components/dashboards/addPanel/Drilldown.vue
web/src/components/dashboards/addPanel/DrilldownPopUp.vue

In dashboard panel edit mode, repeatedly adding and closing a drill-down with an SQL query causes the UI to freeze due to a memory leak in the Quasar dialog component.

fix: Dashboard drilldown editor issue (#6893)

---

web/src/plugins/traces/Index.vue
web/src/plugins/traces/IndexList.vue
web/src/plugins/traces/fields-sidebar/BasicValuesFilter.vue

Duration field was getting added to query as `duration (us)`. Added label key in field object for displaying label

fix: Added label for duration field in traces

---

src/common/migration/pipeline_func.rs
src/config/src/meta/alerts/mod.rs
src/config/src/meta/pipeline/components.rs
src/service/alerts/derived_streams.rs
src/service/alerts/scheduler/handlers.rs
src/service/search/grpc/storage.rs
web/src/components/pipeline/NodeForm/Query.vue
web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
web/src/locales/languages/en.json

companion fix pr for `main` branch:  https://github.com/openobserve/openobserve/pull/6872
- port the main implementation from main branch
- fix new bug introduced since original commit

fix: delay for scheduled pipeline

---

src/handler/http/models/destinations.rs
web/src/components/alerts/AddDestination.vue
web/src/components/pipeline/NodeForm/ExternalDestination.vue
web/src/ts/interfaces/alert.ts

1.This PR adds the output format to the external destination either json / ndjson , bydefault it is json

fix: add output format type for external destination(pipeline destination)

---

.github/workflows/release.yml

Added step to upload openobserve binaries to aws s3 bucket

ci: update release pipeline with s3 upload

---

web/src/composables/useLogs.ts

Auto-refresh-interval was showing `0 events out of 0` as histogram title when used with http2 streaming

fix: fixed auto-refresh-interval for logs http2 streaming

---

web/src/utils/dashboard/convertPromQLData.ts
web/src/utils/dashboard/convertSQLData.ts

fix: allow to select and copy series name from tooltip

---

src/common/utils/redirect_response.rs
src/handler/http/request/short_url/mod.rs
src/service/short_url.rs
web/src/composables/shared/router.ts
web/src/services/short_url.ts
web/src/views/ShortUrl.vue

with this POC we will let FE handle all short url redirections. We keep the old routes intact for backwards compatibility

fix: redirect short url

---

web/src/styles/tailwind.css

This PR fixes the fixed width to auto width before it was 150px which makes some menu to be 150px only

fix: menu , list , item-label at global css should not have fixed width

---

web/src/composables/useLogs.ts

1. This PR disables the search Job popup that comes after 2mins if the search is still going on

fix: disable search job popup 

---

src/config/src/utils/sql.rs

- fix: use sql ast to check distinct

fix: use sql ast to check distinct

---

src/handler/grpc/flight/mod.rs
src/handler/http/request/short_url/mod.rs
src/service/search/grpc/wal.rs

There are some edge case `wal` file can't be released, then the `wal` file can't be removed, it stays over 1 day.

fix: debug wal file lock issue

---

src/common/utils/redirect_response.rs
src/handler/http/request/short_url/mod.rs
src/service/short_url.rs
web/src/composables/shared/router.ts
web/src/plugins/logs/SearchBar.vue
web/src/services/short_url.ts
web/src/test/unit/helpers/handlers.ts
web/src/views/ShortUrl.spec.ts
web/src/views/ShortUrl.vue
web/src/views/__snapshots__/ShortUrl.spec.ts.snap

with this POC we will let FE handle all short url redirections. We keep the old routes intact for backwards compatibility
---------

fix: redirect short url (#7026)

---

web/src/components/iam/users/User.vue

1. This PR fixes the issue #7053

fix: get roles api should be triggered in non enterprise versions 

---

web/src/composables/useLogs.ts

1. This PR disables the search Job popup that comes after 2mins if the search is still going on

fix: disable search job popup  (#7050)

---

web/src/components/pipeline/NodeForm/Stream.vue

1. now we have increased the stream name to 100 chars 
2. this PR should allow user to add 3 different types of stream names 
1. example_stream_name
2. {dynamic_stream_name_output}
3. someprefix{stream_name}somesuffix

fix: pipeline dynamic stream name issue

---

web/src/views/ShortUrl.vue

fix: fixed short url redirection issue

---

src/service/search/datafusion/optimizer/add_sort_and_limit.rs
src/service/search/datafusion/optimizer/limit_join_right_side.rs
src/service/search/datafusion/optimizer/utils.rs
src/service/search/datafusion/plan/deduplication_exec.rs

fixed https://github.com/openobserve/o2-enterprise/issues/446

fix: a corner case for join match one

---

web/src/components/dashboards/VariablesValueSelector.vue
web/src/components/dashboards/settings/AddSettingVariable.vue
web/src/components/dashboards/settings/VariableQueryValueSelector.vue
web/src/composables/dashboard/usePanelDataLoader.ts
web/src/composables/dashboard/useValuesWebSocket.ts
web/src/composables/useDashboardPanel.ts
web/src/composables/useSearchWebSocket.ts
web/src/utils/dashboard/constants.ts
web/src/views/Dashboards/ViewDashboard.vue
web/src/views/Dashboards/addPanel/AddPanel.vue

feat: dashboard variables by default select all values

---

web/src/composables/dashboard/usePanelCache.ts
web/src/composables/dashboard/usePanelDataLoader.ts

fix: store dashboard panel cache on indexDB instead of in memory

---

web/src/composables/dashboard/usePanelDataLoader.ts

fix: cancel query issue with http streaming

---

src/common/infra/cluster/etcd.rs
src/common/infra/cluster/mod.rs
src/common/infra/cluster/nats.rs
src/config/src/config.rs
src/job/stats.rs

Add a separate task to update memory status every second.

fix: improve node status monitor

---

src/handler/http/request/search/mod.rs
src/service/search/cache/mod.rs
src/service/search/mod.rs
src/service/search/search_stream.rs

- fix: remove streaming_id on search error
- fix: skip streaming_aggs if is_http_distinct
- fix: _values_stream must honor payload size

fix: remove streaming_id on search error

---

src/config/src/config.rs
src/handler/http/request/status/mod.rs
src/service/search/datafusion/udf/mod.rs
src/service/search/datafusion/udf/str_match_udf.rs
src/service/search/index.rs
src/service/search/sql.rs

feat: str_match placeholder and match_field alias

---

src/service/search/cluster/flight.rs
src/service/search/super_cluster/follower.rs
src/service/search/super_cluster/leader.rs

This PR for fix enrichmentTable load shouldn't go to alert querier.

fix: node role should be already have value

---

src/service/search/cache/cacher.rs

previous ref: https://github.com/openobserve/openobserve/pull/5872

fix: cache delta start_time (#7367)

---

src/handler/http/request/status/mod.rs
src/service/search/cardinality.rs
src/service/search/mod.rs
src/service/search/partition.rs
web/src/composables/dashboard/usePanelDataLoader.ts

We set cardinality level by unique values:
```
impl From<f64> for CardinalityLevel {
fn from(value: f64) -> Self {
if value < 10000.0 {
CardinalityLevel::Low
} else if value < 1000000.0 {
CardinalityLevel::Medium
} else if value < 5000000.0 {
CardinalityLevel::High
} else {
CardinalityLevel::Huge
}
}
}
```
We set partition interval for cardinality level:
- Huge: skip partition
- High: maximum 2h
- Medium: maximum 6h
- Low: maximum 24h

feat: add cardinality check for agg cache

---

web/src/components/O2AIChat.vue

1.show unauthorised error when we get 403 status code in the o2 ai chat

fix: show unauthorised error in o2 ai chat

---

src/handler/http/request/search/search_stream.rs
src/service/search/cache/multi.rs
src/service/search/search_stream.rs
src/service/websocket_events/search.rs
src/service/websocket_events/values.rs

fix the error for AggStreamingCache
```
Error reading cached file: 
aggregations/default/logs/cdn_production/9412706757618569214_120/1751292000000000_1751296465000000_tmp.arrow, 
error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

chore: add some logs

---

src/config/src/config.rs
src/handler/http/request/status/mod.rs
web/src/components/dashboards/addPanel/ConfigPanel.vue
web/src/composables/useDashboardPanel.ts

New Env: 
```sh
ZO_DASHBOARD_SHOW_SYMBOL_ENABLED=false # default
```

feat: add env to show dashboard symbol

---

src/common/meta/ingestion.rs
src/config/src/config.rs
src/config/src/meta/self_reporting/usage.rs
src/handler/http/request/logs/ingest.rs
src/handler/http/router/mod.rs
src/service/logs/hec.rs
src/service/logs/ingest.rs
src/service/logs/mod.rs
tests/integration_test.rs

Cherry pick of https://github.com/openobserve/openobserve/pull/7043

feat: support hec format for ingestion for rc7

---

web/src/composables/useLogs.ts

fix: UI loading scansize fix rc9

---

web/src/locales/languages/en.json
web/src/plugins/logs/IndexList.vue

Reset button to reset selected table field on logs page

fix: added reset selected table fields button

---

tests/ui-testing/playwright-tests/dashboards/dashboard-transpose.spec.js
tests/ui-testing/playwright-tests/enrichment.spec.js
web/src/components/functions/EnrichmentTableList.vue
web/src/components/reports/ReportList.vue
web/src/composables/shared/router.ts
web/src/composables/useStreamingSearch.ts
web/src/views/Functions.vue

1. Handled Http2 streaming interruption due to cancel query
2. Fixed edit report reset state issue

fix: http2 streaming error handing and reports UI fixes

---

src/config/src/config.rs

This PR adds new Envs, these are for batch exporter exponential retry
___
Enhancement
___
- Add new environment variables for batch retry
- Define `batch_retry_max_attempts` setting
- Introduce `batch_retry_initial_delay_ms` setting
- Introduce `batch_retry_max_delay_ms` setting
___
<tr>
<td>
<details>
<summary><strong>config.rs</strong><dd><code>Add batch retry env configurations</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/config/src/config.rs …

fix: remote wal changes

---

web/src/components/alerts/AlertList.vue
web/src/components/functions/EnrichmentTableList.vue
web/src/components/functions/FunctionList.vue
web/src/components/pipeline/PipelinesList.vue
web/src/views/Dashboards/Dashboards.vue

1.  functions list and enrichment table list --> added padding for functions and enrichment tables list header
2. dashboards --> actions tab in dashboard table should be sticky always 
3. alert list -->  when it is realtime there wont be period and frequency 
4. pipeline list --> removed sql query column for both realtime and scheduled pipeline and also  when it is realtime period and frequency should be -- in all tabs
___
Enhancement
___
- Show “--” for empty alert period and frequency
- Hide period/frequency in real-time alerts tab
- Remove SQL Query column from pipelines list
- Custom table header and styling in dashboards
___ …

fix: Alerts , Dashboards, pipeline Tables made consistent with other tables

---

web/src/components/common/O2AIContextAddBtn.vue
web/src/components/functions/TestFunction.vue
web/src/plugins/logs/DetailTable.vue
web/src/plugins/logs/JsonPreview.vue
web/src/plugins/logs/TenstackTable.vue
web/src/plugins/logs/data-table/CellActions.vue

show o2 ai button when ai chat is enabled

fix: o2 ai button should only show when ai chat is enabled

---

tests/ui-testing/pages/alertsPages/alertsPage.js
web/src/components/alerts/AddAlert.vue
web/src/components/alerts/AlertsContainer.vue
web/src/components/alerts/PreviewAlert.vue
web/src/components/alerts/RealTimeAlert.vue
web/src/components/alerts/ScheduledAlert.vue
web/src/components/functions/AddFunction.vue
web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
web/src/components/pipeline/PipelineEditor.vue
web/src/utils/zincutils.ts

1. the header for every section should have different color than the rest of the section to identify it as a header
2. the preview header should also different color than the rest of the section
3. multi window should be by default collapsed as it is not used that much
4. when loosing focus on sql editor / vrl editor it is emitting 2 times instead of 1 , which causes 2 search calls instead of 1
5. cron expression should be displayed in readable format in multi window section
6. removed go deeper with advanced options subtitle for advanced setup section
___
___
- Adjust alert UI containers and colors
- Collapse Multi Window section by default
- Debounce editor blur events to avoid duplicates
- Display readable cron intervals using new util
___
<details> <summary><h3> …

fix: add alert UI issues

---

src/cli/basic/test.rs
src/cli/data/cli.rs
src/common/meta/middleware_data.rs
src/config/src/meta/inverted_index.rs

Tests
___
- Add grouping function tests for file/time strategies
- Add CLI argument parsing and struct tests
- Add middleware data parsing and filtering tests
- Add inverted index mode Display and conversion tests
- Extend record batch JSON conversion tests
___
<tr>
<td>
<details>
<summary><strong>test.rs</strong><dd><code>Add file grouping strategy tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/cli/basic/test.rs
<ul><li>Introduce tests for …

chore: add UTs, run fmt and clipyy

---

.github/workflows/playwright.yml
tests/test-data/cte_queries.json
tests/ui-testing/playwright-tests/GeneralTests/sanity.spec.js
tests/ui-testing/playwright-tests/Logs/logsqueries.cte.spec.js

___
- Add CTE logs queries E2E test suite
- Include JSON log fixture for CTE queries
- Update workflow to run new spec
- Adjust sanity tests: timeouts and skip histogram
___
```mermaid
flowchart LR
F["cte_queries.json fixture"]
T["logsqueries.cte.spec.js tests"]
W["playwright.yml update"]
S["sanity.spec.js adjustments"]
F -- "used by" --> T
T -- "registered in" --> W
```
<tr>
<td>
<details>
<summary><strong>sanity.spec.js</strong><dd><code>Add timeouts and skip histogram test</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

test: e2e-cte(with-queries)-testcases

---

src/config/src/meta/dashboards/v5/mod.rs
web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
web/src/composables/useDashboardPanel.ts
web/src/locales/languages/en.json
web/src/utils/dashboard/convertDataIntoUnitValue.ts
web/src/utils/dashboard/convertSQLData.ts
web/src/utils/dashboard/convertTableData.ts

- #7641
___
___
- Add `treatAsNonTimestamp` option to AxisItem struct
- Provide checkbox to mark table fields non-timestamp
- Initialize and reset `treatAsNonTimestamp` defaults
- Enhance timestamp detection and conversion utilities
- Fix legend label in English locale
___
```mermaid
flowchart LR
QF["Select field"] -- "toggle" --> CB["Mark as non-timestamp"]
CB -- "sets flag" --> TF["treatAsNonTimestamp"]
TF -- "influences" --> DT["isTimeStamp(sample, flag)"]
DT -- "if timestamp" --> CV["convert16DigitTimestamp"]
DT -- "else" --> OUT["Original value"]
CV -- "formatted date" --> OUT
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody></tr></tbody></table>
</details>
___

fix: dashboard 16 digit numeric value conversion

---

src/cipher/mod.rs
src/cipher/registry.rs
src/common/meta/saved_view.rs
src/common/utils/jwt.rs
src/config/src/utils/hash/mod.rs
src/handler/http/auth/token.rs
src/handler/http/request/status/mod.rs
src/handler/http/request/users/service_accounts.rs
src/job/cipher.rs
src/service/search/grpc/wal.rs

- also cleanup a few functions
- remove `async` from `verify_decode_token`
___
___
- Add unit tests for cipher, registry, saved_view, hash utils
- Refactor `verify_decode_token` logic with algorithm conversion
- Remove async from JWT calls in HTTP handlers
- Simplify code in registry, job/cipher, wal modules
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody></tr></tbody></table>
</details>
___

chore: add UTs, run fmt and clippy

---

.github/workflows/release.yml

updated github action role
___
Enhancement
___
- Use GitHub OIDC for AWS credentials
- Add AWS credentials configuration step
- Remove manual AWS secret environment variables
- Set id-token and contents permissions
___
```mermaid
flowchart LR
A["GitHub Actions release job"] -- "assume role via OIDC" --> B["AWS IAM Role"]
B -- "provide temporary credentials" --> A
A -- "upload artifacts with AWS CLI" --> C["S3 Bucket"]
```
<tr>
<td>
<details>
<summary><strong>release.yml</strong><dd><code>Configure OIDC AWS credentials and permissions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

ci: updated github action role

---

src/handler/http/request/search/mod.rs
src/service/search/sql/mod.rs

fix: value api with complex query

---

web/src/plugins/logs/Index.vue

1. This PR fixes the logs page side panel on close shows blank space

fix: expand logs side panel giving blank space

---

web/src/plugins/logs/Index.vue

This PR solves the issue in #7834

fix: only show message when histogram is eligible is false

---

.github/workflows/playwright.yml
tests/ui-testing/playwright-tests/dashboards/dashboard-html-chart.spec.js

___
- Add e2e tests for HTML chart panel
- Test basic HTML rendering and variable substitution
- Integrate tests with Page Object Model
- Include HTML chart test in CI workflow
___
```mermaid
flowchart LR
A["Login"] --> B["Ingest Data"]
B --> C["Navigate to Dashboard"]
C --> D["Create Dashboard"]
D --> E["Add HTML Panel"]
E --> F["Fill HTML Snippet"]
F --> G["Assert Rendering"]
G --> H["Save & Delete Dashboard"]
```
<tr>
<td>
<details>
<summary><strong>dashboard-html-chart.spec.js</strong><dd><code>Add HTML chart e2e test cases</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

test: add e2e tests for HTML chart

---

web/src/components/dashboards/addPanel/FieldList.vue

- Do not allow to modify stream type on visualization page.

fix: readonly stream type for visualization

---

web/package.json
web/src/plugins/logs/SearchBar.vue

This PR solves the issue in #7870

fix: csv export overlapping the fields

---

web/src/utils/dashboard/convertDataIntoUnitValue.ts
web/src/utils/dashboard/convertTableData.ts

fix: dashboard time conversion (#7869)

---

src/ingester/src/entry.rs
src/ingester/src/immutable.rs
src/ingester/src/partition.rs
src/service/db/enrichment_table.rs
src/service/db/session.rs
src/service/enrichment_table/mod.rs
src/service/metadata/trace_list_index.rs
src/service/traces/mod.rs

feat: remove default partition key for traces

---

web/package.json
web/src/plugins/logs/SearchBar.vue

This PR solves the issue in #7870

fix: json to csv converter using npm package

---

web/package-lock.json
web/package.json
web/src/plugins/logs/SearchBar.vue

This PR fixes the issue in #7870
___
Bug fix
___
- Replace custom CSV converter with `json2csv` library
- Handle commas inside fields correctly
- Add error handling and user notification
- Update dependencies with `json-2-csv`
___
```mermaid
flowchart LR
A["downloadLogs(data)"] --> B["json2csv(data)"]
B --> C["Create CSV file & download"]
B -- "error" --> D["Show error notification"]
```
<tr>
<td>
<details>
<summary><strong>SearchBar.vue</strong><dd><code>Use json2csv for CSV export</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix: use json2csv package for conversion

---

src/config/src/meta/search.rs
src/infra/src/db/mysql.rs
src/infra/src/db/postgres.rs
src/infra/src/file_list/mysql.rs
src/infra/src/file_list/postgres.rs
src/infra/src/scheduler/mysql.rs
src/infra/src/scheduler/postgres.rs
src/infra/src/schema/history/mysql.rs
src/infra/src/schema/history/postgres.rs
src/service/enrichment_table/mod.rs

- fix: remove module key from zo_db_query_nums metrics
- fix: super cluster sync for enrichment table delete file list
- fix: make order_by_metadata field serde optional in query Response

fix: sync changes from rc7 to rc9

---

web/src/locales/languages/en.json
web/src/plugins/logs/SearchBar.spec.ts
web/src/plugins/logs/SearchBar.vue
web/src/test/unit/helpers/setupTests.ts

Enhancement
___
- Add CSV/JSON dropdown in logs download menu
- Support JSON format and size validation
- Introduce file-type selector in custom download dialog
- Refactor CSV conversion with dynamic headers
___
```mermaid
flowchart LR
A["Download Button"] --> B["Show Download Menu"]
B -- "Select CSV/JSON" --> C["downloadLogs(data, format)"]
C --> D{"format == 'csv'?"}
D -- yes --> E["jsonToCsv → Blob(text/csv)"]
D -- no  --> F["JSON.stringify → Blob(application/json)"]
E & F --> G["Create File and Trigger Download"]
```
<tr>
<td>
<details>
<summary><strong>SearchBar.vue</strong><dd><code>Extend …

fix: added json download feature to main

---

src/service/search/cache/cacher.rs

fix: result cache with func

---

src/common/infra/cluster/mod.rs
src/service/search/datafusion/storage/file_statistics_cache.rs
src/service/search/super_cluster/follower.rs

fix: add more logs for follower

---

src/service/search/sql/mod.rs

fix: datatype mismatch #7951

---

.github/workflows/playwright.yml
tests/ui-testing/playwright-tests/Alerts/alerts-import.spec.js

Tests
___
Add artifact download step configuration
Name and path for debug binary
Ignore missing artifacts gracefully
Start OpenObserve using downloaded binary
___
```mermaid
flowchart LR
checkout["Checkout repo"] --> download["Download artifact: debug-binary"]
download --> start["Start OpenObserve from debug-binary"]
```
<tr>
<td>
<details>
<summary><strong>playwright.yml</strong><dd><code>Configure artifact download and service startup</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/playwright.yml
<ul><li>Configure …

test: Updated yml file

---

src/service/search/cache/mod.rs

Bug fix
___
Fix SQL parsing by preserving newlines
Restore correct aggregate query detection
Improve cache key stability with comments
Affects search cache behavior
___
```mermaid
flowchart LR
A["Search request"] -- "build origin_sql (preserve newlines)" --> B["is_aggregate_query"]
B -- "accurate detection" --> C["resolve_stream_names"]
C -- "cache decision" --> D["Search cache usage"]
```
<tr>
<td>
<details>
<summary><strong>mod.rs</strong><dd><code>Preserve SQL newlines for accurate cache parsing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

fix: search doesn't work with comments

---

web/src/plugins/logs/Index.vue

fix: blank chart issue on visualization page rc7

---

src/config/src/config.rs
src/router/http/mod.rs
src/service/compact/retention.rs

Change some logs related to data retention to INFO level.

fix: add logs for compactor

---

tests/ui-testing/pages/logsPages/logsPage.js
tests/ui-testing/pages/logsPages/unflattened.js
tests/ui-testing/pages/streamsPages/streamsPage.js
tests/ui-testing/playwright-tests/GeneralTests/sanity.spec.js
tests/ui-testing/playwright-tests/GeneralTests/schema.spec.js
tests/ui-testing/playwright-tests/Logs/join.spec.js
tests/ui-testing/playwright-tests/Logs/logsquickmode.spec.js
tests/ui-testing/playwright-tests/Logs/unflattened.spec.js
tests/ui-testing/playwright-tests/Pipelines/pipeline-core.spec.js
tests/ui-testing/playwright-tests/Pipelines/pipelines.spec.js
tests/ui-testing/playwright-tests/Streams/multiselect-stream.spec.js
tests/ui-testing/playwright-tests/Streams/streaming.spec.js
web/src/composables/useLogs.ts
web/src/locales/languages/en.json
web/src/plugins/logs/Index.vue
web/src/plugins/logs/IndexList.spec.ts
web/src/plugins/logs/IndexList.vue
web/src/plugins/logs/SearchBar.spec.ts
web/src/plugins/logs/SearchBar.vue

___
- Add toggle to show only interesting fields in quick mode
- Ensure timestamp default in interesting field list
- Implement field‐index mapping for correct ordering
- Refactor deep copies and optional chaining in schema
___
```mermaid
flowchart LR
A["Logs Page Field List"] -- "Quick mode toggle" --> B["Show Only Interesting Fields"]
B -- "Filter rows in UI" --> C["Display filtered fields"]
C -- "Update selected fields array" --> D["Adjust SQL query"]
```
<tr>
<td>
<details>
<summary><strong>Index.vue</strong><dd><code>Refactor schema copy and default timestamp</code>&nbsp; &nbsp; …

fix: Logs page field-list Interesting Fields improvements

---

src/common/meta/organization.rs
src/common/utils/auth_tests.rs
src/config/src/config.rs
src/handler/http/request/organization/settings.rs
src/handler/http/request/status/mod.rs
src/router/http/mod.rs
src/service/search/cluster/flight.rs
src/service/search/mod.rs
src/service/search/super_cluster/leader.rs
web/src/components/settings/General.vue
web/src/layouts/MainLayout.vue
web/src/locales/languages/en.json

streaming aggregation use follow two options contral
```
1. ZO_FEATURE_QUERY_STREAMING_AGGS -> global setting
2. streaming_aggregation_enabled -> org setting
```

fix: streaming aggregation config

---

web/src/components/pipeline/NodeForm/ScheduledPipeline.vue

This PR fixes the nested with queries parsing and showing in the stream list

fix: parse nested with queries in pipeline query node

---

tests/integration_test.rs

___
- Add derived stream e2e tests
- Create/delete pipelines via API helpers
- Validate trigger lifecycle and retries
- Cover invalid SQL evaluation behavior
___
```mermaid
flowchart LR
Create["Create test pipeline"] -- "POST /api/{org}/pipelines" --> List["List pipelines"]
List -- "GET /api/{org}/pipelines" --> TriggerOK["Trigger success path"]
List --> TriggerMaxRetries["Trigger max retries path"]
InvalidPipe["Create invalid pipeline"] -- "POST" --> DeleteField["Delete field from stream"]
DeleteField -- "PUT /streams/.../delete_fields" --> TriggerFail["Trigger evaluation failure"]
Cleanup["Cleanup pipelines"] -- "DB delete" --> End["Done"]
``` …

test: Add tests for derived streams

---

src/infra/src/file_list/mod.rs
src/infra/src/file_list/mysql.rs
src/infra/src/file_list/postgres.rs
src/infra/src/file_list/sqlite.rs
src/service/compact/retention.rs

Fix the case:
It caused add a lot of retention jobs again and again with extended data retention.

fix: data retention with extended retention

---

src/flight/src/common.rs
src/service/search/datafusion/distributed_plan/distribute_analyze.rs

chore: add node_name to analyze

---

web/src/components/dashboards/addPanel/FieldList.vue
web/src/composables/useDashboardPanel.ts
web/src/utils/query/sqlUtils.ts

fix: parse cte query to extract stream name

---

web/src/components/dashboards/addPanel/FieldList.vue
web/src/composables/useDashboardPanel.ts
web/src/utils/query/sqlUtils.ts

fix: parse cte query to extract stream name (#8102)

---

web/src/plugins/logs/Index.vue

This PR solves the issue of field selection when user selects from side panel
___
Bug fix
___
- Fix timeout reference in column update
- Prevent stale timeout and ensure clearTimeout works
- Use component-scoped `updateColumnsTimeout`
___
```mermaid
flowchart LR
UpdateSelectedColumns["updateSelectedColumns()"] --> CheckTimeout["Check this.updateColumnsTimeout"]
CheckTimeout --> ClearTimeout["clearTimeout(this.updateColumnsTimeout)"]
ClearTimeout --> SetTimeout["this.updateColumnsTimeout = setTimeout(...)"]
SetTimeout --> UpdateGrid["this.updateGridColumns()"]
```
<tr>
<td>
<details> …

fix: indexlist field select issue fixed

---

web/src/assets/images/ingestion/oracle.svg
web/src/components/ingestion/Database.spec.ts
web/src/components/ingestion/Database.vue
web/src/components/ingestion/databases/Oracle.spec.ts
web/src/components/ingestion/databases/Oracle.vue
web/src/composables/shared/useIngestionRoutes.ts
web/src/composables/useIngestion.spec.ts
web/src/composables/useIngestion.ts
web/src/locales/languages/en.json

Enhancement, Documentation
___
- Add Oracle ingestion route and page
- Include Oracle in database tabs and i18n
- Link Oracle docs in ingestion helper
___
```mermaid
flowchart LR
Routes["Ingestion routes"] -- add --> OracleRoute["/ingestion/database/oracle"]
DatabaseTabs["Database.vue tabs"] -- show --> OracleTab["Oracle tab"]
OracleTab -- loads --> OracleComponent["Oracle.vue"]
IngestionHelper["useIngestion.ts"] -- adds doc URL --> OracleDocs["Oracle documentation link"]
i18n["en.json"] -- adds key --> OracleLabel["ingestion.oracle"]
```
<tr>
<td>
<details> …

feat: added oracle database page under datasource

---

src/cli/basic/cli.rs
src/common/infra/cluster/etcd.rs
src/common/infra/cluster/nats.rs
src/config/src/cluster.rs
src/config/src/ider.rs
src/config/src/meta/cluster.rs
src/job/files/mod.rs
src/service/db/schema.rs
src/service/ingestion/mod.rs
src/service/schema.rs

- Add duplicated machine id check
- Add 4 random chars for generate parquet filename

fix: enhance machine id check

---

src/common/meta/organization.rs
src/common/meta/user.rs
src/common/utils/auth.rs
src/common/utils/http.rs
src/config/src/meta/ratelimit.rs
src/config/src/meta/timed_annotations.rs
src/infra/src/file_list/mysql.rs
src/infra/src/file_list/postgres.rs
src/main.rs
src/service/metrics/otlp.rs
tests/integration_test.rs

increase UT coverage
improve the email regex to catch `doubledotsequence` in email

fix: Inc UT coverage

---

tests/test-data/cte_queries.json
tests/ui-testing/pages/logsPages/logsPage.js
tests/ui-testing/playwright-tests/Logs/logsqueries.cte.spec.js

Tests
___
- Add advanced CTE logs query e2e tests
- Cover strings, NULLs, joins, unions
- Add error-rate and aggregation analysis
- Add complex multi-part query typing/validation
___
```mermaid
flowchart LR
CTEs["Add advanced CTE query tests"]
String["String ops & NULL handling"]
Joins["JOINs and UNIONs"]
Analytics["Error-rate and aggregations"]
Robust["Multi-part typing + validation"]
CTEs -- "new tests" --> String
CTEs -- "new tests" --> Joins
CTEs -- "new tests" --> Analytics
CTEs -- "new tests" --> Robust
```
<tr>
<td>
<details>
<summary><strong>logsqueries.cte.spec.js</strong><dd><code>Expand CTE logs …

test: e2e-cte-queries

---

src/config/src/config.rs
src/service/search/grpc/storage.rs
src/service/search/index.rs

chore: remove special handler for negative index search

---

src/service/search/cluster/flight.rs
src/service/search/mod.rs
src/service/search/super_cluster/leader.rs

close https://github.com/openobserve/openobserve/issues/8215

fix: sync issue for index

---

tests/ui-testing/pages/generalPages/enrichmentPage.js
tests/ui-testing/pages/logsPages/unflattened.js
tests/ui-testing/playwright-tests/Pipelines/pipeline-core.spec.js
web/src/components/logs/LogsHighLighting.spec.ts
web/src/components/logs/LogsHighLighting.vue
web/src/composables/useLogs.ts
web/src/composables/useTextHighlighter.spec.ts
web/src/composables/useTextHighlighter.ts
web/src/plugins/logs/DetailTable.vue
web/src/plugins/logs/JsonPreview.vue
web/src/plugins/logs/SearchResult.vue
web/src/plugins/logs/TenstackTable.vue
web/src/utils/logs/keyValueParser.ts
web/src/utils/logs/statusParser.ts

This PR helps to highlight text in logs page and also adds a left border for each depending upon the status of the logs
___
Enhancement
___
Add LogsHighLighting component for semantic highlighting
Highlight query terms across logs and JSON
Visual status indicators via colored borders/lines
FTS-aware coloring for selected columns
___
```mermaid
flowchart LR
Highlighter["LogsHighLighting.vue (new)"] -- "used by" --> Detail["DetailTable.vue"]
Highlighter -- "used by" --> JsonPrev["JsonPreview.vue"]
Highlighter -- "used by" --> Table["TenstackTable.vue"]
Status["statusParser.ts (new)"] -- "row/log status color" --> Detail
Status -- "row status stripe" --> Table
Colors["keyValueParser.ts (new)"] -- "theme colors" --> Highlighter
Composable["useTextHighlighter.ts (new)"] -- "highlight + …
```

feat: logs page highlighting

---

src/service/search/datafusion/distributed_plan/decoder_stream.rs

The currently printed scan_stats are accumulated as the node returns, but the scan_stats of a node itself should be output
this change only affect log output

fix: scan_stats for each node info

---

.github/workflows/playwright.yml
Cargo.lock
Cargo.toml
tests/ui-testing/pages/logsPages/logsPage.js
tests/ui-testing/playwright-tests/Logs/logstable.spec.js

___
- Add logs table field management tests
- Extend LogsPage POM with field actions
- Integrate new test into Playwright workflow
- Include ingestion helper for test setup
___
```mermaid
flowchart LR
POM["LogsPage POM"]
Tests["logstable.spec.js"]
CI["playwright.yml matrix"]
Ingest["Ingestion helper"]
Tests -- "uses" --> POM
Tests -- "posts logs" --> Ingest
CI -- "runs" --> Tests
```
<tr>
<td>
<details>
<summary><strong>logsPage.js</strong><dd><code>POM: field add/remove helpers for logs table</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

test: e2e-add-to-table-tests

---

web/src/plugins/traces/Index.vue
web/src/plugins/traces/TraceDetails.vue

Bug fix
___
- Prevent undefined error messages in traces UI
- Safely build HTML for error details
- Reset error detail before each query
- Robust parsing of backend error responses
___
```mermaid
flowchart LR
Query["User runs trace query"] -- "API error" --> Catch["Catch error"]
Catch -- "extract error/message/code" --> Parse["Normalize error fields"]
Parse -- "set errorMsg/errorCode/errorDetail" --> State["UI state updated"]
State -- "render" --> Renderer["SanitizedHtmlRenderer shows details"]
```
<tr>
<td>
<details>
<summary><strong>Index.vue</strong><dd><code>Harden traces error handling and …

fix: fixed traces error handling

---

web/src/composables/dashboard/useAnnotations.spec.ts
web/src/composables/dashboard/useAnnotationsData.spec.ts
web/src/composables/dashboard/useCancelQuery.spec.ts
web/src/composables/dashboard/usePanelCache.spec.ts
web/src/composables/dashboard/usePanelDataLoader.spec.ts
web/src/composables/dashboard/useValuesWebSocket.spec.ts

___
- Add comprehensive unit tests for data loaders
- Add WebSocket/streaming values tests
- Add annotations data workflow tests
- Improve loader mocks and error handling
___
```mermaid
flowchart LR
specs["Add dashboard composables specs"] -- "usePanelDataLoader" --> panelLoader["Panel data loading tests"]
specs -- "useValuesWebSocket" --> valuesWS["Field values WS/stream tests"]
specs -- "useAnnotationsData" --> annotations["Annotations data workflow tests"]
```
<tr>
<td>
<details>
<summary><strong>usePanelDataLoader.spec.ts</strong><dd><code>Comprehensive tests for panel data …

fix: dashboard unit tests

---

.github/workflows/playwright.yml
tests/ui-testing/pages/dashboardPages/dashboard-chart.js
tests/ui-testing/playwright-tests/dashboards/dashboard-transpose.spec.js

___
- Strengthen transpose table validations
- Add waits for table render stability
- Handle missing/variant table structures
- Safeguard comparisons with conditional checks
___
```mermaid
flowchart LR
Start["Open config & apply transpose"] -- "capture headers & data" --> Initial["Initial table snapshot"]
Initial -- "click transpose" --> Action["Trigger transpose"]
Action -- "wait & detect table" --> Detect["Table presence check"]
Detect -- "tbody rows" --> Capture["Capture transposedData"]
Detect -- "fallback all rows" --> Capture
Capture -- "flatten headers vs values" --> Flatten["Flatten initial data"]
Flatten -- "sort & compare" --> Assert["Assert equality"]
Detect -- "no data" --> Error["Throw diagnostic error"]
```
<details> <summary><h3> File …

fix: enhance dashboard transpose validation in UI tests

---

tests/ui-testing/playwright-tests/Logs/logstable.spec.js

Tests
___
- Expand logs table e2e test suite
- Add multi-field add/remove scenarios
- Validate field search and quick mode
- Check persistence across refresh and reselection
___
```mermaid
flowchart LR
Suite["Logs Table Field Management Suite"] --> AddMulti["Add multiple fields test"]
Suite --> RemoveMulti["Remove multiple fields test"]
Suite --> Search["Field search behavior tests"]
Suite --> Data["Field data presence validation"]
Suite --> SearchClear["Add with cleared search"]
Suite --> CaseIns["Search case insensitivity"]
Suite --> QuickMode["Quick mode toggle operations"]
Suite --> Persistence["Field persistence on stream reselection"]
``` …

test: e2e-logs-table-testcases

---

.github/workflows/playwright.yml
tests/ui-testing/pages/dashboardPages/visualise.js
tests/ui-testing/pages/page-manager.js
tests/ui-testing/playwright-tests/dashboards/visualize.spec.js

___
- Add visualize error message test
- Add quick mode toggle verification
- Use enhanced base fixtures for tests
- Enable visualize spec in CI workflow
___
```mermaid
flowchart LR
Tests["Visualize tests updated"] -- "use" --> Fixtures["Enhanced base fixtures"]
Tests -- "verify" --> ErrorMsg["Aggregation alias error message"]
Tests -- "verify" --> QuickMode["Quick mode toggle true"]
CI["Playwright workflow"] -- "enable" --> VisualizeSpec["visualize.spec.js run"]
```
<tr>
<td>
<details>
<summary><strong>visualise.js</strong><dd><code>Add helper to verify quick mode …

test: add dashboard visualize test cases

---

web/src/components/dashboards/PanelSchemaRenderer.vue

Bug fix
___
- Fix table chart no-data validation
- Separate table logic from other charts
- Ensure presence check on x/y aliases
- Prevent false negatives with single row
___
```mermaid
flowchart LR
Renderer["PanelSchemaRenderer.vue"]
Charts["Non-table charts validation"]
Table["Table-specific validation"]
Metric["Metric validation (unchanged)"]
Renderer -- "refine validation" --> Charts
Renderer -- "add distinct logic" --> Table
Renderer -- "keep existing flow" --> Metric
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug
fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>PanelSchemaRenderer.vue</strong><dd><code>Refine table chart data validation …

fix: update table chart no data validation logic (#8422)

---

web/src/plugins/logs/IndexList.vue

This PR fixes the issue in #8456

fix: clear the user searched value on selecting anystream

---

src/config/src/config.rs
src/handler/http/request/status/mod.rs
web/src/plugins/logs/IndexList.vue

This provides the default tab for logs ui sidebar via config api and env config

fix: interesting field config rc9

---

src/config/src/config.rs
src/ingester/src/writer.rs
src/main.rs

close https://github.com/openobserve/openobserve/issues/8478

refactor: replace feature_per_thread_lock with mem_table_bucket_num

---

web/src/components/settings/General.vue

This PR fixes the issue in #8439

fix: UI sync with general settings on refresh

---

src/common/meta/search.rs
src/handler/http/request/search/utils.rs
src/service/search/cache/mod.rs
src/service/search/cluster/flight.rs
src/service/search/datafusion/optimizer/mod.rs
src/service/search/search_stream.rs
src/service/search/super_cluster/follower.rs
src/service/search/super_cluster/leader.rs
src/service/search/utils.rs
web/src/components/dashboards/PanelContainer.vue
web/src/components/dashboards/viewPanel/ViewPanel.vue
web/src/composables/dashboard/usePanelDataLoader.ts
web/src/plugins/logs/Index.vue
web/src/plugins/logs/VisualizeLogsQuery.vue
web/src/utils/zincutils.ts
web/src/views/Dashboards/addPanel/AddPanel.vue

- show warning in dashboards if the `ZO_QUERY_DEFAULT_LIMIT` is reached

feat: partial err warning if results exceeds query limit

---

src/main.rs
src/service/search/super_cluster/follower.rs

fix: move cli loading to top so as to load the configs from custom file

---

src/service/compact/retention.rs

resolves [issues/8494](https://github.com/openobserve/openobserve/issues/8494)

fix: orphaned database entries

---

src/config/src/meta/dashboards/v1/mod.rs
src/config/src/meta/dashboards/v2/mod.rs
src/config/src/meta/dashboards/v3/mod.rs
src/config/src/meta/dashboards/v4/mod.rs
src/config/src/meta/dashboards/v5/mod.rs
src/handler/http/models/dashboards.rs
src/handler/http/request/dashboards/mod.rs
src/handler/http/router/openapi.rs

- Replace separate request/response models with unified `DashboardRequestBody/DashboardResponseBody`
- Add `#[schema(required)]` to `title` and `description` fields across all dashboard versions (v1-v5)
- Eliminate redundant `CreateDashboard/UpdateDashboard` `GetDashboard` model types
- Use tagged enum for version-specific dashboard deserialization instead of manual JSON parsing.
This helps generate `OneOf` schema type in OpenAPI spec.
- Simplify owner validation in dashboard creation/update
- Update OpenAPI schema to use consolidated model types
___
Enhancement, Documentation
___
- Add required schema for titles
- Unify dashboard request/response models
- Use tagged enum for versions
- Simplify owner assignment logic
___
```mermaid
flowchart LR
ReqBody["DashboardRequestBody (tagged …
```

fix: improve dashboard API models & add field annotations

---

src/service/search/cache/cacher.rs
src/service/search/cache/mod.rs
src/service/websocket_events/search.rs

- cherry-pick: fix: logs dedup from cache#8605

fix: logs dedup from cache

---

src/service/search/cache/cacher.rs
src/service/search/cache/mod.rs
src/service/websocket_events/search.rs

- cherry-pick: fix: logs dedup from cache#8605

fix: logs dedup from cache#8605

---

web/src/components/pipeline/PipelinesList.vue

This PR fixes the issue in #8615

fix:  should not show checkbox before loading the pipelines page

---

web/src/components/MenuLink.vue
web/src/layouts/MainLayout.vue
web/src/styles/_menu-animations.scss
web/src/styles/_menu-variables.scss
web/src/views/HomeView.vue

Enhancement, Documentation
___
- Modernize menu item UX and visuals
- Add badges and accessibility to menu
- Redesign Home page tiles and charts
- Introduce animated count-up metrics
___
```mermaid
flowchart LR
Menu["MenuLink.vue: badges, ARIA, active state"] --> Drawer["MainLayout.vue: nav ARIA, drawer styling"]
Drawer --> Home["HomeView.vue: tiles, charts, animations"]
Menu --> Vars["_menu-variables.scss: theme vars"]
Menu --> Anim["_menu-animations.scss: keyframes/mixins"]
Home --> Anim
Home --> Vars
```
<tr>
<td>
<details>
<summary><strong>MenuLink.vue</strong><dd><code>Accessible menu link with …

fix:  menu item + home page ux changes

---

web/src/plugins/traces/SpanBlock.vue
web/src/plugins/traces/TraceDetails.vue
web/src/plugins/traces/TraceDetailsSidebar.vue
web/src/plugins/traces/TraceHeader.spec.ts
web/src/plugins/traces/TraceHeader.vue
web/src/plugins/traces/TraceTree.spec.ts
web/src/plugins/traces/TraceTree.vue

Enhancement, Tests
___
- Refactor header to class-based styling
- Redesign Trace Details layout and styles
- Add span count badges and connectors
- Update tests for new selectors/classes
___
```mermaid
flowchart LR
TraceHeaderSpec["TraceHeader.spec.ts tests"] -- align with classes --> TraceHeaderVue["TraceHeader.vue"]
TraceTreeSpec["TraceTree.spec.ts tests"] -- new badge selectors --> TraceTreeVue["TraceTree.vue"]
TraceDetailsVue["TraceDetails.vue"] -- layout + styles --> SidebarVue["TraceDetailsSidebar.vue"]
TraceTreeVue -- span badges + connectors --> SpanBlockVue["SpanBlock.vue"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><details><summary>2 …

chore: traces UI changes

---

.github/workflows/playwright.yml
tests/ui-testing/pages/dashboardPages/dashboard-filter.js
tests/ui-testing/playwright-tests/dashboards/dashboard-filter.spec.js

___
- Add robust nested group filter helpers
- Introduce E2E test for nested groups
- Stabilize selectors and waits in filters
- Limit CI to dashboard filter suite
___
```mermaid
flowchart LR
helper["DashboardFilter helper"] -- "add stability + nested group API" --> spec["dashboard-filter.spec.js"]
spec -- "adds nested group test" --> ci["playwright.yml matrix"]
ci -- "run only dashboard-filter suite" --> pipeline["CI run scope"]
```
<tr>
<td>
<details>
<summary><strong>dashboard-filter.js</strong><dd><code>Stabilize filter interactions and add nested group …

fix: dashboard filter flaky testcases

---

src/common/meta/search.rs
src/handler/http/request/ai.rs
src/handler/http/request/search/mod.rs
src/handler/http/request/search/search_stream.rs
src/service/search/cache/mod.rs
src/service/search/cluster/http.rs
src/service/search/utils.rs

ref: https://github.com/openobserve/openobserve/pull/8702/

fix: show query limit error only for dashboard rc7
