Cargo.toml, build.rs, src/handler/http/request/mod.rs, src/handler/http/request/status/mod.rs, src/handler/http/router/mod.rs, src/infra/config.rs
Add versions API:
Endpoint: `GET /versions`
Response:
```
{
"version": "v0.0.1",
"commit": "410e5cd4071f05c8840aabfed690239bf2daffcd",
"date": "2023-02-13T02:15:43Z"
}
```
=> feat: add API for versions

Cargo.lock, Cargo.toml, build.rs, src/infra/config.rs
Move from dotenv to dotenvy which is a well maintained fork of dotenv.
=> fix: dotenv -> dotenvy

src/handler/http/request/stream/mod.rs, src/service/db/schema.rs, src/service/file_list.rs
`match stream_type` blocks are overly verbose. Replace them with more concise `stream_type.unwrap_or` expressions.
=> refactor: apply `Option::unwrap_or`

Cargo.toml, src/common/auth.rs, src/common/base64.rs, src/common/file.rs, src/common/str.rs, src/handler/grpc/auth/mod.rs, src/handler/grpc/mod.rs, src/handler/http/auth/mod.rs, src/infra/cache/file_data.rs, src/infra/cache/stats.rs, src/infra/cache/tmpfs.rs, src/infra/cluster.rs, src/infra/db/mod.rs, src/infra/file_lock.rs, src/infra/storage/local.rs, src/meta/sql.rs, src/service/db/compact/file_list.rs, src/service/db/compact/files.rs, src/service/router/mod.rs, src/service/schema.rs, src/service/search/datafusion/regexp_udf.rs, src/service/search/sql.rs, src/service/users.rs
Pattern 1
---------
Before:
```rust
assert_eq!(a, true);
assert_eq!(b, false);
```
After:
```rust
assert!(a);
assert!(!b);
```
Rationale: if `assert_eq!(pred, true)` is clearer than `assert!(pred)`,
then `assert_eq!(pred == true, true)` is even more clearer.
Pattern 2
---------
Before:
```rust
match pred {
true => {
// ...
}
false => {
// ...
}
}
```
After:
```rust
if pred {
// ...
} else {
// ...
}
```
Pattern 3
---------
Before:
```rust
#[test]
fn example() {
// `f` returns `Result<(), Error>`
assert!(f().is_ok());
}
```
After:
```rust
#[test]
fn example() {
// `f` returns `Result<(), Error>`
f().unwrap();
}
```
Wat
---
Before:
```rust
#[test]
fn test_is_router() {
let is_router = is_router();
assert_eq!(is_router, false);
}
```
After:
```rust
#[test]
fn test_is_router() { …
```
=> refactor: refactor the unit tests

proto/cluster/search.proto, src/handler/grpc/mod.rs, src/service/search/sql.rs
Fix search query with limit and change the default behavior:
- if SQL has limit, will use the limit in SQL and skip the param `query.size`
- if SQL has time range, will use the time range in SQL and skip the params `query.start_time` and `query.end_time`
But we still have the limitation:
- in `context` query mode, disallow `limit`, `offset`, `group by`
- doesn't support `join`, `union` and query from multiple tables
=> fix: search query with limit

src/infra/metrics.rs, src/infra/storage/local.rs, src/infra/storage/s3.rs, tests/integration_test.rs
- Adds support for the metric `STORAGE_TIME` for the Block and Local Storage operations  `put`, `get`, `del`
- Fix local put metrics, because of the full path it was never matching the `files` condition 
https://github.com/zinclabs/zincobserve/pull/493/commits/7c5df89d3a582e491ad4783cc8c3f645f9c4fe16#diff-f1a1da44d7bdd8180e86b1c3b2b39b0e8f853def40063173558f019bca07d3b8R71
=> feat: add storage operation times

coverage.sh
- Generate coverage report in JSON format --- it used to be a raw text file (non-JSON) with `.json` extension.
- Parse JSON data with Python instead of counting and `cut`ting fields. The resulting code is more readable.
- Take coverage thresholds from the environment, if possible.
- Generate HTML report and open it in the default browser with `./coverage.sh html` command.
- Add CLI.
=> chore: revamp `coverage.sh`

src/infra/db/mod.rs, src/infra/errors.rs, src/service/db/alerts/mod.rs, src/service/db/compact/delete.rs, src/service/db/compact/file_list.rs, src/service/db/compact/files.rs
This patch began with my attempt to edit `DbError::KeyNotExists` error message. That change caused `cargo test e2e` to fail. There was code that converted `crate::infra::errors::Error` to `String` and searched for a hard-coded substring. Rust compiler, however advanced, is of little help if the code is *stringly*-typed.
=> chore: compare types, not strings

src/handler/http/request/dashboards/mod.rs, src/meta/dashboards.rs
This simplifies "Create a dashboard" API, leaving only two required fields - `title` and `description` - in the request.
=> chore: let Serde fill omitted `Dashboard` fields

Cargo.toml, src/common/time.rs, src/infra/cache/tmpfs.rs, src/meta/dashboards.rs
=> feat: format time

src/service/search/mod.rs
We were off by mere 99 hours. 🤓
```
$ python3 -c 'print((360010001000 - 3600000000) // 1000000 // 3600)'
99
```
=> fix: use correct number of μs in an hour

src/service/alert_manager.rs, src/service/search/mod.rs, src/service/search/sql.rs, tests/integration_test.rs
After `search_in_local` was removed, the compiler started to complain with
`error[E0277]: `*mut ()` cannot be sent between threads safely`. I “fixed”
that error by commenting out tracing span statements in `search_in_cluster`.
> ⚠️ **Warning:** In asynchronous code that uses async/await syntax, `Span::entered`
may produce incorrect traces if the returned drop guard is held across an await point.
See [the `Span::enter` documentation] for details.
[the `Span::enter` documentation]: https://docs.rs/tracing/latest/tracing/span/struct.Span.html#in-asynchronous-code
I started to split `search_in_cluster` into smaller pieces, decorating the extracted
functions with `#[instrument]` attribute macro — it can automatically generate correct
code when used on an async function.
Unfortunately …
=> feat: delete local search

src/common/time.rs, src/service/search/datafusion/date_format_udf.rs, src/service/search/datafusion/exec.rs, src/service/search/datafusion/mod.rs, src/service/search/datafusion/time_range_udf.rs
format: `date_format(field, 'format', 'timezone')
examples:
the inserted time is: `2021-01-01T00:00:00.000Z`
```
select date_format(time, '%Y-%m-%d', '') as ret from t
```
result:
```
"+------------+",
"| ret        |",
"+------------+",
"| 2021-01-01 |",
"+------------+",
```
```
select date_format(time, '%Y-%m-%d', 'UTC') as ret from t
```
result:
```
"+------------+",
"| ret        |",
"+------------+",
"| 2021-01-01 |",
"+------------+",
```
```
select date_format(time, '%H:%M:%S', 'UTC') as ret from t
```
result:
```
"+----------+",
"| ret      |",
"+----------+",
"| 00:00:00 |",
"+----------+",
```
```
select date_format(time, '%H:%M:%S', '+08:00') as ret from t
```
result:
```
"+----------+",
"| ret      |",
"+----------+",
"| 08:00:00 |",
"+----------+",
```
```
select …
```
=> feat: add UDF date_format

web/src/components/MetricLineChart.vue, web/src/plugins/logs/Index.vue
1. Previous refresh interval was not getting cleared on selecting new one.
2. Metrics chart was sometime getting rendered on logs page
=> fix: logs refresh interval and chart issue

Cargo.lock, Cargo.toml, coverage.sh, src/handler/grpc/auth/mod.rs, src/handler/http/request/prom/mod.rs, src/meta/mod.rs, src/meta/prom.rs, src/service/db/schema.rs, src/service/metrics/prom.rs
Part of #692
Obtain `MetricType` directly from protobuf enum,
drop intermediate string representation.
=> feat: implement Prometheus `/metadata` API

Cargo.toml, src/handler/http/request/prom/mod.rs, src/handler/http/router/mod.rs, src/handler/http/router/openapi.rs, src/meta/prom.rs, src/service/metrics/prom.rs, src/service/promql/mod.rs, src/service/promql/search/mod.rs
Part of #692.
HACK: require exactly one `match[]` argument.
NOTE: correct name is `Matchers`, not _matches_; see
- [`promql_parser::label::Matchers`](https://docs.rs/promql-parser/latest/promql_parser/label/struct.Matchers.html)
- [`LabelMatcher`](https://github.com/zinclabs/zincobserve/blob/3843631adedbbef8a0fd199c2778c2c06ec17c39/proto/prometheus/types.proto#L141-L152) in Prometheus' protobuf
=> chore: validate metadata parameters

src/service/router/mod.rs
fix #720 
When router not found other nodes, just reload nodes from etcd maybe won't fix the problem. maybe the router disconnect from etcd. we need reconnect it and load everything again.
The better solution is, just let it `exit` and then `k8s` will restart it.
=> fix: restart router when there is no nodes

src/meta/prom.rs, src/service/metrics/prom.rs
Before:
```json
{
"status": "success",
"data": {
"status": "success",
"data": {
"zo_ingest_records": [
{
"type": "counter",
"help": "Ingested records",
"unit": ""
}
],
"zo_storage_files": [
{
"type": "gauge",
"help": "Storage files",
"unit": ""
}
]
}
}
}
```
After:
```json
{
"status": "success",
"data": {
"zo_ingest_records": [
{
"type": "counter",
"help": "Ingested records",
"unit": ""
}
],
"zo_storage_files": [
{
"type": "gauge",
"help": "Storage files",
"unit": ""
}
]
}
}
```
=> fix: regression in the output of `/metadata/ API

src/meta/dashboards.rs, web/src/components/dashboards/addPanel/Layout.vue, web/src/composables/useDashboardPanel.ts
set default `count-distinct` for y-axis(string), `sum` for y-axis(int) is not suitable, because user add y-axis most cases for show the number. and we have no way to `count(*)`, user must select one field, most user select `log` or `message` for y-axis, so what happened?
```sql
select count(distinct(log)) as y-axis-1
```
or I select `_timestamp` for y-axis, just want to should how many by histogram, then the SQL is:
```sql
select sum(_timestamp) as y-axis-1
```
So, the better solution should keep y-axis aggregation function default is `count`.
=> fix: default Y-axis aggs function should be count

build.rs
These print statements tell Cargo that it needs to rerun the build script if either `build.rs` was modified or any of the files in `proto/` directory was changed.
Without these print statements Cargo doesn't notice edits of *.proto files.
1. Developer executes cargo check/clippy/run/build
2. Developer edits a *.proto file
3. Developer tries to check/clippy/run/build again
4. No recompilation happens — *bad*
1–3. ...same...
4. Code is recompiled — *good*
=> chore: rerun the build script if any of protobufs change

proto/cluster/metrics.proto, src/service/promql/aggregations/avg.rs, src/service/promql/aggregations/count.rs, src/service/promql/aggregations/max.rs, src/service/promql/aggregations/min.rs, src/service/promql/aggregations/mod.rs, src/service/promql/aggregations/sum.rs, src/service/promql/engine.rs, src/service/promql/functions/avg_over_time.rs, src/service/promql/functions/count_over_time.rs, src/service/promql/functions/histogram.rs, src/service/promql/functions/idelta.rs, src/service/promql/functions/irate.rs, src/service/promql/functions/max_over_time.rs, src/service/promql/functions/min_over_time.rs, src/service/promql/functions/mod.rs, src/service/promql/functions/sum_over_time.rs, src/service/promql/search/grpc/mod.rs, src/service/promql/search/mod.rs, src/service/promql/value.rs
Prometheus [only performs extrapolation] when applying `rate`,
`increase`, and `delta` functions.
[only performs extrapolation]: https://github.com/prometheus/prometheus/blob/b727e69b7601b069ded5c34348dca41b80988f4b/promql/functions.go#L63-L67
This patch fixes responses to `/range_query` API calls.
E.g., now sending `zo_http_incoming_requests{namespace="ziox-alpha1"}`
query to vanilla Prometheus and ZincObserve returns the same set
of samples, provided that have been no restarts of ZincObserve during
`[start, end]` time window.
Part of #747.
refactor: rename 'values' to 'samples'
Generic words like "value" and "data" may mean pretty much anything.
"Sample" is more precise --- in the context of time series a *sample*
is a pair of a timestamp and a *value*.
=> fix: don't extrapolate when evaluating vector selector

Cargo.lock, Cargo.toml, src/handler/grpc/mod.rs, src/service/promql/aggregations/avg.rs, src/service/promql/aggregations/count.rs, src/service/promql/aggregations/max.rs, src/service/promql/aggregations/min.rs, src/service/promql/aggregations/sum.rs, src/service/promql/engine.rs, src/service/promql/functions/delta.rs, src/service/promql/functions/histogram.rs, src/service/promql/functions/increase.rs, src/service/promql/functions/mod.rs, src/service/promql/functions/rate.rs, src/service/promql/search/mod.rs, src/service/promql/value.rs
Translate Prometheus' [`extrapolatedRate`] to Rust and use it.
[`extrapolatedRate`]: https://github.com/prometheus/prometheus/blob/80b7f73d267a812b3689321554aec637b75f468d/promql/functions.go#L67
Part of #747
=> feat: adopt Prometheus' `extrapolated_rate`

src/infra/config.rs, src/meta/prom.rs, src/service/metrics/prom.rs
Refer to: https://grafana.com/docs/mimir/latest/configure/configure-high-availability-deduplication/#how-to-configure-grafana-mimir
the labels of deduplication should be configure, like prometheus-operator default is:
```yaml
external_labels:
prometheus: monitoring/k8s
prometheus_replica: prometheus-k8s-0
```
=> fix: make prometheus duplication configurable

src/common/functions.rs
- Remove the stray `to_owned()` function
- Remove `contains()` function as only `strip_prefix()` is enough
- Move the `org_key` definiton out of the loop
- Make the overall function more idiomatic by removing `mut fn_list`
=> refactor: optimize the get_all_transform_keys function()

src/handler/http/request/alerts/mod.rs, src/handler/http/router/mod.rs, src/handler/http/router/openapi.rs, src/service/alerts/mod.rs
Support testing a registered alert via triggers. An `PUT` handler is implemented on:
```
"/{org_id}/{stream_name}/alerts/{alert_name}/trigger"
```
Apart from the unit tests, I tested it using a very trivial echo server as the destination.
```go
✦ ❯ cat main.go 
package main
import (
"fmt"
"github.com/gofiber/fiber/v2"
)
func main() {
app := fiber.New()
app.Post("/", func(c *fiber.Ctx) error {
fmt.Println(string(c.Body()))
return c.SendString("Hello, World 👋!")
})
app.Listen(":8080")
}
```
=> chore: added an api endpoint to trigger alerts

Cargo.toml, deploy/build/buildspec-test.yml, src/job/mod.rs, web/README.md
Start acceppting `-` in email id. Earlier hello-world@gmail.com would fail.
Now we would accept it. https://github.com/zinclabs/zincobserve/issues/807
=> fix: regex - accept "-" in email

src/job/mod.rs, src/service/metrics/prom.rs, src/service/promql/engine.rs, src/service/promql/mod.rs, src/service/promql/search/grpc/mod.rs, src/service/promql/search/grpc/storage.rs, src/service/promql/search/grpc/wal.rs
current version you will get error `the column not exists` when you query with a not exists field. 
But I tested Prometheus, it just skip it and return everything. So I made this change.
=> fix: skip not exists fields for promql query

web/src/components/dashboards/addPanel/ChartRender.vue
- https://github.com/zinclabs/zincobserve/issues/813
=> fix: update tooltip format for metric charts and limit decimal precision to 2 digits

deploy/build/Dockerfile.mimalloc.aarch64, deploy/build/buildspec-arm.yml, deploy/build/buildspec.yml
constrain git hash to 7 characters forcefully. This should avoid the issue of arm build getting 8 characters hash and causing manifest issue and build failure
=> ci: constrain git hash to 7 characters forcefully

src/service/ingestion/mod.rs
disable get_env_var function in VRL
=> fix: disable get_env_var function in VRL

.github/workflows/release.yml, src/handler/http/request/status/mod.rs, src/infra/config.rs, src/service/compact/mod.rs, tests/integration_test.rs
impl #697 
| item | default value | desc |
|--|--|--|
| ZO_DATA_LIFECYCLE* | -- | deprecate |
| ZO_COMPACT_DATA_RETENTION * | -- | deprecate |
| ZO_COMPACT_DATA_RETENTION_DAYS | 0 | global data retention days, zero for disable, eg: set to 15, means every stream keep 15 days|
POST `/api/{org_id}/{stream_name}/settings`
```json
{
"partition_keys": [],
"full_text_search_keys": [],
"data_retention": 0,
}
```
use API set data retention for stream.
The key in config API is:
```
data_retention_days
```
=> feat: return global data retention in config api

src/service/enrichment_table/mod.rs, src/service/ingestion/mod.rs, src/service/logs/mod.rs, src/service/metrics/prom.rs, src/service/search/datafusion/exec.rs, src/service/search/sql.rs, src/service/traces/mod.rs, src/service/traces/otlp_http.rs
Regex::new() invocations have been used in several places, especially on hot paths. Moved them inside static/once_cell lazy object so that we initialize them only once.
https://github.com/rust-lang/regex/blob/master/PERFORMANCE.md#thou-shalt-not-compile-regular-expressions-in-a-loop
=> perf: further removal of clones and regex compile

web/src/locales/languages/en.json
Correct a minor typo in the first message an English-speaking user sees upon startup.
=> fix: minor, but highly visible typo correction

web/src/plugins/traces/Index.vue, web/src/plugins/traces/SearchResult.vue, web/src/plugins/traces/TraceChart.vue, web/src/plugins/traces/TraceDetailsSidebar.vue
User can open trace details on clicking markers from traces scatter chart
=> fix: support to open trace details from traces scatter chart 

Cargo.lock, Cargo.toml, src/handler/grpc/request/metrics.rs, src/handler/grpc/request/search.rs, src/handler/http/request/search/mod.rs, src/service/promql/search/grpc/mod.rs, src/service/promql/search/grpc/storage.rs, src/service/promql/search/grpc/wal.rs, src/service/search/datafusion/exec.rs, src/service/search/datafusion/storage/file_list.rs, src/service/search/datafusion/storage/memory.rs, src/service/search/datafusion/storage/mod.rs, src/service/search/datafusion/storage/nocache.rs, src/service/search/grpc/mod.rs, src/service/search/grpc/storage.rs, src/service/search/grpc/wal.rs, src/service/search/mod.rs, src/service/search/sql.rs, web/src/plugins/logs/Index.vue, web/src/plugins/traces/Index.vue
we will only load the latest parquets based on the record num in the time range when there is no where clause, it will be much optimized default query for UI.
=> perf: optimize the query without where clause

.cargo/config.toml, Cargo.lock, Cargo.toml, deploy/build/Dockerfile.aarch64, deploy/build/Dockerfile.amd64, deploy/build/Dockerfile.tag-simd.amd64, deploy/build/Dockerfile.tag.aarch64, deploy/build/Dockerfile.tag.amd64, src/common/flatten.rs, src/common/json.rs, src/common/mod.rs, src/handler/http/request/logs/ingest.rs, src/handler/http/request/prom/mod.rs, src/service/ingestion/mod.rs, src/service/logs/bulk.rs, src/service/logs/json.rs, src/service/logs/kinesis_firehose.rs, src/service/logs/multi.rs, src/service/logs/syslog.rs, src/service/metrics/prom.rs, src/service/search/mod.rs, src/service/traces/mod.rs, src/service/traces/otlp_http.rs
Ingest data:
```json
[
{
"user": "prabhat",
"access": [
{
"type": "read",
"path": "/home/prabhat"
},
{
"type": "write",
"path": "/home/prabhat",
"groups": [
"admin",
"dev"
]
}
]
}
]
```
the result is: 
```json
{
"_timestamp": 1686964366295822,
"access_0__path": "/home/prabhat",
"access_0__type": "read",
"access_1__groups_0_": "admin",
"access_1__groups_1_": "dev",
"access_1__path": "/home/prabhat",
"access_1__type": "write",
"user": "prabhat"
}
```
now is:
```json
{
"_timestamp": 1687147762824047,
"access_0_path": "/home/prabhat",
"access_0_type": "read",
"access_1_groups_0": "admin",
"access_1_groups_1": "dev",
"access_1_path": "/home/prabhat",
"access_1_type": "write",
"user": "prabhat"
}
```
- Earlier we convert every key to lowercase, it need copy every key once.
- Now we check if the …
=> fix: #978 extra underscore in ingesting records containing array

src/handler/http/request/search/mod.rs, src/main.rs, src/service/search/sql.rs
for api: `/api/:org/:stream/_values`
We rename:
- key -> zo_sql_key
- num -> zo_sql_num
=> fix: in some case we can't use key as alias

Cargo.lock, Cargo.toml, src/service/promql/binaries/mod.rs, src/service/promql/binaries/vector_operations.rs, src/service/promql/engine.rs
For binary operation between two vectors we support `and`, `or` and `unless` operations in this PR.
This also contains the vector arithmatic operators.
=> feat: initial structure of promql vector bin ops

src/main.rs
In order for the server to accept connections from requests using ipv6, the server needs to bind to an ipv6 address. This adds the ipv6 "any" address to bind the server to.
https://github.com/openobserve/openobserve/issues/1019
=> feat: Bind to additional ipv6 address

web/src/components/QueryEditor.vue, web/src/composables/usePromqlSuggestions.ts
As we use same sql language for promql and sql added support to dispose auto-complete-keyword on unmounting editor.
=> fix: support to dispose provider when switching sql and promql editor

src/infra/config.rs
Now we only has three provider for object storage:
- s3
- gcp
- azure
All platform compatible s3, you can use `s3` or just skip this value because default is `s3`.
For s3 compatible platform, maybe you need `ZO_S3_FEATURE_FORCE_PATH_STYLE=true`, this config option default value is `false`.
=> fix: change provider of s3

src/service/promql/engine.rs, src/service/promql/functions/mod.rs, src/service/promql/functions/time_operations.rs
Added a trivial scalar which simply returns the value passed to the promql.
Added several time related operations for e.g. minute, year etc.
=> feat: promql, scalars implementation

src/common/infra/wal.rs, src/job/files/memory.rs
- Avoid per element `vector.push()` in `get_search_in_memory_files()`
- Avoid clone in `list()` of `MEMORY_FILES` i.e let the upstream decide and clone only where required.
=> refactor: couple of optimizations around vector handling

src/common/infra/cache/file_data.rs, src/handler/grpc/request/event.rs, src/handler/http/request/status/mod.rs, src/service/compact/merge.rs, src/service/compact/retention.rs, src/service/db/file_list/broadcast.rs, src/service/db/file_list/local.rs, src/service/db/file_list/mod.rs, src/service/db/file_list/remote.rs, src/service/file_list.rs, src/service/promql/functions/time_operations.rs, src/service/promql/search/grpc/storage.rs, src/service/schema.rs, src/service/search/datafusion/storage/memory.rs, src/service/search/datafusion/storage/nocache.rs, src/service/search/grpc/storage.rs
=> fix: optimize some query cases

src/service/promql/binaries/vector_operations.rs, src/service/promql/engine.rs, src/service/promql/functions/rate.rs
This is the third installment of scalar <-> vector ops
where we support queries like following, which include bool.
```
1 < bool some-vector-metric
```
=> fix: promql vector ops supporting boolean cases.

src/service/metrics/json.rs, src/service/metrics/prom.rs
```json
[
{
"__name__": "zo_incoming_requests",
"__type__": "counter",
"endpoint": "/api/config",
"method": "get",
"status": "200",
"instance": "zo1-openobserve-router-5d9f7d67c6-296wj",
"_timestamp": 1690129406888,
"value": 6.0
}
]
```
```json
[
{
"__name__": "ingest_wal_used_bytes",
"__type__": "gauge",
"organization": "default",
"stream_type": "logs",
"stream": "default",
"instance": "zo1-openobserve-router-5d9f7d67c6-296wj",
"_timestamp": 1690129406888,
"value": 180567.1
}
]
```
Histogram is a complex metrics type, need 4 types data values.
1. The `Histogram` type row of the metrics name.
1. The `Counter` type rows of the `_bucket` values.
1. The `Counter` type row of the `_count` value.
1. The `Counter` type row of the `_sum` value.
```json
[
{"__name__": "http_response_time", …
```
=> fix: histogram ingestion for json api

src/service/promql/engine.rs
This nicely boosts up the compliance with promql
```bash
================================================================================
General query tweaks:
*  Openobserve is sometimes off by 1ms when parsing floating point start/end timestamps.
*  Openobserve fractional tolerance amount for <agg>_over_time queries
================================================================================
Total: 446 / 548 (81.39%) passed, 0 unsupported
```
=> feat: promql offset support

src/service/promql/engine.rs
`range` param was missing while loading the raw data in the cache and was being passed as `None`. Thus, fixing this should improve the promql compliance.
```
================================================================================
General query tweaks:
*  Openobserve is sometimes off by 1ms when parsing floating point start/end timestamps.
*  Openobserve fractional tolerance amount for <agg>_over_time queries
================================================================================
Total: 486 / 548 (88.69%) passed, 0 unsupported
```
=> fix: pass the range param to the matrix data-selector

src/service/promql/binaries/vector_operations.rs, src/service/promql/engine.rs, src/service/promql/functions/label_replace.rs, src/service/promql/value.rs
Whenever a function is applied, on the returning vector or matrix
type we need to check if the label set is duplicated or not.
Sematically it is an undefined operation based on
https://github.com/prometheus/prometheus/issues/4562
Can be tested using
```
label_replace(demo_num_cpus, "instance", "", "", "")
```
----
Another type of queries now are supported between Vector <-> Vector
by using `group-modifiers` and `on/ignoring`. Can be tested using
```
demo_memory_usage_bytes == on(instance, job, type) demo_memory_usage_bytes
```
----
Another improvement is about adding several methods to
`LabelExt` trait for `Labels`.
```
/// Signature for the given set of labels
fn signature(&self) -> Signature;
/// keep the labels as described by the `labels` vector
/// and delete everything else
fn …
```
=> fix: remove label names

src/service/promql/binaries/vector_operations.rs, src/service/promql/engine.rs, src/service/promql/functions/histogram.rs, src/service/promql/functions/mod.rs, src/service/promql/functions/predict_linear.rs, src/service/promql/functions/time_operations.rs, src/service/promql/value.rs
- Now supporting queries like:
```
sum by(instance, type) (demo_memory_usage_bytes) + on(instance, type) group_left(job) demo_memory_usage_bytes
```
- Implemented a subquery parser, i.e. supporting queries like
```
avg_over_time(rate(demo_cpu_usage_seconds_total[1m])[2m:10s])
```
- Fixed a small bug in queries for time-like functions for e.g. `minute()`, `hour()`, ..etc. where the timestamp of the sample was being evaluated, rather than the actual value of the sample.
Running the compliance on this PR, generates the following results:
```
================================================================================
General query tweaks:
*  Openobserve is sometimes off by 1ms when parsing floating point start/end timestamps.
*  Openobserve fractional tolerance amount for <agg>_over_time …
```
=> feat: promql subquery impl and small improvements

src/service/promql/aggregations/bottomk.rs, src/service/promql/aggregations/mod.rs, src/service/promql/aggregations/topk.rs, src/service/promql/engine.rs
Now supporting queries like:
```
topk by(instance) (2, demo_num_cpus)
```
This PR results in the following compliance improvements.
```
================================================================================
General query tweaks:
*  Openobserve is sometimes off by 1ms when parsing floating point start/end timestamps.
*  Openobserve fractional tolerance amount for <agg>_over_time queries
================================================================================
Total: 533 / 548 (97.45%) passed, 0 unsupported
```
=> feat: topk bottomk with by/without

src/service/promql/aggregations/count_values.rs, src/service/promql/aggregations/mod.rs, src/service/promql/engine.rs, src/service/promql/value.rs
Now supporting queries like:
```
count_values("value", demo_api_request_duration_seconds_bucket)
```
=> feat: promql count_values support

Cargo.lock, Cargo.toml, src/service/promql/aggregations/mod.rs, src/service/promql/binaries/vector_operations.rs, src/service/promql/engine.rs, src/service/promql/value.rs
In case of `by` queries, the labels_to_include() was also including the MetricName, this is incorrect, thus fixing it.
=> fix: incorrect labels in aggregations

src/service/promql/binaries/vector_operations.rs, src/service/promql/engine.rs, src/service/promql/value.rs
Due to a mismatch on the label which was used to generate signatures for matching `lhs` with `rhs` metrics was being computed in a wrong way.
Also refactored code a bit to simply `signature` creation and added bunch of tests.
=> fix: fixes #1313

src/service/promql/aggregations/avg.rs, src/service/promql/aggregations/count.rs, src/service/promql/aggregations/count_values.rs, src/service/promql/aggregations/group.rs, src/service/promql/aggregations/max.rs, src/service/promql/aggregations/min.rs, src/service/promql/aggregations/quantile.rs, src/service/promql/aggregations/stddev.rs, src/service/promql/aggregations/stdvar.rs, src/service/promql/aggregations/sum.rs
Aggregations use several `map` operation after the initial `.iter()` over the raw data. This is required to ensure that we have the entries in the ordered manner.
After this it is safe to parallelize the aggregation value, thus implemented.
=> feat: promql aggregations parallelized

src/service/schema.rs
Iteration over the reference of schema fields already does the job as compared to making it a clone.
=> feat: remove the unnecessary calls to  clone(), etc.

web/src/plugins/metrics/Index.vue, web/src/views/StreamExplorer.vue
Metrics query timestamp(start_time, end_time) was not getting updated for relative time period
=> fix: Metrics query timestamp issue

src/common/infra/config.rs, src/common/utils/stream.rs, src/handler/http/request/status/mod.rs, src/service/search/datafusion/mod.rs, src/service/search/sql.rs, src/service/stream.rs
New environment:
```
ZO_FEATURE_FULLTEXT_EXTRA_FIELDS=""
```
Default we use `log`, `message`, `msg`, `content`, `data` as `full text search` fields, you can use `match_all` to search it.
If you want set additional fields as global full text search fields, you can set it like this:
```
ZO_FEATURE_FULLTEXT_EXTRA_FIELDS="fielda,fieldb,fieldc"
```
=> feat: disable dictionary for log fields

src/common/infra/config.rs, src/common/infra/file_list/dynamo.rs, src/common/infra/file_list/postgres.rs, src/common/infra/file_list/sqlite.rs
Delete stream use empty time_range, it can't work now.
=> fix: allow query file list with empty time range

src/service/traces/mod.rs, src/service/traces/otlp_http.rs
Fixes https://github.com/openobserve/openobserve/issues/1471
=> fix: 1471 Increase the precision of the duration field to nanoseconds

proto/cluster/metrics.proto, proto/cluster/search.proto, src/common/infra/config.rs, src/common/meta/search.rs, src/handler/grpc/mod.rs, src/handler/http/request/prom/mod.rs, src/handler/http/request/search/mod.rs, src/service/alert_manager.rs, src/service/alerts/mod.rs, src/service/db/enrichment_table.rs, src/service/db/file_list/remote.rs, src/service/logs/mod.rs, src/service/metrics/prom.rs, src/service/promql/engine.rs, src/service/promql/exec.rs, src/service/promql/search/grpc/mod.rs, src/service/promql/search/grpc/wal.rs, src/service/promql/search/mod.rs, src/service/search/grpc/mod.rs, src/service/search/grpc/storage.rs, src/service/search/grpc/wal.rs, src/service/search/mod.rs, src/service/search/sql.rs, src/service/stream.rs, src/service/usage/stats.rs
impl #1429 
Add `timeout` parameter for each query API, like `/_search` API, you can provide `timeout` like this:
```
{
"query": {},
"aggs": {},
"timeout": 2
}
```
the `timeout` unit is `seconds`.
Add a new environment
```
ZO_QUERY_TIMEOUT=600
```
Deleted an old environment:
```
ZO_GRPC_TIMEOUT=600
```
Now the timeout progress will be:
1. Nginx proxy has a timeout, default is 60s
2. OpenObserve router has a timeout, default is `ZO_ROUTE_TIMEOUT=600`, 600s
3. OpenObserve query engine has a timeout, default is `ZO_QUERY_TIMEOUT=600`, 600s， but you can pass a parameter to change it for each query API.
If the `proxy` timeout, the query will continue work until the `query` timeout.
If the `query` timeout, the engine will cancel the job then the CPU usage will lower down.
=> fix: cancel datafusion execution when it timeout

src/common/meta/stream.rs
First, the duration unit is `second`.
Second, we will use 1 hour expired duration for hourly wal files, and 24 hours expired duration for daily wal files.
And now we have a default file partition level for each stream type and you can change it:
```
ZO_LOGS_FILE_RETENTION=hourly
ZO_TRACES_FILE_RETENTION=hourly
ZO_METRICS_FILE_RETENTION=daily
```
```
POST /api/:org/:stream/settings
{
"data_retention": 0,
"partition_time_level": "hourly / daily"
}
```
if you found there is many very small files in an hour, you can try to change `hourly` to `daily`, it means we will merge files by day, it should reduce 24x small files.
=> fix: wal file retention

src/common/infra/wal.rs
Earlier if the WAL file is daily and it is created at 23:00, it will move to storage at tomorrow 23:00, but actually, after 1 hour we will create a new file and this file will never be written again in tomorrow. so we should move it faster no need wait 24 hours.
=> fix: wal time retention

Cargo.lock, Cargo.toml, src/common/infra/db/dynamo.rs, src/common/meta/telemetry.rs
Openobserve uses vrl & vector from  vector fork. Vrl is available as crate , we can use the crate as dependancy rather than using it from our fork .
This also fixes https://github.com/openobserve/openobserve/issues/1233
=> fix: use vrl crate

src/common/infra/file_list/dynamo.rs, src/common/migration/file_list.rs, src/common/migration/meta.rs, src/handler/grpc/request/logs.rs, src/handler/grpc/request/search.rs, src/main.rs, src/service/promql/exec.rs, src/service/search/mod.rs
1. run `./openobserve migrate-file-list-from-dynamo`
it will upgrade records for the old `file-list` table and create the secondary index for `file-list` table.
3. run `./openobserve reset -c stream-stats` , **after the secondary index for `file-list` table is successfully created**
it will rebuild the stream stats, but need run this command after `10m` or you will got empty stream stats.
=> fix: dynamo migration

web/src/views/Dashboards/ImportDashboard.vue
When we import the dashboard we upgrade it to the latest version before sending it to backend, so it always get saved in the latest version
=> fix: convert dashboard schema to latest version before importing

Cargo.lock, Cargo.toml, src/common/migration/file_list.rs, src/common/migration/mod.rs
We checked if there is `data/stream/` directory, and will skip migration when the directory does not exist. but when the user uses local mode with s3, it has data but there is no `stream` directory.
If the user use `local_mode` + `s3` they need to create an empty `data/openobserve/stream` directory at the same level as `wal` directory. then run the new version, which will upgrade success.
=> fix: migration for local mode with s3

src/handler/tcp_udp/mod.rs
Before the fix supported length in bytes by both TCP & UDP was limited to 1024 bytes, which resulted in values being cut off.
We had two options as fix : 
- Support max size in line with standard [IEEE 802.3](https://en.wikipedia.org/wiki/IEEE_802.3) , which limits 1500 bytes of payload , with this we can support 1472 bytes (1500 - 20 (IP header ) -8 (UDP header) ) for UDP & 1460 bytes(1500 - 20 (IP header ) -20 (TCP header) )  for TCP 
- JUMBO frames - Ruled out  because :  for jumbo frames , frame size used by an end-to-end connection is typically limited by the lowest frame size in intermediate links ,not only sender & receiver has to enable jumbo frames but all intermediate links will have to support it.
Fixes #1514
**Summary : we will support max 1472 bytes  for UDP & 1460 bytes for …
=> fix: Syslog ingestion message values are 'cut off' #1514

src/common/infra/db/mod.rs, src/service/logs/otlp_http.rs
Error:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', github.com/zinclabs/openobserve/src/service/db/metrics.rs:99:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> fix: sqlite metadata panic

web/src/utils/dashboard/convertSQLData.ts
For SQL queries in some timezone, there was a difference between the time showing in the x-axis. This issue is fixed by converting it to the correct timezone.
=> fix: timeseries time zone issue for sql queries

src/service/metrics/json.rs, src/service/metrics/mod.rs, src/service/metrics/otlp_grpc.rs, src/service/metrics/otlp_http.rs, src/service/metrics/prom.rs, src/service/mod.rs
=> fix: all labels to have string values 

src/handler/http/request/dashboards/folders.rs, src/service/dashboards/folders.rs, src/service/dashboards/mod.rs
We create default folder , when we first receive call to create a dashboard in default folder. If an API call tries to create a default folder , it should not be allowed
=> fix: default folder rename issue

src/common/infra/cluster.rs, src/common/infra/config.rs, src/handler/http/request/status/mod.rs, src/job/mod.rs, src/service/db/file_list/local.rs
The latest 10-minute data mayn't be queried when we redeploy the whole cluster, because of the ingester can't broadcast the data in WAL.
Load the file list in WAL into `cache` when it start, and then we will have data to send broadcast.
=> fix: optimize file list broadcast

src/service/logs/mod.rs, src/service/promql/engine.rs
In promql we were reporting as info logs, in case one of the lhs/rhs of a binary-operation was missing, now we just report it as `debug`.
=> fix: change the log::info -> debug for missing vector

web/src/components/DateTime.vue, web/src/composables/useLogs.ts, web/src/plugins/logs/Index.vue
This PR contains a fix for the calendar time selection issue.
Problem: When a user attempts to set the "start time" in the absolute tab and subsequently clears the entire "end time" field, it inadvertently resets the "start time."
Solution: When a user is setting up the time no need to reset it. I have moved out that when users move out from calendar control. If the user tries to click the "Run Query" button without selecting the time user will get an error message.
=> fix: calendar datatime reset issue fix

web/src/components/functions/FunctionList.vue
issue #1542 
This pull request addresses a critical issue related to functions and their synchronization with the Logs page function dropdown.
Problem: Previously, when a function was created, edited, or deleted on the function page, these changes were not being reflected in the function dropdown on the Logs page. This inconsistency was causing confusion and workflow disruptions.
Solution: In this PR, we have implemented a solution to resolve this issue. We have updated the functions data within the logs global object. As a result, any changes made to functions, such as creation, editing, or deletion, will now be immediately and accurately reflected in the function dropdown on the Logs page. This enhancement ensures a seamless and synchronized experience for users across both the function …
=> fix: function issue

web/src/plugins/logs/SearchBar.vue
This PR contains the fix for the syntax error issue in SQL Mode.
issue #1054 
Solution: An additional condition was added to check sql mode is enabled or not and check for the "where" keyword exists in the query while adding a new condition to the query editor.
=> fix: where keyword in sql mode to avoid syntax error

web/src/utils/dashboard/convertPromQLData.ts, web/src/utils/dashboard/convertSQLData.ts
Show single item value only instead of showing all the items in the tooltip when a single element is hovered
=> fix: dashboard tooltips for single item only

src/common/infra/cluster.rs, src/service/db/file_list/broadcast.rs
Sometimes we want to set a node to`NoSchedule`, like we want offline an ingester but there are some WAL files in the node, we need `NoSchedule` the node and wait for some time to let the WAL files move to storage.
With this PR we can use etcd to set the node attribute `scheduled: false` then it will never be scheduled.
=> feat: add schedule for cluster node

src/common/infra/config.rs, src/common/infra/storage/remote.rs
fix #1510 
Add new ENV `ZO_S3_FEATURE_FORCE_HOSTED_STYLE` to replace `ZO_S3_FEATURE_FORCE_PATH_STYLE`, but for compatible, the old ENV is still available for a while.
=> fix: #1510

src/common/utils/cgroup.rs
based on cgroup version limits are part of different files:
- v1 
memory - /sys/fs/cgroup/memory/memory.limit_in_bytes
cpu - sys/fs/cgroup/cpu/cpu.cfs_quota_us 
- v2
memory - /sys/fs/cgroup/memory.max
cpu - /sys/fs/cgroup/cpu.max
=> fix: read cpu & memory limits from cgroup

.gitignore, src/common/utils/cgroup.rs
If there is no limit it will print like this:
```
[2023-10-13T05:04:35Z INFO  openobserve] System info: CPU cores 4, MEM total 8796093022207 MB, Disk total 19 GB, free 15 GB
```
Because of without limit, the file default values is:
1. `/sys/fs/cgroup/cpu/cpu.cfs_quota_us` is -1
2. `/sys/fs/cgroup/memory/memory.limit_in_bytes` is 9223372036854775807
=> fix: get cgroup limit

src/service/search/sql.rs
When function with name like "{name}" is created (UI doesn't allow , however API allows creation) , any search results in failure with error:
[2023-10-16T04:56:03Z INFO  openobserve::service::search::sql] service:search:sql:new; org_id="default"
thread 'actix-server worker 0' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
(?i){name}[ ]*\(.*\)
^
error: repetition operator missing expression
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The PR handles these cases to ignore such functions.
=> fix: function name with invalid chars issue

.github/workflows/release.yml, src/common/infra/cache/file_data/memory.rs, src/common/infra/config.rs, src/service/search/datafusion/mod.rs, src/service/search/datafusion/storage/memory.rs, src/service/search/sql.rs
=> feat: improve parquet writing

web/src/enterprise/components/users/User.vue, web/src/plugins/logs/DetailTable.vue
1. The "Search around" button remains disabled
- There was an unwanted condition to disable the button which was not required. Removed that condition from the button.
=> fix: "Search around" button remains disabled

src/service/search/mod.rs
fix #1647 It is because we changed the rule for `stream name` and the partition key filter was used the pattern. 
The partition key value like this `ab-cd` we replace the `-` to `_` in the stream name. but partition key wasn't so cause the problem.
=> fix: #1647

src/common/meta/functions.rs, src/service/ingestion/mod.rs, src/service/logs/bulk.rs, src/service/logs/ingest.rs, src/service/logs/otlp_grpc.rs, src/service/logs/otlp_http.rs, src/service/logs/syslog.rs, src/service/metrics/otlp_grpc.rs, src/service/metrics/otlp_http.rs, src/service/search/datafusion/exec.rs, src/service/traces/mod.rs, src/service/traces/otlp_http.rs
We were not supporting vrl functions during data ingestion for otlp & syslog endpoints , added support for it.
=> feat: added vrl functions to otlp endpoints & syslogs

web/src/utils/dashboard/convertSQLData.ts
Heatmap charts are not able to render time-series data. Fixed that by considering time related data as a block data for the heatmap
=> fix: heatmap timeseries issue, tooltip unit converting

web/src/components/dashboards/addPanel/ChartSelection.vue
Reordering charts to show related charts together, like lines and area charts.
=> fix: reordering to put related charts together in add panel page

web/src/components/dashboards/panels/ChartRenderer.vue, web/src/utils/dashboard/convertSQLData.ts
Few charts rendered from the SQL queries were not showing the improved tooltip with scrolling. That has been fixed.
=> fix: tooltip scroll issue for sql charts

web/src/components/dashboards/PanelSchemaRenderer.vue, web/src/components/dashboards/panels/ChartRenderer.vue, web/src/utils/dashboard/convertPromQLData.ts, web/src/utils/dashboard/convertSQLData.ts, web/src/views/Dashboards/ViewDashboard.vue
- Fixed metric text throwing error / not visible
- Tooltip dark mode (#1693)
- Table loading dots are hidden behind the rendered table
=> fix: dashboard metric text, tooltip dark mode, table loading indicators

src/common/meta/http.rs, src/handler/http/request/enrichment_table/mod.rs, src/handler/http/request/kv/mod.rs, src/handler/http/request/logs/ingest.rs, src/handler/http/request/organization/settings.rs, src/handler/http/request/rum/ingest.rs, src/handler/http/request/search/mod.rs, src/handler/http/request/search/saved_view.rs
Introduced two new methods in meta::http::HttpResponse struct
- json()
- bad_request()
Main motivation behind this is to unify the actix-response as we had no consistent way for sending out them, especially `bad_request()`
=> feat: refactor actix-http responses

web/src/components/dashboards/panels/ChartRenderer.vue, web/src/utils/dashboard/convertSQLData.ts, web/src/views/Dashboards/ViewDashboard.vue
On dashboard panels, with echarts default horizontal zooming was not On. So enabled it so users can click and select horizontal area to zoom in.
This affects the logs page as well.
=> fix: dashboard chart default horizontal zoom enabled

src/service/logs/otlp_grpc.rs, src/service/logs/otlp_http.rs
Data partitioning for logs ingested using otlp logs endpoint wasnt applied when stream name isnt set.
=> fix: data partitioning for logs using otlp

src/handler/http/request/organization/settings.rs, src/service/db/organization.rs
A small fix to ensure that the prefix for organization setting is consistent everywhere, we use it.
=> fix: use a const to represent the org-setting-key

web/src/components/logstream/schema.vue, web/src/locales/languages/en.json, web/src/services/stream.ts
This PR contains delete unused stream fields related changes.
Problem: There was no way to delete unused stream fields associated with stream. 
Solution: Provide option to delete unused stream fields on stream explorer page. User can select one or more fields from the list and delete it. Once delete it can not be undone.
=> feat: delete unused label

src/common/infra/config.rs, src/common/infra/dist_lock.rs, src/handler/http/request/search/mod.rs
```
ZO_FEATURE_QUERY_QUEUE_ENABLED = true
```
You can disable the global query queue by setting it to `false`.
We still need a better solution for controlling the query queue.
=> feat: add new configure for control query queue

src/handler/http/request/organization/settings.rs, src/job/mmdb_downloader.rs, src/service/db/organization.rs
Needed to match the DBError rather than the string-comparison, hence the refactor.
Another change is to move the function and invoke it as get_or_set i.e. set to default if it doesnt already exist
=> fix: refactor the setting of default scrape-interval

web/src/composables/dashboard/usePanelDataLoader.ts
Chat shows loading even if the API call is not made with the chart waiting for the dependent variable's values. The below issue is fixed:
=> fix: chart loading indicator does not go away if the value of the dependent variables is not present

src/common/infra/config.rs, src/common/infra/errors.rs, src/common/meta/mod.rs, src/handler/http/request/search/mod.rs, src/handler/http/request/status/mod.rs, src/job/files/disk.rs, src/main.rs, src/service/distinct_values.rs, src/service/logs/bulk.rs, src/service/logs/gcs_pub_sub.rs, src/service/logs/ingest.rs, src/service/logs/json.rs, src/service/logs/kinesis_firehose.rs, src/service/logs/multi.rs, src/service/logs/otlp_grpc.rs, src/service/logs/otlp_http.rs, src/service/logs/syslog.rs, src/service/mod.rs, src/service/search/datafusion/mod.rs, src/service/search/sql.rs, src/service/stream.rs, src/service/traces/mod.rs, src/service/traces/otlp_http.rs
impl #1290 
We add a new stream `distinct_values` and the stream type is `metadata`, this stream will collect the distinct values from ingestion based on the fields settings.
Then we can use this stream to accelerate the top N value query.
We enable `distinct_values` for fields `service_name` and `operation_name` as default, you can set the extra default field by environment `ZO_FEATURE_DISTINCT_EXTRA_FIELDS`, like:
```
ZO_FEATURE_DISTINCT_EXTRA_FIELDS = "fielda, fieldb"
```
=> feat: implement distinct_values

src/service/ingestion/grpc.rs, src/service/logs/otlp_grpc.rs, src/service/traces/mod.rs
For GRPC ingestion resource attributes , span attributes  values are currently being stored as string , the PR fixes these to retain data types.
=> fix: resource/span attributes retain data types

src/service/db/user.rs, src/service/organization.rs, src/service/users.rs
Ensure the local-cache is invalidated in case of an update operation. Also ensure that the operation is supported in distributed mode
=> fix: invalidate the local cache with rumtoken

web/src/composables/useDashboardPanel.ts
Values API fetched values with the wrong timestamp after changing the date time picker. This issue has been fixed with this PR.
=> fix: wrong timestamps in add panel page values API

src/handler/http/router/openapi.rs
Added the `RumIngestionResponse` and `RumIngestionToken` models to the swagger-ui
=> fix: Swagger was missing a rum-model

src/common/infra/config.rs, src/job/file_list.rs, src/job/files/disk.rs, src/job/files/mod.rs, src/main.rs
We added two environments to control sidecar pod for the ingester:
```
ZO_INGESTER_SIDECAR_ENABLED = false
ZO_INGESTER_SIDECAR_QUERIER = false
```
You can enable these envs when you deploy a sidecar querier for ingester.
Key points:
- Both containers need to set `ZO_INGESTER_SIDECAR_ENABLED = true`
- The ingester needs to set  `ZO_INGESTER_SIDECAR_QUERIER = false`
- The querier needs to set `ZO_INGESTER_SIDECAR_QUERIER = true`
- The ingester listens on HTTP `5080` for receive HTTP ingrestion
- The querier listens on gRPC `5081` for receive gRPC searching
You can deploy a side querier for ingester like this:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
name: zo1-openobserve-ingester
namespace: "ziox-dev"
labels:
helm.sh/chart: openobserve-0.5.30
app.kubernetes.io/name: openobserve …
```
=> feat: support sidecar querier for ingester

src/handler/http/router/mod.rs, src/handler/http/router/ui.rs, src/job/files/disk.rs, src/service/ingestion/grpc.rs, src/service/logs/otlp_grpc.rs, src/service/metrics/otlp_grpc.rs, src/service/traces/mod.rs
Fixed:
```
'tokio-runtime-worker' panicked at /app/src/job/files/disk.rs:257:37:
called 'Result:unwrap()' on an Err value: JsonError("whilst decoding field 'net_peer_port': expected string got 38910")
```
=> fix: data type conflict for traces

web/src/components/dashboards/PanelSchemaRenderer.vue
Fixed below issues related to dashboard:
- When Query throws an error, loading indicator doesn't go away
- In metric text, when the data is there but the value is zero, the no data still shows because zero was considered as falsy value
=> fix: dashboard on query exception loading indicator doesn't disappear

web/package-lock.json, web/src/components/ingestion/Custom.vue, web/src/components/ingestion/metrics/PrometheusConfig.vue, web/src/components/ingestion/recommended/KubernetesConfig.vue, web/src/components/ingestion/recommended/OtelConfig.vue, web/src/components/ingestion/traces/OpenTelemetry.vue
otel-collector is supposed to send all k8s events to a stream named `k8s_events` for for better analysis. It was being sent to `default` for otlp/grpc
=> fix: k8s events stream name

.cargo/config.toml, .github/workflows/release.yml
Add musl binary for arm64 architecture to generate a binary with no dependencies. https://github.com/openobserve/openobserve/issues/1890
=> feat: add musl release binary for arm64 architecture

src/service/search/mod.rs
fixed the issue return result like this:
```json
{"hits": [{}]}
```
=> fix: Filter out empty rows in search results.

src/common/meta/search.rs, src/service/promql/search/grpc/storage.rs, src/service/promql/search/grpc/wal.rs, src/service/search/datafusion/exec.rs, src/service/search/grpc/storage.rs, src/service/search/grpc/wal.rs
This is an optimized option `DATAFUSION_EXECUTION_PARQUET_PUSHDOWN_FILTERS`, we found it can improve normal query speed like `select * from t where a=b`, but it will slow the aggregation query `select a, count(*) from t group by a`.
So, we only auto enable this option for normal query.
After this change we also support use `datafusion evironments` to control it, like set an environment like this:
```
DATAFUSION_EXECUTION_PARQUET_PUSHDOWN_FILTERS = true
```
=> feat: set pushdown_filters only for normal query

src/common/meta/sql.rs, src/service/promql/engine.rs, src/service/promql/mod.rs, src/service/promql/search/grpc/mod.rs, src/service/promql/search/grpc/storage.rs, src/service/promql/search/grpc/wal.rs, src/service/search/mod.rs, src/service/search/sql.rs
fixed #1910
Partition key filters are working on these scenarios:
=> fix: partition key filter with In and Or

.cargo/config.toml, src/common/meta/alert.rs, src/common/utils/notification.rs, src/main.rs, src/service/alert_manager.rs, src/service/alerts/mod.rs, src/service/db/alerts/mod.rs, src/service/logs/mod.rs, src/service/metrics/otlp_grpc.rs, src/service/metrics/otlp_http.rs, src/service/metrics/prom.rs, src/service/traces/mod.rs, src/service/traces/otlp_http.rs, src/service/triggers.rs
=> fix: alert deletion & notification panic

web/src/components/ingestion/recommended/KubernetesConfig.vue
Automatic instrumentation for each language is now done by a sperate instrumenter. This allows for upgrade of helm chart of openobserve collector without making any changes to OpenObserve ingestion page when changes to individual languages are done.
=> fix: change instrumenter to per language

web/src/components/ingestion/recommended/FrontendRumConfig.vue
Added defaultPrivacyLevel guidance which allows configuration of masking session replay data.
=> docs: defaultPrivacyLevel added for RUM

web/package-lock.json
This adds the resolved and integrity attributes to the package-lock.
This makes the build more reproducible.
I removed the lock and regenerated it.
For context I'm trying to package this with nix to add it to nixpkgs.
let me know if anything.
closes https://github.com/openobserve/openobserve/issues/1936
=> fix: web/deps add resolved and integrity to package-lock

web/src/views/Ingestion.vue
This PR contains a fix for tabs not visible on the Ingestion page.
In the Safari browser, Vertical tabs on the Ingestion page are not visible because of the CSS class.
=> fix: safari issue on ingestion page

src/job/mmdb_downloader.rs
- mmdb-downloader wasn't enabled on ingestor, enabled that.
- mmdb-client wasn't initialized on the first run ( in case the file
already existed ), so enabled that
=> fix: run the mmdb downloader everywhere

web/package-lock.json
when trying to install the latest release frontend just from the package-lock.json here is the error that is generated
```
> npm ERR! code 1
> npm ERR! path /build/source/web/node_modules/@sentry/cli
> npm ERR! command failed
> npm ERR! command sh -c node ./scripts/install.js
> npm ERR! [sentry-cli] Downloading from https://downloads.sentry-cdn.com/sentry-cli/2.21.5/sentry-cli-Linux-x86_64
> npm ERR! Error: Unable to download sentry-cli binary from https://downloads.sentry-cdn.com/sentry-cli/2.21.5/sentry-cli-Linux-x86_64.
> npm ERR! Error message: request to https://downloads.sentry-cdn.com/sentry-cli/2.21.5/sentry-cli-Linux-x86_64 failed, reason: getaddrinfo EAI_AGAIN downloads.sentry-cdn.com
> npm ERR! Error code: EAI_AGAIN
>
> npm ERR! Log files were not written due to an error …
```
=> ci: add missing integrity to package lock

src/common/meta/middleware_data.rs, src/handler/http/auth/mod.rs
We have updated the prefix of the keys from `oo` -> `o2` in rum-browser sdk. This change is to support both the versions of keys in the payload
=> fix: rum browser sdk sends keys with updated o2 prefix

web/src/components/ingestion/recommended/LinuxConfig.vue
Removed newline. Directly copy pasting the linux ingestion command was throwing error 
```
curl: (3) URL using bad/illegal format or missing URL
-bash: syntax error near unexpected token `&&'
```
=> fix: removed newline

web/src/components/ingestion/recommended/WindowsConfig.vue
At least powershell 6 was required to execute the openobserve-collector installation script on windows. By deafult powershell 5.1 is available in most machines. 
This modification allows installation of openobserve-collector without upgrading powershell.
=> feat: remove requirement of powershell6+

src/handler/http/request/search/mod.rs, src/service/distinct_values.rs
Now, you can set url parameter `keyword=abc` to search the values. and use parameter `filter=service_name=a,b,c` to filter multiple values.
=> fix: add keyword search for values API

web/src/components/dashboards/viewPanel/ViewPanel.vue, web/src/utils/dashboard/convertPromQLData.ts, web/src/utils/dashboard/convertSQLData.ts, web/src/views/Dashboards/RenderDashboardCharts.vue
- fix: Tooltip does not working in Add/Edit panel.
- fix: Should not allowed to zoom for non timeseries charts.
- fix: maximize panel initial variable issue.
=> fix: zoom issue for non timeseries charts

Cargo.lock, Cargo.toml, src/common/infra/config.rs, src/main.rs
The idea behind this PR is to generate logs in a structured-json
format, such that we can use automated tooling to parse and debug
O2 logs as well.
If logs are to be written and analysed in files, one can enable:
`ZO_LOG_FILE_DIR=/tmp/openobserve`
The output file will be of format - `/tmp/openobserve/o2.log.2023-12-18-10`
and it will be rotated daily.
And add a new environment `ZO_LOG_JSON_FORMAT=false`, set to `true` to enable json format.
=> feat: support structured logging

web/src/composables/useDashboardPanel.ts, web/src/views/Dashboards/addPanel/AddPanel.vue
- fix: zoom issue in add/edit panel.
- fix: tooltip highlight issue in add/edit panel.
- fix: by default, histogram field should use 'ASC' in sort by field.
=> fix: add/edit panel zoom, tooltip highlight and histogram field should use ASC as a default in sort by field issue

web/src/components/rum/VideoPlayer.vue, web/src/views/RUM/AppSessions.vue
1. Session video frame was overlapping the video display area.
2. Updated the start and end time of relative date selected on clicking run query
=> fix: RUM session replay issues

src/common/infra/config.rs, src/handler/http/request/status/mod.rs
Control redirection of a user to ingestions page in case no data This is an extension to #2173, just that user can now control this behavior.
```
ZO_RESTRICTED_ROUTES_ON_EMPTY_DATA=false cargo run
curl -s -u user:pass -k http://localhost:5080/config | jq .restricted_routes_on_empty_data
```
=> feat: control redirection of a user to ingestions

web/src/utils/logs/convertLogData.ts
=> fix: logs chart y-axis overlapping issue in logs page

deploy/build/Dockerfile, deploy/build/Dockerfile.aarch64, deploy/build/Dockerfile.amd64, deploy/build/Dockerfile.tag-debug.aarch64, deploy/build/Dockerfile.tag-debug.amd64, deploy/build/Dockerfile.tag-simd.amd64, deploy/build/Dockerfile.tag.aarch64, deploy/build/Dockerfile.tag.amd64
Bump Node.js to latest v18 release: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.19.0
=> chore: Bump Node.js to v18.19.0

src/handler/http/request/search/mod.rs, src/service/search/mod.rs
vrl functions during query make query execution very slow, which makes function unusable, the PR aims to fix this by:
This will result in values for derived field values not being returned for _values api
=> fix: vrl function for query execution

web/src/utils/dashboard/convertPromQLData.ts, web/src/utils/dashboard/convertSQLData.ts, web/src/utils/logs/convertLogData.ts
- fix: logs chart decimal point issue in yaxis
- add: showing split line in charts.
=> fix: logs chart decimal point issue in yaxis and show grid lines

web/src/components/dashboards/addPanel/ConfigPanel.vue, web/src/utils/dashboard/convertDataIntoUnitValue.ts, web/src/utils/dashboard/convertPromQLData.ts, web/src/utils/dashboard/convertSQLData.ts, web/src/utils/dashboard/convertTableData.ts
- decimal points for table chart.
- for pie chart, use decimal point in percentage label.
=> feat: decimal points for table chart

tests/ui-testing/cypress/e2e/tests/dashboard/create_dashboard.cy.js, tests/ui-testing/cypress/support/commons.js
- Add a panel 
- drag and drop an element 
- Verify query generation on the when fields are added and removed from axis
- Update the chart when field configurations are updated including filters
- Update the value automatically when trying to save the chart after switching from the auto to custom mode
- Clear the field after switch from custom to auto mode
- Generate chart with the custom query mode
- Display error when add new chartype with existing chart type value
- Delete all dashboards
=> feat: e2e add dashboard panel testcases

src/common/meta/middleware_data.rs, src/lib.rs, src/main.rs
UserAgent parser is currently used exclusively in RUM related middleware. Loading it lazily when RUM data is ingested results in significant RSS reduction at the startup of O2.
=> fix: RSS reduction due to lazily loading ua-parser

Cargo.lock, web/src/composables/useLogs.ts, web/src/locales/languages/en.json, web/src/plugins/logs/Index.vue, web/src/plugins/logs/SearchBar.vue, web/src/plugins/logs/SearchResult.vue, web/src/utils/logs/convertLogData.ts
**Problem Statement:**
The Logs page experienced excessive memory consumption, exceeding 2-3 GB. This issue was attributed to the highlight feature on the table grid data, compounded by the rendering of a large volume of data on the grid.
**Solution:**
Removed the highlight feature.
Implemented pagination on the Logs page.
**Enhancements:**
Improved the download feature.
Users now have the option to download:
- Entire table data.
- Custom data, specifying the starting number and the desired number of records.
This pull request addresses the memory consumption issue and introduces optimizations for better performance.
=> feat: Logs page pagination

web/src/composables/useLogs.ts, web/src/main.ts, web/src/plugins/logs/Index.vue, web/src/plugins/logs/SearchBar.vue, web/src/plugins/logs/SearchResult.vue
PR contains changes related to memory issue on logs page.
- to avoid memory leak, cleaning up the data from the composable variable. So user navigates away from the logs page all data will be removed to free up memory. Once user come back to logs page data will be pulled again.
- fixed function editor content issue which was wiped out once user navigate back to logs page.
=> fix: Memory leak pagination test

src/cli/basic/cli.rs, src/common/infra/db/dynamo.rs, src/common/migration/file_list.rs, src/common/migration/meta.rs, src/common/migration/mod.rs
impl #2469 
```
./openobserve migrate-meta --help
migrate meta
Usage: openobserve migrate-meta --from <from> --to <to>
Options:
-f, --from <from>  migrate from: sled, sqlite, etcd, mysql, postgresql
-t, --to <to>      migrate to: sqlite, etcd, mysql, postgresql
-h, --help         Print help
```
```
./openobserve migrate-file-list --help
migrate file-list
Usage: openobserve migrate-file-list [OPTIONS] --from <from> --to <to>
Options:
-p, --prefix <prefix>  only migrate specified prefix, default is all
-f, --from <from>      migrate from: sled, sqlite, etcd, mysql, postgresql
-t, --to <to>          migrate to: sqlite, mysql, postgresql
-h, --help             Print help
```
=> feat: migrate from any to any

src/common/infra/cluster.rs, src/common/utils/base64.rs, src/config/src/config.rs, src/handler/http/request/status/mod.rs, src/handler/http/router/mod.rs, src/ingester/src/lib.rs, src/ingester/src/writer.rs, src/service/alerts/alert_manager.rs, src/service/alerts/mod.rs, src/service/ingestion/mod.rs, src/service/logs/bulk.rs, src/service/logs/ingest.rs, src/service/logs/mod.rs, src/service/logs/multi.rs, src/service/logs/otlp_grpc.rs, src/service/logs/otlp_http.rs, src/service/logs/syslog.rs, src/service/metrics/otlp_grpc.rs, src/service/metrics/otlp_http.rs, src/service/metrics/prom.rs, src/service/traces/mod.rs, src/service/traces/otlp_http.rs, web/src/components/alerts/AddTemplate.vue
1. PUT `/api/node/enable?value=false` let the node leave from cluster
2. PUT `/api/node/flush` let the node flush all memory data into disk
3. Waiting for 30 minutes, let everything move to s3
4. You can use command `find /data/wal/ -name '*.parquet' to confirm there is no parquet files.
5. Remove the pod
Add a new ENV for it: `ZO_WEB_URL=http://log.zinc.dev`
=> feat: add alert_url variable for alerts

.github/workflows/build-pr-image.yml
More information in this - https://github.com/actions/checkout/issues/237
=> fix: ensure correct commit-id is fetched during a PR build

src/common/utils/json.rs, src/config/src/utils/schema.rs, src/service/enrichment_table/mod.rs, src/service/logs/mod.rs, src/service/metrics/json.rs, src/service/metrics/otlp_grpc.rs, src/service/metrics/otlp_http.rs, src/service/metrics/prom.rs, src/service/schema.rs, src/service/traces/mod.rs, src/service/traces/otlp_http.rs
1. avoid record_val clone operation when inferring schemas in writing/reading procedure.
2. use estimate_bytes for json size calculating instead of serializing it.
3. match snippet optimizes.
=> refactor: avoid record_val clone operation when inferring schemas

web/src/components/ingestion/logs/SyslogNg.vue
source should be "s_src" as defined in syslog-ng.conf, otherwise syslog-ng will fail to start, displaying:
>  Error resolving reference; content='source', name='src', location='/etc/syslog-ng/conf.d/openobserve.conf:13:5
=> fix: Replace src with s_src in SyslogNg.vue

deploy/build/Dockerfile, deploy/build/Dockerfile.aarch64, deploy/build/Dockerfile.amd64, deploy/build/Dockerfile.tag-debug.aarch64, deploy/build/Dockerfile.tag-debug.amd64, deploy/build/Dockerfile.tag-simd.amd64, deploy/build/Dockerfile.tag.aarch64, deploy/build/Dockerfile.tag.amd64, proto/cluster/search.proto, src/common/meta/search.rs, src/handler/grpc/mod.rs, src/handler/http/request/authz/fga.rs, src/ingester/src/immutable.rs, src/service/promql/search/grpc/storage.rs, src/service/promql/search/grpc/wal.rs, src/service/search/datafusion/exec.rs, src/service/search/grpc/mod.rs, src/service/search/grpc/storage.rs, src/service/search/grpc/wal.rs, src/service/search/mod.rs
Impl #2506 
Implemented global search work groups:
- long query group
- O2_SEARCH_GROUP_LONG_MAX_CPU = 80%
- O2_SEARCH_GROUP_LONG_MAX_MEMORY = 80%
- O2_SEARCH_GROUP_LONG_MAX_CONCURRENCY = 2
- short query group
- O2_SEARCH_GROUP_LONG_MAX_CPU = 20%
- O2_SEARCH_GROUP_LONG_MAX_MEMORY = 20%
- O2_SEARCH_GROUP_LONG_MAX_CONCURRENCY = 4
Enterprise version will default enable two search queue. 1 for long term query, 1 for short query. when you are running a long term query, if you fire another small query it sill can be quickly response. but more than `MAX_CONCURRENCY` of the group still need to wait in a queue.
Open source version still only has a global search queue, default is enabled. it means only support 1 QPS for query. Also you can disable it by `ZO_FEATURE_QUERY_QUEUE_ENABLED=false`. After …
=> feat: search queue

src/common/infra/cluster.rs
This causes the compactor to invoke `continue` and hence never compacts
=> fix: during compaction in single node mode, the uuids were different

src/common/meta/dashboards/v3/mod.rs, web/src/components/dashboards/PanelContainer.vue, web/src/components/dashboards/PanelSchemaRenderer.vue, web/src/components/dashboards/VariablesValueSelector.vue, web/src/components/dashboards/addPanel/ConfigPanel.vue, web/src/components/dashboards/addPanel/Drilldown.vue, web/src/components/dashboards/addPanel/DrilldownPopUp.vue, web/src/components/dashboards/addPanel/DrilldownUserGuide.vue, web/src/components/dashboards/panels/ChartRenderer.vue, web/src/components/dashboards/panels/TableRenderer.vue, web/src/components/dashboards/viewPanel/ViewPanel.vue, web/src/composables/useDashboardPanel.ts, web/src/views/Dashboards/RenderDashboardCharts.vue, web/src/views/Dashboards/ViewDashboard.vue
Drilldown, which allows users to navigate seamlessly between dashboards or specified URLs, carrying over all current variables.
To add a Drilldown, follow these steps:
1. Edit the panel where you wish to add or modify a Drilldown.
2. Navigate to the configuration panel. Here, you'll find an option for Drilldown.
3. You'll see a list of existing Drilldowns.
4. From here, you can add a new Drilldown or edit an existing one by clicking on the Drilldown name.
When adding or editing a Drilldown, you have two options:
1. **Drilldown to another dashboard:** Specify the target folder, dashboard, and tab. You can also pass variables to the target dashboard.
2. **Drilldown to a specified URL:** Provide the URL where you want the Drilldown to navigate to. Here too, you can pass variables to the …
=> feat: dashboard drilldown to another dashboard

web/src/components/dashboards/addPanel/FieldList.vue
- dashboard streams not loaded when switched between chart types like HTML and Markdown and back to any chart type that has field list
=> fix: dashboard streams not loaded when switched between chart types like HTML and Markdown

src/handler/http/request/alerts/destinations.rs, src/handler/http/request/alerts/mod.rs, src/handler/http/request/alerts/templates.rs, src/service/alerts/destinations.rs, src/service/alerts/mod.rs, src/service/alerts/templates.rs, src/service/db/alerts/mod.rs
=> fix: can't create same name alerts

web/src/composables/useLogs.ts
Steps: Load the home page, and navigate to the logs page. After changing the organization streams not getting populated.
Need to add a delay so store state refresh gets complete by adding nextTick()
=> fix: organization change not loads stream data

src/config/src/config.rs
change ZO_RESTRICTED_ROUTES_ON_EMPTY_DATA to false. This will not restrict self hosted users from visiting all the pages unless data is ingested.
=> fix: change ZO_RESTRICTED_ROUTES_ON_EMPTY_DATA default to false

CONTRIBUTING.md, Cargo.lock, Cargo.toml, src/config/Cargo.toml, src/config/src/config.rs
Addresses #2601.
`lettre` crate requires Rust `1.70+`. `ZO_SMTP_ENCRYPTION` env variable offers two important encryption method - `starttls` and `ssltls`.
=> feat: introduce SMTP env configurations

src/config/src/config.rs, src/service/search/datafusion/exec.rs
```
ZO_FEATURE_QUERY_INFER_SCHEMA=false
```
- By default, this is set to `false`. In this case, the latest schema we have created is used by Datafusion, reducing the need to infer the schema from the files.
- When set to `true`, our own schema is ignored, allowing Datafusion to infer the schema from all the Parquet files and merge the resulting schema.
An alternative solution:
```
ZO_FEATURE_QUERY_INFER_SCHEMA_IF_FIELDS_MORE_THAN=0
```
- This value can be set to a larger number, such as `1000`. If the number of fields in the latest schema exceeds this value, our schema will be skipped and the schema will be inferred from the Parquet files being searched.
=> perf: add a new configure to enable infer schema in datafusion

src/common/meta/alerts/destinations.rs, src/common/meta/alerts/templates.rs, src/handler/http/request/alerts/destinations.rs, src/service/alerts/destinations.rs, src/service/alerts/mod.rs
Addresses #2601.
No breaking API changes. For destination and template, previous API payloads work as "http" type destination/template payload. For "email" destination/template -
**Email destination**
supports multiple emails. Example payload -
```
{
"name": "email destination",
"template": "my new template",
"emails": ["example@hi.com", "hi@mail.com"],
"type": "email"
}
```
The above payload creates the following Destination instance - 
```
{
"name": "email destination",
"url": "", //ignored
"method": "post", //ignored
"skip_tls_verify": false, //ignored
"template": "my new template",
"emails": [
"subhradeepc461@gmail.com",
"chakrabortyabhradeep79@gmail.com"
],
"type": "email"
}
```
**Email template**
Example API payload. Supports all variables in "{}" as it does for the "http" template …
=> feat: introduce alert emails in backend

src/infra/src/cache/tmpfs.rs, src/job/compact.rs, src/job/files/parquet.rs, src/service/compact/file_list_deleted.rs, src/service/compact/merge.rs, src/service/compact/mod.rs, src/service/ingestion/mod.rs, src/service/logs/bulk.rs, src/service/logs/otlp_grpc.rs, src/service/logs/otlp_http.rs, src/service/metrics/json.rs, src/service/metrics/otlp_grpc.rs, src/service/metrics/otlp_http.rs, src/service/metrics/prom.rs, src/service/search/datafusion/exec.rs, src/service/search/datafusion/storage/file_list.rs, src/service/search/grpc/wal.rs, src/service/traces/mod.rs, src/service/traces/otlp_http.rs
The error like this:
```
[session_id 2dFw4lQuKJC4YzLWGUTgdlCj2To] datafusion execute error: Object Store error: Object at location 2dFw4lQuKJC4YzLWGUTgdlCj2To/files/xxxxx/logs/default/0/2024/03/05/05/ef044358a99e1951/1709616013000000.1709616616553572.7170652240892412148.parquet not found: DbError# key /2dFw4lQuKJC4YzLWGUTgdlCj2To/files/xxxxx/logs/default/0/2024/03/05/05/ef044358a99e1951/1709616013000000.1709616616553572.7170652240892412148.parquet does not exist
````
The reason is recently we added search on arrow, but it used same tmpfs directory name, it will clean the tmpfs when arrow search done.
=> fix: search got parquet not found

web/src/components/ingestion/recommended/KubernetesConfig.vue
Add Servicemonitor and Podmonitor CRDs of prometheus operator. These can be used by Opentelemetry operator target allocator. target allocator can discover prometheus metrics using existing Servicemonitor and Podmonitor CRDs
=> fix: add prometheus operator CRDs

src/service/search/mod.rs, src/service/search/sql.rs
=> fix: debug inverted index

Cargo.lock, Cargo.toml, src/common/meta/alerts/mod.rs, src/service/alerts/alert_manager.rs, src/service/alerts/mod.rs
Uses `cron` crate to parse the cron expressions. Additionally, rather than the standard 5 column cron expressions, it uses 7 columns (sec and year is added) -
| sec | min |  hour |  day of month |    month  |   day of week  |   year |
|-----|-----|--------|----------------|------------|-----------------|-------|
|  0   |  30  |  15     |      1,15            | May-Aug |  Mon,Wed,Fri  |     *    |
The above expression evaluates to - each year from May to Aug, on 1st and 15th day of month, on Mon/Wed/Fri at 15:30.
Non-breaking API changes. Adds the following optional extra fields -
```
{
"name": "cron_alert_test_1",
"org_id": "default",
"stream_type": "logs",
"stream_name": "default",
"is_real_time": false,
"query_condition": {
"type": "custom",
"conditions": [
{
"column": …
```
=> feat: introduce cron jobs for alerts

src/config/src/config.rs, src/job/files/parquet.rs, src/service/search/datafusion/string_to_array_v2_udf.rs, src/service/search/mod.rs
We now ensure that trim/split are being done on different set of chars. Earlier they were shared.
Also added a new env var to split ZO_INVERTED_INDEX_SPLIT_CHARS e.g.
ZO_INVERTED_INDEX_SPLIT_CHARS: '_/- '
=> fix: ensure trim and split on different chars

src/common/meta/sql.rs, src/service/db/file_list/broadcast.rs
fix #2982 
```
Search field not found
```
The query SQL is like this:
```sql
select a, b, c from table
```
We have the 3 fields `a`, `b`, `c` in latest schema. but for earlier parquet files there is no field `c`. when we run query will got `field c not found`.
**The solution is:**
```
we infer all the fields that we need and then add it into the schema.
```
=> fix: search field not found

web/src/components/DateTime.vue, web/src/components/DateTimePickerDashboard.vue, web/src/views/Dashboards/ViewDashboard.vue
- show absolute time for print mode with provided timezone.
=> fix: show absoulte time with timezone in header for printmode

tests/api-testing/tests/conftest.py, tests/api-testing/tests/test_search.py, tests/ui-testing/cypress/e2e/tests/alerts_tests.cy.js, tests/ui-testing/cypress/e2e/tests/dashboard/add_dashboard.cy.js, tests/ui-testing/cypress/e2e/tests/dashboard/create_dashboard.cy.js, tests/ui-testing/cypress/e2e/tests/dashboard/edit_dashboard.cy.js, tests/ui-testing/cypress/e2e/tests/dashboard/folders.cy.js, tests/ui-testing/cypress/e2e/tests/functions_tests.cy.js, tests/ui-testing/cypress/e2e/tests/logs_fastmode.cy.js, tests/ui-testing/cypress/e2e/tests/logs_queries.cy.js, tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js, tests/ui-testing/cypress/e2e/tests/menu_tests.cy.js
Created a fixture which will be available during scope=session. This will ingest data present in tests/test-data/logs_data.json to org_pytest_data and stream_pytest_data
API Tests positive and negative scenarios - 
- Search without payload
- Search with valid sql query
- search with invalid sql query
- search with limit and sql query
- valid histogram query
- histogram query with limit
=> test: prepopulate the amount of data for each test #3000

web/src/views/RUM/SessionViewer.vue
Problem:
Observed that the User Session Viewer was yielding incorrect results when filtering session events data. The root cause was identified as the improper handling of a compound predicate within the SQL query used for data retrieval.
Solution:
When parentheses were added around the conditions `session_id='xyz' && (type='error' or type='action' or type='view')` to logically group them, this fixed the issue.
=> fix: fixed event filtering condition in Session Viewer events query

src/handler/http/request/status/mod.rs, src/handler/http/router/mod.rs, src/service/search/mod.rs
- `/healthz` will always return `ok` when the node is ready.
- `/schedulez` will return the working status and return `ok` when the node is online and scheduled, or will return `not ok`.
=> feat: add new endpoint for health check

src/handler/http/request/search/mod.rs, src/service/promql/search/mod.rs, src/service/usage/mod.rs
Reports `query.start_time` and `query.end_time` as `min_ts` and `max_ts` respectively for the "Search" event in `usage` stream.
=> feat: add query start_time and end_time for reporting a search query usage

web/src/components/dashboards/settings/VariableQueryValueSelector.vue
While implementing a filter search feature with dropdown menus for variables, an error occurred due to undefined values. This error hindered the functionality of the search feature, causing unexpected behavior when attempting to filter results.
=> fix: dashboard variable dropdown on typing getting error

tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js, web/src/composables/useLogs.ts, web/src/plugins/logs/Index.vue
In sql mode, if query does not contains  " order by " it throws error.
Solution:
On switching to sql mode, by default added "order by _timestamp desc" in logs query
=> fix: added order by _timestamp desc in logs query

Cargo.lock, src/service/dashboards/reports.rs
Instead of waiting for `CONFIG.chrome.chrome_sleep_secs` to let the data load in the dashboard for report, frequently, check for the `span` element with a loop.
=> feat: frequently check for span element render for dashboard report

src/infra/src/lib.rs, src/infra/src/scheduler/mod.rs, src/job/alert_manager.rs
Instead of initializing the scheduler inside `infra::init()`, the `alert_manager` only now initializes the scheduler.
=> fix: only alert_manager should init the scheduler

web/src/views/Dashboards/Dashboards.vue, web/src/views/Dashboards/ViewDashboard.vue
Sharing dashboard URLs didn't work properly when tabs were involved. Regardless of the selected tab, the link always took users to the first tab. This issue has been fixed, ensuring that shared URLs now correctly direct users to the intended tab, providing a smoother experience for navigating dashboards.
=> fix: On sharing URL link, by default 1st tab was getting selected

Cargo.lock, src/common/utils/auth.rs, web/packages/rrweb-player/public/index.html, web/src/components/iam/roles/EditRole.vue
Problem:
Suppose we want to give POST permission for all log streams. Then we use orgId as entity, as we give permission for all log streams in that org. If orgId and stream name are same. For eg. default log stream in default org. The permission object for post permission on single "default" (name of stream) log stream and Post permission on all log streams in "default" org, both are same. And this creates a conflict
Solution:
While giving all resources permission on any of resource type, we prefix orgId with `_all_` and this will not conflict with any resource
=> fix: IAM resource type permissions

src/infra/src/db/nats.rs
This PR prints error message with NATS server address when connection to NATS fails.
=> fix: print better error message with NATS server address for which failed to connect

src/config/src/config.rs, src/service/usage/mod.rs
ENVs introduced - 
| `ENV` | Description |
|--------|-------------|
| `ZO_USAGE_REPORTING_MODE` | Possible values - `local`, `remote` and `both`. `local` means usage is only reported in internal cluster. `remote` means store it in remote address and `both` means reporting is done in the both `local` and `remote`. Default is `local` |
| `ZO_USAGE_REPORTING_URL` | Remote Reporting URL (with full api endpoint). Default is `http://localhost:5080/api/_meta/usage/_json` |
| `ZO_USAGE_REPORTING_CREDS` | Credentials required for posting the usage report to remote reporting URL |
=> feat: publish usage report to external url

src/config/src/config.rs, src/config/src/utils/flatten.rs, src/job/files/parquet.rs, src/service/ingestion/mod.rs, src/service/logs/bulk.rs, src/service/logs/ingest.rs, src/service/logs/multi.rs, src/service/logs/otlp_grpc.rs, src/service/logs/otlp_http.rs, src/service/logs/syslog.rs
=> perf: improve ingestion load and flatten

src/service/search/cluster/mod.rs
=> fix: trace get_file_list

src/handler/http/auth/validator.rs, web/src/components/rum/VideoPlayer.vue, web/src/workers/rumcssworker.js
Due to changes in the current architecture the access-token is being sent as a cookie - `access_token` so this change facilitates accessing the proxy url via the same mechanism
=> fix: ensure that rum proxy endpoint uses cookies

web/src/components/dashboards/QueryInspector.vue
The dashboard query inspector originally set the start and end times in UTC. These times, however, have been adjusted to the appropriate time zone.
=> fix: dashboard query inspector time based on its time zone

src/config/src/config.rs
Improve the default list of characters using which the field content will be split for inverted index search
=> fix: improve default list of split characters

src/common/migration/mod.rs, src/common/migration/triggers.rs, src/infra/src/lib.rs, src/infra/src/scheduler/mod.rs, src/job/alert_manager.rs, src/main.rs
Fixes #3249 .
Migrates previously used alert `Triggers` into `scheduled_jobs` table.
=> fix: migration from old TRIGGERS to scheduled jobs

src/config/src/config.rs, src/job/files/parquet.rs
Added a new option for limit merge files on ingester
```
ZO_FILE_MOVE_FIELDS_LIMIT=2000
```
=> feat: add a new option for limit merge on ingester

.github/workflows/build-fork-pr-image.yml, .github/workflows/ok-to-test.yml
Several of the contributors who sent a PR see several failures in the CI especially the part where a docker container image is built and pushed to public aws-ecr.
This PR ensures that whenever a PR comes from an external contributor, a developer after carefully reviewing the code, writes `/ok-to-test <commit-to-test>` This comment will trigger a repository_dispatch event which will run a new workflow `build-fork-pr-image.yml` in the context of a privileged user, thus building and pushing the image to ECR and in the end it also updates the status of the existing pipelines.
Finally, the `build-pr-image.yml` will now run for only the members of the Openobserve organization.
=> ci: integrate an ok-to-test pull-request command

.github/workflows/build-fork-pr-image.yml
Since this workflow runs via a repository_dispatch event the payload contains all the data behind `github.event.client_payload.pull_request`
=> fix: for forked pull-requests pick up the correct git ref

src/handler/http/request/alerts/mod.rs, src/service/alerts/mod.rs
=> fix: don't use stream_type from query params for alert create/update

src/common/utils/auth.rs, src/handler/http/request/dashboards/reports.rs, src/service/alerts/destinations.rs, src/service/alerts/mod.rs, src/service/alerts/templates.rs, src/service/dashboards/folders.rs, src/service/dashboards/reports.rs, src/service/functions.rs, src/service/stream.rs, web/src/components/iam/roles/EditRole.vue
For enterprise in rbac, `GET` methods for `reports` and `savedviews` consists of `{org_id}/<reports|savedviews>/{id}` format, i.e. `url_len` is 3. This PR corrects how the fga object string is extracted (which should be `report:{report_name}` or `savedview:{view_id}`) from the url path with the above format with `GET` method.
=> fix: show savedview and report resources in role permissions and fix `list_objects_for_user` for `_all_{org}`

src/config/src/config.rs, src/infra/src/cache/stats.rs, src/service/stream.rs, src/service/usage/mod.rs, src/service/usage/stats.rs
The `ZO_USAGE_REPORTING_COMPRESSED_SIZE` we no longer use it, but i saw we enabled this configure in alpha1 and monitor, it will cause problem because there is no backend report job for it.
=> fix: remove unused code

src/common/infra/config.rs, src/common/migration/meta.rs, src/config/src/meta/usage.rs, src/infra/src/scheduler/mod.rs, src/infra/src/scheduler/mysql.rs, src/infra/src/scheduler/postgres.rs, src/infra/src/scheduler/sqlite.rs, src/job/mod.rs, src/service/alerts/alert_manager.rs, src/service/db/alerts/mod.rs, src/service/db/alerts/realtime_triggers.rs, src/service/db/scheduler.rs, src/service/ingestion/mod.rs
Fixes #2908 
When the realtime alert is triggered and the notification is sent successfully, the silence period is now updated in the scheduled jobs table and updated locally via the realtime triggers cache.
=> fix: introduce realtime alert triggers cache

web/src/components/dashboards/VariablesValueSelector.vue
Avoid using `SELECT * FROM` for performance while loading dashboard variables
=> fix: dashboard variables values API context SQL

tests/ui-testing/playwright-tests/logspage.spec.js
Automation for bug - #3480 
-Logs: Blank page displayed after user adds a function on logs page, clicks on any log result and then selects search around
=> test: e2e-search-around

src/service/pipelines.rs, src/service/users.rs
=> fix: user, pipeline list rbac issues

src/service/dashboards/folders.rs
Since for rbac, the `dfolder:default` permissions are being created while creating an org, it is ok to ignore `set_ownership` for default folders.
=> fix: don't set rbac ownership for creating default folders

src/ingester/src/memtable.rs, src/ingester/src/partition.rs, src/ingester/src/stream.rs, src/ingester/src/wal.rs, src/ingester/src/writer.rs, src/router/http/mod.rs, src/service/db/compact/stats.rs, src/service/db/file_list/remote.rs, src/service/metadata/distinct_values.rs
=> perf: optimize ingester writing

src/common/utils/auth.rs, src/job/alert_manager.rs, src/service/alerts/alert_manager.rs, src/service/dashboards/reports.rs, src/service/db/dashboards/reports.rs, src/service/db/scheduler.rs
=> fix: report issues

src/common/meta/dashboards/reports.rs, src/config/src/config.rs, src/service/dashboards/reports.rs
Fixes #3355 
User must use a separate chrome server if `ZO_CHROME_PATH` is not specified. `ZO_REPORT_SERVER_URL` is introduced to specify the report server url.
=> feat: use a separate chrome server for report

src/config/src/config.rs, src/config/src/utils/parquet.rs, src/job/files/parquet.rs, src/service/compact/merge.rs, src/service/search/datafusion/exec.rs, src/service/search/grpc/storage.rs, src/service/search/grpc/wal.rs
add a new test environment:
```
ZO_DATAFUSION_PARQUET_STAT_DISABLE_FOR_AGGS=false
```
Set to `true` will skip collect stat for parquet files, then it will faster.
And, i am thinking the final solution should be cache parquet statistics, or we can optimize datafusion let it only collect stat for registered schema fields.
=> perf: testing optimise aggeration query

Cargo.lock, Cargo.toml, src/config/src/config.rs, src/handler/http/request/status/mod.rs, src/infra/src/cache/mod.rs, src/service/search/datafusion/exec.rs, src/service/search/datafusion/storage/file_list.rs, src/service/search/datafusion/storage/file_statistics_cache.rs, src/service/search/datafusion/storage/mod.rs
Last PR i added a new ENV `ZO_DATAFUSION_PARQUET_STAT_DISABLE_FOR_AGGS`, but now we can use parquet file statistics cache to do better, so i deleted the ENV.
Query for last 3 days within 100GB data:
- without cache: 10s
- with stat cache: 8s
This is for all the query not only for aggregation.
Also added a new ENV:
```
ZO_DATAFUSION_FILE_STAT_CACHE_MAX_ENTRIES=100000
```
=> perf: use parquet file static cache

src/config/src/config.rs, src/config/src/utils/record_batch_ext.rs, src/handler/http/request/stream/mod.rs, src/infra/src/file_list/mysql.rs, src/infra/src/file_list/postgres.rs, src/infra/src/file_list/sqlite.rs, src/ingester/src/errors.rs, src/ingester/src/immutable.rs, src/ingester/src/lib.rs, src/ingester/src/partition.rs, src/ingester/src/writer.rs, src/job/compactor.rs, src/job/files/parquet.rs, src/job/flatten_compactor.rs, src/service/compact/file_list.rs, src/service/compact/flatten.rs, src/service/compact/merge.rs, src/service/compact/mod.rs
- `ZO_COMPACT_FAST_MODE=true`, Enable fast mode compact, will use more memory but faster
- `ZO_FILE_MOVE_THREAD_NUM=0`, threads num for file move on ingester
- `ZO_MEM_DUMP_THREAD_NUM=0`, threads num for memtable dump to disk on ingester
- `ZO_FILE_MERGE_THREAD_NUM=0`, threads num for file merge on compactor
- Optimize file_list index
- Optimize MemTable dump to disk, use worker and channels
- Optimize compactor merging to reduce memory usage
=> feat: sync hotfix from v0.10.6-rc3

src/infra/src/db/postgres.rs, src/infra/src/file_list/postgres.rs, src/infra/src/scheduler/postgres.rs, src/infra/src/schema/history/postgres.rs
Add PRIMARY KEY constraints on `id` field to all tables in `postgres` database.
Tables considered here:
```
meta
file_list
file_list_history
file_list_deleted
file_list_jobs
stream_stats
scheduled_jobs
schema_history
```
=> fix: Add PRIMARY KEY constraint to tables in postgres

src/service/search/cluster/mod.rs
=> perf: keep improve inverted index

src/config/src/config.rs, src/main.rs
Run grpc server in a separate tokio runtime with appropriate number of threads.
These 2 env variables will control the number of threads for the grpc runtime.
```
ZO_GRPC_RUNTIME_WORKER_NUM
ZO_GRPC_RUNTIME_BLOCKING_WORKER_NUM
```
=> fix: Separate runtime for grpc server

src/handler/grpc/request/ingest.rs, src/service/alerts/scheduler.rs, src/service/enrichment_table/mod.rs, src/service/search/cluster/mod.rs, src/service/search/datafusion/exec.rs, src/service/search/grpc/mod.rs, src/service/search/grpc/storage.rs, src/service/search/grpc/wal.rs, src/service/search/mod.rs
The reason is in some case the plan is difference. if there is only one partition and that is a simple query then there is no `sort` and simple add a new `Projection` plan, and it is difference with other nodes which have multiple partitions, then the merge got RecordBatch mismatch.
The solution have two:
- Format all the RecordBatch before merge using the Schema from partial plan. 
- I used it in this PR
- Use `EmptyTable` to generate plan then we can guarantee the plan is same, then replace the `EmptyTable` to `MemoryTable` or `ParquetTable` in different node based on the data. 
- We will use this in the next big release
By the way:
Also updated a logic of derived schema
=> fix: merge plan panic

src/service/search/datafusion/exec.rs, src/service/search/datafusion/udf/transform_udf.rs
fix #4462
Now you can use VRL function as query UDF. for example:
create one function:
- Name: `test_abc`
- Param: `value`
```
if .value == "abc" {
. = true
} else {
. = false
}
.
```
then we can query like this:
```sql
select test_abc(field) as abc from default
```
Also you can create a function with two params:
- Name: `test_eq`
- Params: `v1, v2`
```
if .v1 == .v2 {
. = true
} else {
. = false
}
.
```
Then we can query like this:
```sql
select test_eq(field1, field2) as val from default
```
- If you create function from query, the param only one and the name is `row`.
- The input field value will convert to `string` also the return always `string`.
=> fix: vrl as query UDF

src/job/files/parquet.rs, src/service/enrichment_table/mod.rs, src/service/ingestion/mod.rs, src/service/logs/mod.rs, src/service/metadata/distinct_values.rs, src/service/metadata/trace_list_index.rs, src/service/metrics/json.rs, src/service/metrics/otlp_grpc.rs, src/service/metrics/otlp_http.rs, src/service/metrics/prom.rs, src/service/traces/mod.rs
Earlier if a partition key doesn't contains in one row, we will skip generate partition key for this record. then we need always scan it because these data have no partition key.
For example:
- 70 % event with tenant_id 1
- 10 % event with tenant_id 2
- 20 % event no tenant_id
if you search for `tenant_id=2` we already need to scan the `20%` data which there is no `tenant_id` field.
We can always generate partition key if there is no the partition field, we can set the value to `null`.
=> fix: generate partition key with null if the field is not exists

src/config/src/metrics.rs, src/infra/src/db/mysql.rs, src/infra/src/db/postgres.rs, src/infra/src/file_list/mysql.rs, src/infra/src/file_list/postgres.rs, src/infra/src/scheduler/mysql.rs, src/infra/src/scheduler/postgres.rs, src/infra/src/schema/history/mysql.rs, src/infra/src/schema/history/postgres.rs, src/service/file_list.rs
This cherry-picks commits from https://github.com/openobserve/openobserve/pull/4676 , and adds two metrics
- db_query_nums : total number of db queries done, labeled by query type and table
- db_query_time: time taken for db query.
=> feat: add db metrics

src/cli/data/export.rs, src/handler/http/request/search/mod.rs, src/handler/http/request/search/multi_streams.rs, src/handler/http/request/traces/mod.rs, src/infra/src/file_list/postgres.rs, src/service/alerts/mod.rs, src/service/db/enrichment_table.rs, src/service/metrics/prom.rs, src/service/search/cache/mod.rs, src/service/search/mod.rs, src/service/usage/stats.rs
use only on trace_id for all query in query cache
=> feat: use one trace_id for all query in query cache

src/common/utils/redirect_response.rs, src/handler/http/auth/validator.rs, src/handler/http/request/short_url/mod.rs
=> feat: redirect response builder with query params & handle `Result` for AuthExtractor in oo_validator

src/common/meta/alerts/mod.rs, src/config/src/config.rs, src/config/src/meta/usage.rs, src/config/src/utils/rand.rs, src/infra/src/scheduler/mod.rs, src/infra/src/scheduler/mysql.rs, src/infra/src/scheduler/postgres.rs, src/infra/src/scheduler/sqlite.rs, src/job/alert_manager.rs, src/service/alerts/scheduler.rs, src/service/db/scheduler.rs, src/service/ingestion/mod.rs
Whenever alert, report and derived stream retries reaches the maximum retries (`ZO_SCHEDULER_MAX_RETRIES`, default `3`), with this pr, the alert manager will skip to the next run timestamp.
Also, some flexibility added to the ENVs. For example, if the values of `ZO_SCHEDULER_CLEAN_INTERVAL` and `ZO_SCHEDULER_WATCH_INTERVAL` are negative, the background jobs for cleaning up and watching timeout for `scheduled_jobs` table will not run.
`ZO_SCHEDULER_MAX_RETRIES` now accepts both negative and positive values -
- For negative value, the max retries is the absolute value. But when pulling jobs, it will pull jobs matching condition `< max_retries`. If a job reaches max retries, it will never be pulled by the alert manager.
- For positive value (default case), It will pull jobs matching …
=> fix: After maximum alert retries, skip to the next run of the alert

src/infra/src/db/etcd.rs, src/infra/src/db/mysql.rs, src/infra/src/db/nats.rs, src/infra/src/db/postgres.rs, src/infra/src/db/sqlite.rs, src/infra/src/file_list/mysql.rs, src/infra/src/file_list/postgres.rs, src/infra/src/file_list/sqlite.rs, src/infra/src/scheduler/mysql.rs, src/infra/src/scheduler/postgres.rs, src/infra/src/scheduler/sqlite.rs, src/infra/src/schema/history/mysql.rs, src/infra/src/schema/history/postgres.rs, src/infra/src/schema/history/sqlite.rs, src/service/search/mod.rs, src/service/search/sql.rs
This adds traces to db related operations, so we can get a better idea when debugging via traces of how much time db operations are taking. There are no code logic changes, only tracing instrument macros are added. A couple of major diff are just space changes after running `cargo fmt`.
=> fix: add db operation related traces

src/infra/src/db/postgres.rs, src/infra/src/db/sqlite.rs, src/service/search/mod.rs, src/service/search/sql.rs
This removes traces from `match_source` functions, as they create a lot of noise without any useful info.
=> fix: remove trace from match_source

src/service/search/sql.rs
The result of this query is wrong:
```sql
SELECT histogram(_timestamp, '1 second') as x_axis_1, count(_timestamp) as y_axis_1 FROM "test8" GROUP BY x_axis_1 ORDER BY x_axis_1 ASC
```
Because we get order field from `alias` in cache module, but the original field of `x_axis_1` and `y_axis_1` both `_timestamp`, so it will get `x_axis_1` or `x_axis_1` as the final order field.
The solution is follow the old version, when we generate `alias` we use the full name like this:
```
aliases: [
(
"count(_timestamp)",
"y_axis_1",
),
(
"histogram(_timestamp, '1 second')",
"x_axis_1",
),
],
```
=> fix: order by with histogram logic

src/config/src/meta/dashboards/mod.rs, src/handler/http/models/dashboards.rs, src/infra/src/table/dashboards.rs
This PR introduces the optional `page_size` query parameter to the `ListDashboards` endpoint. When set this will limit the size of the result set to the specified value. The client/frontend will be able to set this query parameter in calls to `ListDashboards` to limit the number of results returned - specifically in requests to search dashboards across folders.
This PR only implements limiting the result set size and does not actually expose pagination as functionality of the `ListDashboards` endpoint. My hope however is that this implementation will put us in a good place to easily expose pagination on this endpoint if that's something we want to do in the future - though it would by no means be necessary.
There are a couple of idiosyncrasies here.
1. The `ListDashboards` endpoint does …
=> feat: Limit dashboard search results

src/handler/http/models/alerts/mod.rs, src/handler/http/request/alerts/mod.rs, src/infra/src/table/alerts/mod.rs
#5253 
Miscellaneous cleanup tasks for the new alerts v2 endpoints:
- fixes some of the new route paths
- removes utoipa schema attribute from a Unix timestamp field on the HTTP model
- removes unnecessary call to DB in "delete" operation
=> feat: Alerts API v2 - part 9 - cleanup

src/config/src/meta/search.rs, src/handler/http/request/search/search_job.rs
=> feat: search job return total result

src/service/promql/search/mod.rs, src/service/search/datafusion/distributed_plan/remote_scan.rs, web/src/utils/zincutils.ts, web/src/views/HomeView.vue
This PR shorted the job_id, now it is 7 chars, earlier it is 32 chars. Also fixed the issue UI shows zero if the size less than `0.01` MB.
=> fix: optimize job id for search

src/common/utils/auth.rs, src/common/utils/auth_tests.rs
Fixes #5826 
Also add new tests for cypher keys and action scripts rbac tests
=> fix: rbac for GET for individual folders, destinations, alerts and templates

src/service/search/cache/mod.rs
Result cache cannot be used when from is a value apart form zero, i.e. (100, 200, etc) when a request needs results from in between records present in cache.
=> fix: search api pagination when cache enabled

src/common/infra/ofga.rs, src/common/migration/schema.rs, src/common/utils/auth.rs, src/handler/http/auth/jwt.rs, src/handler/http/auth/token.rs, src/handler/http/auth/validator.rs, src/handler/http/request/authz/fga.rs, src/handler/http/request/pipeline.rs, src/handler/http/request/promql/mod.rs, src/handler/http/request/search/mod.rs, src/handler/http/request/search/multi_streams.rs, src/handler/http/request/search/utils.rs, src/handler/http/request/status/mod.rs, src/handler/http/request/stream/mod.rs, src/handler/http/request/traces/mod.rs, src/handler/http/request/users/mod.rs, src/handler/http/request/users/service_accounts.rs, src/handler/http/request/websocket/utils.rs, src/job/mod.rs, src/service/dashboards/mod.rs, src/service/db/ofga.rs, src/service/metadata/distinct_values.rs, src/service/metadata/trace_list_index.rs, src/service/users.rs
Note: This PR has an [accompanying PR](https://github.com/openobserve/o2-enterprise/pull/331) in the enterprise repo
This splits the `openfga` and `dex` modules into their own crates, `o2_openfga` and `o2_dex`.
**Why?** 
We want to be able to reference the `o2_enterprise::openfga` module from within the `infra::table` module so that we can perform OpenFGA data migrations as part of data transformation migrations in the `openobserve` app. However, the `o2_enterprise` module references the `infra::table` module in various places (eg: inside `o2_enterprise::enterprise::actions::action_manager`). Therefore we cannot reference `o2_enterprise::enterprise::openfga` from `infra::table` without introducing a circular dependency.
The solution presented by this PR is to move the `openfga` module …
=> refactor: Split `openfga` and `dex` modules into their own crates

src/handler/http/router/middlewares/slow_log.rs, src/service/compact/merge.rs, src/service/compact/retention.rs, src/service/stream.rs
This PR fixed the issue that we deleted stream stats when we delete the stream, but we are using sortDelete for file_list, later the file will calculate again, that will cause the stream stats become negative.
=> fix: stream stats with data retention

src/common/utils/websocket.rs, src/handler/http/request/websocket/search.rs
The`Sql::new()` has optimization where it removes all the filters in sql,  when the tantivy index is enable.
By using the sql from the original req, the above scenario can be avoided.
=> fix: ws update histogram interval sql

src/handler/http/request/search/mod.rs
Fixes an issue reported by user where if the field name is a reserved keyword in sql, the values api would error out. By adding quotes around the field, we specifically indicate that it is a field name and not a kw, so it works. Also checked for non-kw names, also works.
fixes #5917
=> fix: add quotes for fixing values api for reserved keywords

src/common/infra/cluster/mod.rs, src/config/src/config.rs, src/infra/src/storage/remote.rs
This pulls some of the search related improvements that I found out from the search perf testing.
- Adds keep alive timeout to object_store crate
- Sets the disk cache buckets based on query thread count
- Changes the hash template string for more uniform hashing
=> perf: search improve

src/common/infra/cluster/mod.rs
When the `test_consistent_hashing` unit test is ran alone it seems to pass consistently. However when it is ran along with `test_consistent_hashing` it seems to fail consistently.
`cargo test` runs tests in parallel by default, and functions under test in both of these unit tests mutate the global mutable `_CONSISTENT_HASH` state variables. I believe, therefore, that when these tests run concurrently they are contending for and mutating this global state concurrently, producing unexpected results.
The quick fix presented here is to 
1. Combine these two tests into one test so that they run sequentially
2. "Reset" the state of the `_CONSISTENT_HASH` global mutable variables after the first stage of the test runs, so that the second stage of the test starts from a clean slate and produces …
=> fix: Force cluster unit tests to run sequentially

web/src/composables/useLogs.ts
When a search request is canceled by the backend, we receive an error response with code 20009 (cancel query). However, in the cancel query API response, is_success is set to false, whereas it should be true since the search request was successfully canceled.
On the frontend, we were interpreting is_success: false as an indication that the search operation was not canceled, causing us to block further pending partitions or histogram/page-count search requests. This was unintentionally preventing new search requests from being initiated.
To resolve this, we should reset the cancel query state when a new request is initiated and when a search request encounters an error.
=> fix: reset cancel query on search error or new search request

src/config/src/config.rs, src/config/src/meta/websocket.rs, src/handler/http/request/websocket/mod.rs, src/handler/http/request/websocket/search.rs, src/handler/http/request/websocket/session.rs, src/handler/http/request/websocket/sort.rs, src/handler/http/request/websocket/utils.rs, web/src/composables/dashboard/usePanelDataLoader.ts
New Env:
```sh
ZO_WEBSOCKET_CLOSE_FRAME_DELAY=10
```
Changes:
memory cache
> - [x] introduced a new `optional` parameter `fallback_order_by_col`
for ws search req `SearchEventReq`
> - For queries where there is no `_timestamp` field and no `order_by`
specified:
```sql
SELECT level, COUNT(*) as count
FROM logs
GROUP BY level
```
> - The default sql behavior is to return the results in a non-ordered
manner.
> - However, with web sockets this behavior impacts the UX in both
`logs` and `dashboards` when `streaming aggregates` is `enabled` as the
results in page/dashboards will keep fluctuating.
> - To fix this there a new sort behavior introduced in web sockets
```rust
/// Represents different sorting strategies
enum SortStrategy {
SqlOrderBy,
FallbackColumn(String, OrderBy), …
```
=> fix: web socket streaming aggregates search for dashboards and logs (#5970)

src/super_cluster_queue/dashboards.rs
Add temporary catch-all logic for dashboard super cluster messages so that we can add a new "put dashboard" message field in [this other PR](https://github.com/openobserve/o2-enterprise/pull/349) without breaking the build.
=> feat: Add temporary catch-all logic for fields on "put dashboard" super cluster messages

src/router/http/ws.rs
Introduced a coordinator channel at `ws_proxy` to handle close frames between the `client_to_backend` and `backend_to_client` task threads.
=> fix: ws close wait

src/router/http/ws.rs
Introduced a coordinator channel at `ws_proxy` to handle close frames between the `client_to_backend` and `backend_to_client` task threads.
=> fix: ws close wait (#6030)

src/service/search/sql.rs
Current behaviour is that we expect the first function in a query to be histogram. If any other function is present (for example `count`) prior to the histogram then the histogram interval is not set. 
We can be more lenient in our parsing and allow other functions to occur before histogram.
This PR fixes the HistogramVisitor to break the chain only when histogram function occurs.
=> fix: histogram visitor

src/common/infra/cluster/mod.rs, src/config/src/config.rs, src/config/src/meta/meta_store.rs, src/infra/src/db/mysql.rs, src/infra/src/db/postgres.rs, src/infra/src/db/sqlite.rs, src/service/search/sql.rs
- Health check shouldn't remove node for etcd only print error message. because etcd didn't keep send events for node heartbeat then the node never online again. we will lost the node permanent.
- Also fixed the issue that we need to pickup fields from UDS when we enabled and UDS and quick_mode.
=> fix: health check shouldn't remove node for etcd

src/service/search/datafusion/exec.rs, src/service/search/datafusion/udf/cast_to_timestamp_udf.rs, src/service/search/datafusion/udf/mod.rs
When we want to query a time before `4 hour`, What will you write the SQL?
```
SELECT * FROM default WHERE _timestamp > NOW() - '4h'
```
This is the best SQL what we want, but sorry, it can't work, at least you need add `INTERVAL` keyword.
```
SELECT * FROM default WHERE _timestamp > NOW() - INTERVAL '4h'
```
Sorry, it still can't work, because `NOW() - INTERVAL '4h'` this is a `Timestamp` type, our `_timestamp` is `int64`. Let's convert to micro_timestamp.
```
SELECT * FROM default WHERE _timestamp > to_unixtime(to_timestamp_micros(NOW() - INTERVAL '4 hour')::TIMESTAMP) * 1000000
```
Yes, you are right, it is pretty long, but this is SQL how it works.
This PR add a new UDF to simple this query, now you can write it like this:
```
SELECT * FROM default WHERE _timestamp > …
```
=> feat: implement cast_to_timestamp

src/config/src/meta/self_reporting/usage.rs, src/config/src/meta/triggers.rs, src/infra/src/scheduler/mysql.rs, src/infra/src/scheduler/postgres.rs, src/job/alert_manager.rs, src/service/alerts/scheduler.rs, src/service/ingestion/mod.rs, tests/integration_test.rs
This PR adds a `source_node` field to the `triggers` stream to indicate which alert manager processed the particular trigger. This is the name of the node.
=> feat: add source_node to triggers stream

src/common/utils/auth_tests.rs, src/service/search/datafusion/udf/regexp_matches_udf.rs
The `re_matches` UDF was returning the entire match instead of just the captured value when using regex capture groups. This led to unwanted prefixes and quotes in the results.
Example:
```sql
SELECT re_matches(text, '"value":"([^"]+)"')
-- Input: {"value":"hello"}
-- Old output: ["value":"hello"] 
-- New output: [hello]           
```
=> fix: re_matches udf

src/config/src/config.rs, src/handler/http/request/status/mod.rs, web/src/components/dashboards/PanelContainer.vue, web/src/components/dashboards/PanelSchemaRenderer.vue, web/src/composables/dashboard/usePanelDataLoader.ts, web/src/utils/dashboard/convertPromQLData.ts, web/src/utils/dashboard/convertSQLData.ts
- #6015 
- Introduced new Env variable `ZO_MAX_DASHBOARD_SERIES`, to limit number of series per panel.
- Comparison against series will not be counted. 
- Additionally, for multiple Y-axes, there will be a limit per individual Y-axis
=> fix: dashboard freeze issue with more than 100 series in single panel

src/service/dashboards/mod.rs
Apart from filtering dashboard list based on `dashboard:{folder_id}/dashboard_id` and `dashboard:_all_{org_id}`, filter with `dashboard:{dashboard_id}` as well.
=> fix: filter dashboard list based on dashboard:{dashboar_id}

src/handler/http/request/websocket/session.rs
- The goal is to not sleep/timeout but also wait a tiny bit before sending close and at the same time not keeping the threads hanging which could lead to resource exhaustion on the querier
1. **Message In-Flight Control**:
```rust
message_in_flight: AtomicBool
```
- Uses atomic boolean for lightweight synchronization
- Ensures only one message is being sent at a time
- Prevents message overlap and potential race conditions
2. **Limited Retry Mechanism**:
```rust
let mut attempts = 0;
while attempts < 3 {
match session.message_in_flight.compare_exchange(...) {
// ...
Err(_) => {
attempts += 1;
if attempts < 3 {
tokio::task::yield_now().await;
}
}
}
}
```
- Maximum 3 retries
- Uses `yield_now()` instead of sleep
- Quick failure path if message can't be sent
3. **Non-Blocking Cleanup Before …
=> fix: add `msg_in_flight` flag and `yield` with retries before closing

src/common/migration/schema.rs, src/config/src/meta/alerts/alert.rs, src/config/src/meta/mod.rs, src/config/src/meta/triggers.rs, src/handler/http/models/alerts/mod.rs, src/handler/http/models/alerts/responses.rs, src/handler/http/request/alerts/deprecated.rs, src/handler/http/request/alerts/mod.rs, src/infra/src/scheduler/mod.rs, src/infra/src/scheduler/mysql.rs, src/infra/src/scheduler/postgres.rs, src/infra/src/scheduler/sqlite.rs, src/infra/src/table/alerts/mod.rs, src/job/alert_manager.rs, src/service/alerts/alert.rs, src/service/alerts/scheduler.rs, src/service/alerts/scheduler/handlers.rs, src/service/alerts/scheduler/mod.rs, src/service/alerts/scheduler/worker.rs, src/service/db/alerts/alert.rs, src/service/db/alerts/realtime_triggers.rs, src/service/db/scheduler.rs, src/super_cluster_queue/scheduler.rs, tests/integration_test.rs
- Moves the `last_satisfied_at` to scheduled_jobs table.
- Uses mpsc channels for scheduler
- We spawn the same number of worker threads as the configured max concurreny env.
- After pulling jobs, it sends to each worker through the mpsc channel
- Each worker processes the received trigger
- After the scheduler interval, the puller job checks how many workers are still available i.e. how many workers are done with processing triggers.
- It only pulls the same number of jobs from db as the number of available workers at that particular time.
The cycle continues.
So, the scheduler pulls at max the "max concurrency" number of jobs at a time depending on the availability of worker threads.
=> feat: Alert manager improve pb (move last_satisfied_at and use mpsc)

src/config/src/meta/alerts/alert.rs, src/handler/http/models/alerts/requests.rs, src/handler/http/models/alerts/responses.rs, src/handler/http/request/alerts/mod.rs, src/infra/src/table/alerts/mod.rs, tests/api-testing/tests/test_alertsnew.py
Makes the following fixes to these routes:
- `ListAlerts`
- adds `enabled` to the response body
- adds `name_substring` to the request body
- `MoveAlerts`
- changes the method type to `PATCH` since this is a non-idempotent update
- changing to `PATCH` coincidentally happens to fix a routing issue where requests to `MoveAlerts` were being routed to the `UpdateAlerts` handler
- `EnableAlert`
- changes the method type to `PATCH` since this is a non-idempotent update
- `TriggerAlert`
- changes the method type to `PATCH` since this is a non-idempotent update
=> fix: Misc V2 alerts routes fixes

src/super_cluster_queue/mod.rs
This uses a new scheduler super cluster queue. Currently, the alert super cluster queue is used for handling scheduler updates. This creates a problem when we want to purge scheduler events (for whatever reason). Currently doing that is not possible without purging even the alert updates that are done by the users.
=> feat: use new scheduler super cluster queue for new scheduler events

src/handler/http/request/websocket/session.rs, src/router/http/ws.rs
Issue: Close frame description field causes frame malformation in Chrome/Brave
- Description field causes inconsistent frame encoding
- Firefox handles it fine, but Chrome/Brave show malformed data
- Workaround: Skip description field in close frames
Actions:
- Set `CloseFrame` description at both `router` & `querier` to `None`
=> fix: ws malformed data

src/handler/http/request/websocket/session.rs, src/router/http/ws.rs
Ref: https://github.com/openobserve/openobserve/issues/5974
Issue: Close frame description field causes frame malformation in
Chrome/Brave
- Description field causes inconsistent frame encoding
- Firefox handles it fine, but Chrome/Brave show malformed data
- Workaround: Skip description field in close frames
Actions:
- Set `CloseFrame` description at both `router` & `querier` to `None`
=> fix: ws malformed data (#6157)

src/config/src/config.rs, src/config/src/meta/alerts/mod.rs, src/config/src/meta/self_reporting/usage.rs, src/service/alerts/alert.rs, src/service/alerts/derived_streams.rs, src/service/alerts/mod.rs, src/service/alerts/scheduler/handlers.rs, src/service/ingestion/mod.rs, src/service/logs/mod.rs, src/service/metrics/json.rs, src/service/metrics/otlp.rs, src/service/metrics/prom.rs, src/service/traces/mod.rs, tests/integration_test.rs, web/src/components/pipeline/NodeForm/Query.vue, web/src/components/pipeline/PipelinesList.vue
=> fix: scheduled pipeline don't pause after retries

Cargo.lock, src/common/infra/cluster/mod.rs, src/common/infra/cluster/scheduler.rs, src/router/http/mod.rs
The router will select node with weight by node status (CPU, MEM, CONNECTIONS) with this PR.
And the total weight is 1, each part has different weight:
- TCP Conns: `0.5`
- CPU Usage:`0.3`
- MEM Usage: `0.2`
And set a const variable `MAX_EXPECTED_CONNECTIONS=2000`
The score formula is:
```
(tcp_conns / 2000 * 0.5) + (cpu_usage / 100 * 0.3) + (mem_usage / mem_total * 0.2)
```
Select the node which has minimal score.
=> feat: improve router scheduler with weight 2/2

.github/workflows/cargo-deny.yml, src/config/src/config.rs, src/job/file_downloader.rs, src/job/mod.rs, src/service/search/datafusion/exec.rs, src/service/search/grpc/storage.rs
This uses background jobs in order to download files asynchronously, and a mpsc queue in order to send file names to the jobs threads. This limits the number of threads we spawn to a fixed number configurable via config var.
=> fix: parallel download

src/service/db/user.rs
Fixes https://github.com/openobserve/openobserve/issues/6171 and https://github.com/openobserve/openobserve/issues/6206.
In the `db::user::get` function we check for root user only if the `org_id` is `Some`. This may lead to bugs in many places, if we don't check for root user first and pass `None` as `org_id` for root user.
=> fix: check for root user even if org_id is provided in db::user::get

.cargo/audit.toml, src/common/migration/dashboards.rs, src/handler/http/request/search/mod.rs, src/job/files/parquet.rs, src/service/dashboards/mod.rs, src/service/metadata/distinct_values.rs, src/service/stream.rs
fixes #6202 
We use field `count` ourselves to mark the number of occurrences for a certain field combination. However if user stream also has a field with same name, and they use it in dashboard variables, then it can cause issues at file merge as schemas might differ. In any case because we use it as a field internally, we should never allow user stream's count field in distinct stream. Thus in this PR we ignore that field at all places, and simply fall back to the normal search in case distinct values of count are requested.
- tested that adding count as dashboard variable does not add it to distinct fields
- tested getting distinct values on count uses normal stream search and not distinct stream
- tested using any other field that is distinct correctly uses distinct stream.
=> fix: ignore count field from user stream for distinct values

web/src/components/alerts/PipelinesDestinationList.vue, web/src/components/common/sidebar/FieldList.vue, web/src/components/functions/EnrichmentTableList.vue, web/src/components/functions/FullViewContainer.vue, web/src/components/functions/FunctionList.vue, web/src/components/pipeline/NodeForm/Query.vue, web/src/components/pipeline/NodeForm/ScheduledPipeline.vue, web/src/components/pipeline/PipelineEditor.vue, web/src/components/pipeline/PipelinesList.vue, web/src/locales/languages/en.json, web/src/plugins/pipelines/CustomNode.vue
1.  validate and close  text instead of save button 
2. when user selects stream name query wipes out if any previous query is there
3.add the click event on whole expand bar 
4. after opening the sidebar clicking on the SQL editor moves the focus away from the SQL editor
5. remove the pipeline view on the row and introduce a eye icon in actions section
6. when user clicks on edit the schema should auto populate respective to the query
=> fix: pipeline query node improvements

src/common/infra/cluster/mod.rs, src/config/src/config.rs, src/job/file_downloader.rs, src/job/mod.rs, src/service/search/grpc/storage.rs
This takes the following changes from main. Not directly cherry picked, as their commits also had some other changes in them.
- ~Change the hash format string we use for file allocation to queriers. This is behind a new config , by default picks the existing one.~ This is already present.
- Change the cache download to background thread. This is not configurable, and is always on.
=> fix: cherry pick perf related changed from main

src/common/infra/cluster/mod.rs, src/common/meta/organization.rs, src/config/src/meta/cluster.rs, src/handler/http/request/organization/org.rs, src/handler/http/router/mod.rs, src/main.rs, src/proto/build.rs, src/proto/proto/cluster/node.proto, src/proto/src/generated/cluster.rs, src/service/grpc.rs, src/service/mod.rs, src/service/node.rs
This PR adds a new endpoint `/{org}/node/list` for `_meta` org, which displays the node info of all the nodes in all clusters. 
- The hierarchy of the response is as follows `regions -> clusters -> nodes`. 
- Filtering is also enabled on the api where region names can be provided as query params as comma separated values
=> feat: report node config over super cluster

Cargo.lock, Cargo.toml, src/infra/src/db/nats.rs, src/infra/src/queue/nats.rs, src/ingester/src/partition.rs
There one edge case, use nats client run `kv.keys()` you can't get all the keys, it will lost or duplicated some keys. 
This PR use our own method replace the `keys()` function to get correct result.
=> fix: NATS list value error for edge case

src/infra/src/storage/local.rs, src/infra/src/storage/remote.rs, src/service/search/grpc/storage.rs
This PR optimized the background download for cache, we don't need download the file which already in cache.
Also update the metrics for object_store.
```
zo_storage_time{org, stream_type, method_type, storage_type}
```
- We can check `zo_storage_time{method_type="get_range"}` to check how much time we spent on range request.
- We can check `zo_storage_time{method_type="get"}` to check how much time we spent on download file.
=> perf: only download the file not in cache

src/config/src/utils/tantivy/tokenizer/mod.rs, src/config/src/utils/tantivy/tokenizer/o2_tokenizer.rs, src/service/compact/merge.rs
This PR fixed the case camelCase tokenizer with base64 data, it will a lot of time, in our case one 3764 events parquet took over `30mins` to do tokenizer.
This PR add a check of base64 data if one token over `1KB` and all of `[0-9a-zA-Z]` we will skip camelCase check and let it be a single token.
With the PR the file earlier need `30mins`, now only need `200ms`.
=> fix: check base64 parts for camelCase tokenizer

src/handler/http/request/dashboards/reports.rs, src/service/dashboards/reports.rs
This PR just does some refactoring of service layer report errors. It is not intended to change the behavior of any endpoints.
Refactoring:
- Replaces `anyhow::Error` in the service layer report logic with `ReportError`, `SendReportError`, and `GenerateReport` error to explicitly model the different types of errors that can occur.
- Introduces logic in the HTTP request handler module to convert from `ReportError`s into HTTP responses.
The new error type and transformation logic introduced in this PR will be used in the new V2 reports endpoints that will be introduced in a followup PR.
=> feat: Use new error types to model service layer errors for reports

.cargo/audit.toml, Cargo.lock, Cargo.toml, src/infra/src/storage/local.rs, src/infra/src/storage/remote.rs, src/service/search/datafusion/table_provider/mod.rs, src/service/search/datafusion/table_provider/parquet_reader.rs
This PR enhance the error message for the case
```
Parquet error: Parquet error: Invalid Parquet file. Corrupt footer
```
We don't know which file caused the problem.
Now it prints like this:
```
Failed to infer stats for file: c72ac03eb2dd4138bde94c2dd232a513-0-dkOVFSi-storage-0/schema=b9de91322c863c9e/$$/files/default/logs/locust1/2025/03/18/03/7307607906797486089.parquet, 
error: Parquet error: Parquet error: Invalid Parquet file. Corrupt footer
```
=> fix: enhance error log for parquet error

src/config/src/meta/search.rs, src/service/search/mod.rs, src/service/search/sql.rs
If the query body have no `limit` but the SQL has a `limit` we will exact it and apply to query limit.
=> feat: exact limit from SQL when the query limit is known

src/service/alerts/mod.rs, src/service/search/grpc_search.rs, src/service/search_jobs.rs
This PR implement use querier node as query leader for AlertManager.
> Only for single stream query(standard search request), there is no gRPC for MultipleStreamQuery request for now.
=> perf: use querier as leader for AlertManager

src/common/utils/auth.rs, src/config/src/meta/self_reporting/usage.rs, src/infra/src/scheduler/mysql.rs, src/infra/src/scheduler/postgres.rs, src/service/alerts/scheduler/handlers.rs, src/service/alerts/scheduler/mod.rs, src/service/alerts/scheduler/worker.rs, src/service/ingestion/mod.rs
- Fixes #6289 
- Also, Removes use of semaphore inside the scheduler. Currently it only uses the mpsc channel and waits if the mpsc channel is full. Apart from this, it uses db locks in postgres and mysql when pulling scheduled_jobs.
=> fix: remove semaphore in alert manager

web/src/components/pipeline/NodeForm/Query.vue, web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
this PR will introduce a validation check that if the query is validating then we need to disable the validate and close button so that user don't click on it multiple times and also changed text from validate and close to validating while the query is validating.
=> fix: pipeline query node validation issue

src/config/src/meta/search.rs, src/handler/http/request/search/multi_streams.rs, src/handler/http/request/websocket/search.rs, src/service/alerts/mod.rs, src/service/search/cache/mod.rs, src/service/search/cluster/http.rs, src/service/search/mod.rs, src/service/search_jobs.rs
The search response should be cached only when it is not a partial error or if it is so, only for range errors we should cache the result. This is a hacky fix which caches the result when the above condition is satisfied.
Partly addresses #6311 (does not fix the root cause where is_partial is false even when there is function error).
=> fix: Partial error fix main

web/src/components/alerts/ScheduledAlert.vue, web/src/components/pipeline/NodeForm/Query.vue, web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
This PR fixes couple of issues 
1. changed the warning message to minimum frequency should be -- minutes when user tries to give less than minimum frequency interval  in alert and pipeline
2. other is made period in sync with frequency so whenever user toggles the cron so in pipelines we are auto selecting the period according the frequency so toggling not picking up the latest values of freq to period
=> fix: alert and pipeline frequency warning message change

src/service/alerts/scheduler/handlers.rs
When a pipeline takes more than the scheduler timeout to complete the task, the scheduler background job `watch_timeout` increases the `retries` field by 1 and again updates the scheduled jobs status back to `waiting` from `processing`. If this happens three times, the `retries` field value go beyond the max retries and hence is never pulled by scheduler again.
With this change, whenever we process a derived stream we first check if the current `retries` field matches with the max retries. If it matches then we simply make the `retries` `0` and again run it after the scheduled frequency. The start_time for the query is not changed though, so there should not be any data loss when quering.
=> fix: when pipeline reaches max retries by watch_timeout, skip to next run

src/config/src/meta/dashboards/mod.rs, src/handler/http/request/dashboards/mod.rs
Currently in the main, when creating a dashboard, we check if the `owner` field is there in the backend. If it is not present, it returns Missing Owner error. This PR fixes this by checking first if the `owner` field is non-empty, otherwise it uses the currently logged in user as `owner`.
=> fix: when dashboard owner not present in creation payload, use currently logged in user

src/common/utils/auth.rs, src/handler/http/request/actions/action.rs, src/handler/http/request/actions/operations.rs, src/handler/http/request/alerts/mod.rs, src/handler/http/request/service_accounts/mod.rs, src/handler/http/request/users/mod.rs, src/service/alerts/alert.rs, src/service/folders.rs, src/service/users.rs
- Fixes 403 error when alert move api is called
- 403 error when trying to create alert in default folder even after having permission
- Fixes # Regular user without `GET` user permission should not be able to get list of all users
=> fix: alert move rbac issues

src/service/alerts/mod.rs, src/service/alerts/scheduler/handlers.rs
- Triggers stream error field blank when status is failed
- Pipeline pauses when watch_timeout job increases retries
=> fix: triggers stream error field should contain message when status is failed

src/service/alerts/alert.rs, web/src/components/alerts/AddTemplate.vue
This pr adds two more variables to alert templates - `alert_trigger_time_millis` (the alert trigger occurance time in epoch milliseconds) and `alert_trigger_time_seconds` (the alert trigger occurance time in epoch seconds). Note that the `alert_trigger_time` is alert trigger occurance time in UTC epoch microseconds.
=> feat: add variables for trigger time in seconds, millis for alert template

src/service/alerts/alert.rs
This fix allows users to define any valid json in the alert template. Alert module will take care of converting the msg to action request. They need not adhere to a format.
=> fix: Action as a destination input format

web/src/components/alerts/AlertList.vue
1. This PR fixes that alert enable is not updated in the UI when filter is applied 
2. This PR also fixes the alert enable disable in search across folders
3. This PR also removes the id from exported alert
=> fix: alert enable or disable is not updated in the UI when filter applied

src/infra/src/scheduler/mysql.rs, src/infra/src/scheduler/postgres.rs, src/infra/src/scheduler/sqlite.rs, src/job/alert_manager.rs, src/service/alerts/derived_streams.rs, src/service/pipeline/mod.rs
The `clean_complete` scheduler job is not really required as in the handler job we can check if the job has exceeded max retries, if it does exceed, we will skip to the next scheduled trigger.
=> fix: remove clean_complete job in scheduler

src/router/http/mod.rs
when dynamic part of the path contains querier routes
fix #6413
=> fix: router incorrectly route routes to querier

src/common/infra/cluster/mod.rs, src/router/http/mod.rs, src/service/grpc.rs
The ingester will still can be search when it set to unscheduled
=> fix: let the scheduled only work for ingestion

src/config/src/config.rs, src/handler/http/request/ws_v2/mod.rs, src/router/http/ws_v2/error.rs, src/router/http/ws_v2/handler.rs, src/router/http/ws_v2/session.rs, web/src/composables/dashboard/usePanelDataLoader.ts, web/src/composables/useLogs.ts, web/src/composables/useSearchWebSocket.ts, web/src/composables/useWebSocket.ts
=> fix: ws session drain

src/cli/basic/cli.rs, src/common/meta/user.rs, src/common/utils/auth.rs, src/common/utils/auth_tests.rs, src/config/src/config.rs, src/handler/http/auth/validator.rs, src/handler/http/request/service_accounts/mod.rs, src/job/mod.rs, src/service/organization.rs, src/service/users.rs
Now we can use environment to set ingestion token for root user.
```
ZO_ROOT_USER_TOKEN=""
```
Default is empty will auto generate.
=> feat: add new ENV to set token for root user

src/handler/http/request/search/error_utils.rs, src/handler/http/router/mod.rs
Whenever there is a search error, we put a custom header to use the error message creating the audit message for that event. Also, the custom header is removed while sending the response back to user.
=> fix: add http api search error in the audit stream

web/src/components/alerts/AlertList.vue, web/src/components/alerts/ImportAlert.vue
1. This PR makes sure that cloned alert and imported alert owners should be logged in users only
=> fix: alerts owner should be logged in user

src/config/src/meta/triggers.rs, src/handler/http/request/enrichment_table/mod.rs, src/service/alerts/scheduler/handlers.rs, src/service/db/enrichment_table.rs, src/service/db/schema.rs, src/service/enrichment_table/mod.rs
When append_data is false (`?append=false`), and user uploads a enrichment file with only headers, we replace the whole enrichment table with a single json record with the headers as keys and empty string as values. When `append=true` we do nothing.
Also, while uploading an enrichment table, it estimates the probable json size and checks if that exceeds the total enrichment table size limit (`ZO_ENRICHMENT_TABLE_LIMIT`) in MB. This pr introduces another key-value pair in meta table to store the current size of an enrichment table so that while uploading we can keep a track how much of enrichment table size is available. This is because, we can't rely on the stream_stats table which is not realtime and takes some time to update.
It also fixes one bug where if the pipeline name contains …
=> fix: when uploading enrichment table with column name only, do not delete the enrichment table

src/service/search/grpc/wal.rs
Input multiple target partition and output one partition get data lossing.
=> fix: search in memtable

src/config/src/config.rs, src/service/search/super_cluster/leader.rs
Reduce the default value of `ZO_FILE_DOWNLOAD_THREAD_NUM` from `cpu_num * 4` to `cpu_num / 2`, it took too many CPU for downloading.
=> perf: reduce default download thread num

web/src/plugins/logs/SearchSchedulersList.vue
1. This PR fixes the issue that for search jobs stream type should be taken from the response not static stream type
=> fix: dynamic stream name should be taken for search job

src/common/infra/cluster/mod.rs, src/common/infra/config.rs, src/handler/http/request/ws_v2/session.rs, src/router/http/ws_v2/connection.rs, src/router/http/ws_v2/handler.rs, src/router/http/ws_v2/pool.rs, src/router/http/ws_v2/session.rs, src/service/websocket_events/search.rs, src/service/websocket_events/utils.rs
=> fix: read and write locks

web/src/components/alerts/AddAlert.vue, web/src/components/alerts/AlertList.vue, web/src/composables/useLogs.ts
1. this PR fixes the issue that is related to when user tries to run distinct query when histogram is on 
eg:
`SELECT DISTINCT body FROM "default"`
currently it will show total events as if 50 records per page it will show 
1 to 50 out of 50 events
=> fix: show total events in distinct query when histogram is on

web/src/components/alerts/AlertList.vue, web/src/components/common/sidebar/FolderList.vue, web/src/plugins/logs/Index.vue, web/src/plugins/logs/JsonPreview.vue, web/src/plugins/logs/SearchResult.vue
this PR fixes
1. histogram loader should while both search and histogram request as well as no data found should only show when there is no actual data not at the time of loading
2. in the detail table when we add a field to the table it again shows add a field to the table instead should show remove from the table
3. when user try to add fields using quick mode with sql mode off there is one console error
=> fix: logs page issues

Cargo.lock, src/common/utils/auth_tests.rs, src/config/src/config.rs, src/config/src/metrics.rs, src/handler/grpc/request/event.rs, src/infra/src/cache/file_data/delete.rs, src/infra/src/cache/file_data/disk.rs, src/infra/src/cache/file_data/memory.rs, src/infra/src/cache/file_data/mod.rs, src/service/compact/merge.rs, src/service/db/file_list/mod.rs, src/service/promql/search/mod.rs, src/service/search/cluster/flight.rs, src/service/search/cluster/http.rs
- `query_parquet_cache_requests`: how many query requests
- `query_parquet_cache_ratio`: total parquet files cached ratio
For each request on each node, the `requests` will +1, the `ratio` will +%, for example, need query 100 files, cached 71 files on local, `ratio` will +71 (71/100).
Also updated query cache metrics for metrics
- `query_metrics_cache_requests`: how many PromQL metrics query requests
- `query_metrics_cache_ratio`: total metrics result cache ratio for PromQL
For each PromQL request(leader), the `requests` will +1, the `ratio` will +%, for example, query for 1 hour, step is 1min, cached 50 mins, only need query for last 10 mins, `ratio` will +83 (50/60).
deprecated
```
ZO_MEMORY_CACHE_CACHE_LATEST_FILES
```
Start using 4 new env:
```
ZO_CACHE_LATEST_FILES_ENABLED=false …
```
=> feat: add query parquet cache metrics

src/common/utils/auth_tests.rs, src/config/src/config.rs, src/service/search/mod.rs, src/service/search/partition.rs
This PR introduces "mini partitions" to improve user experience for search queries by providing faster initial results, especially for large time range queries.
- Created partitions of roughly equal size based on time range and data volume
- Optimized for balanced workload distribution across processing nodes
- Users had to wait until a full partition was processed before seeing any results
- For large time ranges (e.g., 7 days), the first result could take long time to appear
- Creates small "mini partitions" at the beginning of the time range
- Followed by regular-sized partitions for the remaining time range
- Preserves all the original constraints and optimizations for regular partitions
- Users see initial results within seconds, even for large time range queries
```sh …
```
=> feat: add mini search partitions

web/src/components/alerts/AddAlert.vue, web/src/components/pipeline/NodeForm/Query.vue, web/src/composables/useLogs.ts
encoding of sql to base64 from UI when specified only in logs page not in alerts or pipelines page
=> fix: base64 encode should be only in logs page

Cargo.lock, Cargo.toml, src/config/Cargo.toml, src/config/src/meta/alerts/mod.rs, src/service/alerts/scheduler/handlers.rs
This pr aligns the next_run_at of the alerts/pipelines according to the timezone of the given alert/pipeline. For example, if the current time is 11:03pm, and the frequency is 5 mins, the next run at should be 11:05pm, then 11:10pm, and so on. In future, we may want to make aligntime an optional feature, by giving a toggle option in the alert/pipeline itself.
=> feat: implement `aligntime` for alert manager alerts/pipelines

src/service/alerts/alert.rs, src/service/alerts/derived_streams.rs, src/service/alerts/mod.rs, src/service/alerts/scheduler/handlers.rs, src/service/logs/mod.rs, src/service/metrics/json.rs, src/service/metrics/otlp.rs, src/service/metrics/prom.rs, src/service/traces/mod.rs
In this pr, the Alert Manager passes the trace id to query requests.
=> fix: pass trace id from alert manager to queries

src/service/search/cache/mod.rs, src/service/websocket_events/search.rs
=> fix: any responses with function error will not be result cached

src/config/src/utils/sql.rs, src/service/alerts/derived_streams.rs
API layer enforcement: scheduled pipeline queries must generate a `_timestamp` filed in the result, use alias for functions.
recommended:
```sql
SELECT MAX(_timestamp) AS _timestamp, ... FROM ...
```
***This rule is not applied to any existing scheduled pipelines**
=> feat: enforce mandatory _timestamp field selection in scheduled pipeline

.github/workflows/release.yml, deploy/build/Dockerfile.tag-simd.amd64, src/config/src/meta/search.rs, src/config/src/metrics.rs, src/handler/grpc/request/event.rs, src/handler/grpc/request/search/mod.rs, src/handler/http/request/search/around.rs, src/handler/http/request/search/mod.rs, src/handler/http/request/search/multi_streams.rs, src/handler/http/request/traces/mod.rs, src/handler/http/router/openapi.rs, src/proto/proto/cluster/common.proto, src/proto/src/generated/cluster.rs, src/service/promql/search/mod.rs, src/service/search/cache/mod.rs, src/service/search/cluster/flight.rs, src/service/search/cluster/http.rs, src/service/search/mod.rs, src/service/search/super_cluster/follower.rs, src/service/search/super_cluster/leader.rs, src/service/search_jobs.rs
We already checked `ConsistentHash` on the source node, so we don't need check again, just cache the file send to the node.
=> fix: cache file for alert querier

src/config/src/config.rs, src/handler/http/request/organization/org.rs, src/infra/src/storage/mod.rs, src/job/file_downloader.rs, src/service/cluster_info.rs, src/service/grpc.rs, src/service/ingestion/ingestion_service.rs, src/service/node.rs, src/service/promql/search/mod.rs, src/service/search/cluster/cache_multi.rs, src/service/search/cluster/cacher.rs, src/service/search/grpc/storage.rs, src/service/search/grpc_search.rs, src/service/search/mod.rs, src/service/search_jobs.rs
```
ZO_S3_FEATURE_BULK_DELETE=false
```
If your object_store support `stream delete` you can enable it, as we know `AWS S3` and `Azure ObjectStore` support it.
=> feat: support stream delete for object store

src/config/src/meta/alerts/mod.rs, src/config/src/meta/self_reporting/usage.rs, src/service/alerts/scheduler/handlers.rs, src/service/ingestion/mod.rs
Adds aligntime feature for alerts periods. If the frequency and period is 5 mins, current time is 11:53pm, it will use the period of 11:45pm to 11:50pm to evaluate the alert. The next time it will be triggered at at 11:55pm, and data evaluation timerange will be 11:50pm to 11:55pm
=> fix: align time for alerts

src/service/alerts/mod.rs, src/service/alerts/scheduler/handlers.rs, src/service/websocket_events/search.rs, src/service/websocket_events/values.rs
fixes: https://github.com/openobserve/openobserve/issues/6610
=> fix: if `streaming_aggs` allow entire query to be processed

web/src/components/settings/Nodes.vue
1. This PR fixes the issue that sometimes BE may return id's in non sorting manner which is used in FE so now we are making the indexing in the FE so that it will always be in sorted manner 
2.it was handled in both normal cluster and super cluster as well
=> fix: indexing for the nodelist UI should be done in FE

src/handler/http/request/search/mod.rs, src/handler/http/request/ws/session.rs, src/router/http/ws/connection.rs, src/service/websocket_events/search.rs, src/service/websocket_events/values.rs, web/src/composables/useLogs.ts, web/src/composables/useSearchWebSocket.ts, web/src/plugins/logs/IndexList.vue
=> fix: ui `should_client_retry` & `values` event to search cancel

src/handler/http/request/ws/session.rs, src/router/http/ws/connection.rs, src/service/websocket_events/search.rs, src/service/websocket_events/values.rs, web/src/composables/useLogs.ts, web/src/composables/useSearchWebSocket.ts, web/src/plugins/logs/IndexList.vue
`should_client_retry` is `true`, and is in loop.
cancelled
=> fix: cherry-pick rc7 fixes

src/service/search/grpc/wal.rs, src/service/search/sql.rs
We generate schema for query only pickup the field which we used, but for the query
```sql
select count(*) from table
```
there is no field found as a backoff we give the original schema.
It will be very slow if the original schema have thousands fields.
=> fix: select star in wal maybe very slow for thousands fields

src/service/alerts/alert.rs, src/service/alerts/scheduler/handlers.rs, src/service/stream.rs
- When in the alert, frequency is changed from cron to minutes, we don't delete the old cron expression. This pr fixes that.
- Fixes false reporting of skipped alert events
=> fix: remove cron if frequency changed to minutes

src/service/alerts/alert.rs, src/service/alerts/scheduler/handlers.rs, src/service/stream.rs
- When in the alert, frequency is changed from cron to minutes, we don't delete the old cron expression. This pr fixes that.
- Fixes false reporting of skipped alert events
- Enrichment table doc_time_min and doc_time_max should use meta table stats not stream stats in the enrichment table list api.
=> fix: remove cron if frequency changed to minutes (#6676)

src/infra/src/file_list/mysql.rs, src/infra/src/file_list/postgres.rs
Recently a label was added to one of our metrics in main. In file dump PR I had added couple of new DB functions which uses this metric, however when testing the label changes were not merged in main yet. Thus, I did not catch that the additional label needed to be added, and now it panics because of incorrect labels. Fix is simple, add an empty string for the missing label. No other change. Tested it on usertest for ~12 hours, didn't see any issues.
=> fix: missing prom labels

src/service/search/mod.rs
We recently started using grpc search for alerts inside alert manager. Now, the grpc search uses `cache::search` (and `service::search` when no data in cache). `service::search` already reports usage for alert search event, and also the same is done by `cache::search` as well. Hence, there are duplicate search usage reporting for alerts. In this pr, only the `cache::search` reports usage in case of alerts.
=> fix: duplicate usage reporting for alerts

src/handler/http/request/ws/mod.rs, src/handler/http/request/ws/session.rs, src/router/http/ws/connection.rs, src/router/http/ws/error.rs, src/router/http/ws/handler.rs, src/service/db/short_url.rs, src/service/websocket_events/search.rs, src/service/websocket_events/utils.rs, src/service/websocket_events/values.rs, web/src/composables/useWebSocket.ts
=> fix: ws `tokio::select`, `health_check` & `router_id` for router-querier conn

src/service/ingestion/mod.rs, src/service/logs/otlp.rs, src/service/traces/mod.rs
fixed #6684
There are two panic:
```
for item in service_name_value.as_object().unwrap().values().cloned() 
```
The service_name is not an object, panicked.
```
local_val[ORIGINAL_DATA_COL_NAME] = original_data.clone().unwrap().into();
```
the local_val can't index by the name, panicked.
=> fix: otlp logs ingestion

src/handler/grpc/flight/mod.rs, src/handler/grpc/request/search/mod.rs, src/handler/http/request/ws/session.rs, src/service/alerts/mod.rs, src/service/mod.rs, src/service/websocket_events/search.rs, src/service/websocket_events/utils.rs, src/service/websocket_events/values.rs
Currently, the scheduler trace_ids are not searchable in the traces page, because they are only used in the logs and not in the instrumentation. This pr fixes that - so, the scheduler query trace id (which can be obtained from the `triggers` stream, field name - `scheduler_trace_id`, the trace_id after the `/` is the scheduler query trace_id), can be used as `trace_id` to search the trace in the traces page.
Also, the `grpc::search` and `grpc::search_multi` does not use the trace_id from the grpc "request" for instrumentation. This pr fixes that as well.
=> fix: scheduler query trace_id should be searchable in traces page

src/infra/src/lib.rs
In PR for separating ddl client from normal db client, a new function was created which would do all db initialization. Consequently, fn call to create the local db dir was also moved into that function. However, this function is called only if version key in db is mismatch, so if the version in db matches, this function would not be called, and thus db dir creation will aalso not happen.
This works on stateful set, because most of the time db dir will already be present. However, for non-stateful sets such as router or compactor, this errors because of missing db dir. 
This PR fixes this by always calling create_dir_all in infra::init. They way things are setup, this will get called twice if f db_init also runs, but that is ok. Tested the commit on dev3/dev4 for ~2 hours, container init …
=> fix: always create db dir in infra::init

src/config/src/config.rs
Recently the `align_time` column was added to `alerts` table, but the `config::DB_SCHEMA_VERSION` version now needs to be upgraded so that the migration can be run.
=> fix: update `config::DB_SCHEMA_VERSION` for alert table align time column

src/handler/grpc/request/search/mod.rs, src/service/search_jobs.rs, src/super_cluster_queue/action_scripts.rs
Always use first (default) object store account for search_job & actions.
=> fix: multiple object store for search_job & actions

src/job/file_downloader.rs, src/service/compact/merge.rs
Removed the update_compress_size because we found after 3 times we still can download partial parquets.
=> fix: remove update compress size to db

src/service/db/enrichment_table.rs, src/service/enrichment_table/mod.rs
For an existing old enrichment table, if the `enrichment_table_meta_stream_stats` key record is not present in the `meta` table  and also there is no record for the enrichment table in the stream_stats table, the `enrichment_table::get` function returns error with `invalid timerange` because, it now uses default value `0`.
=> fix: enrichment_table::get returns error when both meta and stream_stats table is empty

src/infra/src/storage/remote.rs
If the file not found S3 will check `ListBucket` permission, it is tricky, but it works like that. 
This PR will skip that error, that is not a real problem. we should skip that.
=> fix: s3 ListBucket error

src/common/utils/stream.rs, src/handler/http/request/status/mod.rs, src/service/stream.rs, web/src/composables/useLogs.ts, web/src/plugins/traces/Index.vue
Returns `ZO_DEFAULT_MAX_QUERY_RANGE_DAYS` in the `/config` api so that UI can restrict the maximum query range by default based on the env value given.
=> fix: ZO_DEFAULT_MAX_QUERY_RANGE_DAYS env should be returned by streams list api (#6762)

src/handler/http/request/search/error_utils.rs, src/handler/http/request/search/mod.rs, src/handler/http/request/search/multi_streams.rs, src/handler/http/request/search/search_inspector.rs, src/handler/http/request/search/search_job.rs, src/handler/http/request/short_url/mod.rs, src/handler/http/request/traces/mod.rs, src/handler/http/request/ws/session.rs, src/infra/src/errors/mod.rs, src/service/enrichment_table/mod.rs, src/service/functions.rs, src/service/logs/syslog.rs, src/service/metrics/otlp.rs, src/service/stream.rs, src/service/traces/mod.rs, src/service/websocket_events/utils.rs
This adds the error header to all cases of internal server error so they show up properly in audit. This is done by one of two approaches -
1. preferably using the `map_error_to_http_response` function , so that everything goes via the same function
2. directly adding the header where the above function cannot be used because is is not an error per say like trying to ingest at non-ingester.
=> fix: internal error audit

src/handler/http/request/search/error_utils.rs, src/handler/http/request/search/mod.rs, src/handler/http/request/search/multi_streams.rs, src/handler/http/request/search/search_inspector.rs, src/handler/http/request/search/search_job.rs, src/handler/http/request/short_url/mod.rs, src/handler/http/request/traces/mod.rs, src/handler/http/request/ws/session.rs, src/infra/src/errors/mod.rs, src/service/enrichment_table/mod.rs, src/service/functions.rs, src/service/logs/syslog.rs, src/service/metrics/otlp.rs, src/service/stream.rs, src/service/traces/mod.rs, src/service/websocket_events/utils.rs
This adds the error header to all cases of internal server error so they show up properly in audit. This is done by one of two approaches -
1. preferably using the `map_error_to_http_response` function , so that everything goes via the same function
2. directly adding the header where the above function cannot be used because is is not an error per say like trying to ingest at non-ingester.
cherry pick of https://github.com/openobserve/openobserve/pull/6768
=> fix: internal error audit (#6768)

web/src/components/QueryEditor.vue, web/src/components/dashboards/QueryEditor.vue, web/src/composables/useLogs.ts, web/src/locales/languages/en.json, web/src/plugins/logs/Index.vue, web/src/plugins/logs/IndexList.vue, web/src/plugins/logs/SearchBar.vue, web/src/plugins/logs/SearchResult.vue, web/src/utils/common.ts
#6771 
1. When we get streaming aggs response, streaming_output key was getting added to page-count api payload, causing the api to fail.
2. Histogram loader is not visible when loading histogram is in progress.
3. Remove histogram refresh in live mode
4. Get `undefined` when histogram query is cancelled
5. query editor undo redo functionality even after user looses focus and focus again
6. Cmd enter fix on logs page
=> fix: fixed page-count api for streaming aggs query

src/handler/http/request/search/mod.rs
Change the query type to do a dummy aggregation for no count query
=> fix: Values API get partitions for no count

web/src/composables/useLogs.ts
consider only actual per page records size while searching schedule job because when it is histogram the size is -1 then it becomes -1 per page records , so we can consider actual per page records.
=> fix: consider actual records size per page for search job

web/src/components/pipeline/PipelinesList.vue
if cron is enabled for scheduled pipeline then it should it be shown in the listing page 
and it should show cron column as true 
This PR fixes #6809
=> fix: pipeline list show cron expression if enabled

src/config/src/config.rs, src/config/src/metrics.rs, src/job/file_downloader.rs, src/job/mod.rs, src/service/promql/search/grpc/storage.rs, src/service/search/grpc/storage.rs
Closes: https://github.com/openobserve/openobserve/issues/6786
New Env: 
```
ZO_FILE_DOWNLOAD_ENABLE_PRIORITY_QUEUE # default true
ZO_FILE_DOWNLOAD_PRIORITY_QUEUE_THREAD_NUM # default 0
ZO_FILE_DOWNLOAD_PRIORITY_QUEUE_WINDOW_SECS # default 3600
```
New Metrics:
```
zo_query_disk_cache_hit_count
zo_query_disk_cache_miss_count
zo_file_downloader_normal_queue_size
zo_file_downloader_priority_queue_size
```
Todo:
=> feat: download manager improvements

src/infra/src/cache/file_data/mod.rs
- get file size from db and download file from blob
- if mismatch in size between db and file downloaded then
- get content length of file from blob
- if content length != file downloaded -> we had a partial download from blob -> retry download with exponential backoff
- if content length == file downloaded -> check footer of downloaded file to see if parquet in blob is actually corrupt
- if file is corrupt -> log as info and mark deleted in db
- if file is good -> update size in db
=> fix: validate downlaod size with blob store and validate file

src/config/src/meta/triggers.rs, src/service/alerts/scheduler/handlers.rs, src/service/db/enrichment_table.rs, src/service/enrichment_table/mod.rs, src/super_cluster_queue/meta.rs
- when creating an enrichment table, the `notify_update` is called before the enrichment table stats is stored in the meta table.
- When pipeline reaches max retries and gets triggered again in the next run, it uses one single time window for the whole delayed timerange.
=> fix: Update enrichment table cache with correct start time after meta table update and pipeline delayed timerange fix

src/config/src/utils/sql.rs, src/handler/grpc/request/search/mod.rs, src/handler/http/request/search/mod.rs, src/service/search/mod.rs, src/service/search/search_stream.rs, src/service/websocket_events/search.rs
- if sql has `distinct` with no `group by` and req is http api -> disable partitions
=> fix: simple distinct sql for http api

src/infra/src/cache/file_data/mod.rs
Previously we did a footer check even when after all retries the blob download was partial. Now we skip and return error, as no sense in checking footer when we know the blob size is incomplete.
=> fix: skip download if partial downalod after all retries

src/config/src/config.rs, src/service/search/mod.rs
closes: https://github.com/openobserve/openobserve/issues/6863
New Env
```
ZO_USE_STREAM_SETTINGS_FOR_PARTITIONS_ENABLED # default false
```
=> feat: add env to enable use_stream_setting for partitions

src/common/utils/auth.rs, src/config/src/config.rs, src/config/src/utils/sql.rs, src/handler/grpc/request/search/mod.rs, src/handler/http/request/search/mod.rs, src/service/search/mod.rs, src/service/search/search_stream.rs, src/service/websocket_events/search.rs
- fix: auth for _values_stream (#6849)
- fix: simple distinct sql for http api (#6836)
- feat: add env to enable use_stream_setting for partitions (#6866)
- https://github.com/openobserve/openobserve/issues/6863
New Env
```
ZO_USE_STREAM_SETTINGS_FOR_PARTITIONS_ENABLED # default false
```
=> fix: chery-pick fixes 

src/migration/mod.rs
Issue was that we use a lock function to lock sqlite client  when doing write ops, because only one thread should do them at a time. However, the client init also requires a lock. When running ent version, ent init had a function which would lock as well as be the first one to access the client, hence deadlock on the client lock. 
This issue was not there when running for the first time, because in migration function we init clients without the locks. However when running second time, the migration returns early, and does not int clients hence the ent function deadlocks, and subsequently locks everything that need the db access. 
The fix is simple, in migration function move the client init before return, so that we always have an initialized client and do not get deadlocked in ent or non …
=> fix: ent deadlock with sqlite

src/service/search/mod.rs
Handle the case when stream stats end time is set to unix epoch
=> fix: Partition stream stats handle case when end time is 0

src/common/infra/cluster/nats.rs, src/common/infra/config.rs, src/infra/src/db/nats.rs, src/infra/src/queue/nats.rs
Refreshing in-memory cache in such NATs event trigger by NATs client's callback closure.
---------
=> fix: cache miss after NATs restarts (#6726)

src/job/mod.rs
There is one issue the `tantivy::TIMESTAMP_UPDATED_AT` never create before call search, but maybe we already created a lot of index files. 
So we need to init this time when the app start.
=> fix: tantivy timestamp update time

web/src/components/dashboards/PanelSchemaRenderer.vue, web/src/components/dashboards/addPanel/DrilldownPopUp.vue, web/src/components/dashboards/addPanel/DrilldownUserGuide.vue
- `series.__axisValue` variable support to pass axis value for drilldown.
=> feat: axis value support for drilldown

web/src/components/dashboards/PanelSchemaRenderer.vue, web/src/components/dashboards/addPanel/DrilldownPopUp.vue, web/src/components/dashboards/addPanel/DrilldownUserGuide.vue
- `series.__axisValue` variable support to pass axis value for drilldown.
=> feat: additional drilldown variable support to pass axis value

src/config/src/config.rs
Since the organization revamp is merged, all the migrations for organization revamp needs to run. So, the `DB_SCHEMA_VERSION` needs to be upgraded.
=> fix: update `DB_SCHEMA_VERSION`

src/cli/basic/cli.rs, src/handler/grpc/request/stream.rs
The issue is when we get cluster list we didn't filter the alert querier cluster then the stats duplicated. The fix in o2 enterprise. this pr only update some logs.
=> fix: stream stats for super cluster

src/infra/src/file_list/sqlite.rs, src/service/file_list.rs
demotes the log level to debug for when local cache insert fails. This can happen when multiple queries on same stream for same range are fired, and after getting file meta from pg, all of them try to insert in local cache, and after one of them succeeds others will fail with sqlite error of unique constraint violation. This will simply log it on debug level instead of error, because even if insert fails in local cache, not a big problem.
=> fix: demote log level to debug when local cache insert fails

web/src/utils/query/sqlUtils.ts
- `NOT IN`, `Starts With` and `Ends With` filters support for visualization.
=> fix: `NOT IN` filter parsing issue for visualization

web/src/utils/query/sqlUtils.ts
- Parser fails to parse Data fusion functions which throws error.
- Pass original user written query if not able to parse.
=> fix: return original query if not able to parse via parser

src/config/src/config.rs, src/service/compact/stats.rs
This PR fixed the issue when compactor not working for a long time, it will have millions files need to be update stream stats. it will take a long time or time out.
=> perf: optimize stream stats calculate with limit

src/service/search/datafusion/optimizer/add_sort_and_limit.rs, src/service/search/datafusion/optimizer/limit_join_right_side.rs, src/service/search/datafusion/optimizer/utils.rs, src/service/search/datafusion/plan/deduplication_exec.rs
fix the below query
```sql
with abc as (select histogram(_timestamp, '1 minute') AS zo_sql_key, count(*) AS zo_sql_num from default GROUP BY zo_sql_key ORDER BY zo_sql_key), edf as (select histogram(_timestamp, '1 minute') AS zo_sql_key, sum(_timestamp) AS zo_sql_num from default GROUP BY zo_sql_key ORDER BY zo_sql_key) select abc.zo_sql_key from abc where zo_sql_key in (select zo_sql_key from edf)
```
=> fix: a corner case for join match one

src/common/utils/auth.rs
For rbac for _around api, the method needs to be converted into `GET` method instead of `POST`.
=> fix: _around api rbac returns 403 error

src/infra/src/table/migration/m20241227_000400_populate_users_table.rs
`member` role should also be deserialized to the `admin` role.
=> fix: deserialize from `member` to `admin`

web/src/plugins/logs/SearchBar.vue
Parsed SQL query object was getting saved with saved-view payload.
When we have very long search query, size of parsedSQL increases which causes error while saving in BE
=> fix: saved views for long queries

web/src/composables/useStreamingSearch.ts, web/src/workers/streamWorker.js
1. TransferableStream: Safari has limited support for transferring ReadableStreams to workers.
2. TextDecoder : Safari has incomplete support for decoder.decode() in workers
Moved ReadableStreams and TextDecoder logic to streaming composable
=> fix: http2 streaming in Safari browser

web/src/composables/useLogs.ts
http - Fixed partition logic for multiple partitions in single page. Example partition: [14, 144]
http - Fixed partition logic for partition with 0 events. Example partition: [14, 0, 144]
http - Last page was not visible for specific partitions. Example partition: [14, 144]
http - + was shown for the last page total-count
http2 streaming - Incremental ( size + 1 ) was not working with multiple partitions
=> fix: http partition pagination for less number of partition counts

web/src/composables/useLogs.ts
#7161 
Modified pagination logic to continue partitions when hits exceed rowsPerPage limit
Changed pagination logic for streaming-output partitions
=> fix: Modified pagination logic to continue partitions when hits exceed rowsPerPage limit

src/config/src/config.rs, src/infra/src/errors/mod.rs, src/ingester/src/errors.rs, src/ingester/src/lib.rs, src/ingester/src/writer.rs, src/service/ingestion/mod.rs, src/service/logs/bulk.rs, src/service/logs/ingest.rs, src/service/logs/otlp_grpc.rs, src/service/logs/otlp_http.rs, src/service/logs/syslog.rs, src/service/metrics/json.rs, src/service/metrics/otlp.rs, src/service/metrics/prom.rs, src/service/search/grpc/mod.rs, src/service/search/grpc/storage.rs, src/service/search/grpc/wal.rs, src/service/search/search_stream.rs, src/service/traces/mod.rs
This PR add circuit breaker for ingester to protect OOM.  To enable this feature we need to config:
```
ZO_CIRCUIT_BREAKER_ENABLE=true
ZO_CIRCUIT_BREAKER_RATIO=90
```
If the system memory usage over `90%` , we will return `503` with error `MemoryCircuitBreakerError`.
Default is `false`, disabled.
=> fix: add memory circuit breaker for ingester

src/handler/http/request/search/search_stream.rs
This reverts commit c9c96489534e219c1cc22a117ea3eb52487b491e.
=> fix: Revert "fix: histogram interval for http2 streaming (#7329)"

src/common/infra/ofga/mod.rs, src/common/utils/auth.rs
Since, AI agent api is now RBAC controlled, this pr adds the migration needed for ai openfga queries.
=> fix: openfga migration for ai

web/src/components/O2AIChat.vue, web/src/components/functions/AddFunction.vue, web/src/components/functions/FunctionList.vue, web/src/components/functions/TestFunction.vue, web/src/components/pipeline/NodeForm/ScheduledPipeline.vue, web/src/layouts/MainLayout.vue, web/src/plugins/logs/DetailTable.vue, web/src/plugins/logs/Index.vue, web/src/plugins/logs/JsonPreview.vue, web/src/plugins/logs/SearchResult.vue, web/src/plugins/logs/TenstackTable.vue, web/src/plugins/logs/data-table/CellActions.vue, web/src/views/Functions.vue
1. This adds additional info  to the o2 ai chat
Add short cut at row to send the event to O2-ai
On inline expand of log row , add short cut at row to send the event to O2-ai
On Side panel with details of logs line , add short cut at row to send the event to O2-ai
On pipelines page send selected stream context
On functions creation page send the event to O2-ai
=> fix: O2 ai add info

web/src/components/O2AIChat.vue, web/src/components/functions/AddFunction.vue, web/src/components/functions/FunctionList.vue, web/src/components/functions/TestFunction.vue, web/src/components/pipeline/NodeForm/ScheduledPipeline.vue, web/src/layouts/MainLayout.vue, web/src/plugins/logs/DetailTable.vue, web/src/plugins/logs/Index.vue, web/src/plugins/logs/JsonPreview.vue, web/src/plugins/logs/SearchResult.vue, web/src/plugins/logs/TenstackTable.vue, web/src/plugins/logs/data-table/CellActions.vue, web/src/views/Functions.vue
1. This adds additional info  to the o2 ai chat
Add short cut at row to send the event to O2-ai
On inline expand of log row , add short cut at row to send the event to
O2-ai
On Side panel with details of logs line , add short cut at row to send
the event to O2-ai
On pipelines page send selected stream context
On functions creation page send the event to O2-ai
when there is uds enabled , we need to send _timestamp and _all field in the context
=> fix: O2 ai additional info 

web/src/composables/useLogs.ts
1. Fixed an issue where scan_size and time_taken were not resetting after running a query.
2. In streaming aggregate queries, the No Events Found message appeared before the actual results were displayed.
=> fix: UI loading scansize fix rc7

src/service/search/datafusion/udf/arr_descending_udf.rs, src/service/search/datafusion/udf/arrcount_udf.rs, src/service/search/datafusion/udf/arrindex_udf.rs, src/service/search/datafusion/udf/arrjoin_udf.rs, src/service/search/datafusion/udf/arrsort_udf.rs, src/service/search/datafusion/udf/arrzip_udf.rs, src/service/search/datafusion/udf/cast_to_arr_udf.rs, src/service/search/datafusion/udf/to_arr_string_udf.rs
Fixes #7614 
- Replace `.expect()` calls with `.ok()` and option chaining in array UDFs
- Add comprehensive test coverage for edge cases and invalid inputs
- Update UDFs to return null for invalid input following DataFusion standards
- Fix potential panics in `arrcount_udf`, `arrindex_udf`, `arrjoin_udf`, `arrsort_udf`, `arr_descending_udf`, `arrzip_udf`, and `to_arr_string_udf`
The UDFs previously used .expect() calls that could panic on invalid JSON or serialization errors. This change makes them more robust by:
- Use `.ok()` to convert `Result` to `Option` and chain with `.and_then()`
- Return `null` (`None`) for invalid inputs instead of panicking
- Add test coverage for edge cases including:
- Invalid JSON input
- Null inputs
- Empty arrays
- Out-of-bounds indices
- Wrong argument …
=> fix: UDFs panic for invalid JSON (#7614)

src/service/search/datafusion/udf/arr_descending_udf.rs, src/service/search/datafusion/udf/arrcount_udf.rs, src/service/search/datafusion/udf/arrindex_udf.rs, src/service/search/datafusion/udf/arrjoin_udf.rs, src/service/search/datafusion/udf/arrsort_udf.rs, src/service/search/datafusion/udf/arrzip_udf.rs, src/service/search/datafusion/udf/cast_to_arr_udf.rs, src/service/search/datafusion/udf/to_arr_string_udf.rs
- Replace `.expect()` calls with `.ok()` and option chaining in array UDFs
- Add comprehensive test coverage for edge cases and invalid inputs
- Update UDFs to return null for invalid input following DataFusion standards
- Fix potential panics in `arrcount_udf`, `arrindex_udf`, `arrjoin_udf`, `arrsort_udf`, `arr_descending_udf`, `arrzip_udf`, and `to_arr_string_udf`
The UDFs previously used .expect() calls that could panic on invalid JSON or serialization errors. This change makes them more robust by:
- Use `.ok()` to convert `Result` to `Option` and chain with `.and_then()`
- Return `null` (`None`) for invalid inputs instead of panicking
- Add test coverage for edge cases including:
- Invalid JSON input
- Null inputs
- Empty arrays
- Out-of-bounds indices
- Wrong argument counts
- Mixed …
=> fix: UDFs panic for invalid JSON (#7614) (rc7)

web/src/composables/useLogs.ts
Bug fix
___
- Wrap partition fetching in a Promise
- Reset metrics on initial request
- Await `processPostPaginationData()` pre-pagination
- Sequentially await `fetchAllParitions` calls
___
```mermaid
flowchart LR
A["getPaginatedData"] -- "on response" --> B["processPostPaginationData"]
B -- "then" --> C["fetchAllParitions"]
C -- "recurses" --> A
```
<tr>
<td>
<details>
<summary><strong>useLogs.ts</strong><dd><code>Update pagination and metrics in logs</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: streaming aggregates scansize tooktime and noevents found issue fix

web/src/components/functions/TestFunction.vue, web/src/plugins/logs/DetailTable.vue, web/src/plugins/logs/JsonPreview.vue, web/src/plugins/logs/TenstackTable.vue, web/src/plugins/logs/data-table/CellActions.vue
show o2 ai button when ai chat is enabled
___
Bug fix
___
- Wrap AI chat buttons with enterprise & AI enabled checks
- Import and expose `config` and `store` in affected components
- Hide O2 AI UI when AI chat is disabled or non-enterprise
___
<tr>
<td>
<details>
<summary><strong>TestFunction.vue</strong><dd><code>Feature-flag AI button in TestFunction</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
web/src/components/functions/TestFunction.vue
<ul><li>Wrapped AI button template …
=> fix: only show o2 ai btn when ai chat is enabled

src/config/src/config.rs, src/service/search/mod.rs
Enhancement
___
- Add `align_partitions_for_index` config option.
- Compute `step_factor` using index vs storage sizes.
- Adjust partition `step` when index-based search.
- Refactor stats retrieval in `search_partition`.
___
```mermaid
flowchart LR
Cfg["Config: align_partitions_for_index"]
Search["search_partition"]
Stats["Calculate step_factor"]
Step["Adjust partition step"]
Gen["Generate_partitions"]
Cfg -- "enabled" --> Search
Search -- "retrieve stats" --> Stats
Stats -- "index vs storage" --> Step
Step -- "apply to step" --> Gen
```
<tr>
<td>
<details> …
=> fix: align partitions for indexed search (#7642)

src/config/src/config.rs, src/handler/http/request/status/mod.rs, src/infra/src/cache/file_data/disk.rs, src/service/search/datafusion/distributed_plan/enrich_exec.rs, src/service/search/grpc/storage.rs
We get a write lock then write the files to disk, if the file is big it will lock the lock for a long time, in the mean time others check file exists calls need read lock will both blocked until the write file done.
This PR improved this case by:
1. check file is exists or not.
2. if cache is not exists, write file to local disk with a tmp file name.
3. get write lock and rename the tmp file to real file name.
4. release lock.
This can much improve the lock contention.
=> perf: improve disk cache lock time

src/handler/http/request/search/search_stream.rs, src/service/search/datafusion/distributed_plan/enrich_exec.rs
We were depending on query params for stream type in HTTP2 streaming APIs but the value was being sent in body.
=> fix: values api read stream type from body

src/config/src/config.rs, src/handler/http/request/status/mod.rs, src/service/alerts/mod.rs
str_match we can use secondary index now.
___
___
- Expose secondary index fields in config response  
- Replace SQL LIKE with `str_match` for contains
___
<tr>
<td>
<details>
<summary><strong>mod.rs</strong><dd><code>Expose secondary index in config response</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/handler/http/request/status/mod.rs
<ul><li>Imported <code>SQL_SECONDARY_INDEX_SEARCH_FIELDS</code> constant  <br> <li> Added <code>default_secondary_index_fields</code> to …
=> fix: use str_match replace LIKE for contains for alert

src/service/search/cluster/flight.rs, src/service/search/grpc/storage.rs
Enhancement
___
- Add human-readable index size to logs
- Use bytes_to_human_readable for compressed_size
- Modify log message in storage.rs
- Improve search observability
___
<tr>
<td>
<details>
<summary><strong>storage.rs</strong><dd><code>Include index size in search logs</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/service/search/grpc/storage.rs
<ul><li>Include <code>index size: {}</code> placeholder in log format<br> <li> Add …
=> fix: show index size when search tantivy

src/common/utils/auth_tests.rs, src/config/src/config.rs, src/config/src/utils/record_batch_ext.rs, src/service/search/grpc/storage.rs, src/service/search/streaming/mod.rs
Add new env 
```
ZO_QUERY_INDEX_THREAD_NUM = 0
```
Default value is `CPU * 4`.
___
Enhancement, Tests
___
- Add env var for index search concurrency
- Configure default query_index thread counts
- Use new thread count in search filter
- Refactor file grouping and update tests
___
```mermaid
flowchart LR
A["Load ZO_QUERY_INDEX_THREAD_NUM env"] --> B["Set query_index_thread_num default"]
B --> C["filter_file_list_by_tantivy_index uses new count"]
C --> D["Refactor group & repartition logic"]
D --> E["Update grouping tests"]
```
<tr>
<td>
<details> …
=> perf: improve concurrency for index search

src/service/search/grpc/wal.rs
Enhancement
___
- Parallelized batch adaptation and merging using Rayon
- Added logs measuring adapt and merge durations
- Refactored `adapt_batch` to return `diff_fields`
___
<tr>
<td>
<details>
<summary><strong>wal.rs</strong><dd><code>Parallel batch processing and logging</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/service/search/grpc/wal.rs
<ul><li>Imported <code>rayon</code> for parallel iteration<br> <li> Adapted and merged batches in parallel<br> <li> Logged timing and …
=> perf: improve search memtable

web/src/components/common/O2AIContextAddBtn.spec.js, web/src/components/common/O2AIContextAddBtn.vue, web/src/components/functions/TestFunction.vue, web/src/plugins/logs/DetailTable.vue, web/src/plugins/logs/TenstackTable.vue, web/src/plugins/logs/data-table/CellActions.vue, web/src/utils/validatePipeline.ts
fix: o2 ai add context button as component
___
Enhancement
___
- Introduce `O2AIContextAddBtn` component
- Refactor AI buttons across components
- Remove redundant logo and config logic
- Centralize AI button styling and emit
___
```mermaid
flowchart LR
A["O2AIContextAddBtn"] --> B["TestFunction.vue"]
A --> C["DetailTable.vue"]
A --> D["TenstackTable.vue"]
A --> E["CellActions.vue"]
```
<tr>
<td>
<details>
<summary><strong>O2AIContextAddBtn.vue</strong><dd><code>Create reusable AI context button component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: o2 ai add context button as component

src/config/src/meta/self_reporting/usage.rs, src/service/alerts/scheduler/handlers.rs, src/service/ingestion/mod.rs
When for some reason, alert manager is stuck for long time, once it is starts working fine, it can report hundreds/thousands of skipped events potentially keeping the alert manager stuck with every alert.
=> fix: use single event for alert skipped event triggers reporting

src/common/infra/ofga/mod.rs
adds a ofga migration missed in first PR
___
Bug fix
___
- Add missing re_patterns permissions migration
- Define migration version threshold to v0.0.19
- Introduce migration flag for re_patterns
- Trigger ownership tuple generation for re_patterns
___
```mermaid
flowchart LR
VersionCheck["Check existing_model_version < \"0.0.19\""]
FlagSet["Set need_re_pattern_permission_migration = true"]
TupleGen["Call get_ownership_all_org_tuple(\"re_patterns\")"]
VersionCheck -- "true" --> FlagSet
FlagSet --> TupleGen
```
<tr>
<td>
<details>
<summary><strong>mod.rs</strong><dd><code>Add re_patterns migration …
=> fix: rbac migration for re_patterns

web/src/components/dashboards/PanelContainer.vue
Enhancement
___
- Integrate short URL service for log panel redirection
- Show warning notification before redirecting
- Fallback to original URL on shortening error
___
```mermaid
flowchart LR
A["Log panel click"] --> B["Construct logsUrl"]
B --> C["Call shortURL.create"]
C --> D{"short_url exists?"}
D -- yes --> E["Open short_url"]
D -- no/fail --> F["Open original URL"]
```
<tr>
<td>
<details>
<summary><strong>PanelContainer.vue</strong><dd><code>Short URL integration for logs</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: dashboard go to logs with long url

src/service/alerts/scheduler/worker.rs, src/service/search/cluster/flight.rs
Bug fix
___
- Replace panic with graceful Option handling
- Log warnings for missing nodes or indices
- Default partition index to zero on failure
___
```mermaid
flowchart LR
A["Iterate file IDs"] --> B["get_node_from_consistent_hash"]
B -- "Some(node_name)" --> C["Lookup in node_idx"]
B -- "None result" --> F["Warn and idx=0"]
C -- "Found index" --> D["Use idx"]
C -- "Index missing" --> E["Warn and idx=0"]
D --> G["Push to partitions[idx]"]
E --> G
F --> G
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Error handling</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>flight.rs</strong><dd><code>Gracefully handle missing hash nodes</code>&nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: improve log message of partition file by consistent hashing

web/src/components/logstream/schema.vue
Enhancement
___
- Detect environment-specific index fields
- Disable selection and show tooltip for env settings
- Add environment options to index type dropdown
- Extend getFieldIndices to include env defaults
___
<tr>
<td>
<details>
<summary><strong>schema.vue</strong><dd><code>Support environment settings for index fields</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
web/src/components/logstream/schema.vue
<ul><li>Bound <code>disable</code> on q-select to <code>isEnvironmentSettings</code><br> <li> Conditional …
=> fix: environment FTS and secondary fields default selected

web/src/components/dashboards/VariablesValueSelector.vue, web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
Bug fix
___
- Use `str_match` for filtering in variable queries
- Preserve existing `treatAsNonTimestamp` panel settings
- Remove redundant whitespace in function call
___
<tr>
<td>
<details>
<summary><strong>VariablesValueSelector.vue</strong><dd><code>Update dummyQuery to use str_match</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
web/src/components/dashboards/VariablesValueSelector.vue
<ul><li>Replace <code>LIKE '%…%'</code> filter with <code>str_match</code> …
=> fix: dashboard values api filter query

web/src/components/dashboards/PanelContainer.vue
Enhancement
___
- Integrate short URL service for log panel redirection
- Show warning notification before redirecting
- Fallback to original URL on shortening error
___
```mermaid
flowchart LR
A["Log panel click"] --> B["Construct logsUrl"]
B --> C["Call shortURL.create"]
C --> D{"short_url exists?"}
D -- yes --> E["Open short_url"]
D -- no/fail --> F["Open original URL"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table> <tr>
<td>
<details>
<summary><strong>PanelContainer.vue</strong><dd><code>Short URL integration for logs</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: dashboard go to logs with long url (#7712)

Cargo.lock, Cargo.toml, src/common/utils/auth_tests.rs, src/config/src/meta/search.rs, src/config/src/utils/sql.rs, src/handler/http/request/search/error_utils.rs, src/handler/http/request/search/mod.rs, src/handler/http/request/search/search_stream.rs, src/infra/src/errors/mod.rs, src/service/search/cache/cacher.rs, src/service/search/cache/mod.rs, src/service/search/mod.rs, src/service/search/partition.rs, src/service/search/sql/histogram.rs, src/service/search/super_cluster/leader.rs, web/src/composables/useLogs.ts, web/src/plugins/logs/Index.vue, web/src/plugins/logs/SearchBar.vue, web/src/ts/interfaces/query.ts
1. Error code `20013` for histogram not applicable
```
{
"code": 20013,
"message": "Search histogram not available",
"error_detail": "Histogram unavailable for SUBQUERY, CTE, DISTINCT and LIMIT queries.",
"trace_id": "bb560cf815ae458680a6f506be58f0ed"
}
```
2. Modify partitions generation to able to generate mini partition for histogram query only when `search_type=ui` 
```
// Expected partitions with mini partition and histogram alignment:
// 1. 10:16 - 10:17 (mini partition)
// 2. 10:15 - 10:16 
// 3. 10:10 - 10:15 (histogram aligned)
// 4. 10:05 - 10:10 (histogram aligned)
// 5. 10:02 - 10:05 
```
cons: There could be an overlap of data points only for the mini partition. Hence, its limited only to `search_type=ui`
=> fix: hist interval bug fixes

src/handler/http/request/search/mod.rs, src/service/search/sql.rs
close #7751
___
Bug fix, Tests
___
- Refactor `pickup_where` with proper SQL parsing  
- Skip filters on subqueries, joins, CTEs  
- Update handler calls to new signature  
- Add extensive unit tests for extraction
___
```mermaid
flowchart LR
A["HTTP Request"] --> B["Search Handler"]
B --> C["Call pickup_where(sql)"]
C --> D["SQL Parser Visitor"]
D -- "simple WHERE" --> E["Return filter string"]
D -- "complex query" --> F["Return None"]
```
<tr>
<td>
<details>
<summary><strong>mod.rs</strong><dd><code>Update calls to new `pickup_where` signature</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: value api with complex query

src/service/alerts/scheduler/handlers.rs
Currently there is a bug in reporting the delay_in_secs field in triggers stream for skipped events. It uses microseconds in the delay_in_seconds field instead of seconds.
=> fix: convert microseconds to seconds for delay_in_secs in triggers stream

src/handler/http/request/search/search_stream.rs, src/service/search/sql/mod.rs
- histogram query with interval specified in http2 streaming will be have interval generated based on the query and request duration
- http2 stream responses will now also contain the `converted_histogram_query`
=> fix: hist_http2_streaming

web/src/composables/useDashboardPanel.ts, web/src/utils/query/sqlUtils.ts
Bug fix
___
- Support "Contains" operator in str_match logic
- Deprecate legacy LIKE-based Contains handling
- Update DashboardPanel and SQL utils
___
<tr>
<td>
<details>
<summary><strong>useDashboardPanel.ts</strong><dd><code>Add Contains operator to str_match logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
web/src/composables/useDashboardPanel.ts
<ul><li>Map "Contains" to str_match filter<br> <li> Commented out old LIKE-based Contains logic</ul>
</details>
</td>
<td><a …
=> fix: update string matching logic to include 'Contains' operator

web/src/components/alerts/AlertList.vue, web/src/components/common/sidebar/FolderList.vue, web/src/utils/commons.ts
1. currently sometimes it is not giving the results of the current folder when user tries to refresh the page when user is non default folder
=> fix: alert list refresh when user tries to refresh in non default folder

src/handler/http/request/search/search_stream.rs
- The histogarm interval needs to be re-calculated if the original query is modified to a histogram query when `is_ui_histogram`
- Similarly when `is_ui_histogram` is `true` a query that is already has hist interval in the query will need to be parsed for the interval before modified for the actual histogram query 
```rust
// Update histogram interval -- initial interval assignment
// Need to calculate the histogram interval before converting the query to a histogram query
// when `is_ui_histogram` is true. This is because if a query is already a histogram query
// with interval, for http2 streaming at the point of converting the query to a
// histogram query the interval will be generated again and not honor the original interval
// mentioned in the query.
```
```sql
select …
```
=> fix: re-cal hist interval http2 streaming if `is_ui_histogram`

src/config/src/meta/search.rs, src/service/search/search_stream.rs, web/src/composables/useLogs.ts, web/src/plugins/logs/Index.vue, web/src/plugins/logs/SearchResult.vue
This PR fixes 
1. when user refreshes the page with histogram toggle off it was auto enabling it to on
2. in search streaming when there is no data for histogram and if we have already a chart rendered it was not getting cleared 
3. removed WITH(CTE) query check as we are not depending on the BE whether to call histogram or not based up on the flag that we get from the BE that is is_histogram_eligible
4. modified BE response whenever we have no data for histogram BE was giving no search_response_hits event
=> fix: histogram interval bug fixes

src/service/search/sql/histogram.rs, web/src/plugins/logs/Index.vue, web/src/plugins/logs/SearchBar.vue, web/src/plugins/logs/TransformSelector.vue, web/src/plugins/logs/VisualizeLogsQuery.vue
* **When is the histogram query chosen?**  
If your query **does not** use `GROUP BY` at all — that is, `group_by` is *empty* — then there’s no natural way to aggregate the rows, so the visualization will show the same histogram chart as shown on the logs page.
* **When is the user-written query chosen?**  
If your query already has a `GROUP BY`, the normal results are good enough.
---
By default, only two chart types will be selected.
After the histogram check, the app looks at `group_by` fields to decide between a **Line chart** and a **Table**.
The app chooses a *line chart* when **all** of these are true:
1. There **is** a *timeseries field* (a column that represents time).  
2. There are **zero, one, or two** `GROUP BY` columns.
What goes where:
* **X-axis** – the timeseries field.
* …
=> fix: visualization enhancement minor fixes

src/handler/http/request/search/search_stream.rs, src/handler/http/request/stream/mod.rs, src/service/search/search_stream.rs
- fix order by for histogram query if alredy present in the query and the `search_type=ui` the partitions should honor the same
```
SELECT 
histogram(_timestamp) AS x_axis_1,
COUNT(k8s_namespace_name) AS "y_axis_1"
FROM default
GROUP BY x_axis_1
ORDER BY x_axis_1 ASC
```
- [fix: delete cahce api return error when no ts query param provided](https://github.com/openobserve/openobserve/pull/7787/commits/c0bc005e3f36015ea0c9470a0dc50939053f741d)
=> fix: http2_streaming bugs with new histogram flow

src/service/search/sql.rs
Bug fix
___
- Fix histogram interval variable usage
- Correct bucket width calculation
___
<tr>
<td>
<details>
<summary><strong>sql.rs</strong><dd><code>Correct histogram interval variable usage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/service/search/sql.rs
<ul><li>Replace <code>histogram_interval_visitor.interval</code> with <code>histogram_interval</code><br> <li> Multiply interval by 1,000,000 for microseconds<br> <li> Round bucket edges to even boundaries</ul>
</details>
</td>
<td><a …
=> fix: tantivy histogram interval

src/config/src/metrics.rs, src/infra/src/db/mysql.rs, src/infra/src/db/postgres.rs, src/infra/src/file_list/mysql.rs, src/infra/src/file_list/postgres.rs, src/infra/src/scheduler/mysql.rs, src/infra/src/scheduler/postgres.rs, src/infra/src/schema/history/mysql.rs, src/infra/src/schema/history/postgres.rs
Enhancement
___
- Remove third 'key' label dimension in DB_QUERY_NUMS
- Update all with_label_values to two labels only
- Remove empty-string label arguments across modules
- Applies to file_list, db, scheduler, schema, and metrics config
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody></tr></tbody></table>
</details>
___
=> fix: remove module key from zo_db_query_nums metrics (#7845)

web/src/utils/dashboard/convertDataIntoUnitValue.ts, web/src/utils/dashboard/convertTableData.ts
- #7864
___
Bug fix
___
- Removed outdated timestamp converter function
- Introduced inline microsecond timestamp parsing
- Unified ISO string and Date handling
- Formatted dates using timezone consistently
___
```mermaid
flowchart LR
A["val (any)"] --> B{"16-digit micro?"}
B -- yes --> C["timestamp = parseInt(val)/1000"]
B -- no --> D{"string ISO?"}
D -- yes --> E["timestamp = `${val}Z`"]
D -- no --> F["timestamp = new Date(val).getTime()/1000"]
C --> G["formatDate(toZonedTime(timestamp, timezone))"]
E --> G
F --> G
```
<tr>
<td>
<details>
<summary><strong>convertDataIntoUnitValue.ts</strong><dd><code>Re …
=> fix: dashboard time conversion (#7869)

tests/ui-testing/playwright-tests/GeneralTests/enrichment.spec.js, web/src/components/functions/AddEnrichmentTable.vue, web/src/components/functions/EnrichmentTableList.vue
This PR fixes the issues that are there in #7815
___
Bug fix
___
- Frontend restricts enrichment file uploads to CSV.
- Retains add/update form on page refresh.
___
```mermaid
flowchart LR
A["AddEnrichmentTable: accept .csv"]
B["EnrichmentTableList: onMounted check action"]
B -- "action=add" --> C["Show add form"]
B -- "action=update" --> D["Show update form"]
```
<tr>
<td>
<details>
<summary><strong>AddEnrichmentTable.vue</strong><dd><code>Restrict file uploader to CSV</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: enrichment table issues #7815

src/service/compact/retention.rs, src/service/db/enrichment_table.rs, src/service/enrichment_table/mod.rs, src/service/stream.rs, src/super_cluster_queue/enrichment_table.rs, src/super_cluster_queue/mod.rs
Enrichment table deletion should not create compact jobs, that is because compaction is a background job, and until that happens, the search on enrichment table is blocked. So, instead, we can directly delete the file_lists when enrichment tables are deleted.
___
___
- Directly delete enrichment file lists on rewrite
- Remove redundant compactor job creation
- Enhance logs with org_id and table name context
- Broadcast file list deletions in enterprise
___
```mermaid
flowchart LR
A["Rewrite enrichment table"] --> B["Compute time_range"]
B --> C["delete_enrichment_table(...)"]
C --> D["delete_from_file_list(...)"]
D --> E["Compact service removes file lists"]
D --> F{"Enterprise mode?"}
F -- "yes" --> G["Broadcast delete event"]
```
<details> <summary><h3> File …
=> fix: enrichment table rewrite should not create compact jobs

src/infra/src/table/migration/m20250801_000001_create_system_prompts_table.rs
___
- Change `updated_at` column to bigint
- Update migration tests to expect bigint
- Include `enterprise` in default features
- Add optional `o2_*` dependencies and roaring
___
<tr>
<td>
<details>
<summary><strong>m20250801_000001_create_system_prompts_table.rs</strong><dd><code>Change `updated_at` column type to bigint</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/infra/src/table/migration/m20250801_000001_create_system_prompts_table.rs
<ul><li>Changed <code>updated_at</code> column to …
=> fix: change `updated_at` AI prompts table to bigint

Cargo.lock, Cargo.toml, src/config/Cargo.toml, src/config/src/config.rs, src/config/src/meta/inverted_index.rs, src/config/src/metrics.rs, src/service/search/grpc/mod.rs, src/service/search/grpc/storage.rs, src/service/search/grpc/tantivy_result_cache.rs, src/service/search/grpc/utils.rs, src/service/search/index.rs, src/service/search/mod.rs
```
ZO_INVERTED_INDEX_RESULT_CACHE_ENABLED = false
ZO_INVERTED_INDEX_RESULT_CACHE_MAX_ENTRIES = 10000
ZO_INVERTED_INDEX_RESULT_CACHE_MAX_ENTRY_SIZE = 20480 // 20KB
```
by default the tantivy result only can cache at mot 10000 entry, and the max entry size is 20KB, it can modify by ZO_INVERTED_INDEX_RESULT_CACHE_MAX_ENTRIES, and ZO_INVERTED_INDEX_RESULT_CACHE_MAX_ENTRY_SIZE.
the cache struct is like below
```rust
#[derive(Debug, Clone)]
pub enum CacheEntry {
RowIdsBitVec(usize, BitVec),
RowIdsRoaring(usize, RoaringBitmap),
Count(usize),              // simple count optimization
Histogram(Vec<u64>),       // simple histogram optimization
TopN(Vec<(String, u64)>),  // simple top n optimization
Distinct(HashSet<String>), // simple distinct optimization
}
```
RowIdsBitVec is for row_ids / …
=> feat: impl tantivy result cache for rc9

src/config/src/config.rs, src/config/src/meta/self_reporting/error.rs, src/infra/src/cache/file_data/disk.rs, src/infra/src/lib.rs, src/service/search/index.rs, src/service/search/mod.rs, src/service/self_reporting/queues.rs
Add a new ENV and then we can disable error report:
```
ZO_USAGE_REPORTING_ERRORS_ENABLED=true
```
set to `false` will disable error report.
=> feat: improve internal error report

src/cli/basic/cli.rs, src/cli/basic/http.rs, src/config/src/metrics.rs, src/config/src/utils/schema_ext.rs, src/handler/http/request/status/mod.rs, src/infra/src/schema/mod.rs, src/job/metrics.rs, src/service/enrichment/storage.rs, src/service/search/datafusion/storage/file_statistics_cache.rs, src/service/self_reporting/ingestion.rs
- Add parquet metadata cache in metrics:
- `zo_query_parquet_metadata_cache_files` and `zo_query_parquet_metadata_cache_used_bytes`
- Add parquet metadata cache size in `/node/status` API, also create one CLI for that:
```
./target/debug/openobserve node status   
+-------------------------------------+-------------------------------+
| KEY                                 | VALUE                         |
+-------------------------------------+-------------------------------+
| cardinality_expired_count           | 0                             |
+-------------------------------------+-------------------------------+
| cardinality_total_count             | 0                             |
+-------------------------------------+-------------------------------+
| compact_file_list_offset …
```
=> feat: add parquet cache size in status

src/service/search/cache/cacher.rs
fix #7919
___
Bug fix
___
Avoid unwrap panic when ts column missing
Return default cache response when None
Preserve order_by in default response
Update result cache key with timestamp
___
```mermaid
flowchart LR
A["check_cache: determine result_ts_col"] -- "was None" --> B["return default MultiCachedQueryResponse"]
A -- "found ts col" --> C["use result_ts_col for cache key"]
C -- "set discard_interval, file_path" --> D["proceed with caching logic"]
```
<tr>
<td>
<details>
<summary><strong>cacher.rs</strong><dd><code>Guard missing timestamp column to avoid panic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: result cache with func

src/job/mod.rs
pick from https://github.com/openobserve/openobserve/pull/7925/ for main
Without this the alert manager panics on init
___
Bug fix
___
Guard local cache table creation for alert manager
Prevent alert-manager init panics on startup
Create global file index table as before
No behavior change for non-alert nodes
___
```mermaid
flowchart LR
Init["job::init()"] --> CreateGlobal["create_table_index() for infra_file_list"]
Init --> Cond{"LOCAL_NODE.is_alert_manager()?"}
Cond -- "No" --> CreateLocal["LOCAL_CACHE.create_table_index()"]
Cond -- "Yes" --> Skip["Skip local cache table creation"]
```
<tr>
<td> …
=> fix: local cache table for alert manager

web/src/composables/useLogs.ts
___
Strip SQL comment lines before execution
Enable SQL mode by setting `sql_mode` to full
Preserve multiline queries after filtering
Clear hits when rebuilding SQL string
___
```mermaid
flowchart LR
A["Incoming SQL query"] -- "replace backticks" --> B["Normalized SQL"]
B -- "split by newline" --> C["Filter out '--' comments"]
C -- "join back" --> D["Clean SQL"]
D -- "set sql_mode='full'" --> E["Request query params"]
```
<tr>
<td>
<details>
<summary><strong>useLogs.ts</strong><dd><code>SQL sanitization and full sql_mode enablement</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: commented query with sql mode

web/src/components/alerts/RealTimeAlert.vue, web/src/components/alerts/ScheduledAlert.vue
1. This PR fixes the issue in add alert page when user tries to provide invalid input for threshold it was showing under the input , it should show below the input
___
Bug fix
___
- Fix threshold error message positioning
- Treat empty silence input as invalid
- Standardize undefined/null checks with strict equality
- Remove absolute positioning from threshold error
___
```mermaid
flowchart LR
RT["RealTimeAlert.vue validation"] -- add '' check --> RTERR["Show 'Field is required!'"]
SA1["ScheduledAlert.vue threshold error"] -- remove absolute --> SAERR["Inline error display"]
SA2["ScheduledAlert.vue silence validation"] -- strict null/undef + '' --> SAERR2["Consistent required error"]
```
<table><thead><tr><th></th><th …
=> fix: show error for threshold while user provides invalid input

deploy/build/Dockerfile.pr.amd64, src/router/http/mod.rs
Currently we do not handle `base_uri` in the router, so if it is set, the path which should go to queriers incorrectly gets sent to ingesters. This fixes it by stripping `base_uri` from path if `base_uri` is non empty and then checking the resulting path.
=> fix: handle non-empty base-uri in router

src/config/src/meta/pipeline/components.rs, src/service/alerts/scheduler/handlers.rs, src/service/pipeline/mod.rs
- When delay is non-zero for derived stream, currently sometimes the start time becomes greater than the end time. This pr fixes that by moving to the next run where the end time eventually becomes greater than the start time and also follows the given delay.
- Currently when updating a derived stream, it deletes the old scheduled job, and hence the start time for the scheduled job changes. As a result, there can be duplicate results in the derived stream because of updates. This pr fixes this by just updating only the next_run_at field of the scheduled_job.
=> fix: skip when start time > end time for delayed derived stream

src/handler/http/request/stream/mod.rs, src/infra/src/file_list/mod.rs, src/infra/src/file_list/mysql.rs, src/infra/src/file_list/postgres.rs, src/infra/src/file_list/sqlite.rs, src/service/compact/mod.rs, src/service/compact/retention.rs, src/service/db/compact/retention.rs
impl #8055
___
Enhancement
___
- Add daily retention job creation
- Delete by hour within daily jobs
- Query min available date from storage
- Avoid duplicate jobs via cache window
___
```mermaid
flowchart LR
HTTP["HTTP delete by time range"] -- calls --> DBRet["db.compact.retention.delete_stream (returns key,created)"]
RetSvc["Retention service delete_by_stream"] -- get min date --> FileList["infra.file_list.get_min_date (MySQL/PG/SQLite)"]
RetSvc -- generate daily jobs --> DBRet
DBRet -- cache prevent duplicates --> KV["KV db put(/compact/delete/...)"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>7 files</summary><table>
<tr> …
=> feat: create data retention by day

src/infra/src/db/nats.rs, src/infra/src/queue/nats.rs
___
- Clarify NATS KV bucket error messages
- Improve stream creation error handling
- Refine consumer creation error logs
- Include bucket and stream names in errors
___
```mermaid
flowchart LR
KV["KV bucket creation"] -- "include bucket_name in error" --> ErrMsg1["More specific error"]
Stream["Stream get_or_create"] -- "map_err with logging" --> ErrMsg2["Detailed error + log"]
Consumer["Consumer get_or_create"] -- "refined log and message" --> ErrMsg3["Detailed error + log"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Error handling</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>nats.rs</strong><dd><code>More specific KV bucket error …
=> fix: improve error msg of nats

src/service/pipeline/batch_execution.rs
When the realtime pipeline gets 0 records to process, currently it panics as the mpsc channel uses the number of given records as the buffer size which can not be zero. This pr returns early if the number of records is zero.
=> fix: return from pipeline batch_execution if batch size is zero

web/src/components/dashboards/addPanel/FieldList.vue
Bug fix
___
Handle missing or empty stream schemas
Fetch schema when absent or zero-length
Default to empty schema to avoid errors
Improve robustness of dashboard field loading
___
```mermaid
flowchart LR
UI["FieldList.vue"]
Check["Check stream.schema present and non-empty"]
Fetch["Fetch schema via loadStreamFields(name)"]
Validate["Validate schema not null/empty"]
Assign["Assign settings and schema"]
DefaultEmpty["Set stream.schema = [] and return"]
UI -- "iterate streams" --> Check
Check -- "missing or empty" --> Fetch
Fetch --> Validate
Validate -- "valid schema" --> Assign
Validate -- "invalid/empty" --> DefaultEmpty
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug …
=> fix: dashboard stream fields not found

web/src/components/pipeline/NodeForm/Query.vue
1. This PR changes the user limits to 100 by default while validating the query so it will solve the issue of larger limit
2. we dont change the original query but instead while sending for the validation we replace the limit if it is greater than 100 to 100
3. it will also detect limit in the entire query so multiple limit is possible in ctes , sub queries so handled that as well
4. if no limit then we will simply return it
=> fix: normalize the limit to 100 by default rc9   (#8075)

web/src/views/Dashboards/addPanel/AddPanel.vue
Bug fix
___
Prevent dashboard editor panel overlap
Wrap errors component in fixed-width container
Adjust layout with non-shrinking sidebar div
Improve panel/side content separation
___
```mermaid
flowchart LR
Layout["AddPanel layout"] -- "add fixed-width div" --> Errors["DashboardErrorsComponent container"]
Errors -- "prevent flex shrink" --> NoOverlap["No overlap in editor"]
```
<tr>
<td>
<details>
<summary><strong>AddPanel.vue</strong><dd><code>Prevent errors panel from shrinking and overlapping</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> fix: dashboard editor getting overlap for custom chart

src/config/src/meta/dashboards/v5/mod.rs, web/src/components/dashboards/OverrideConfigPopup.vue, web/src/components/dashboards/addPanel/OverrideConfig.vue, web/src/components/dashboards/panels/TableRenderer.vue, web/src/utils/dashboard/colorPalette.ts, web/src/utils/dashboard/convertTableData.ts
Enhancement
___
- Add unique value auto-color for tables
- Introduce typed override config schema
- Update popup UI for new config types
- Pass color mode through table pipeline
___
```mermaid
flowchart LR
Schema["Dashboard v5 Config enum"]
Popup["OverrideConfigPopup UI logic"]
Convert["convertTableData column metadata"]
Renderer["TableRenderer cell style"]
Palette["colorPalette getColorForTable"]
Schema -- "new type 'unique_value_color'" --> Popup
Popup -- "persist {type, autoColor|value}" --> Convert
Convert -- "set col.colorMode='auto'" --> Renderer
Renderer -- "map unique values to colors" --> Palette
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td …
=> feat: dashboard unique colors to the table column automatically.

web/src/composables/useLogs.ts, web/src/plugins/logs/Index.vue
Steps:
1. Go to logs page.
2. Select stream and render logs.
3. Toggle to visualization
4. modify chart type or chart configs.
5. Go back to logs page.
6. Again switch to visualization.(config should be synced and default chart type will be automatically selected).
- Share visualization will always sync config and chart type both.
=> fix: config sync on logs to visualization toggle

src/config/src/meta/dashboards/v5/mod.rs, web/src/components/dashboards/OverrideConfigPopup.vue, web/src/components/dashboards/addPanel/OverrideConfig.vue, web/src/components/dashboards/panels/TableRenderer.vue, web/src/utils/dashboard/colorPalette.ts, web/src/utils/dashboard/convertTableData.ts
Enhancement
___
- Add unique value auto-color for tables
- Introduce typed override config schema
- Update popup UI for new config types
- Pass color mode through table pipeline
___
```mermaid
flowchart LR
Schema["Dashboard v5 Config enum"]
Popup["OverrideConfigPopup UI logic"]
Convert["convertTableData column metadata"]
Renderer["TableRenderer cell style"]
Palette["colorPalette getColorForTable"]
Schema -- "new type 'unique_value_color'" --> Popup
Popup -- "persist {type, autoColor|value}" --> Convert
Convert -- "set col.colorMode='auto'" --> Renderer
Renderer -- "map unique values to colors" --> Palette
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td …
=> feat: dashboard unique colors to the table column automatically. (#8051)

web/src/components/pipeline/NodeForm/Query.vue
1. This PR changes the user limits to 100 by default while validating the query so it will solve the issue of larger limit
2. we dont change the original query but instead while sending for the validation we replace the limit if it is greater than 100 to 100
3. it will also detect limit in the entire query so multiple limit is possible in ctes , sub queries so handled that as well
4. if no limit then we will simply return it
___
___
- Normalize SQL LIMIT during validation
- Cap LIMIT to 100 across query parts
- Preserve original user query intact
- Handle multiple LIMIT/OFFSET safely
___
```mermaid
flowchart LR
A["User SQL"] -- "pass to validation" --> B["normalizeLimit(sql, 100)"]
B -- "replace LIMIT > 100" --> C["Capped SQL for validation"]
B -- "no LIMIT found" --> …
```
=> fix: normalize the limit to 100 by default  (#8075)

src/config/src/meta/folder.rs, src/config/src/utils/base64.rs, src/config/src/utils/file.rs, src/config/src/utils/hash/mod.rs, src/config/src/utils/json.rs, src/handler/http/request/status/mod.rs, src/infra/src/table/migration/m20241217_155000_populate_alerts_table.rs, src/infra/src/table/migration/m20250611_000002_populate_reports_table.rs, src/service/file_list_dump.rs, src/service/metrics/otlp.rs, src/service/search/grpc/utils.rs, src/service/search/index.rs, src/service/search/streaming/cache.rs, src/service/search/streaming/execution.rs, src/service/search/streaming/sorting.rs, src/service/search/streaming/utils.rs, src/service/traces/mod.rs
___
- Add extensive unit tests across modules
- Enable serde Deserialize for structs
- Derive Clone/Debug/PartialEq for report types
- Adjust router test placeholder behavior
___
```mermaid
flowchart LR
search_tests["search/index tests"] -- "new unit tests" --> search_index_rs["src/service/search/index.rs"]
metrics_tests["OTLP metrics tests"] -- "new unit tests" --> metrics_otlp_rs["src/service/metrics/otlp.rs"]
grpc_utils_tests["search grpc utils tests"] -- "new unit tests" --> grpc_utils_rs["src/service/search/grpc/utils.rs"]
file_dump_tests["file list dump tests"] -- "new unit tests" --> file_list_dump_rs["src/service/file_list_dump.rs"]
status_derives["status structs derives"] -- "add Deserialize + tests" --> status_mod_rs["src/handler/http/request/status/mod.rs"] …
```
=> chore: add UTs, run fmt and clipyy

src/config/src/meta/mod.rs, src/config/src/meta/projections.rs, src/service/search/cache/mod.rs, src/service/search/datafusion/plan/mod.rs, src/service/search/datafusion/plan/regex_projections.rs, src/service/search/streaming/cache.rs, src/service/search/streaming/execution.rs, web/src/components/logstream/AssociatedRegexPatterns.vue
Enhancement, Tests, Documentation
___
- Apply regex patterns at search time
- Map projections to source columns
- Integrate enterprise pattern manager
- Add tests for projection extraction
___
```mermaid
flowchart LR
SearchReq["Search request"] -- "execute query" --> DatafusionPlan["DataFusion logical plan"]
DatafusionPlan -- "extract projection mappings" --> ProjMap["ProjectionColumnMapping"]
SearchReq -- "fetch hits" --> Hits["Search results (hits)"]
ProjMap -- "guide field processing" --> PatternMgr["Pattern manager (enterprise)"]
Hits -- "apply regex patterns" --> Hits2["Transformed results"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details …
=> feat: search time patterns

web/src/composables/useLogs.spec.ts, web/src/composables/useLogs.ts, web/src/plugins/logs/Index.vue
Steps:
1. Go to logs page.
2. Select stream and render logs.
3. Toggle to visualization
4. modify chart type or chart configs.
5. Go back to logs page.
6. Again switch to visualization.(config should be synced and default chart type will be automatically selected).
- Share visualization will always sync config and chart type both.
___
___
- Restore visualization config from URL reliably
- Preserve chart type on first toggle
- Prevent re-trigger during URL restoration
- Persist visualization_data across routes
___
```mermaid
flowchart LR
LogsPage["Logs page toggle"] -- "to visualize" --> RestoreURL["Restore config from URL"]
RestoreURL -- "preserve config + maybe type" --> ExtractFields["Extract fields (auto-select?)"]
ExtractFields -- "build data" --> …
```
=> fix: config sync on logs to visualization toggle main

web/src/components/dashboards/addPanel/FieldList.vue, web/src/composables/useDashboardPanel.ts, web/src/utils/query/sqlUtils.ts
- #8080
- #8098
___
___
- Fix stream selection for CTE queries
- Add robust stream extraction utility
- Make query updates async-aware
- Adjust watchers to trigger reliably
___
```mermaid
flowchart LR
SQL["SQL query (incl. CTE)"] -- parse --> Extract["getStreamNameFromQuery()"]
Extract -- returns stream --> Panel["useDashboardPanel: updateQueryValue()"]
Panel -- set --> StreamField["currentQuery.fields.stream"]
Watcher["Vue watch hooks"] -- trigger on changes --> Panel
```
<tr>
<td>
<details>
<summary><strong>FieldList.vue</strong><dd><code>Stabilize watcher for stream type …
=> fix: parse cte query to extract stream name (#8102)

web/src/components/logstream/AssociatedRegexPatterns.vue, web/src/services/stream.ts
1. we are now support both redaction or dropping of matched regex field during search time and ingestion time
___
___
- Add confirmation dialog before removing pattern
- Support deselecting apply_at with safe revert
- Generalize redact/drop copy beyond ingestion
- Track dialog state and handlers
___
```mermaid
flowchart LR
UI["AssociatedRegexPatterns.vue"]
Dialog["ConfirmDialog component"]
State["showWarningDialogToRemovePattern state"]
Logic["apply_at change handler"]
Revert["transformApplyAtValue + cancel handler"]
Actions["handleAddOrRemovePattern"]
UI -- "imports & registers" --> Dialog
UI -- "manages" --> State
Logic -- "empty selection triggers" --> State
State -- "cancel" --> Revert
State -- "ok" --> Actions
Revert -- "restore previous apply_at" --> UI
``` …
=> fix: regex patterns introduce search as well

web/src/components/logstream/schema.vue
Enhancement
___
- Split index options for environment fields
- Remove env options from default list
- Conditionally render options based on row settings
- Expose new env options in component state
___
```mermaid
flowchart LR
UI["Schema Index Select (QSelect)"]
RowCheck["isEnvironmentSettings(row)"]
DefaultOpts["streamIndexType"]
EnvOpts["streamIndexTypeEnv"]
State["Component exports"]
UI -- evaluates --> RowCheck
RowCheck -- true --> EnvOpts
RowCheck -- false --> DefaultOpts
EnvOpts -- provided as :options --> UI
DefaultOpts -- provided as :options --> UI
EnvOpts -- added to --> State
```
<tr>
<td> …
=> fix: remove environment option from list

web/src/views/HomeView.vue
Enhancement
___
- Add right margin to home cards
- Improve spacing between dashboard boxes
- Visual polish on HomeView layout
___
```mermaid
flowchart LR
A["HomeView.vue"] -- "add q-mr-lg" --> B["Card containers"]
B -- "improved spacing" --> C["Home page layout"]
```
<tr>
<td>
<details>
<summary><strong>HomeView.vue</strong><dd><code>Add right margin to HomeView card containers</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
web/src/views/HomeView.vue
<ul><li>Add <code>q-mr-lg</code> to three <code>.card-container</code> divs.<br> …
=> fix: added spacing between box

src/ingester/src/writer.rs
- During ingestion there are instances where the writer channel is closed. And this will need an app restart. 
- So instead when we do `get_writer` check if channel is closed and if it is creates a new writer
=> fix: ingester writer channel closed

src/cli/basic/cli.rs, src/common/infra/cluster/etcd.rs, src/common/infra/cluster/mod.rs, src/common/infra/cluster/nats.rs, src/config/src/cluster.rs, src/config/src/ider.rs, src/config/src/meta/cluster.rs, src/job/files/mod.rs, src/service/db/schema.rs, src/service/ingestion/mod.rs, src/service/schema.rs
- Add duplicated machine id check
- Add 4 random chars for generate parquet filename
- Use Atomic replace unsafe code
___
___
- Centralize node ID generation logic
- Replace unsafe globals with atomics
- Detect and resolve duplicate node IDs
- Truncate long Snowflake IDs when parsing
___
```mermaid
flowchart LR
A["Cluster register (etcd/nats)"] -- "collect node ids" --> B["generate_node_id()"]
B -- "new id" --> C["LOCAL_NODE_ID (AtomicI32)"]
C -- "reload if changed" --> D["Snowflake ID generator"]
E["set_status()"] -- "detect duplicate id" --> B
F["CLI parse-id"] -- "truncate to 19 digits" --> G["parse i64"]
H["Parquet filename"] -- "append 4-hex random" --> I["unique file path"]
``` …
=> fix: enhance machine id check

src/service/alerts/mod.rs
Bug fix
___
- Fix WHERE placement in grouped alert SQL
- Ensure filter applied before GROUP BY/HAVING
- Minor spacing cleanup in non-grouped query
___
```mermaid
flowchart LR
buildSQL["build_sql in alerts/mod.rs"]
groupCase["Grouped query path"]
noGroupCase["Non-grouped query path"]
bug["WHERE placed after FROM"]
fix["Move WHERE before GROUP BY/HAVING"]
buildSQL -- "when group_by present" --> groupCase
groupCase -- "was" --> bug
bug -- "now" --> fix
buildSQL -- "when no group_by" --> noGroupCase
noGroupCase -- "retain WHERE placement" --> fix
```
<tr>
<td>
<details> …
=> fix: sql generation for quick alerts

src/config/src/config.rs, src/service/promql/search/cache/mod.rs, src/service/search/cache/cacher.rs, src/service/search/cache/mod.rs, src/service/search/cache/multi.rs
- `ZO_CACHE_DELAY_SECS` default 300 secs (5mins)
=> fix: unify cache delay secs across result cache, aggs cache and metrics

src/infra/src/schema/mod.rs, src/service/alerts/mod.rs
___
- Add schema cache lookup helper
- Skip alert evaluation if stream missing
- Improve error message for missing stream
___
```mermaid
flowchart LR
A["Alert evaluation"] -- "resolve stream names" --> B["Per-stream checks"]
B -- "schema missing" --> C["Return error: skip evaluation"]
B -- "schema exists" --> D["Fetch settings & validate period"]
```
<tr>
<td>
<details>
<summary><strong>mod.rs</strong><dd><code>Introduce schema cache lookup utility</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: skip alert evaluation when stream not found

web/src/plugins/logs/IndexList.vue
1. in index list that is there in logs page when user adds any filter and clicks on the row instead of toggle , then the filter stays there it should be cleared
___
___
- Clear index filter after stream selection
- Add ref to stream select component
- Use Quasar updateInputValue via nextTick
___
```mermaid
flowchart LR
UI["IndexList.vue QSelect (stream)"] -- "ref=streamSelect" --> Ref["Access component ref"]
Ref -- "nextTick" --> Safe["DOM ready"]
Safe -- "updateInputValue('')" --> Clear["Clear filter input"]
Clear -- "then" --> Change["Trigger onStreamChange(\"\")"]
```
<tr>
<td> …
=> fix: manually clear the input using updateInputValue function

src/job/files/parquet.rs, src/service/compact/merge.rs, src/service/tantivy/mod.rs
We also should check if cache latest files enabled when we try to cache local file to disk cache.
___
Bug fix
___
- Guard caching with `enabled` flag
- Apply to parquet merge paths
- Apply to Tantivy index caching
- Prevent unintended disk writes
___
```mermaid
flowchart LR
CFG["Config: cache_latest_files.enabled"]
P1["parquet.rs merge_files"]
M1["compact/merge.rs merge_files (path 1)"]
M2["compact/merge.rs merge_files (path 2)"]
T1["tantivy create_tantivy_index"]
DISK["disk cache set(...)"]
CFG -- "enabled && cache_* && download_from_node" --> P1
CFG -- "enabled && cache_* && download_from_node" --> M1
CFG -- "enabled && cache_* && download_from_node" --> M2
CFG -- "enabled && cache_* && download_from_node" --> T1
P1 -- "conditional write" --> DISK
M1 -- "conditional write" --> DISK
M2 …
```
=> fix: check if cache latest files enabled for cache local file

src/config/src/config.rs, src/service/search/datafusion/distributed_plan/decoder_stream.rs
The currently printed scan_stats are accumulated as the node returns, but the scan_stats of a node itself should be output
this change only affect log output
=> fix: scan_stats for each node info

web/src/views/LogStream.vue
Bug fix
___
- Pass quick mode flag in log stream redirect
- Preserve org and datetime query params
- Ensure compatibility with stream explorer navigation
___
```mermaid
flowchart LR
LogStream["LogStream.vue redirect"] -- "router.push with query" --> Logs["Logs view"]
Store["Store zoConfig.quick_mode_enabled"] -- "evaluate true/false" --> LogStream
```
<tr>
<td>
<details>
<summary><strong>LogStream.vue</strong><dd><code>Add quick_mode to logs redirect query</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: quick mode by default check explore 15

web/src/plugins/logs/TenstackTable.vue
#8249 
When a logs short URL is created and opened, trying to add a column to the table using the eye icon does not add the column.
=> fix: Add field to table in logs

Cargo.lock, Cargo.toml, deny.toml, src/config/Cargo.toml, src/config/src/ider.rs, src/handler/http/request/traces/mod.rs, web/src/plugins/traces/TraceBlock.spec.ts, web/src/utils/zincutils.spec.ts, web/src/utils/zincutils.ts
Enhancement, Tests
___
- Switch trace IDs to UUID v7
- Add timestamp extraction from trace ID
- Improve HTTP header parsing robustness
- Add frontend UUID v7 utils and tests
___
```mermaid
flowchart LR
RustGen["Rust: generate_trace_id uses UUID v7"] -- "u128 -> OTel TraceId" --> OTel["OpenTelemetry TraceId"]
RustExtract["Rust: get_start_time_from_trace_id"] -- "parse v7 timestamp" --> QueryTime["Adjust query time window"]
HTTP["HTTP traces handler"] -- "robust headers + trace_id param" --> RustExtract
WebUtil["Web utils: getUUIDv7 + generateTraceContext"] -- "v7 traceId, v4 spanId" --> BrowserTraces["Browser trace context"]
TestsRust["Rust tests"] -- "validate v7, ordering, parsing" --> RustGen
TestsWeb["Web tests"] -- "validate v7, ordering, context" --> WebUtil
```
<details> …
=> feat: use uuid v7 for internal trace ids

src/config/src/config.rs
related to https://github.com/openobserve/openobserve/issues/8280
in some case, the utf8view will result in large memory usage, and slow down performance, so current make it default disable
=> chore: default disable utf8view

src/config/src/meta/stream.rs
close #8264
___
- Add Default for `StreamSettings`
- Set `enable_distinct_fields` default to true
- Fix serialization key for distinct fields flag
- Use serde defaults for optional fields
___
```mermaid
flowchart LR
A["StreamSettings struct"] -- "add Default impl" --> B["enable_distinct_fields defaults to true"]
A -- "serde default on fields" --> C["robust deserialization"]
A -- "Serialize impl update" --> D["serialize 'enable_distinct_fields' key"]
```
<tr>
<td>
<details>
<summary><strong>stream.rs</strong><dd><code>StreamSettings defaults and serialization corrected</code>&nbsp; …
=> fix: default value for enable_distinct_fields

src/config/src/config.rs
related to https://github.com/openobserve/openobserve/issues/8280
in some case, the utf8view will result in large memory usage, and slow down performance, so current make it default disable
=> chore: default disable utf8view for main

src/job/grpc.rs, src/job/mod.rs, src/main.rs
This PR added a new job it will check is there `grpc_runtime` thread every minute. if `grpc_runtime` thread no longer exist, it will exit the app.
With systemd, we can set 
```
Restart=on-failure
```
The app will auto start again if it exist.
=> feat: add grpc health check

src/service/search/sql/visitor/column.rs
for query
```sql
select * from t1 union select * from t2
```
if the column number and schema not match, we should return error
=> fix: correct union query with wildcard[main]

src/infra/src/db/mysql.rs, src/infra/src/db/postgres.rs, src/migration/mod.rs
Enhancement
___
- Add DDL pool shutdown helpers
- Invoke shutdown after migrations complete
- Handle MySQL and PostgreSQL cases
- Log outcomes and warnings
___
```mermaid
flowchart LR
MIG["Migrations complete"] -- "meta_store=postgres" --> P["Call postgres::shutdown_ddl_pool()"]
MIG -- "meta_store=mysql" --> M["Call mysql::shutdown_ddl_pool()"]
MIG -- "meta_store=sqlite/other" --> S["No-op"]
P -- "close CLIENT_DDL" --> PDONE["Postgres DDL pool closed"]
M -- "close CLIENT_DDL" --> MDONE["MySQL DDL pool closed"]
```
<tr>
<td>
<details>
<summary><strong>mysql.rs</strong><dd><code>MySQL DDL pool shutdown …
=> chore: shutdown ddl pool

src/config/src/utils/async_file.rs, src/config/src/utils/file.rs, src/service/search/grpc/wal.rs
Chore
The function async scan_files_filtered() is relocated to async_file.rs file which is far more appropriate place instead of utils/file.rs which only contains blocking file operations. 
Updated extension matching to be case insensitive which was previously case sensitive. 
Tests are copied from @hengfeiyang's [PR](https://github.com/openobserve/openobserve/pull/8352/files)
___
Enhancement, Tests
___
- Move async scanning to `async_file.rs`
- Add `scan_files` async wrapper
- Update imports in WAL gRPC
- Add async scanning tests
___
```mermaid
flowchart LR
fileRs["utils/file.rs"]
asyncFileRs["utils/async_file.rs"]
walGrpc["service/search/grpc/wal.rs"]
fileRs -- "remove async scan + tests" --> asyncFileRs
asyncFileRs -- "provide scan_files_filtered + scan_files" --> walGrpc
```
<details> …
=> chore: Move async scan_files_filtered() into appropriate async_file module

web/src/plugins/logs/Index.vue, web/src/plugins/logs/VisualizeLogsQuery.vue, web/src/utils/query/sqlUtils.ts
- #8338 
Resolved Issues:
- Implemented a check for `ZO_QUICK_MODE_ENABLED` before enabling quick mode on logs for visualization toggle.
1.   If `ZO_QUICK_MODE_ENABLED=true`, quick mode is enabled when the query is `select *`.
2.   Otherwise, `select *` query is always permitted in visualization mode.
- Restricted the use of `SELECT *` queries in visualization mode.    
- As API call triggered on changing the chart type, such changes are now disallowed for `SELECT *` queries.
=> fix: restrict `select *` query for visualization

src/cli/basic/cli.rs, src/infra/src/queue/nats.rs
Add some tips:
```
Warning: !!!
calculate_stats_step_limit_secs good to be greater than 3600 for stats reset,
suggested to run again with:
ZO_CALCULATE_STATS_STEP_LIMIT_SECS=3600 ./openobserve reset -c stream-stats
```
___
___
- Add warning for low stats step limit
- Guide to rerun with recommended env var
- Improve stream-stats reset safety messaging
___
```mermaid
flowchart LR
CLI["CLI reset command"]
Check["Check calculate_stats_step_limit_secs"]
Warn["Print warning and rerun tip"]
ResetOffset["Reset stats update offset"]
ResetData["Reset stream stats table"]
CLI -- "reset -c stream-stats" --> Check
Check -- "< 3600" --> Warn
Check -- "any value" --> ResetOffset
ResetOffset --> ResetData
``` …
=> fix: improve stream stats reset

src/cli/basic/cli.rs, src/config/src/config.rs, src/config/src/config_path_manager.rs, src/config/src/lib.rs, src/handler/http/request/status/mod.rs, src/job/config_watcher.rs, src/service/search/index.rs
Now match_all support:
- term search: `match_all('keyword')`
- contains search: `match_all('*wor*')`
- prefix search: `match_all('keyw*')`
- suffix search: `match_all('*word')`
=> fix: contains search for match_all

src/config/src/meta/stream.rs, src/config/src/utils/inverted_index.rs, src/job/files/parquet.rs, src/service/compact/merge.rs, src/service/search/grpc/storage.rs
impl #8482
___
___
- Enable inverted index for `Metadata` streams
- Rename helper to `support_index`
- Update file-name conversion to include `metadata`
- Fix logging format pluralization
___
```mermaid
flowchart LR
ST["StreamType::support_index includes Metadata"]
--> MF["Merge/compact paths check support_index before indexing"]
MF --> II["Generate inverted index for Metadata"]
PFN["Parquet->Tantivy path conversion includes metadata"]
--> II
LOG["Tantivy search log message fix"]
```
<tr>
<td>
<details>
<summary><strong>stream.rs</strong><dd><code>StreamType now declares index …
=> feat: support inverted index for metadata stream

src/config/src/config.rs, src/handler/http/request/status/mod.rs, web/src/plugins/logs/IndexList.vue
This provides the default tab for logs ui sidebar via config api and env config
___
Enhancement
___
- Add env to set default fields tab
- Validate and expose config via status API
- Set frontend default tab based on config
- Add watcher to apply tab on toggle
___
```mermaid
flowchart LR
A["Env var ZO_LOG_PAGE_DEFAULT_FIELD_LIST"] --> B["Backend Config (Common.log_page_default_field_list)"]
B --> C["Config validation (uds|all|interesting)"]
C --> D["/api/config response (zo_config)"]
D --> E["Frontend store.state.zoConfig.log_page_default_field_list"]
E --> F["Logs UI sets default tab via setDefaultFieldTab()"]
F --> G["Watch toggle to re-apply default"]
``` …
=> fix: interesting field config

src/cli/basic/cli.rs, src/config/src/config.rs, src/config/src/config_path_manager.rs, src/config/src/lib.rs, src/config/src/utils/pausable_job.rs, src/handler/http/request/status/mod.rs, src/job/config_watcher.rs, src/job/mod.rs, src/job/stats.rs
This feature adds a new cli argument to openobserve binary, i.e. `-c` which allows user to pass in path to a config file, adding flexibility to load env variables from different files. Earlier versions strictly looked for `.env` file in the current directory.
If this flag is not specified when running o2, the default file path (`.env`) from current directory will be used to load the config files.
This feature also adds a job to watch the config file. By default this job will run every `30` seconds, and can be configured via `ZO_CONFIG_WATCHER_INTERVAL` env variable. The watcher will watch the config file and reload the config if any changes are detected. By default the watcher watches `.env` file if no other file is configured using `-c` flag.
=> feat: add custom env file path support (#8365)

web/src/components/alerts/ScheduledAlert.vue
This PR fixes the issue in #8433
___
Bug fix
___
- Prevent SQL editor height growth
- Set minimum height to 18rem
- Compute height via inline style binding
- Adjust for error message presence
___
```mermaid
flowchart LR
UI["Alert Form UI"] -- contains --> Editor["SQL Query Editor"]
ErrorState["SQL Error State"] -- toggles --> EditorHeight["Dynamic Height Style"]
Editor -- renders with --> EditorHeight
```
<tr>
<td>
<details>
<summary><strong>ScheduledAlert.vue</strong><dd><code>Stabilize SQL editor height with dynamic styles</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: sql query editor rapidly increases

src/job/config_watcher.rs
Bug fix
___
- Fix enterprise config path import
- Ensure enterprise config reload compiles
___
```mermaid
flowchart LR
Watcher["Config watcher reload_config"] -- "imports enterprise refresh" --> Import["o2_enterprise::enterprise::common::config::refresh_config"]
Import -- "used in" --> Reload["refresh_o2_config() chain"]
```
<tr>
<td>
<details>
<summary><strong>config_watcher.rs</strong><dd><code>Correct enterprise config import path</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> fix: correct ent repo path

src/config/src/utils/async_file.rs, src/config/src/utils/time.rs, src/service/search/grpc/wal.rs
This PR fixed in some edge case we missing records on ingester but it will appear again after a while.
___
___
- Fix WAL datetime filter to hour precision
- Align search range to hour boundaries
- Add HOUR_MICRO_SECS constant
___
```mermaid
flowchart LR
query["Query time range (microseconds)"] -- "align to hour (floor)" --> aligned["Aligned start/end (hour)"]
aligned -- "scan WAL parquet dirs" --> filter["Hour-based datetime filter"]
filter -- "list matching files" --> results["File list for search"]
```
<tr>
<td>
<details>
<summary><strong>async_file.rs</strong><dd><code>Hour-level …
=> fix: search parquet for wal

web/src/components/dashboards/addPanel/ConfigPanel.vue
Bug fix
___
- Disable drilldown on Logs page
- Guard chart compare against Logs context
- Expose page key to template
___
```mermaid
flowchart LR
ConfigPanel["ConfigPanel.vue"]
DrilldownGuard["Add 'pageKey !== logs' guard"]
CompareGuard["Guard compare UI for logs"]
ExposeKey["Return dashboardPanelDataPageKey from setup()"]
ConfigPanel -- "update Drilldown v-if" --> DrilldownGuard
ConfigPanel -- "update compare v-if" --> CompareGuard
ConfigPanel -- "export key to template" --> ExposeKey
```
<tr>
<td>
<details>
<summary><strong>ConfigPanel.vue</strong><dd><code>Disable drilldown/compare when page key is …
=> fix: remove drilldown and compare against config on visualization rc7(#8534)

web/src/plugins/logs/IndexList.vue, web/src/services/stream.ts
Bug fix
___
- Add optional trace header to values API
- Propagate generated trace id from UI
- Use http client with custom headers
___
```mermaid
flowchart LR
UI["Logs IndexList.vue: generate trace id"] -- "pass traceparent" --> Service["stream.values() accepts traceparent"]
Service -- "set headers if present" --> HTTP["http({ headers }).get(url)"]
```
<tr>
<td>
<details>
<summary><strong>stream.ts</strong><dd><code>Support optional traceparent header in service</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
web/src/services/stream.ts …
=> fix: trace id added for values api

deny.toml
Fix
cargo builds were failing on the license checking. Reason being the zip crate needed a sub dependency `ppmd-rust` which is CC0-1.0 which wasn't explicitly listed in the allowed licenses. This broke builds. We are adding it back ti fix this.
___
Bug fix, Configuration changes
___
- Allow CC0-1.0 in license policy
- Unblocks cargo license checks
___
```mermaid
flowchart LR
deny["deny.toml license allowlist"] -- "add" --> cc0["CC0-1.0"]
cc0 -- "permits" --> cargo["Cargo license check passes"]
```
<tr>
<td>
<details>
<summary><strong>deny.toml</strong><dd><code>Add CC0-1.0 to allowed …
=> fix: Add CC0-1.0 license to allow list

src/service/metadata/distinct_values.rs
There is no `_timestamp` field in schema but the schema has other fields in some edge case. for example we lost some events for super cluster.
=> fix: distinct values has no _timestamp

src/config/src/meta/stream.rs, src/handler/http/request/ai.rs
The `doc_time_min` become `zero` when we merge stream stats in super cluster.
=> fix: stream stats merge

src/service/search/cache/cacher.rs, src/service/search/cache/mod.rs, tests/api-testing/tests/test_streaming.py
___
___
- Improve full cache hit detection
- Align histogram time bounds precisely
- Respect cache delay in end time
- Refine cache metadata time range
___
```mermaid
flowchart LR
A["Cached responses"] -- "calculate_deltas_multi" --> B["Deltas & adjusted start/end"]
B -- "no gaps + enough hits" --> C["Full cache hit"]
B -- "gaps or not enough" --> D["Query deltas logged"]
E["Write results"] -- "align histogram bounds" --> F["Adjusted accept_start/end"]
F -- "apply cache delay & interval" --> G["Final cache time range"]
G -- "persist" --> H["Cache file + metadata"]
```
<tr>
<td> …
=> fix: optimize cache metadata

src/config/src/config.rs, src/service/promql/engine.rs, src/service/promql/mod.rs, src/service/promql/rewrite.rs, src/service/search/sql/rewriter/remove_dashboard_placeholder.rs
fixed #8427
___
Bug fix, Tests
___
- Strip "_o2_all_" placeholder from PromQL
- Add rewriter to clean vector/matrix selectors
- Integrate rewrite in engine evaluation
- Unit tests for placeholder handling
___
```mermaid
flowchart LR
placeholder["_o2_all_ placeholder in matchers"]
rewriter["RemoveFilterAll rewriter"]
engineVS["Engine: VectorSelector eval"]
engineMS["Engine: MatrixSelector eval"]
cleanVS["Cleaned matchers"]
result["Correct PromQL execution"]
placeholder -- detected by --> rewriter
rewriter -- rewrite --> cleanVS
cleanVS -- used by --> engineVS
cleanVS -- used by --> engineMS
engineVS -- yields --> result
engineMS -- yields --> result
``` …
=> fix: remove select all placeholder for metrics

web/src/components/ConfirmDialog.vue, web/src/components/pipeline/NodeForm/Stream.vue, web/src/plugins/pipelines/CustomNode.vue, web/src/plugins/pipelines/useDnD.ts, web/src/utils/pipelines/constants.ts
This PR solves the issue of deleting the default destination node added implicitly so it will throw a warning message and also it will be only available for realtime pipeline because we only add default destination node for realtime pipelines #8597 8597
___
___
- Warn on deleting default destination node
- Detect default output for realtime pipelines
- Add reusable warning message constant
- Extend confirm dialog to show banner
___
```mermaid
flowchart LR
useDnD["useDnD: detect default destination"] -- "expose checkIfDefaultDestinationNode" --> StreamVue["Stream.vue: delete dialog"]
useDnD -- "expose checkIfDefaultDestinationNode" --> CustomNodeVue["CustomNode.vue: delete dialog"]
constants["constants.ts: warning message"] -- "import" --> StreamVue
constants -- …
```
=> fix: added warning message to the pipeline default destination node

web/src/components/logstream/schema.vue, web/src/components/settings/NoRegexPatterns.spec.ts, web/src/components/settings/NoRegexPatterns.vue, web/src/components/settings/RegexPatternList.vue, web/src/components/settings/index.vue, web/src/locales/languages/en.json
Enhancement, Documentation
___
- Rename UI to Sensitive Data Redaction
- Update i18n keys and labels
- Adjust tooltips and table headers
- Simplify import/create wording
___
```mermaid
flowchart LR
UI["Components (schema.vue, settings/*.vue)"] -- "rename labels/tooltips" --> SDR["Sensitive Data Redaction terminology"]
I18N["en.json i18n strings"] -- "update keys/values" --> SDR
SDR -- "reflected in lists, tabs, empty state" --> UX["Consistent SDR UI"]
```
<tr>
<td>
<details>
<summary><strong>schema.vue</strong><dd><code>Add SDR tooltip to patterns column</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: rename regex patterns to sensitive data redaction

src/handler/http/models/ai.rs, src/handler/http/models/dashboards.rs, src/handler/http/request/ai/chat.rs
- Add context parameter to PromptRequest for passing additional data
- Update AiServerRequest initialization to include context across chat endpoints
- Change PromptResponse role field from String to Role enum for type safety
- Add Serialize trait to DashboardRequestBody for serialization support
___
Enhancement
___
- Add `context` to `PromptRequest`
- Use `Role` enum in responses
- Pass context into AI server requests
- Serialize `DashboardRequestBody` with untagged enum
___
```mermaid
flowchart LR
PromptRequest["PromptRequest: +context Map<String, Value>"] -- "propagated" --> AiServerRequest["AiServerRequest::new(..., context)"]
AiMessage["AiMessage"] -- "converted to" --> PromptResponse["PromptResponse: role -> Role enum"]
DashboardReq["DashboardRequestBody"] -- "derive Serialize, …
```
=> feat: add context support to chat requests and improve type safety

src/config/src/config.rs, src/handler/http/models/pipelines.rs, src/handler/http/request/pipeline.rs, src/infra/src/table/entity/mod.rs, src/infra/src/table/entity/pipeline_last_errors.rs, src/infra/src/table/entity/prelude.rs, src/infra/src/table/migration/m20250930_000001_create_pipeline_last_errors_table.rs, src/infra/src/table/migration/mod.rs, src/service/db/mod.rs, src/service/db/pipeline_errors.rs, src/service/ingestion/mod.rs, src/service/self_reporting/mod.rs, src/service/self_reporting/queues.rs, web/src/components/pipeline/PipelineView.vue, web/src/components/pipeline/PipelinesList.vue, web/src/plugins/pipelines/CustomNode.vue
___
- Surface last pipeline error in API
- Persist pipeline errors in new table
- Batch upsert pipeline errors from reporting
- Safer error messages in VRL failures
___
```mermaid
flowchart LR
Reporting["Self-reporting errors"] -- "batch_upsert" --> DB["Table: pipeline_last_errors"]
API["GET /pipelines"] -- "join with errors" --> UIData["PipelineList.last_error"]
UIData -- "render" --> ListUI["PipelinesList error icon"]
UIData -- "per-node errors" --> NodeUI["CustomNode error badge"]
Ingestion["VRL apply_vrl_fn"] -- "clean error message" --> Reporting
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><details><summary>2 …
=> feat: pipeline errors on ui

src/infra/src/table/migration/m20250930_000001_create_pipeline_last_errors_table.rs
Bug fix
___
- Add safeguard to index creation
- Prevent failures on existing index
___
```mermaid
flowchart LR
Migration["Migration: create index on pipeline_last_errors"]
IndexCreate["Index::create with OrgId, LastErrorTimestamp"]
IfNotExists["Add .if_not_exists()"]
SafeMigrate["Idempotent migration without duplicate index error"]
Migration -- "build index" --> IndexCreate
IndexCreate -- "ensure exists check" --> IfNotExists
IfNotExists -- "prevents duplicate creation" --> SafeMigrate
```
<tr>
<td>
<details>
<summary><strong>m20250930_000001_create_pipeline_last_errors_table.rs</strong><dd><code>Guard …
=> fix: pipeline_last_errors existing index issue

web/src/components/alerts/AddAlert.vue, web/src/components/dashboards/AlertContextMenu.vue, web/src/components/dashboards/PanelSchemaRenderer.vue, web/src/components/dashboards/panels/ChartRenderer.vue
___
- Add alert context menu on charts
- Pass threshold/condition to Add Alert
- Correct query-type handling from panels
- Sync HAVING with threshold when aggregated
___
```mermaid
flowchart LR
Chart["ChartRenderer (ECharts)"] -- "emit contextmenu {x,y,value}" --> Panel["PanelSchemaRenderer"]
Panel -- "show AlertContextMenu" --> Menu["AlertContextMenu (above/below)"]
Menu -- "select {condition, threshold}" --> Panel
Panel -- "router.push addAlert?panelData=..." --> AddAlert["AddAlert.vue"]
AddAlert -- "init form from panelData" --> Form["Query/Trigger setup"]
AddAlert -- "set threshold/operator/HAVING" --> Form
``` …
=> fix: alerts with threshold from dashboards

src/handler/http/models/dashboards.rs, src/lib.rs, tests/api-testing/tests/test_dashboards.py, tests/api-testing/tests/test_folders.py, tests/api-testing/tests/test_summary.py, tests/integration_test.rs
In `CreateDashboard` API, the default dashboard version when `version` key was absent in the payload used to be 1, which was wrong. It is now 5 (for v5).
Going forward, this value should default to the latest version supported by OpenObserve.
This is tracked by `const LATEST_DASHBOARD_VERSION`, which is automatically populated at compile time by counting the number of variants of `enum DashboardRequestBody`, requiring no human intervention beyond adding the new variant itself to the enum.
___
___
- Default dashboard version auto-detected
- Replace hardcoded default with enum variant count
- Add nightly feature gate for variant_count
- Prevent stale defaults on new versions
___
```mermaid
flowchart LR
Enum["DashboardRequestBody enum"]
Const["LATEST_DASHBOARD_VERSION = …
```
=> chore: update default dashboard version from 1 to 5

web/src/components/MenuLink.vue, web/src/views/HomeView.vue
Enhancement
___
- Refine menu link hover/active behavior
- Add Streams header icon
- Redesign charts layout with CSS grid
- Improve tiles responsiveness and spacing
___
```mermaid
flowchart LR
Menu["MenuLink.vue styles"] -- "remove scale, add border" --> HoverActive["Stable hover/active states"]
HomeHeader["HomeView Streams header"] -- "add icon" --> Accessibility["Improved visual affordance"]
Layout["HomeView charts layout"] -- "CSS grid + wrappers" --> Responsive["Responsive, consistent tiles/charts"]
```
<tr>
<td>
<details>
<summary><strong>MenuLink.vue</strong><dd><code>Stabilize menu item …
=> fix: menu item and home view changes

web/src/components/dashboards/PanelSchemaRenderer.vue, web/src/composables/dashboard/usePanelDataLoader.ts
___
- Fetch annotations in parallel with queries
- Update watcher to re-render on annotations
- Preserve error handling and tracing
- Cache saving remains asynchronous
___
```mermaid
flowchart LR
Q["Build and run queries"] -- "Promise.all" --> QR["Query results"]
A["Start annotations fetch"] -- "in parallel" --> AP["Annotations Promise"]
QR -- "update state.data/metadata" --> S["Update state"]
AP -- "await & assign" --> AN["state.annotations"]
AN -- "watcher triggers" --> R["Panel re-render"]
```
<tr>
<td>
<details>
<summary><strong>usePanelDataLoader.ts</strong><dd><code>Parallel …
=> fix: fetch annotations in parallel with queries

web/src/components/alerts/ScheduledAlert.vue
This PR fixes the issues in
**No query is sent from the PromQL Editor resulting in error**
**PromQL Editor goes on infinite scrolling. shows console error ResizeObserver loop completed with undelivered notifications**
___
___
- Fix PromQL editor height and classes
- Correct query payload for PromQL range
- Reset outputs on tab change
- Dynamic AI button text by tab
___
```mermaid
flowchart LR
UI["Tab switch & buttons"] -- "reset outputs" --> Outputs["Output panes"]
UI -- "dynamic label" --> AIBtn["AI Generate button"]
PromEditor["PromQL editor"] -- "stable height/style" --> Layout["Editor layout"]
RunQuery["Run query (PromQL)"] -- "proper payload & parsing" --> Outputs
```
<table><thead><tr><th></th><th …
=> fix: promql editor issues in add alert page

src/service/search/cluster/flight.rs
Currently, if the given role_group is interactive and the LOCAL_NODE is an alert querier it still tries to run the below code 
```
nodes.retain(|n| n.name.eq(&LOCAL_NODE.name));
```
Which results in empty `nodes` vector and hence "no querier node online" because the `nodes` vec contains only the interactive queriers, not background queriers.
=> fix: alert querier should pick interactive querier when given role group is interactive

src/common/meta/search.rs, src/handler/grpc/request/query_cache.rs, src/service/search/cache/cacher.rs, src/service/search/cache/mod.rs, src/service/search/cache/multi.rs, src/service/search/cache/result_utils.rs, src/service/search/cluster/cache_multi.rs, src/service/search/cluster/cacher.rs, src/service/websocket_events/search.rs
```sql
SELECT histogram(_timestamp) AS x_axis_1, count(_timestamp) AS y_axis_1 
FROM "oly" 
GROUP BY x_axis_1 
ORDER BY y_axis_1 DESC
```
**Expected:** Results cached, ordered by count descending, correct count returned
```sql
SELECT histogram(_timestamp) AS x_axis_1, count(_timestamp) AS y_axis_1 
FROM "oly" 
GROUP BY x_axis_1 
ORDER BY y_axis_1 ASC
```
**Expected:** Results cached, ordered by count ascending
```sql
SELECT histogram(_timestamp) AS time_bucket, SUM(bytes) AS total_bytes 
FROM "logs" 
GROUP BY time_bucket 
ORDER BY total_bytes DESC
```
**Expected:** Results cached, ordered by sum of bytes
```sql
SELECT histogram(_timestamp) AS time_bucket, AVG(response_time) AS avg_response 
FROM "metrics" 
GROUP BY time_bucket 
ORDER BY avg_response DESC
```
**Expected:** Results cached, …
=> feat: cache hist query with non ts col order by

src/infra/src/table/timed_annotations.rs
Bug fix
___
- Fix null handling for `end_time` update
- Replace JSON None with integer None
- Ensure correct column value type
___
```mermaid
flowchart LR
UpdateFn["update() in timed_annotations.rs"] -- "when end_time is None" --> EndTimeExpr["Expr::value(Option::<i64>::None)"]
UpdateFn -- "when end_time is Some" --> EndTimeValue["Expr::value(end_time)"]
EndTimeExpr -- "correct null type" --> ColumnUpdate["timed_annotations::Column::EndTime"]
EndTimeValue -- "set integer value" --> ColumnUpdate
```
<tr>
<td>
<details>
<summary><strong>timed_annotations.rs</strong><dd><code>Correct end_time None …
=> fix: `timed_annotations.end_time` column update type
